---
apiVersion: v1
kind: Service
metadata:
  name: dinner-done-better-consumer-webapp-svc
  labels:
    app: dinner-done-better-consumer-webapp
    app.kubernetes.io/name: dinner-done-better-consumer-webapp
spec:
  selector:
    app.kubernetes.io/name: dinner-done-better-consumer-webapp
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  type: ClusterIP
---
