export type PageName =
  | 'LOGIN_PAGE'
  | 'RECIPE_PAGE'
  | 'RECIPES_PAGE'
  | 'MEAL_PAGE'
  | 'MEALS_PAGE'
  | 'MEAL_PLAN_PAGE'
  | 'MEAL_PLAN_BALLOT_PAGE'
  | 'MEAL_PLANS_PAGE'
  | 'USER_SETTINGS_PAGE'
  | 'HOUSEHOLD_SETTINGS_PAGE';

export type AnalyticsEvent = 'RECIPE_STEP_TOGGLED';
