package events

const (
	MealCreated                     = "meal_created"
	MealArchived                    = "meal_archived"
	MealPlanCreated                 = "meal_plan_created"
	MealPlanUpdated                 = "meal_plan_updated"
	MealPlanArchived                = "meal_plan_archived"
	MealPlanEventCreated            = "meal_plan_event_created"
	MealPlanEventUpdated            = "meal_plan_event_updated"
	MealPlanEventArchived           = "meal_plan_event_archived"
	MealPlanOptionCreated           = "meal_plan_option_created"
	MealPlanOptionUpdated           = "meal_plan_option_updated"
	MealPlanOptionArchived          = "meal_plan_option_archived"
	MealPlanOptionVoteCreated       = "meal_plan_option_vote_created"
	MealPlanOptionVoteUpdated       = "meal_plan_option_vote_updated"
	MealPlanOptionVoteArchived      = "meal_plan_option_vote_archived"
	MealPlanTaskCreated             = "meal_plan_task_created"
	MealPlanTaskStatusChanged       = "meal_plan_task_status_changed"
	MealPlanTaskUpdated             = "meal_plan_task_updated"
	MealPlanTaskArchived            = "meal_plan_task_archived"
	MealPlanGroceryListItemCreated  = "meal_plan_grocery_list_item_created"
	MealPlanGroceryListItemUpdated  = "meal_plan_grocery_list_item_updated"
	MealPlanGroceryListItemArchived = "meal_plan_grocery_list_item_archived"
	InstrumentOwnershipCreated      = "instrument_ownership_created"
	InstrumentOwnershipUpdated      = "instrument_ownership_updated"
	InstrumentOwnershipArchived     = "instrument_ownership_archived"
	IngredientPreferenceCreated     = "ingredient_preference_created"
	IngredientPreferenceUpdated     = "ingredient_preference_updated"
	IngredientPreferenceArchived    = "ingredient_preference_archived"
)
