package events

const (
	RecipeCreated                         = "recipe_created"
	RecipeUpdated                         = "recipe_updated"
	RecipeArchived                        = "recipe_archived"
	RecipeCloned                          = "recipe_cloned"
	RecipeStepCreated                     = "recipe_step_created"
	RecipeStepUpdated                     = "recipe_step_updated"
	RecipeStepArchived                    = "recipe_step_archived"
	RecipeStepProductCreated              = "recipe_step_product_created"
	RecipeStepProductUpdated              = "recipe_step_product_updated"
	RecipeStepProductArchived             = "recipe_step_product_archived"
	RecipeStepInstrumentCreated           = "recipe_step_instrument_created"
	RecipeStepInstrumentUpdated           = "recipe_step_instrument_updated"
	RecipeStepInstrumentArchived          = "recipe_step_instrument_archived"
	RecipeStepIngredientCreated           = "recipe_step_ingredient_created"
	RecipeStepIngredientUpdated           = "recipe_step_ingredient_updated"
	RecipeStepIngredientArchived          = "recipe_step_ingredient_archived"
	RecipePrepTaskCreated                 = "recipe_prep_task_created"
	RecipePrepTaskUpdated                 = "recipe_prep_task_updated"
	RecipePrepTaskArchived                = "recipe_prep_task_archived"
	RecipeStepCompletionConditionCreated  = "recipe_step_completion_condition_created"
	RecipeStepCompletionConditionUpdated  = "recipe_step_completion_condition_updated"
	RecipeStepCompletionConditionArchived = "recipe_step_completion_condition_archived"
	RecipeStepVesselCreated               = "recipe_step_vessel_created"
	RecipeStepVesselUpdated               = "recipe_step_vessel_updated"
	RecipeStepVesselArchived              = "recipe_step_vessel_archived"
	RecipeRatingCreated                   = "recipe_rating_created"
	RecipeRatingUpdated                   = "recipe_rating_updated"
	RecipeRatingArchived                  = "recipe_rating_archived"
)
