package events

const (
	ValidIngredientGroupCreated            = "valid_ingredient_group._created"
	ValidIngredientGroupUpdated            = "valid_ingredient_group._updated"
	ValidIngredientGroupArchived           = "valid_ingredient_group._archived"
	ValidIngredientMeasurementUnitCreated  = "valid_ingredient_measurement_unit_created"
	ValidIngredientMeasurementUnitUpdated  = "valid_ingredient_measurement_unit_updated"
	ValidIngredientMeasurementUnitArchived = "valid_ingredient_measurement_unit_archived"
	ValidIngredientPreparationCreated      = "valid_ingredient_preparation_created"
	ValidIngredientPreparationUpdated      = "valid_ingredient_preparation_updated"
	ValidIngredientPreparationArchived     = "valid_ingredient_preparation_archived"
	ValidIngredientCreated                 = "valid_ingredient_created"
	ValidIngredientUpdated                 = "valid_ingredient_updated"
	ValidIngredientArchived                = "valid_ingredient_archived"
	ValidIngredientStateIngredientCreated  = "valid_ingredient_state_ingredient_created"
	ValidIngredientStateIngredientUpdated  = "valid_ingredient_state_ingredient_updated"
	ValidIngredientStateIngredientArchived = "valid_ingredient_state_ingredient_archived"
	ValidIngredientStateCreated            = "valid_ingredient_state_created"
	ValidIngredientStateUpdated            = "valid_ingredient_state_updated"
	ValidIngredientStateArchived           = "valid_ingredient_state_archived"
	ValidMeasurementUnitCreated            = "valid_measurement_unit_created"
	ValidMeasurementUnitUpdated            = "valid_measurement_unit_updated"
	ValidMeasurementUnitArchived           = "valid_measurement_unit_archived"
	ValidInstrumentCreated                 = "valid_instrument_created"
	ValidInstrumentUpdated                 = "valid_instrument_updated"
	ValidInstrumentArchived                = "valid_instrument_archived"
	ValidMeasurementUnitConversionCreated  = "valid_measurement_unit_conversion_created"
	ValidMeasurementUnitConversionUpdated  = "valid_measurement_unit_conversion_updated"
	ValidMeasurementUnitConversionArchived = "valid_measurement_unit_conversion_archived"
	ValidPreparationInstrumentCreated      = "valid_preparation_instrument_created"
	ValidPreparationInstrumentUpdated      = "valid_preparation_instrument_updated"
	ValidPreparationInstrumentArchived     = "valid_preparation_instrument_archived"
	ValidPreparationCreated                = "valid_preparation_created"
	ValidPreparationUpdated                = "valid_preparation_updated"
	ValidPreparationArchived               = "valid_preparation_archived"
	ValidPreparationVesselCreated          = "valid_preparation_vessel_created"
	ValidPreparationVesselUpdated          = "valid_preparation_vessel_updated"
	ValidPreparationVesselArchived         = "valid_preparation_vessel_archived"
	ValidVesselCreated                     = "valid_vessel_created"
	ValidVesselUpdated                     = "valid_vessel_updated"
	ValidVesselArchived                    = "valid_vessel_archived"
)
