# See: https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# See: https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/resource/
resources:
  - namespace.yaml
  - ingress.yaml
  - ../../../kustomize/components/api_server
  - ../../../kustomize/components/jobs/db_cleaner
#  - ../../../kustomize/components/jobs/email_prober
#  - ../../../kustomize/components/jobs/meal_plan_finalizer
#  - ../../../kustomize/components/jobs/meal_plan_grocery_list_initializer
#  - ../../../kustomize/components/jobs/meal_plan_task_creator
#  - ../../../kustomize/components/jobs/search_data_index_scheduler

images:
  - name: dinner-done-better-service-api
    newName: us-central1-docker.pkg.dev/dinner-done-better-dev/containers/dinner-done-better-service-api
    newTag: latest
  - name: dinner-done-better-job-db-cleaner
    newName: us-central1-docker.pkg.dev/dinner-done-better-dev/containers/dinner-done-better-job-db-cleaner
    newTag: latest
#  - name: dinner-done-better-job-email-prober
#    newName: us-central1-docker.pkg.dev/dinner-done-better-dev/containers/dinner-done-better-job-email-prober
#    newTag: latest
#  - name: dinner-done-better-job-meal-plan-finalizer
#    newName: us-central1-docker.pkg.dev/dinner-done-better-dev/containers/dinner-done-better-job-meal-plan-finalizer
#    newTag: latest
#  - name: dinner-done-better-job-meal-plan-grocery-list-init
#    newName: us-central1-docker.pkg.dev/dinner-done-better-dev/containers/dinner-done-better-job-meal-plan-grocery-list-init
#    newTag: latest
#  - name: dinner-done-better-job-meal-plan-task-creator
#    newName: us-central1-docker.pkg.dev/dinner-done-better-dev/containers/dinner-done-better-job-meal-plan-task-creator
#    newTag: latest
#  - name: dinner-done-better-job-search-data-index-scheduler
#    newName: us-central1-docker.pkg.dev/dinner-done-better-dev/containers/dinner-done-better-job-search-data-index-scheduler
#    newTag: latest

# See: https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/patches/
patches:
  ### let's set up some API service environment variables sourced by kubernetes secrets.
  - patch: |-
      - op: add
        path: "/spec/template/spec/containers/0/env/-"
        value:
          name: DINNER_DONE_BETTER_DATABASE_CONNECTION_DETAILS_HOST
          valueFrom:
            secretKeyRef:
              name: api-service-config
              key: DATABASE_HOST
    target:
      version: v1
      kind: Deployment
      name: dinner-done-better-service-api-deployment
  - patch: |-
      - op: add
        path: "/spec/template/spec/containers/0/env/-"
        value:
          name: DINNER_DONE_BETTER_DATABASE_CONNECTION_DETAILS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: api-service-config
              key: DATABASE_PASSWORD
    target:
      version: v1
      kind: Deployment
      name: dinner-done-better-service-api-deployment
  - patch: |-
      - op: add
        path: "/spec/template/spec/containers/0/env/-"
        value:
          name: DINNER_DONE_BETTER_DATABASE_OAUTH2_TOKEN_ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: api-service-config
              key: OAUTH2_TOKEN_ENCRYPTION_KEY
    target:
      version: v1
      kind: Deployment
      name: dinner-done-better-service-api-deployment
  - patch: |-
      - op: add
        path: "/spec/template/spec/containers/0/env/-"
        value:
          name: DINNER_DONE_BETTER_ANALYTICS_SEGMENT_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: api-service-config
              key: SEGMENT_API_TOKEN
    target:
      version: v1
      kind: Deployment
      name: dinner-done-better-service-api-deployment
  - patch: |-
      - op: add
        path: "/spec/template/spec/containers/0/env/-"
        value:
          name: DINNER_DONE_BETTER_SEARCH_ALGOLIA_API_KEY
          valueFrom:
            secretKeyRef:
              name: api-service-config
              key: ALGOLIA_API_KEY
    target:
      version: v1
      kind: Deployment
      name: dinner-done-better-service-api-deployment
  - patch: |-
      - op: add
        path: "/spec/template/spec/containers/0/env/-"
        value:
          name: DINNER_DONE_BETTER_SEARCH_ALGOLIA_APP_ID
          valueFrom:
            secretKeyRef:
              name: api-service-config
              key: ALGOLIA_APPLICATION_ID
    target:
      version: v1
      kind: Deployment
      name: dinner-done-better-service-api-deployment
  - patch: |-
      - op: add
        path: "/spec/template/spec/containers/0/env/-"
        value:
          name: DINNER_DONE_BETTER_EMAIL_SENDGRID_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: api-service-config
              key: SENDGRID_API_TOKEN
    target:
      version: v1
      kind: Deployment
      name: dinner-done-better-service-api-deployment
  - patch: |-
      - op: add
        path: "/spec/template/spec/containers/0/env/-"
        value:
          name: DINNER_DONE_BETTER_FEATURE_FLAGS_POSTHOG_PERSONAL_API_KEY
          valueFrom:
            secretKeyRef:
              name: api-service-config
              key: POSTHOG_PERSONAL_API_KEY
    target:
      version: v1
      kind: Deployment
      name: dinner-done-better-service-api-deployment
  - patch: |-
      - op: add
        path: "/spec/template/spec/containers/0/env/-"
        value:
          name: DINNER_DONE_BETTER_FEATURE_FLAGS_POSTHOG_PROJECT_API_KEY
          valueFrom:
            secretKeyRef:
              name: api-service-config
              key: POSTHOG_API_KEY
    target:
      version: v1
      kind: Deployment
      name: dinner-done-better-service-api-deployment
  - patch: |-
      - op: add
        path: "/spec/template/spec/containers/0/env/-"
        value:
          name: DINNER_DONE_BETTER_SERVICE_AUTH_JWT_SIGNING_KEY
          valueFrom:
            secretKeyRef:
              name: api-service-config
              key: JWT_SIGNING_KEY
    target:
      version: v1
      kind: Deployment
      name: dinner-done-better-service-api-deployment
  - patch: |-
      - op: add
        path: "/spec/template/spec/containers/0/env/-"
        value:
          name: DINNER_DONE_BETTER_SERVICE_AUTH_SSO_CONFIG_GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: api-service-config
              key: GOOGLE_SSO_OAUTH2_CLIENT_ID
    target:
      version: v1
      kind: Deployment
      name: dinner-done-better-service-api-deployment
  - patch: |-
      - op: add
        path: "/spec/template/spec/containers/0/env/-"
        value:
          name: DINNER_DONE_BETTER_SERVICE_AUTH_SSO_CONFIG_GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: api-service-config
              key: GOOGLE_SSO_OAUTH2_CLIENT_SECRET
    target:
      version: v1
      kind: Deployment
      name: dinner-done-better-service-api-deployment
  - patch: |-
      - op: add
        path: "/spec/template/spec/containers/0/env/-"
        value:
          name: DINNER_DONE_BETTER_QUEUES_DATA_CHANGES_TOPIC_NAME
          valueFrom:
            secretKeyRef:
              name: pubsub-topic-names
              key: data_changes
    target:
      version: v1
      kind: Deployment
      name: dinner-done-better-service-api-deployment
  - patch: |-
      - op: add
        path: "/spec/template/spec/containers/0/env/-"
        value:
          name: DINNER_DONE_BETTER_QUEUES_OUTBOUND_EMAILS_TOPIC_NAME
          valueFrom:
            secretKeyRef:
              name: pubsub-topic-names
              key: outbound_emails
    target:
      version: v1
      kind: Deployment
      name: dinner-done-better-service-api-deployment
  - patch: |-
      - op: add
        path: "/spec/template/spec/containers/0/env/-"
        value:
          name: DINNER_DONE_BETTER_QUEUES_SEARCH_INDEX_REQUESTS_TOPIC_NAME
          valueFrom:
            secretKeyRef:
              name: pubsub-topic-names
              key: search_index_requests
    target:
      version: v1
      kind: Deployment
      name: dinner-done-better-service-api-deployment
  - patch: |-
      - op: add
        path: "/spec/template/spec/containers/0/env/-"
        value:
          name: DINNER_DONE_BETTER_QUEUES_USER_DATA_AGGREGATION_TOPIC_NAME
          valueFrom:
            secretKeyRef:
              name: pubsub-topic-names
              key: user_data_aggregator
    target:
      version: v1
      kind: Deployment
      name: dinner-done-better-service-api-deployment
  - patch: |-
      - op: add
        path: "/spec/template/spec/containers/0/env/-"
        value:
          name: DINNER_DONE_BETTER_QUEUES_WEBHOOK_EXECUTION_REQUESTS_TOPIC_NAME
          valueFrom:
            secretKeyRef:
              name: pubsub-topic-names
              key: webhook_execution_requests
    target:
      version: v1
      kind: Deployment
      name: dinner-done-better-service-api-deployment

  #
  # otel collctor sidecar patches
  #

  - patch: |-
      - op: add
        path: "/spec/template/spec/containers/1/env/-"
        value:
          name: PROMETHEUS_USERNAME
          valueFrom:
            secretKeyRef:
              name: api-service-config
              key: GRAFANA_CLOUD_PROMETHEUS_USERNAME
    target:
      version: v1
      kind: Deployment
      name: dinner-done-better-service-api-deployment
  - patch: |-
      - op: add
        path: "/spec/template/spec/containers/1/env/-"
        value:
          name: PROMETHEUS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: api-service-config
              key: GRAFANA_CLOUD_PROMETHEUS_PASSWORD
    target:
      version: v1
      kind: Deployment
      name: dinner-done-better-service-api-deployment
  - patch: |-
      - op: add
        path: "/spec/template/spec/containers/1/env/-"
        value:
          name: LOKI_USERNAME
          valueFrom:
            secretKeyRef:
              name: api-service-config
              key: GRAFANA_CLOUD_LOKI_USERNAME
    target:
      version: v1
      kind: Deployment
      name: dinner-done-better-service-api-deployment
  - patch: |-
      - op: add
        path: "/spec/template/spec/containers/1/env/-"
        value:
          name: LOKI_PASSWORD
          valueFrom:
            secretKeyRef:
              name: api-service-config
              key: GRAFANA_CLOUD_LOKI_PASSWORD
    target:
      version: v1
      kind: Deployment
      name: dinner-done-better-service-api-deployment
  - patch: |-
      - op: add
        path: "/spec/template/spec/containers/1/env/-"
        value:
          name: TEMPO_USERNAME
          valueFrom:
            secretKeyRef:
              name: api-service-config
              key: GRAFANA_CLOUD_TEMPO_USERNAME
    target:
      version: v1
      kind: Deployment
      name: dinner-done-better-service-api-deployment
  - patch: |-
      - op: add
        path: "/spec/template/spec/containers/1/env/-"
        value:
          name: TEMPO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: api-service-config
              key: GRAFANA_CLOUD_TEMPO_PASSWORD
    target:
      version: v1
      kind: Deployment
      name: dinner-done-better-service-api-deployment

labels:
  - pairs:
      app.kubernetes.io/name: dinner-done-better-backend

configMapGenerator:
  - name: opentelemetry-collector-config
    namespace: dev
    files:
      - config.yaml=./configs/otel_collector_config.yaml

  - name: dinner-done-better-service-api-config
    namespace: dev
    files:
      - config.json=./configs/api_service_config.json

  - name: dinner-done-better-job-db-cleaner-config
    namespace: dev
    files:
      - config.json=./configs/job_db_cleaner_config.json

  - name: dinner-done-better-job-email-prober-config
    namespace: dev
    files:
      - config.json=./configs/job_email_prober_config.json

  - name: dinner-done-better-job-meal-plan-finalizer-config
    namespace: dev
    files:
      - config.json=./configs/job_meal_plan_finalizer_config.json

  - name: dinner-done-better-job-meal-plan-grocery-list-init-config
    namespace: dev
    files:
      - config.json=./configs/job_meal_plan_grocery_list_initializer_config.json

  - name: dinner-done-better-job-meal-plan-task-creator-config
    namespace: dev
    files:
      - config.json=./configs/job_meal_plan_task_creator_config.json

  - name: dinner-done-better-job-search-data-index-scheduler-config
    namespace: dev
    files:
      - config.json=./configs/job_search_data_index_scheduler_config.json

generatorOptions:
  disableNameSuffixHash: true
  labels:
    type: generated
  annotations:
    note: generated
