---
# See: https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# See: https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/resource/
resources:
  - ../../../kustomize/components/webapp
  - ../../../kustomize/components/admin
  - ../../../kustomize/components/landing

images:
  - name: dinner-done-better-webapp
    newName: us-central1-docker.pkg.dev/dinner-done-better-dev/containers/dinner-done-better-webapp
    newTag: latest
  - name: dinner-done-better-admin-app
    newName: us-central1-docker.pkg.dev/dinner-done-better-dev/containers/dinner-done-better-admin-app
    newTag: latest
  - name: dinner-done-better-landing
    newName: us-central1-docker.pkg.dev/dinner-done-better-dev/containers/dinner-done-better-landing
    newTag: latest

# See: https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/patches/
patches:
  - patch: |-
      - op: add
        path: "/spec/template/spec/containers/0/env/-"
        value:
          name: PORT
          value: "7000"
      - op: add
        path: "/spec/template/spec/containers/0/env/-"
        value:
          name: NEXT_API_ENDPOINT
          value: "https://dinner-done-better-api-svc.dev.svc.cluster.local:8000"
      - op: add
        path: "/spec/template/spec/containers/0/env/-"
        value:
          name: NEXT_PUBLIC_API_ENDPOINT
          value: "https://api.dinnerdonebetter.dev"
      - op: add
        path: "/spec/template/spec/containers/0/env/-"
        value:
          name: NEXT_DINNER_DONE_BETTER_OAUTH2_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: frontend-service-config
              key: OAUTH2_CLIENT_ID
      - op: add
        path: "/spec/template/spec/containers/0/env/-"
        value:
          name: NEXT_DINNER_DONE_BETTER_OAUTH2_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: frontend-service-config
              key: OAUTH2_CLIENT_SECRET
      - op: add
        path: "/spec/template/spec/containers/0/env/-"
        value:
          name: NEXT_COOKIE_ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: frontend-service-config
              key: COOKIE_ENCRYPTION_KEY
      - op: add
        path: "/spec/template/spec/containers/0/env/-"
        value:
          name: NEXT_BASE64_COOKIE_ENCRYPT_IV
          valueFrom:
            secretKeyRef:
              name: frontend-service-config
              key: COOKIE_ENCRYPTION_IV
    target:
      version: v1
      kind: Deployment
      name: dinner-done-better-admin-app-deployment

  - patch: |-
      - op: add
        path: "/spec/template/spec/containers/0/env/-"
        value:
          name: PORT
          value: "9000"
      - op: add
        path: "/spec/template/spec/containers/0/env/-"
        value:
          name: NEXT_API_ENDPOINT
          value: "https://dinner-done-better-api-svc.dev.svc.cluster.local:8000"
      - op: add
        path: "/spec/template/spec/containers/0/env/-"
        value:
          name: NEXT_PUBLIC_API_ENDPOINT
          value: "https://api.dinnerdonebetter.dev"
      - op: add
        path: "/spec/template/spec/containers/0/env/-"
        value:
          name: NEXT_DINNER_DONE_BETTER_OAUTH2_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: frontend-service-config
              key: OAUTH2_CLIENT_ID
      - op: add
        path: "/spec/template/spec/containers/0/env/-"
        value:
          name: NEXT_DINNER_DONE_BETTER_OAUTH2_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: frontend-service-config
              key: OAUTH2_CLIENT_SECRET
      - op: add
        path: "/spec/template/spec/containers/0/env/-"
        value:
          name: NEXT_COOKIE_ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: frontend-service-config
              key: COOKIE_ENCRYPTION_KEY
      - op: add
        path: "/spec/template/spec/containers/0/env/-"
        value:
          name: NEXT_BASE64_COOKIE_ENCRYPT_IV
          valueFrom:
            secretKeyRef:
              name: frontend-service-config
              key: COOKIE_ENCRYPTION_IV
      - op: add
        path: "/spec/template/spec/containers/0/env/-"
        value:
          name: NEXT_PUBLIC_SEGMENT_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: frontend-service-config
              key: SEGMENT_API_TOKEN
    target:
      version: v1
      kind: Deployment
      name: dinner-done-better-webapp-deployment

  - patch: |-
      - op: add
        path: "/spec/template/spec/containers/0/env/-"
        value:
          name: PORT
          value: "10000"
    target:
      version: v1
      kind: Deployment
      name: dinner-done-better-landing-deployment

labels:
  - pairs:
      deployed_by: skaffold

configMapGenerator:
  - name: frontend-opentelemetry-collector-config
    namespace: dev
    files:
      - config.yaml=configs/otel_collector_config.yaml

generatorOptions:
  disableNameSuffixHash: true
  labels:
    deployed_by: skaffold
    generated_by: skaffold
  annotations:
    deployed_by: skaffold
    generated_by: skaffold
