---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dinner-done-better-admin-app-deployment
  labels:
    app: dinner-done-better-admin-app
    app.kubernetes.io/name: dinner-done-better-admin-app
spec:
  selector:
    matchLabels:
      app: dinner-done-better-admin-app
      app.kubernetes.io/name: dinner-done-better-admin-app
  replicas: 1
  template:
    metadata:
      labels:
        app: dinner-done-better-admin-app
        app.kubernetes.io/name: dinner-done-better-admin-app
    spec:
      containers:
      - name: dinner-done-better-admin-app
        image: dinner-done-better-admin-app
        imagePullPolicy: IfNotPresent
        env:
          - name: "DISABLE_REGISTRATION"
            value: "false"
          - name: "NEXT_API_ENDPOINT"
            value: "dinner-done-better.dev.svc.cluster.local:8000"
          - name: "NEXT_COOKIE_ENCRYPTION_KEY"
            value: "ZOTGz4KEhZFSM6udeESOX5JVqhtEdHdS"
          - name: "NEXT_BASE64_COOKIE_ENCRYPT_IV"
            value: "S2IwVXVvMW9hSEl4WjQ0ak1NYW50QndMTzJBWDJFV2o="
          - name: "NEXT_DINNER_DONE_BETTER_OAUTH2_CLIENT_ID"
            value: ""
          - name: "NEXT_DINNER_DONE_BETTER_OAUTH2_CLIENT_SECRET"
            value: ""
          - name: "REWRITE_COOKIE_SECURE"
            value: "false"
          - name: "REWRITE_COOKIE_HOST_FROM"
            value: ""
          - name: "REWRITE_COOKIE_HOST_TO"
            value: ""
          - name: "NEXT_PUBLIC_SEGMENT_API_TOKEN"
            value: ""
        volumeMounts:
          - name: logs
            mountPath: /var/log/application
        ports:
        - containerPort: 7000
          name: http
        resources:
          requests:
            memory: 128Mi
            cpu: "50m"
        livenessProbe:
          httpGet:
            path: "/api/_meta_/live"
            port: 7000
          initialDelaySeconds: 15
          periodSeconds: 32
        readinessProbe:
          httpGet:
            path: "/api/_meta_/ready"
            port: 7000
          initialDelaySeconds: 15
          periodSeconds: 3
        # This is the OpenTelemetry collector sidecar
      - name: opentelemetry-collector
        image: otel/opentelemetry-collector-contrib:0.115.1
        command:
          - "/otelcol-contrib"
          - "--config"
          - "/conf/config.yaml"
        ports:
          - containerPort: 4317
            name: otel1
          - containerPort: 4318
            name: otel2
          - containerPort: 13313
            name: health
        volumeMounts:
          - name: logs
            mountPath: /var/log/application
            readOnly: true
          - name: opentelemetry-config
            mountPath: /conf
        env:
          - name: "RUNNING_IN_KUBERNETES"
            value: "true"
      volumes:
        # this volume is where we write logs to in the API, and where we read logs from in the collector.
        - name: logs
          emptyDir:
            sizeLimit: 500Mi
        # this volume contains the configuration file for the OTel collector.
        - name: opentelemetry-config
          configMap:
            name: opentelemetry-collector-config
---
