---
line_ending: "lf"
doublestar: true
continue_on_error: false
match_type: "standard"
include:
  - "**/*.{yaml,yml}"
exclude: []
gitignore_excludes: false
regex_exclude: []
extensions: []
output_format: "default"
formatter:
  indent: 2
  include_document_start: true
  include_document_end: true
  line_ending: "lf"
  retain_line_breaks_single: true
  disallow_anchors: true
  max_line_length: 0
  scan_folded_as_literal: true
  indentless_arrays: false
  drop_merge_tag: false
  pad_line_comments: 1
  trim_trailing_whitespace: true
  eof_newline: true
  strip_directives: false
