apiVersion: skaffold/v4beta11
kind: Config

metadata:
  name: dinner-done-better-backend

profiles:
  - name: localdev

    build:
      tagPolicy:
        sha256: {}
      artifacts:
          # backend artifacts
        - image: dinner-done-better-service-api
          context: ./backend
          ko:
            dir: .
            env:
              - CGO_ENABLED=1
            flags:
              - -trimpath
            ldflags:
              - -s -w
              - -extldflags "-static"
            main: ./cmd/services/api/http
            fromImage: golang:1.22-bullseye

        - image: dinner-done-better-job-db-cleaner
          context: backend
          ko:
            dir: .
            env:
              - CGO_ENABLED=1
            flags:
              - -trimpath
            ldflags:
              - -s -w
              - -extldflags "-static"
            main: ./cmd/jobs/db_cleaner
            fromImage: golang:1.22-bullseye

        - image: dinner-done-better-job-email-prober
          context: backend
          ko:
            dir: .
            env:
              - CGO_ENABLED=1
            flags:
              - -trimpath
            ldflags:
              - -s -w
              - -extldflags "-static"
            main: ./cmd/jobs/email_prober
            fromImage: golang:1.22-bullseye

        - image: dinner-done-better-job-meal-plan-finalizer
          context: backend
          ko:
            dir: .
            env:
              - CGO_ENABLED=1
            flags:
              - -trimpath
            ldflags:
              - -s -w
              - -extldflags "-static"
            main: ./cmd/jobs/meal_plan_finalizer
            fromImage: golang:1.22-bullseye

        - image: dinner-done-better-job-meal-plan-grocery-list-init
          context: backend
          ko:
            dir: .
            env:
              - CGO_ENABLED=1
            flags:
              - -trimpath
            ldflags:
              - -s -w
              - -extldflags "-static"
            main: ./cmd/jobs/meal_plan_grocery_list_initializer
            fromImage: golang:1.22-bullseye

        - image: dinner-done-better-job-meal-plan-task-creator
          context: backend
          ko:
            dir: .
            env:
              - CGO_ENABLED=1
            flags:
              - -trimpath
            ldflags:
              - -s -w
              - -extldflags "-static"
            main: ./cmd/jobs/meal_plan_task_creator
            fromImage: golang:1.22-bullseye

        - image: dinner-done-better-job-search-data-index-scheduler
          context: backend
          ko:
            dir: .
            env:
              - CGO_ENABLED=1
            flags:
              - -trimpath
            ldflags:
              - -s -w
              - -extldflags "-static"
            main: ./cmd/jobs/search_data_index_scheduler
            fromImage: golang:1.22-bullseye

          # NOTE: no cmd/functions here

          # frontend artifacts
        - image: dinner-done-better-webapp
          context: ./frontend
          docker:
            dockerfile: ./apps/web/Dockerfile

        - image: dinner-done-better-admin-app
          context: ./frontend
          docker:
            dockerfile: ./apps/admin/Dockerfile

        - image: dinner-done-better-landing
          context: ./frontend
          docker:
            dockerfile: ./apps/landing/Dockerfile


    manifests:
      kustomize:
        paths:
          - backend/deploy/kustomize/environments/localdev
          - frontend/deploy/kustomize/environments/localdev
      output: deploy/environments/local/generated/kubernetes.yaml

    deploy:
      kubeContext: docker-desktop
      helm:
        releases:
          - name: postgres
            namespace: localdev
            createNamespace: true
            remoteChart: oci://registry-1.docker.io/bitnamicharts/postgresql
            version: 16.1.2
            overrides:
              global:
                postgresql:
                  auth:
                    username: dbuser
                    password: hunter2
                    database: dinner-done-better

          - name: redis
            namespace: localdev
            createNamespace: true
            remoteChart: oci://registry-1.docker.io/bitnamicharts/redis
            version: 20.2.1
            overrides:
              architecture: standalone

          - name: grafana
            namespace: localdev
            createNamespace: true
            remoteChart: oci://registry-1.docker.io/bitnamicharts/grafana
            version: 11.3.26

      kubectl:
        defaultNamespace: localdev

  - name: dev