apiVersion: skaffold/v4beta11
kind: Config

metadata:
  name: dinner-done-better-backend

profiles:
  - name: localdev

    build:
      tagPolicy:
        sha256: {}
      artifacts:
        - image: dinner-done-better-service-api
          context: .
          ko:
            dir: .
            env:
              - CGO_ENABLED=1
            flags:
              - -trimpath
            ldflags:
              - -s -w
              - -extldflags "-static"
            main: ./cmd/services/api/http
            fromImage: golang:1.22-bullseye

        - image: dinner-done-better-job-db-cleaner
          context: .
          ko:
            dir: .
            env:
              - CGO_ENABLED=1
            flags:
              - -trimpath
            ldflags:
              - -s -w
              - -extldflags "-static"
            main: ./cmd/jobs/db_cleaner
            fromImage: gcr.io/distroless/static:nonroot

#        - image: dinner-done-better-job-email-prober
#          context: .
#          ko:
#            dir: .
#            env:
#              - CGO_ENABLED=1
#            flags:
#              - -trimpath
#            ldflags:
#              - -s -w
#              - -extldflags "-static"
#            main: ./cmd/jobs/email_prober
#            fromImage: gcr.io/distroless/static:nonroot
#
#        - image: dinner-done-better-job-meal-plan-finalizer
#          context: .
#          ko:
#            dir: .
#            env:
#              - CGO_ENABLED=1
#            flags:
#              - -trimpath
#            ldflags:
#              - -s -w
#              - -extldflags "-static"
#            main: ./cmd/jobs/meal_plan_finalizer
#            fromImage: gcr.io/distroless/static:nonroot
#
#        - image: dinner-done-better-job-meal-plan-grocery-list-initializer
#          context: .
#          ko:
#            dir: .
#            env:
#              - CGO_ENABLED=1
#            flags:
#              - -trimpath
#            ldflags:
#              - -s -w
#              - -extldflags "-static"
#            main: ./cmd/jobs/meal_plan_grocery_list_initializer
#            fromImage: gcr.io/distroless/static:nonroot
#
#        - image: dinner-done-better-job-meal-plan-task-creator
#          context: .
#          ko:
#            dir: .
#            env:
#              - CGO_ENABLED=1
#            flags:
#              - -trimpath
#            ldflags:
#              - -s -w
#              - -extldflags "-static"
#            main: ./cmd/jobs/meal_plan_task_creator
#            fromImage: gcr.io/distroless/static:nonroot
#
#        - image: dinner-done-better-job-search-data-index-scheduler
#          context: .
#          ko:
#            dir: .
#            env:
#              - CGO_ENABLED=1
#            flags:
#              - -trimpath
#            ldflags:
#              - -s -w
#              - -extldflags "-static"
#            main: ./cmd/jobs/search_data_index_scheduler
#            fromImage: gcr.io/distroless/static:nonroot

        # TODO: cmd/functions

    manifests:
      kustomize:
        paths:
          - deploy/kustomize/environments/localdev
      output: ./environments/local/generated/kubernetes.yaml

    deploy:
      kubeContext: docker-desktop
      helm:
        releases:
#          - name: postgres
#            namespace: localdev
#            createNamespace: true
#            remoteChart: oci://registry-1.docker.io/bitnamicharts/postgresql
#            version: 16.1.2
#            overrides:
#              global:
#                postgresql:
#                  auth:
#                    username: dbuser
#                    password: hunter2
#                    database: dinner-done-better

#          - name: redis
#            namespace: localdev
#            createNamespace: true
#            remoteChart: oci://registry-1.docker.io/bitnamicharts/redis
#            version: 20.2.1
#            overrides:
#              architecture: standalone

#          - name: grafana
#            namespace: localdev
#            createNamespace: true
#            remoteChart: oci://registry-1.docker.io/bitnamicharts/grafana
#            version: 11.3.26
#
#          - name: jaeger
#            namespace: localdev
#            createNamespace: true
#            remoteChart: oci://registry-1.docker.io/bitnamicharts/jaeger
#            version: 3.0.6

#          - name: dinnerdonebetter
#            namespace: localdev
#            createNamespace: true
#            chartPath: environments/local/helm/charts/api-server
      kubectl: {}

    portForward:
      - resourceType: Service
        namespace: localdev
        resourceName: postgres-postgresql
        port: 5432
        localPort: 5434
        address: 127.0.0.1

      # - resourceType: Service
      #   namespace: localdev
      #   resourceName: dinner-done-better
      #   port: 8000
      #   localPort: 8008
      #   address: 127.0.0.1

  - name: dev