---
apiVersion: skaffold/v4beta11
kind: Config

metadata:
  name: dinner-done-better-backend

profiles:
  - name: localdev
    activation:
      - kubeContext: docker-desktop
    build:
      tagPolicy:
        sha256: {}
      artifacts:
        # backend artifacts (ko)
        - image: dinner-done-better-service-api
          ko:
            dir: .
            flags:
              - -trimpath
            ldflags:
              - -s -w
              - -extldflags "-static"
            main: ./cmd/services/api/http
            fromImage: golang:1.24-bullseye

        - image: dinner-done-better-job-db-cleaner
          ko:
            dir: .
            flags:
              - -trimpath
            ldflags:
              - -s -w
              - -extldflags "-static"
            main: ./cmd/jobs/db_cleaner
            fromImage: golang:1.24-bullseye

        - image: dinner-done-better-job-email-prober
          ko:
            dir: .
            flags:
              - -trimpath
            ldflags:
              - -s -w
              - -extldflags "-static"
            main: ./cmd/jobs/email_prober
            fromImage: golang:1.24-bullseye

        - image: dinner-done-better-job-meal-plan-finalizer
          ko:
            dir: .
            flags:
              - -trimpath
            ldflags:
              - -s -w
              - -extldflags "-static"
            main: ./cmd/jobs/meal_plan_finalizer
            fromImage: golang:1.24-bullseye

        - image: dinner-done-better-job-meal-plan-grocery-list-init
          ko:
            dir: .
            flags:
              - -trimpath
            ldflags:
              - -s -w
              - -extldflags "-static"
            main: ./cmd/jobs/meal_plan_grocery_list_initializer
            fromImage: golang:1.24-bullseye

        - image: dinner-done-better-job-meal-plan-task-creator
          ko:
            dir: .
            flags:
              - -trimpath
            ldflags:
              - -s -w
              - -extldflags "-static"
            main: ./cmd/jobs/meal_plan_task_creator
            fromImage: golang:1.24-bullseye

        - image: dinner-done-better-job-search-data-index-scheduler
          ko:
            dir: .
            flags:
              - -trimpath
            ldflags:
              - -s -w
              - -extldflags "-static"
            main: ./cmd/jobs/search_data_index_scheduler
            fromImage: golang:1.24-bullseye

          # NOTE: no cmd/functions here

    manifests:
      kustomize:
        paths:
          - deploy/environments/localdev/kustomize

    deploy:
      kubeContext: docker-desktop
      kubectl:
        defaultNamespace: localdev
    portForward:
      - resourceType: Service
        resourceName: dinner-done-better-api-svc
        namespace: localdev
        port: 8000

  - name: dev
    build:
      tagPolicy:
        inputDigest: {}
      artifacts:
        # backend artifacts (ko)
        - image: us-central1-docker.pkg.dev/dinner-done-better-dev/containers/dinner-done-better-service-api
          ko:
            dir: .
            flags:
              - -trimpath
            ldflags:
              - -s -w
              - -extldflags "-static"
            main: ./cmd/services/api/http
            fromImage: golang:1.24-bullseye

        - image: us-central1-docker.pkg.dev/dinner-done-better-dev/containers/dinner-done-better-job-db-cleaner
          ko:
            dir: .
            flags:
              - -trimpath
            ldflags:
              - -s -w
              - -extldflags "-static"
            main: ./cmd/jobs/db_cleaner
            fromImage: golang:1.24-bullseye

        - image: us-central1-docker.pkg.dev/dinner-done-better-dev/containers/dinner-done-better-job-email-prober
          ko:
            dir: .
            flags:
              - -trimpath
            ldflags:
              - -s -w
              - -extldflags "-static"
            main: ./cmd/jobs/email_prober
            fromImage: golang:1.24-bullseye

        - image: us-central1-docker.pkg.dev/dinner-done-better-dev/containers/dinner-done-better-job-meal-plan-finalizer
          ko:
            dir: .
            flags:
              - -trimpath
            ldflags:
              - -s -w
              - -extldflags "-static"
            main: ./cmd/jobs/meal_plan_finalizer
            fromImage: golang:1.24-bullseye

        - image: us-central1-docker.pkg.dev/dinner-done-better-dev/containers/dinner-done-better-job-meal-plan-grocery-list-init
          ko:
            dir: .
            flags:
              - -trimpath
            ldflags:
              - -s -w
              - -extldflags "-static"
            main: ./cmd/jobs/meal_plan_grocery_list_initializer
            fromImage: golang:1.24-bullseye

        - image: us-central1-docker.pkg.dev/dinner-done-better-dev/containers/dinner-done-better-job-meal-plan-task-creator
          ko:
            dir: .
            flags:
              - -trimpath
            ldflags:
              - -s -w
              - -extldflags "-static"
            main: ./cmd/jobs/meal_plan_task_creator
            fromImage: golang:1.24-bullseye

        - image: us-central1-docker.pkg.dev/dinner-done-better-dev/containers/dinner-done-better-job-search-data-index-scheduler
          ko:
            dir: .
            flags:
              - -trimpath
            ldflags:
              - -s -w
              - -extldflags "-static"
            main: ./cmd/jobs/search_data_index_scheduler
            fromImage: golang:1.24-bullseye

        - image: us-central1-docker.pkg.dev/dinner-done-better-dev/containers/dinner-done-better-async-message-handler
          ko:
            dir: .
            flags:
              - -trimpath
            ldflags:
              - -s -w
              - -extldflags "-static"
            main: ./cmd/functions/async_message_handler
            fromImage: golang:1.24-bullseye

    manifests:
      kustomize:
        paths:
          - deploy/environments/dev/kustomize

    deploy:
      kubectl:
        defaultNamespace: dev
