ALTER TABLE households ADD COLUMN "address_line_1" TEXT NOT NULL DEFAULT '';
ALTER TABLE households ADD COLUMN "address_line_2" TEXT NOT NULL DEFAULT '';
ALTER TABLE households ADD COLUMN "city" TEXT NOT NULL DEFAULT '';
ALTER TABLE households ADD COLUMN "state" TEXT NOT NULL DEFAULT '';
ALTER TABLE households ADD COLUMN "zip_code" TEXT NOT NULL DEFAULT '';
ALTER TABLE households ADD COLUMN "latitude" TEXT NOT NULL DEFAULT '';
ALTER TABLE households ADD COLUMN "longitude" TEXT NOT NULL DEFAULT '';
ALTER TABLE households DROP COLUMN IF EXISTS "contact_email";