---
apiVersion: skaffold/v4beta11
kind: Config

metadata:
  name: dinner-done-better-infra

profiles:
  # localdev profile - uses plain K8s manifests, no Helm required
  - name: localdev
    activation:
      - kubeContext: docker-desktop
    manifests:
      kustomize:
        paths:
          - infra/deploy/environments/localdev/kustomize
    deploy:
      kubeContext: docker-desktop
      kubectl:
        defaultNamespace: localdev

  - name: dev
    manifests:
      kustomize:
        paths:
          - infra/deploy/environments/dev/kustomize

    deploy:
      kubectl:
        defaultNamespace: dev
