version: "3.8"
services:
    workers:
        container_name: integration_tests_workers
        build:
            context: '../../../../'
            dockerfile: 'environments/testing/dockerfiles/workers.Dockerfile'
        environment:
            CONFIGURATION_FILEPATH: '/etc/service.config'
            PRIXFIXE_WORKERS_LOCAL_CONFIG_STORE_KEY: 'SUFNQVdBUkVUSEFUVEhJU1NFQ1JFVElTVU5TRUNVUkU='
        volumes:
            - source: '../../../../environments/testing/config_files/integration-tests-postgres.config'
              target: '/etc/service.config'
              type: 'bind'
    prixfixe_api_server:
        hostname: api_server
        container_name: integration_tests_server
#        logging:
#            driver: none
        depends_on:
            - workers
        links:
            - redis
            - postgres
            - elasticsearch
        environment:
            USE_NOOP_LOGGER: 'nope'
            CONFIGURATION_FILEPATH: '/etc/service.config'
            PRIXFIXE_SERVER_LOCAL_CONFIG_STORE_KEY: 'SUFNQVdBUkVUSEFUVEhJU1NFQ1JFVElTVU5TRUNVUkU='
        ports:
            - '8888:8888'
        build:
            context: '../../../../'
            dockerfile: 'environments/testing/dockerfiles/integration-server.Dockerfile'
        volumes:
            - source: '../../../../environments/testing/config_files/integration-tests-postgres.config'
              target: '/etc/service.config'
              type: 'bind'
    test:
        environment:
            TARGET_ADDRESS: 'http://api_server:8888'
        depends_on:
            - workers
        links:
            - prixfixe_api_server
        build:
            context: '../../../../'
            dockerfile: 'environments/testing/dockerfiles/integration-tests.Dockerfile'
        container_name: 'integration_tests'
