version: '3.3'
services:
    coverage-server:
        environment:
            CONFIGURATION_FILEPATH: '/etc/config.toml'
            RUNTIME_DURATION: '30s'
        ports:
            - 80:8888
        links:
            - database
        volumes:
            - source: '../../../../artifacts/'
              target: '/home/'
              type: 'bind'
            - source: '../../../../environments/testing/config_files/coverage.toml'
              target: '/etc/config.toml'
              type: 'bind'
        build:
            context: '../../../../'
            dockerfile: 'environments/testing/dockerfiles/integration-coverage-server.Dockerfile'
    database:
        image: postgres:latest
        environment:
            POSTGRES_DB: 'prixfixe'
            POSTGRES_PASSWORD: 'hunter2'
            POSTGRES_USER: 'dbuser'
        logging:
            driver: none
        ports:
            - 2345:5432
    test:
        environment:
            JAEGER_AGENT_HOST: 'tracing-server'
            JAEGER_AGENT_PORT: '6831'
            JAEGER_SAMPLER_MANAGER_HOST_PORT: 'tracing-server:5778'
            JAEGER_SERVICE_NAME: 'coverage-server'
            TARGET_ADDRESS: 'http://coverage-server'
            DB_ADDRESS: 'postgres://dbuser:hunter2@database:5432/prixfixe?sslmode=disable'
            WAIT_FOR_COVERAGE: 'yes'
        links:
            - coverage-server
        build:
            context: '../../../../'
            dockerfile: 'environments/testing/dockerfiles/integration-tests.Dockerfile'
