ALTER TABLE valid_ingredient_measurement_units DROP CONSTRAINT valid_ingredient_measurement__valid_ingredient_id_valid_mea_key;
ALTER TABLE valid_ingredient_measurement_units ADD CONSTRAINT valid_ingredient_measurement__valid_ingredient_id_valid_mea_key unique(valid_ingredient_id,valid_measurement_unit_id,archived_on);

ALTER TABLE valid_ingredient_preparations DROP CONSTRAINT valid_ingredient_preparations_valid_preparation_id_valid_in_key;
ALTER TABLE valid_ingredient_preparations ADD CONSTRAINT valid_ingredient_preparations_valid_preparation_id_valid_in_key unique(valid_preparation_id,valid_ingredient_id,archived_on);

ALTER TABLE valid_preparation_instruments DROP CONSTRAINT valid_preparation_instruments_valid_preparation_id_valid_in_key;
ALTER TABLE valid_preparation_instruments ADD CONSTRAINT valid_preparation_instruments_valid_preparation_id_valid_in_key unique(valid_preparation_id,valid_instrument_id,archived_on);
