---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dinner-done-better-webapp-deployment
  labels:
    app: dinner-done-better-webapp
spec:
  selector:
    matchLabels:
      app: dinner-done-better-webapp
      app.kubernetes.io/name: dinner-done-better-webapp
  replicas: 1
  template:
    metadata:
      labels:
        app: dinner-done-better-webapp
        app.kubernetes.io/name: dinner-done-better-webapp
    spec:
      containers:
        - name: dinner-done-better-webapp
          image: dinner-done-better-webapp
          imagePullPolicy: IfNotPresent
          env:
            - name: "DISABLE_REGISTRATION"
              value: "false"
            - name: "NEXT_API_ENDPOINT"
              value: "dinner-done-better.dev.svc.cluster.local:8000"
          ports:
            - containerPort: 9000
              name: http
          volumeMounts:
            - name: "routingcfg"
              mountPath: "routingcfg.json"
              subPath: "routingcfg.json"
          livenessProbe:
            httpGet:
              path: "/api/_meta_/live"
              port: 9000
            initialDelaySeconds: 15
            periodSeconds: 32
          readinessProbe:
            httpGet:
              path: "/api/_meta_/ready"
              port: 9000
            initialDelaySeconds: 15
            periodSeconds: 3
            # This is the OpenTelemetry collector sidecar
        - name: opentelemetry-collector
          image: otel/opentelemetry-collector-contrib:0.115.1
          command:
            - "/otelcol-contrib"
            - "--routingcfg"
            - "/conf/routingcfg.yaml"
          ports:
            - containerPort: 4317
              name: otel1
            - containerPort: 4318
              name: otel2
            - containerPort: 13313
              name: health
          volumeMounts:
            - name: logs
              mountPath: /var/log/application
              readOnly: true
            - name: opentelemetry-routingcfg
              mountPath: /conf
          env:
            - name: "RUNNING_IN_KUBERNETES"
              value: "true"
      volumes:
        # this volume contains the configuration file for the API service
        - name: "routingcfg"
          configMap:
            name: "frontend-service-config"
        - name: logs
          emptyDir:
            sizeLimit: 500Mi
        - name: opentelemetry-routingcfg
          configMap:
            name: opentelemetry-collector-routingcfg
---
