---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dinner-done-better-webapp-deployment
  labels:
    app: dinner-done-better-webapp
spec:
  selector:
    matchLabels:
      app: dinner-done-better-webapp
      app.kubernetes.io/name: dinner-done-better-webapp
  replicas: 1
  template:
    metadata:
      labels:
        app: dinner-done-better-webapp
        app.kubernetes.io/name: dinner-done-better-webapp
    spec:
      containers:
        - name: dinner-done-better-webapp
          image: dinner-done-better-webapp
          imagePullPolicy: Always
          env:
            - name: "RUNNING_IN_KUBERNETES"
              value: "true"
          ports:
            - containerPort: 9000
              name: http
          volumeMounts:
            - name: "config"
              mountPath: "/app/apps/web/config.json"
              subPath: "config.json"
          livenessProbe:
            httpGet:
              path: "/api/_ops_/live"
              port: 9000
            initialDelaySeconds: 15
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: "/api/_ops_/ready"
              port: 9000
            initialDelaySeconds: 15
            periodSeconds: 5
          resources:
            requests:
              cpu: "128m"
              memory: "128Mi"
            limits:
              cpu: "256m"
              memory: "256Mi"
      volumes:
        # this volume contains the configuration file for the API service
        - name: "config"
          configMap:
            name: "frontend-service-config"
---
