package main

import (
	"github.com/dinnerdonebetter/backend/pkg/types"
)

type routeDetails struct {
	ResponseType  any
	InputType     any
	ID            string
	Description   string
	InputTypeName string
	OAuth2Scopes  []string
	Authless      bool
	ListRoute     bool
	SearchRoute   bool
}

const (
	serviceAdmin    = "service_admin"
	householdAdmin  = "household_admin"
	householdMember = "household_member"
)

var routeInfoMap = map[string]routeDetails{
	"GET /_meta_/live": {
		ID:          "CheckForLiveness",
		Description: "checks for service liveness",
		Authless:    true,
	},
	"GET /_meta_/ready": {
		ID:          "CheckForReadiness",
		Description: "checks for service readiness",
		Authless:    true,
	},
	"DELETE /api/v1/data_privacy/destroy": {
		ID:           "DestroyAllUserData",
		Description:  "Destroys a user's data",
		ResponseType: &types.DataDeletionResponse{},
		OAuth2Scopes: []string{householdMember},
	},
	"POST /api/v1/data_privacy/disclose": {
		ID:           "AggregateUserDataReport",
		Description:  "Aggregates a user's data into a big disclosure blob",
		ResponseType: &types.UserDataCollectionResponse{},
		OAuth2Scopes: []string{householdMember},
	},
	"GET /api/v1/data_privacy/reports/{userDataAggregationReportID}": {
		ID:           "FetchUserDataReport",
		Description:  "Reads a user's data report from storage",
		ResponseType: &types.UserDataCollection{},
		OAuth2Scopes: []string{householdMember},
	},
	"POST /api/v1/admin/users/status": {
		ID:           "AdminUpdateUserStatus",
		Description:  "Updates a user's account status",
		InputType:    &types.UserAccountStatusUpdateInput{},
		ResponseType: &types.UserStatusResponse{},
		OAuth2Scopes: []string{serviceAdmin},
	},
	"POST /api/v1/admin/queues/test": {
		ID:           "PublishArbitraryQueueMessage",
		Description:  "Publishes an arbitrary message onto a queue",
		InputType:    &types.ArbitraryQueueMessageRequestInput{},
		ResponseType: &types.ArbitraryQueueMessageResponse{},
		OAuth2Scopes: []string{serviceAdmin},
	},
	"GET /api/v1/audit_log_entries/for_household": {
		ID:           "GetAuditLogEntriesForHousehold",
		Description:  "Retrieves audit log entries for a household",
		ResponseType: []*types.AuditLogEntry{},
		ListRoute:    true,
		OAuth2Scopes: []string{householdAdmin},
	},
	"GET /api/v1/audit_log_entries/for_user": {
		ID:           "GetAuditLogEntriesForUser",
		Description:  "Retrieves audit log entries for a user",
		ResponseType: []*types.AuditLogEntry{},
		ListRoute:    true,
		OAuth2Scopes: []string{householdMember},
	},
	"GET /api/v1/audit_log_entries/{auditLogEntryID}": {
		ID:           "GetAuditLogEntryByID",
		Description:  "Retrieves an audit log entry by ID",
		ResponseType: &types.AuditLogEntry{},
		OAuth2Scopes: []string{householdMember},
	},
	"GET /api/v1/household_invitations/received": {
		ID:           "GetReceivedHouseholdInvitations",
		Description:  "Fetches received household invitations",
		ResponseType: &types.HouseholdInvitation{},
		ListRoute:    true,
		OAuth2Scopes: []string{householdMember},
	},
	"GET /api/v1/household_invitations/sent": {
		ID:           "GetSentHouseholdInvitations",
		Description:  "Fetches sent household invitations",
		ResponseType: &types.HouseholdInvitation{},
		ListRoute:    true,
		OAuth2Scopes: []string{householdMember},
	},
	"GET /api/v1/household_invitations/{householdInvitationID}/": {
		ID:           "GetHouseholdInvitation",
		Description:  "Fetches household invitations for a given household",
		ResponseType: &types.HouseholdInvitation{},
		OAuth2Scopes: []string{householdMember},
	},
	"PUT /api/v1/household_invitations/{householdInvitationID}/accept": {
		ID:           "AcceptHouseholdInvitation",
		Description:  "Accepts a received household invitation",
		ResponseType: &types.HouseholdInvitation{},
		InputType:    &types.HouseholdInvitationUpdateRequestInput{},
		OAuth2Scopes: []string{householdMember},
	},
	"PUT /api/v1/household_invitations/{householdInvitationID}/cancel": {
		ID:           "CancelHouseholdInvitation",
		Description:  "Cancels a sent household invitation",
		ResponseType: &types.HouseholdInvitation{},
		InputType:    &types.HouseholdInvitationUpdateRequestInput{},
		OAuth2Scopes: []string{householdMember},
	},
	"PUT /api/v1/household_invitations/{householdInvitationID}/reject": {
		ID:           "RejectHouseholdInvitation",
		Description:  "Rejects a received household invitation",
		ResponseType: &types.HouseholdInvitation{},
		InputType:    &types.HouseholdInvitationUpdateRequestInput{},
		OAuth2Scopes: []string{householdMember},
	},
	"GET /api/v1/households/": {
		ID:           "GetHouseholds",
		Description:  "Fetches a list of households",
		ResponseType: &types.Household{},
		ListRoute:    true,
		OAuth2Scopes: []string{householdMember},
	},
	"POST /api/v1/households/": {
		ID:           "CreateHousehold",
		Description:  "Creates a household",
		ResponseType: &types.Household{},
		InputType:    &types.HouseholdCreationRequestInput{},
		OAuth2Scopes: []string{householdMember},
	},
	"GET /api/v1/households/current": {
		ID:           "GetActiveHousehold",
		Description:  "Fetches the currently active household",
		ResponseType: &types.Household{},
		OAuth2Scopes: []string{householdMember},
	},
	"POST /api/v1/households/instruments/": {
		ID:           "CreateHouseholdInstrumentOwnership",
		Description:  "Creates a household instrument ownership",
		ResponseType: &types.HouseholdInstrumentOwnership{},
		InputType:    &types.HouseholdInstrumentOwnershipCreationRequestInput{},
		OAuth2Scopes: []string{householdAdmin},
	},
	"GET /api/v1/households/instruments/": {
		ID:           "GetHouseholdInstrumentOwnerships",
		Description:  "creates a household instrument",
		ResponseType: &types.HouseholdInstrumentOwnership{},
		OAuth2Scopes: []string{householdMember},
		ListRoute:    true,
	},
	"GET /api/v1/households/instruments/{householdInstrumentOwnershipID}/": {
		ID:           "GetHouseholdInstrumentOwnership",
		Description:  "Fetches a household instrument ownership",
		ResponseType: &types.HouseholdInstrumentOwnership{},
		OAuth2Scopes: []string{householdMember},
	},
	"PUT /api/v1/households/instruments/{householdInstrumentOwnershipID}/": {
		ID:           "UpdateHouseholdInstrumentOwnership",
		Description:  "Updates a household instrument ownership",
		ResponseType: &types.HouseholdInstrumentOwnership{},
		InputType:    &types.HouseholdInstrumentOwnershipUpdateRequestInput{},
		OAuth2Scopes: []string{householdAdmin},
	},
	"DELETE /api/v1/households/instruments/{householdInstrumentOwnershipID}/": {
		ID:           "ArchiveHouseholdInstrumentOwnership",
		Description:  "Archives a household instrument ownership",
		ResponseType: &types.HouseholdInstrumentOwnership{},
		OAuth2Scopes: []string{householdAdmin},
	},
	"PUT /api/v1/households/{householdID}/": {
		ID:           "UpdateHousehold",
		Description:  "Updates a household",
		ResponseType: &types.Household{},
		InputType:    &types.HouseholdUpdateRequestInput{},
		OAuth2Scopes: []string{householdAdmin},
	},
	"DELETE /api/v1/households/{householdID}/": {
		ID:           "ArchiveHousehold",
		Description:  "Archives a household",
		ResponseType: &types.Household{},
		OAuth2Scopes: []string{householdAdmin},
	},
	"GET /api/v1/households/{householdID}/": {
		ID:           "GetHousehold",
		Description:  "Fetches a household",
		ResponseType: &types.Household{},
		OAuth2Scopes: []string{householdMember},
	},
	"POST /api/v1/households/{householdID}/default": {
		ID:           "SetDefaultHousehold",
		Description:  "Updates the default household assigned at login",
		ResponseType: &types.Household{},
		OAuth2Scopes: []string{householdMember},
	},
	"GET /api/v1/households/{householdID}/invitations/{householdInvitationID}/": {
		ID:           "GetHouseholdInvitationByID",
		Description:  "Fetches a household invitation by its ID",
		ResponseType: &types.HouseholdInvitation{},
		OAuth2Scopes: []string{householdMember},
	},
	// these are duplicate routes lol
	"POST /api/v1/households/{householdID}/invite": {
		ID:           "CreateHouseholdInvitation",
		Description:  "Create a household invitation",
		ResponseType: &types.HouseholdInvitation{},
		InputType:    &types.HouseholdInvitationCreationRequestInput{},
		OAuth2Scopes: []string{householdAdmin},
	},
	"DELETE /api/v1/households/{householdID}/members/{userID}": {
		ID:           "ArchiveUserMembership",
		Description:  "Archive a household user membership",
		ResponseType: &types.HouseholdUserMembership{},
		OAuth2Scopes: []string{householdAdmin},
	},
	"PATCH /api/v1/households/{householdID}/members/{userID}/permissions": {
		ID:           "UpdateHouseholdMemberPermissions",
		Description:  "Update a household member's household permissions",
		ResponseType: &types.UserPermissionsResponse{},
		InputType:    &types.ModifyUserPermissionsInput{},
		OAuth2Scopes: []string{householdAdmin},
	},
	"POST /api/v1/households/{householdID}/transfer": {
		ID:           "TransferHouseholdOwnership",
		Description:  "Transfer household ownership to another user",
		ResponseType: &types.Household{},
		InputType:    &types.HouseholdOwnershipTransferInput{},
		OAuth2Scopes: []string{householdAdmin},
	},
	"GET /api/v1/meal_plans/{mealPlanID}/events/{mealPlanEventID}/options/{mealPlanOptionID}/votes/": {
		ID:           "GetMealPlanOptionVotes",
		Description:  "Fetches a meal plan option's votes",
		ResponseType: &types.MealPlanOptionVote{},
		ListRoute:    true,
		OAuth2Scopes: []string{householdMember},
	},
	"PUT /api/v1/meal_plans/{mealPlanID}/events/{mealPlanEventID}/options/{mealPlanOptionID}/votes/{mealPlanOptionVoteID}/": {
		ID:           "UpdateMealPlanOptionVote",
		Description:  "Updates a meal plan option vote",
		ResponseType: &types.MealPlanOptionVote{},
		InputType:    &types.MealPlanOptionVoteUpdateRequestInput{},
		OAuth2Scopes: []string{householdMember},
	},
	"DELETE /api/v1/meal_plans/{mealPlanID}/events/{mealPlanEventID}/options/{mealPlanOptionID}/votes/{mealPlanOptionVoteID}/": {
		ID:           "ArchiveMealPlanOptionVote",
		Description:  "Archives a meal plan option vote",
		ResponseType: &types.MealPlanOptionVote{},
		OAuth2Scopes: []string{householdMember},
	},
	"GET /api/v1/meal_plans/{mealPlanID}/events/{mealPlanEventID}/options/{mealPlanOptionID}/votes/{mealPlanOptionVoteID}/": {
		ID:           "GetMealPlanOptionVote",
		Description:  "Fetches a meal plan option vote",
		ResponseType: &types.MealPlanOptionVote{},
		OAuth2Scopes: []string{householdMember},
	},
	"POST /api/v1/meal_plans/{mealPlanID}/events/{mealPlanEventID}/options/": {
		ID:           "CreateMealPlanOption",
		Description:  "Creates a meal plan option",
		ResponseType: &types.MealPlanOption{},
		InputType:    &types.MealPlanOptionCreationRequestInput{},
		OAuth2Scopes: []string{householdAdmin},
	},
	"GET /api/v1/meal_plans/{mealPlanID}/events/{mealPlanEventID}/options/": {
		ID:           "GetMealPlanOptions",
		Description:  "Fetches a meal plan's options",
		ResponseType: &types.MealPlanOption{},
		ListRoute:    true,
		OAuth2Scopes: []string{householdMember},
	},
	"GET /api/v1/meal_plans/{mealPlanID}/events/{mealPlanEventID}/options/{mealPlanOptionID}/": {
		ID:           "GetMealPlanOption",
		Description:  "Fetches a meal plan option by its ID",
		ResponseType: &types.MealPlanOption{},
		OAuth2Scopes: []string{householdMember},
	},
	"PUT /api/v1/meal_plans/{mealPlanID}/events/{mealPlanEventID}/options/{mealPlanOptionID}/": {
		ID:           "UpdateMealPlanOption",
		Description:  "Updates a meal plan option",
		ResponseType: &types.MealPlanOption{},
		InputType:    &types.MealPlanOptionUpdateRequestInput{},
		OAuth2Scopes: []string{householdAdmin},
	},
	"DELETE /api/v1/meal_plans/{mealPlanID}/events/{mealPlanEventID}/options/{mealPlanOptionID}/": {
		ID:           "ArchiveMealPlanOption",
		Description:  "Archives a MealPlanOption",
		ResponseType: &types.MealPlanOption{},
		OAuth2Scopes: []string{householdAdmin},
	},
	"POST /api/v1/meal_plans/{mealPlanID}/events/": {
		ID:           "CreateMealPlanEvent",
		Description:  "Creates a MealPlanEvent",
		ResponseType: &types.MealPlanEvent{},
		InputType:    &types.MealPlanEventCreationRequestInput{},
		OAuth2Scopes: []string{householdAdmin},
	},
	"GET /api/v1/meal_plans/{mealPlanID}/events/": {
		ID:           "GetMealPlanEvents",
		Description:  "Fetches a MealPlanEvents",
		ResponseType: &types.MealPlanEvent{},
		ListRoute:    true,
		OAuth2Scopes: []string{householdMember},
	},
	"PUT /api/v1/meal_plans/{mealPlanID}/events/{mealPlanEventID}/": {
		ID:           "UpdateMealPlanEvent",
		Description:  "Updates a MealPlanEvent",
		ResponseType: &types.MealPlanEvent{},
		InputType:    &types.MealPlanEventUpdateRequestInput{},
		OAuth2Scopes: []string{householdAdmin},
	},
	"DELETE /api/v1/meal_plans/{mealPlanID}/events/{mealPlanEventID}/": {
		ID:           "ArchiveMealPlanEvent",
		Description:  "Archives a MealPlanEvent",
		ResponseType: &types.MealPlanEvent{},
		OAuth2Scopes: []string{householdAdmin},
	},
	"GET /api/v1/meal_plans/{mealPlanID}/events/{mealPlanEventID}/": {
		ID:           "GetMealPlanEvent",
		Description:  "Fetches a MealPlanEvent",
		ResponseType: &types.MealPlanEvent{},
		OAuth2Scopes: []string{householdMember},
	},
	"POST /api/v1/meal_plans/{mealPlanID}/events/{mealPlanEventID}/vote": {
		ID:           "CreateMealPlanOptionVote",
		Description:  "Creates a MealPlanOptionVote",
		ResponseType: []types.MealPlanOptionVote{},
		InputType:    &types.MealPlanOptionVoteCreationRequestInput{},
		OAuth2Scopes: []string{householdMember},
	},
	"GET /api/v1/meal_plans/{mealPlanID}/grocery_list_items/": {
		ID:           "GetMealPlanGroceryListItemsForMealPlan",
		Description:  "Fetches a MealPlanGroceryListItemsForMealPlan",
		ResponseType: &types.MealPlanGroceryListItem{},
		ListRoute:    true,
		OAuth2Scopes: []string{householdMember},
	},
	"POST /api/v1/meal_plans/{mealPlanID}/grocery_list_items/": {
		ID:           "CreateMealPlanGroceryListItem",
		Description:  "Creates a MealPlanGroceryListItem",
		ResponseType: &types.MealPlanGroceryListItem{},
		InputType:    &types.MealPlanGroceryListItemCreationRequestInput{},
		OAuth2Scopes: []string{serviceAdmin},
	},
	"GET /api/v1/meal_plans/{mealPlanID}/grocery_list_items/{mealPlanGroceryListItemID}/": {
		ID:           "GetMealPlanGroceryListItem",
		Description:  "Fetches a MealPlanGroceryListItem",
		ResponseType: &types.MealPlanGroceryListItem{},
		OAuth2Scopes: []string{householdMember},
	},
	"PUT /api/v1/meal_plans/{mealPlanID}/grocery_list_items/{mealPlanGroceryListItemID}/": {
		ID:           "UpdateMealPlanGroceryListItem",
		Description:  "Updates a MealPlanGroceryListItem",
		ResponseType: &types.MealPlanGroceryListItem{},
		InputType:    &types.MealPlanGroceryListItemUpdateRequestInput{},
		OAuth2Scopes: []string{householdMember},
	},
	"DELETE /api/v1/meal_plans/{mealPlanID}/grocery_list_items/{mealPlanGroceryListItemID}/": {
		ID:           "ArchiveMealPlanGroceryListItem",
		Description:  "Archives a MealPlanGroceryListItem",
		ResponseType: &types.MealPlanGroceryListItem{},
		OAuth2Scopes: []string{householdMember},
	},
	"GET /api/v1/meal_plans/{mealPlanID}/tasks/": {
		ID:           "GetMealPlanTasks",
		Description:  "Fetches a MealPlanTasks",
		ResponseType: &types.MealPlanTask{},
		ListRoute:    true,
		OAuth2Scopes: []string{householdMember},
	},
	"POST /api/v1/meal_plans/{mealPlanID}/tasks/": {
		ID:           "CreateMealPlanTask",
		Description:  "Creates a MealPlanTask",
		ResponseType: &types.MealPlanTask{},
		InputType:    &types.MealPlanTaskCreationRequestInput{},
		OAuth2Scopes: []string{serviceAdmin},
	},
	"GET /api/v1/meal_plans/{mealPlanID}/tasks/{mealPlanTaskID}/": {
		ID:           "GetMealPlanTask",
		Description:  "Fetches a MealPlanTask",
		ResponseType: &types.MealPlanTask{},
		OAuth2Scopes: []string{householdMember},
	},
	"PATCH /api/v1/meal_plans/{mealPlanID}/tasks/{mealPlanTaskID}/": {
		ID:           "UpdateMealPlanTaskStatus",
		Description:  "Updates a MealPlanTaskStatus",
		ResponseType: &types.MealPlanTask{},
		InputType:    &types.MealPlanTaskStatusChangeRequestInput{},
		OAuth2Scopes: []string{householdMember},
	},
	"POST /api/v1/meal_plans/": {
		ID:           "CreateMealPlan",
		Description:  "Creates a MealPlan",
		ResponseType: &types.MealPlan{},
		InputType:    &types.MealPlanCreationRequestInput{},
		OAuth2Scopes: []string{householdAdmin},
	},
	"GET /api/v1/meal_plans/": {
		ID:           "GetMealPlansForHousehold",
		Description:  "Fetches a MealPlans",
		ResponseType: &types.MealPlan{},
		ListRoute:    true,
		OAuth2Scopes: []string{householdMember},
	},
	"GET /api/v1/meal_plans/{mealPlanID}/": {
		ID:           "GetMealPlan",
		Description:  "Fetches a MealPlan",
		ResponseType: &types.MealPlan{},
		OAuth2Scopes: []string{householdMember},
	},
	"PUT /api/v1/meal_plans/{mealPlanID}/": {
		ID:           "UpdateMealPlan",
		Description:  "Updates a MealPlan",
		ResponseType: &types.MealPlan{},
		InputType:    &types.MealPlanUpdateRequestInput{},
		OAuth2Scopes: []string{householdAdmin},
	},
	"DELETE /api/v1/meal_plans/{mealPlanID}/": {
		ID:           "ArchiveMealPlan",
		Description:  "Archives a MealPlan",
		ResponseType: &types.MealPlan{},
		OAuth2Scopes: []string{householdAdmin},
	},
	"POST /api/v1/meal_plans/{mealPlanID}/finalize": {
		ID:           "FinalizeMealPlan",
		Description:  "Finalizes a meal plan",
		ResponseType: &types.FinalizeMealPlansResponse{},
		OAuth2Scopes: []string{householdAdmin},
		// No input type for this route
	},
	"POST /api/v1/meals/": {
		ID:           "CreateMeal",
		Description:  "Creates a Meal",
		ResponseType: &types.Meal{},
		InputType:    &types.MealCreationRequestInput{},
		OAuth2Scopes: []string{householdMember},
	},
	"GET /api/v1/meals/": {
		ID:           "GetMeals",
		Description:  "Fetches a MealPlanning",
		ResponseType: &types.Meal{},
		ListRoute:    true,
		OAuth2Scopes: []string{householdMember},
	},
	"GET /api/v1/meals/search": {
		ID:           "SearchForMeals",
		Description:  "Searches for MealPlanning",
		SearchRoute:  true,
		ResponseType: &types.Meal{},
		OAuth2Scopes: []string{householdMember},
	},
	"DELETE /api/v1/meals/{mealID}/": {
		ID:           "ArchiveMeal",
		Description:  "Archives a Meal",
		ResponseType: &types.Meal{},
		OAuth2Scopes: []string{householdMember},
	},
	"GET /api/v1/meals/{mealID}/": {
		ID:           "GetMeal",
		Description:  "Fetches a Meal",
		ResponseType: &types.Meal{},
		OAuth2Scopes: []string{householdMember},
	},
	"GET /api/v1/oauth2_clients/": {
		ID:           "GetOAuth2Clients",
		Description:  "Fetches a OAuth2Clients",
		ResponseType: &types.OAuth2Client{},
		ListRoute:    true,
		OAuth2Scopes: []string{householdMember},
	},
	"POST /api/v1/oauth2_clients/": {
		ID:           "CreateOAuth2Client",
		Description:  "Creates a OAuth2Client",
		ResponseType: &types.OAuth2ClientCreationResponse{},
		InputType:    &types.OAuth2ClientCreationRequestInput{},
		OAuth2Scopes: []string{serviceAdmin},
	},
	"GET /api/v1/oauth2_clients/{oauth2ClientID}/": {
		ID:           "GetOAuth2Client",
		Description:  "Fetches a OAuth2Client",
		ResponseType: &types.OAuth2Client{},
		OAuth2Scopes: []string{householdMember},
	},
	"DELETE /api/v1/oauth2_clients/{oauth2ClientID}/": {
		ID:           "ArchiveOAuth2Client",
		Description:  "Archives a OAuth2Client",
		ResponseType: &types.OAuth2Client{},
		OAuth2Scopes: []string{serviceAdmin},
	},
	"POST /api/v1/recipes/{recipeID}/prep_tasks/": {
		ID:           "CreateRecipePrepTask",
		Description:  "Creates a RecipePrepTask",
		ResponseType: &types.RecipePrepTask{},
		InputType:    &types.RecipePrepTaskCreationRequestInput{},
		OAuth2Scopes: []string{householdMember},
	},
	"GET /api/v1/recipes/{recipeID}/prep_tasks/": {
		ID:           "GetRecipePrepTasks",
		Description:  "Fetches a RecipePrepTasks",
		ResponseType: &types.RecipePrepTask{},
		ListRoute:    true,
		OAuth2Scopes: []string{householdMember},
	},
	"DELETE /api/v1/recipes/{recipeID}/prep_tasks/{recipePrepTaskID}/": {
		ID:           "ArchiveRecipePrepTask",
		Description:  "Archives a RecipePrepTask",
		ResponseType: &types.RecipePrepTask{},
		OAuth2Scopes: []string{householdMember},
	},
	"GET /api/v1/recipes/{recipeID}/prep_tasks/{recipePrepTaskID}/": {
		ID:           "GetRecipePrepTask",
		Description:  "Fetches a RecipePrepTask",
		ResponseType: &types.RecipePrepTask{},
		OAuth2Scopes: []string{householdMember},
	},
	"PUT /api/v1/recipes/{recipeID}/prep_tasks/{recipePrepTaskID}/": {
		ID:           "UpdateRecipePrepTask",
		Description:  "Updates a RecipePrepTask",
		ResponseType: &types.RecipePrepTask{},
		InputType:    &types.RecipePrepTaskUpdateRequestInput{},
		OAuth2Scopes: []string{householdMember},
	},
	"GET /api/v1/recipes/{recipeID}/steps/{recipeStepID}/completion_conditions/": {
		ID:           "GetRecipeStepCompletionConditions",
		Description:  "Fetches a RecipeStepCompletionConditions",
		ResponseType: &types.RecipeStepCompletionCondition{},
		ListRoute:    true,
		OAuth2Scopes: []string{householdMember},
	},
	"POST /api/v1/recipes/{recipeID}/steps/{recipeStepID}/completion_conditions/": {
		ID:           "CreateRecipeStepCompletionCondition",
		Description:  "Creates a RecipeStepCompletionCondition",
		ResponseType: &types.RecipeStepCompletionCondition{},
		InputType:    &types.RecipeStepCompletionConditionForExistingRecipeCreationRequestInput{},
		OAuth2Scopes: []string{householdMember},
	},
	"PUT /api/v1/recipes/{recipeID}/steps/{recipeStepID}/completion_conditions/{recipeStepCompletionConditionID}/": {
		ID:           "UpdateRecipeStepCompletionCondition",
		Description:  "Updates a RecipeStepCompletionCondition",
		ResponseType: &types.RecipeStepCompletionCondition{},
		InputType:    &types.RecipeStepCompletionConditionUpdateRequestInput{},
		OAuth2Scopes: []string{householdMember},
	},
	"DELETE /api/v1/recipes/{recipeID}/steps/{recipeStepID}/completion_conditions/{recipeStepCompletionConditionID}/": {
		ID:           "ArchiveRecipeStepCompletionCondition",
		Description:  "Archives a RecipeStepCompletionCondition",
		ResponseType: &types.RecipeStepCompletionCondition{},
		OAuth2Scopes: []string{householdMember},
	},
	"GET /api/v1/recipes/{recipeID}/steps/{recipeStepID}/completion_conditions/{recipeStepCompletionConditionID}/": {
		ID:           "GetRecipeStepCompletionCondition",
		Description:  "Fetches a RecipeStepCompletionCondition",
		ResponseType: &types.RecipeStepCompletionCondition{},
		OAuth2Scopes: []string{householdMember},
	},
	"POST /api/v1/recipes/{recipeID}/steps/{recipeStepID}/ingredients/": {
		ID:           "CreateRecipeStepIngredient",
		Description:  "Creates a RecipeStepIngredient",
		ResponseType: &types.RecipeStepIngredient{},
		InputType:    &types.RecipeStepIngredientCreationRequestInput{},
		OAuth2Scopes: []string{householdMember},
	},
	"GET /api/v1/recipes/{recipeID}/steps/{recipeStepID}/ingredients/": {
		ID:           "GetRecipeStepIngredients",
		Description:  "Fetches a RecipeStepIngredients",
		ResponseType: &types.RecipeStepIngredient{},
		ListRoute:    true,
		OAuth2Scopes: []string{householdMember},
	},
	"GET /api/v1/recipes/{recipeID}/steps/{recipeStepID}/ingredients/{recipeStepIngredientID}/": {
		ID:           "GetRecipeStepIngredient",
		Description:  "Fetches a RecipeStepIngredient",
		ResponseType: &types.RecipeStepIngredient{},
		OAuth2Scopes: []string{householdMember},
	},
	"PUT /api/v1/recipes/{recipeID}/steps/{recipeStepID}/ingredients/{recipeStepIngredientID}/": {
		ID:           "UpdateRecipeStepIngredient",
		Description:  "Updates a RecipeStepIngredient",
		ResponseType: &types.RecipeStepIngredient{},
		InputType:    &types.RecipeStepIngredientUpdateRequestInput{},
		OAuth2Scopes: []string{householdMember},
	},
	"DELETE /api/v1/recipes/{recipeID}/steps/{recipeStepID}/ingredients/{recipeStepIngredientID}/": {
		ID:           "ArchiveRecipeStepIngredient",
		Description:  "Archives a RecipeStepIngredient",
		ResponseType: &types.RecipeStepIngredient{},
		OAuth2Scopes: []string{householdMember},
	},
	"POST /api/v1/recipes/{recipeID}/steps/{recipeStepID}/instruments/": {
		ID:           "CreateRecipeStepInstrument",
		Description:  "Creates a RecipeStepInstrument",
		ResponseType: &types.RecipeStepInstrument{},
		InputType:    &types.RecipeStepInstrumentCreationRequestInput{},
		OAuth2Scopes: []string{householdMember},
	},
	"GET /api/v1/recipes/{recipeID}/steps/{recipeStepID}/instruments/": {
		ID:           "GetRecipeStepInstruments",
		Description:  "Fetches a RecipeStepInstruments",
		ResponseType: &types.RecipeStepInstrument{},
		ListRoute:    true,
		OAuth2Scopes: []string{householdMember},
	},
	"GET /api/v1/recipes/{recipeID}/steps/{recipeStepID}/instruments/{recipeStepInstrumentID}/": {
		ID:           "GetRecipeStepInstrument",
		Description:  "Fetches a RecipeStepInstrument",
		ResponseType: &types.RecipeStepInstrument{},
		OAuth2Scopes: []string{householdMember},
	},
	"PUT /api/v1/recipes/{recipeID}/steps/{recipeStepID}/instruments/{recipeStepInstrumentID}/": {
		ID:           "UpdateRecipeStepInstrument",
		Description:  "Updates a RecipeStepInstrument",
		ResponseType: &types.RecipeStepInstrument{},
		InputType:    &types.RecipeStepInstrumentUpdateRequestInput{},
		OAuth2Scopes: []string{householdMember},
	},
	"DELETE /api/v1/recipes/{recipeID}/steps/{recipeStepID}/instruments/{recipeStepInstrumentID}/": {
		ID:           "ArchiveRecipeStepInstrument",
		Description:  "Archives a RecipeStepInstrument",
		ResponseType: &types.RecipeStepInstrument{},
		OAuth2Scopes: []string{householdMember},
	},
	"GET /api/v1/recipes/{recipeID}/steps/{recipeStepID}/products/": {
		ID:           "GetRecipeStepProducts",
		Description:  "Fetches a RecipeStepProducts",
		ResponseType: &types.RecipeStepProduct{},
		ListRoute:    true,
		OAuth2Scopes: []string{householdMember},
	},
	"POST /api/v1/recipes/{recipeID}/steps/{recipeStepID}/products/": {
		ID:           "CreateRecipeStepProduct",
		Description:  "Creates a RecipeStepProduct",
		ResponseType: &types.RecipeStepProduct{},
		InputType:    &types.RecipeStepProductCreationRequestInput{},
		OAuth2Scopes: []string{householdMember},
	},
	"GET /api/v1/recipes/{recipeID}/steps/{recipeStepID}/products/{recipeStepProductID}/": {
		ID:           "GetRecipeStepProduct",
		Description:  "Fetches a RecipeStepProduct",
		ResponseType: &types.RecipeStepProduct{},
		OAuth2Scopes: []string{householdMember},
	},
	"PUT /api/v1/recipes/{recipeID}/steps/{recipeStepID}/products/{recipeStepProductID}/": {
		ID:           "UpdateRecipeStepProduct",
		Description:  "Updates a RecipeStepProduct",
		ResponseType: &types.RecipeStepProduct{},
		InputType:    &types.RecipeStepProductUpdateRequestInput{},
		OAuth2Scopes: []string{householdMember},
	},
	"DELETE /api/v1/recipes/{recipeID}/steps/{recipeStepID}/products/{recipeStepProductID}/": {
		ID:           "ArchiveRecipeStepProduct",
		Description:  "Archives a RecipeStepProduct",
		ResponseType: &types.RecipeStepProduct{},
		OAuth2Scopes: []string{householdMember},
	},
	"POST /api/v1/recipes/{recipeID}/steps/{recipeStepID}/vessels/": {
		ID:           "CreateRecipeStepVessel",
		Description:  "Creates a RecipeStepVessel",
		ResponseType: &types.RecipeStepVessel{},
		InputType:    &types.RecipeStepVesselCreationRequestInput{},
		OAuth2Scopes: []string{householdMember},
	},
	"GET /api/v1/recipes/{recipeID}/steps/{recipeStepID}/vessels/": {
		ID:           "GetRecipeStepVessels",
		Description:  "Fetches a RecipeStepVessels",
		ResponseType: &types.RecipeStepVessel{},
		ListRoute:    true,
		OAuth2Scopes: []string{householdMember},
	},
	"GET /api/v1/recipes/{recipeID}/steps/{recipeStepID}/vessels/{recipeStepVesselID}/": {
		ID:           "GetRecipeStepVessel",
		Description:  "Fetches a RecipeStepVessel",
		ResponseType: &types.RecipeStepVessel{},
		OAuth2Scopes: []string{householdMember},
	},
	"PUT /api/v1/recipes/{recipeID}/steps/{recipeStepID}/vessels/{recipeStepVesselID}/": {
		ID:           "UpdateRecipeStepVessel",
		Description:  "Updates a RecipeStepVessel",
		ResponseType: &types.RecipeStepVessel{},
		InputType:    &types.RecipeStepVesselUpdateRequestInput{},
		OAuth2Scopes: []string{householdMember},
	},
	"DELETE /api/v1/recipes/{recipeID}/steps/{recipeStepID}/vessels/{recipeStepVesselID}/": {
		ID:           "ArchiveRecipeStepVessel",
		Description:  "Archives a RecipeStepVessel",
		ResponseType: &types.RecipeStepVessel{},
		OAuth2Scopes: []string{householdMember},
	},
	"POST /api/v1/recipes/{recipeID}/steps/": {
		ID:           "CreateRecipeStep",
		Description:  "Creates a RecipeStep",
		ResponseType: &types.RecipeStep{},
		InputType:    &types.RecipeStepCreationRequestInput{},
		OAuth2Scopes: []string{householdMember},
	},
	"GET /api/v1/recipes/{recipeID}/steps/": {
		ID:           "GetRecipeSteps",
		Description:  "Fetches a RecipeSteps",
		ResponseType: &types.RecipeStep{},
		ListRoute:    true,
		OAuth2Scopes: []string{householdMember},
	},
	"DELETE /api/v1/recipes/{recipeID}/steps/{recipeStepID}/": {
		ID:           "ArchiveRecipeStep",
		Description:  "Archives a RecipeStep",
		ResponseType: &types.RecipeStep{},
		OAuth2Scopes: []string{householdMember},
	},
	"GET /api/v1/recipes/{recipeID}/steps/{recipeStepID}/": {
		ID:           "GetRecipeStep",
		Description:  "Fetches a RecipeStep",
		ResponseType: &types.RecipeStep{},
		OAuth2Scopes: []string{householdMember},
	},
	"PUT /api/v1/recipes/{recipeID}/steps/{recipeStepID}/": {
		ID:           "UpdateRecipeStep",
		Description:  "Updates a RecipeStep",
		ResponseType: &types.RecipeStep{},
		InputType:    &types.RecipeStepUpdateRequestInput{},
		OAuth2Scopes: []string{householdMember},
	},
	"POST /api/v1/recipes/": {
		ID:           "CreateRecipe",
		Description:  "Creates a Recipe",
		ResponseType: &types.Recipe{},
		InputType:    &types.RecipeCreationRequestInput{},
		OAuth2Scopes: []string{householdMember},
	},
	"GET /api/v1/recipes/": {
		ID:           "GetRecipes",
		Description:  "Fetches a Recipes",
		ResponseType: &types.Recipe{},
		ListRoute:    true,
		OAuth2Scopes: []string{householdMember},
	},
	"GET /api/v1/recipes/search": {
		ID:           "SearchForRecipes",
		Description:  "Searches for Recipes",
		SearchRoute:  true,
		ResponseType: &types.Recipe{},
		OAuth2Scopes: []string{householdMember},
	},
	"DELETE /api/v1/recipes/{recipeID}/": {
		ID:           "ArchiveRecipe",
		Description:  "Archives a Recipe",
		ResponseType: &types.Recipe{},
		OAuth2Scopes: []string{householdMember},
	},
	"GET /api/v1/recipes/{recipeID}/": {
		ID:           "GetRecipe",
		Description:  "Fetches a Recipe",
		ResponseType: &types.Recipe{},
		OAuth2Scopes: []string{householdMember},
	},
	"PUT /api/v1/recipes/{recipeID}/": {
		ID:           "UpdateRecipe",
		Description:  "Updates a Recipe",
		ResponseType: &types.Recipe{},
		InputType:    &types.RecipeUpdateRequestInput{},
		OAuth2Scopes: []string{householdMember},
	},
	"POST /api/v1/recipes/{recipeID}/clone": {
		ID: "CloneRecipe",
		// No input type for this route
		Description:  "Clones a recipe",
		ResponseType: &types.Recipe{},
		OAuth2Scopes: []string{householdMember},
	},
	"GET /api/v1/recipes/{recipeID}/mermaid": {
		ID:           "GetMermaidDiagramForRecipe",
		Description:  "Fetches a MermaidDiagramForRecipe",
		OAuth2Scopes: []string{householdMember},
		ResponseType: "string",
	},
	"GET /api/v1/recipes/{recipeID}/prep_steps": {
		ID:           "GetRecipeMealPlanTasks",
		Description:  "Fetches a RecipeMealPlanTasks",
		ResponseType: &types.RecipePrepTaskStep{},
		OAuth2Scopes: []string{householdMember},
	},
	"POST /api/v1/recipes/{recipeID}/ratings/": {
		ID:           "CreateRecipeRating",
		Description:  "Creates a RecipeRating",
		ResponseType: &types.RecipeRating{},
		InputType:    &types.RecipeRatingCreationRequestInput{},
		OAuth2Scopes: []string{householdMember},
	},
	"GET /api/v1/recipes/{recipeID}/ratings/": {
		ID:           "GetRecipeRatingsForRecipe",
		Description:  "Fetches a RecipeRatings",
		ResponseType: &types.RecipeRating{},
		ListRoute:    true,
		OAuth2Scopes: []string{householdMember},
	},
	"PUT /api/v1/recipes/{recipeID}/ratings/{recipeRatingID}/": {
		ID:           "UpdateRecipeRating",
		Description:  "Updates a RecipeRating",
		ResponseType: &types.RecipeRating{},
		InputType:    &types.RecipeRatingUpdateRequestInput{},
		OAuth2Scopes: []string{householdMember},
	},
	"DELETE /api/v1/recipes/{recipeID}/ratings/{recipeRatingID}/": {
		ID:           "ArchiveRecipeRating",
		Description:  "Archives a RecipeRating",
		ResponseType: &types.RecipeRating{},
		OAuth2Scopes: []string{householdMember},
	},
	"GET /api/v1/recipes/{recipeID}/ratings/{recipeRatingID}/": {
		ID:           "GetRecipeRating",
		Description:  "Fetches a RecipeRating",
		ResponseType: &types.RecipeRating{},
		OAuth2Scopes: []string{householdMember},
	},
	"POST /api/v1/settings/": {
		ID:           "CreateServiceSetting",
		Description:  "Creates a ServiceSetting",
		ResponseType: &types.ServiceSetting{},
		InputType:    &types.ServiceSettingCreationRequestInput{},
		OAuth2Scopes: []string{serviceAdmin},
	},
	"GET /api/v1/settings/": {
		ID:           "GetServiceSettings",
		Description:  "Fetches a ServiceSettings",
		ResponseType: &types.ServiceSetting{},
		ListRoute:    true,
		OAuth2Scopes: []string{householdMember},
	},
	"POST /api/v1/settings/configurations/": {
		ID:           "CreateServiceSettingConfiguration",
		Description:  "Creates a ServiceSettingConfiguration",
		ResponseType: &types.ServiceSettingConfiguration{},
		InputType:    &types.ServiceSettingConfigurationCreationRequestInput{},
		OAuth2Scopes: []string{householdMember},
	},
	"GET /api/v1/settings/configurations/household": {
		ID:           "GetServiceSettingConfigurationsForHousehold",
		Description:  "Fetches a ServiceSettingConfigurationsForHousehold",
		ListRoute:    true,
		ResponseType: &types.ServiceSettingConfiguration{},
		OAuth2Scopes: []string{householdMember},
	},
	"GET /api/v1/settings/configurations/user": {
		ID:           "GetServiceSettingConfigurationsForUser",
		Description:  "Fetches a ServiceSettingConfigurationsForUser",
		ListRoute:    true,
		ResponseType: &types.ServiceSettingConfiguration{},
		OAuth2Scopes: []string{householdMember},
	},
	"GET /api/v1/settings/configurations/user/{serviceSettingConfigurationName}": {
		ID:           "GetServiceSettingConfigurationByName",
		Description:  "Fetches a ServiceSettingConfigurationByName",
		ResponseType: &types.ServiceSettingConfiguration{},
		ListRoute:    true,
		OAuth2Scopes: []string{householdMember},
	},
	"DELETE /api/v1/settings/configurations/{serviceSettingConfigurationID}": {
		ID:           "ArchiveServiceSettingConfiguration",
		Description:  "Archives a ServiceSettingConfiguration",
		ResponseType: &types.ServiceSettingConfiguration{},
		OAuth2Scopes: []string{householdMember},
	},
	"PUT /api/v1/settings/configurations/{serviceSettingConfigurationID}": {
		ID:           "UpdateServiceSettingConfiguration",
		Description:  "Updates a ServiceSettingConfiguration",
		ResponseType: &types.ServiceSettingConfiguration{},
		InputType:    &types.ServiceSettingConfigurationUpdateRequestInput{},
		OAuth2Scopes: []string{householdMember},
	},
	"GET /api/v1/settings/search": {
		ID:           "SearchForServiceSettings",
		Description:  "Searches for ServiceSettings",
		SearchRoute:  true,
		ResponseType: &types.ServiceSetting{},
		OAuth2Scopes: []string{householdMember},
	},
	"GET /api/v1/settings/{serviceSettingID}/": {
		ID:           "GetServiceSetting",
		Description:  "Fetches a ServiceSetting",
		ResponseType: &types.ServiceSetting{},
		OAuth2Scopes: []string{householdMember},
	},
	"DELETE /api/v1/settings/{serviceSettingID}/": {
		ID:           "ArchiveServiceSetting",
		Description:  "Archives a ServiceSetting",
		ResponseType: &types.ServiceSetting{},
		OAuth2Scopes: []string{serviceAdmin},
	},
	"POST /api/v1/user_ingredient_preferences/": {
		ID:           "CreateUserIngredientPreference",
		Description:  "Creates a UserIngredientPreference",
		ResponseType: []*types.UserIngredientPreference{},
		InputType:    &types.UserIngredientPreferenceCreationRequestInput{},
		OAuth2Scopes: []string{householdMember},
	},
	"GET /api/v1/user_ingredient_preferences/": {
		ID:           "GetUserIngredientPreferences",
		Description:  "Fetches a UserIngredientPreferences",
		ResponseType: &types.UserIngredientPreference{},
		ListRoute:    true,
		OAuth2Scopes: []string{householdMember},
	},
	"PUT /api/v1/user_ingredient_preferences/{userIngredientPreferenceID}/": {
		ID:           "UpdateUserIngredientPreference",
		Description:  "Updates a UserIngredientPreference",
		ResponseType: &types.UserIngredientPreference{},
		InputType:    &types.UserIngredientPreferenceUpdateRequestInput{},
		OAuth2Scopes: []string{householdMember},
	},
	"DELETE /api/v1/user_ingredient_preferences/{userIngredientPreferenceID}/": {
		ID:           "ArchiveUserIngredientPreference",
		Description:  "Archives a UserIngredientPreference",
		ResponseType: &types.UserIngredientPreference{},
		OAuth2Scopes: []string{householdMember},
	},
	"POST /api/v1/user_notifications/": {
		ID:           "CreateUserNotification",
		Description:  "Creates a UserNotification",
		ResponseType: &types.UserNotification{},
		InputType:    &types.UserNotificationCreationRequestInput{},
		OAuth2Scopes: []string{serviceAdmin},
	},
	"GET /api/v1/user_notifications/": {
		ID:           "GetUserNotifications",
		Description:  "Fetches a UserNotifications",
		ResponseType: &types.UserNotification{},
		ListRoute:    true,
		OAuth2Scopes: []string{householdMember},
	},
	"GET /api/v1/user_notifications/{userNotificationID}/": {
		ID:           "GetUserNotification",
		Description:  "Fetches a UserNotification",
		ResponseType: &types.UserNotification{},
		OAuth2Scopes: []string{householdMember},
	},
	"PATCH /api/v1/user_notifications/{userNotificationID}/": {
		ID:           "UpdateUserNotification",
		Description:  "Updates a UserNotification",
		InputType:    &types.UserNotificationUpdateRequestInput{},
		ResponseType: &types.UserNotification{},
		OAuth2Scopes: []string{householdMember},
	},
	"GET /api/v1/users/": {
		ID:           "GetUsers",
		Description:  "Fetches a Users",
		ResponseType: &types.User{},
		ListRoute:    true,
		OAuth2Scopes: []string{householdMember},
	},
	"POST /api/v1/users/avatar/upload": {
		ID:           "UploadUserAvatar",
		Description:  "Uploads a new user avatar",
		InputType:    &types.AvatarUpdateInput{},
		ResponseType: &types.User{},
		OAuth2Scopes: []string{householdMember},
	},
	"PUT /api/v1/users/details": {
		ID:           "UpdateUserDetails",
		Description:  "Updates a UserDetails",
		ResponseType: &types.User{},
		InputType:    &types.UserDetailsUpdateRequestInput{},
		OAuth2Scopes: []string{householdMember},
	},
	"PUT /api/v1/users/email_address": {
		ID:           "UpdateUserEmailAddress",
		Description:  "Updates a UserEmailAddress",
		ResponseType: &types.User{},
		InputType:    &types.UserEmailAddressUpdateInput{},
		OAuth2Scopes: []string{householdMember},
	},
	"POST /api/v1/users/email_address_verification": {
		ID:           "RequestEmailVerificationEmail",
		Description:  "Requests an email address verification email",
		ResponseType: &types.User{},
		OAuth2Scopes: []string{householdMember},
	},
	"PUT /api/v1/users/password/new": {
		ID:           "UpdatePassword",
		Description:  "Updates a Password",
		InputType:    &types.PasswordUpdateInput{},
		ResponseType: &types.PasswordResetResponse{},
		OAuth2Scopes: []string{householdMember},
	},
	"POST /api/v1/users/permissions/check": {
		ID:           "CheckPermissions",
		Description:  "Checks a user's permissions",
		ResponseType: &types.UserPermissionsResponse{},
		InputType:    &types.UserPermissionsRequestInput{},
		OAuth2Scopes: []string{householdMember},
	},
	"GET /api/v1/users/search": {
		ID:           "SearchForUsers",
		Description:  "Searches for Users",
		SearchRoute:  true,
		ResponseType: &types.User{},
		ListRoute:    true,
		OAuth2Scopes: []string{householdMember},
	},
	"GET /api/v1/users/self": {
		ID:           "GetSelf",
		Description:  "Fetches a Self",
		ResponseType: &types.User{},
		OAuth2Scopes: []string{householdMember},
	},
	"POST /api/v1/users/totp_secret/new": {
		ID:           "RefreshTOTPSecret",
		Description:  "Refreshes a user's TOTP secret",
		InputType:    &types.TOTPSecretRefreshInput{},
		ResponseType: &types.TOTPSecretRefreshResponse{},
		OAuth2Scopes: []string{householdMember},
	},
	"PUT /api/v1/users/username": {
		ID:           "UpdateUserUsername",
		Description:  "Updates a UserUsername",
		ResponseType: &types.User{},
		InputType:    &types.UsernameUpdateInput{},
		OAuth2Scopes: []string{householdMember},
	},
	"GET /api/v1/users/{userID}/": {
		ID:           "GetUser",
		Description:  "Fetches a User",
		ResponseType: &types.User{},
		OAuth2Scopes: []string{householdMember},
	},
	"DELETE /api/v1/users/{userID}/": {
		ID:           "ArchiveUser",
		Description:  "Archives a User",
		ResponseType: &types.User{},
		OAuth2Scopes: []string{householdMember},
	},
	"POST /api/v1/valid_ingredient_groups/": {
		ID:           "CreateValidIngredientGroup",
		Description:  "Creates a ValidIngredientGroup",
		ResponseType: &types.ValidIngredientGroup{},
		InputType:    &types.ValidIngredientGroupCreationRequestInput{},
		OAuth2Scopes: []string{serviceAdmin},
	},
	"GET /api/v1/valid_ingredient_groups/": {
		ID:           "GetValidIngredientGroups",
		Description:  "Fetches a ValidIngredientGroups",
		ResponseType: &types.ValidIngredientGroup{},
		ListRoute:    true,
		OAuth2Scopes: []string{householdMember},
	},
	"GET /api/v1/valid_ingredient_groups/search": {
		ID:           "SearchForValidIngredientGroups",
		Description:  "Searches for ValidIngredientGroups",
		SearchRoute:  true,
		ResponseType: &types.ValidIngredientGroup{},
		OAuth2Scopes: []string{householdMember},
	},
	"DELETE /api/v1/valid_ingredient_groups/{validIngredientGroupID}/": {
		ID:           "ArchiveValidIngredientGroup",
		Description:  "Archives a ValidIngredientGroup",
		ResponseType: &types.ValidIngredientGroup{},
		OAuth2Scopes: []string{serviceAdmin},
	},
	"GET /api/v1/valid_ingredient_groups/{validIngredientGroupID}/": {
		ID:           "GetValidIngredientGroup",
		Description:  "Fetches a ValidIngredientGroup",
		ResponseType: &types.ValidIngredientGroup{},
		OAuth2Scopes: []string{householdMember},
	},
	"PUT /api/v1/valid_ingredient_groups/{validIngredientGroupID}/": {
		ID:           "UpdateValidIngredientGroup",
		Description:  "Updates a ValidIngredientGroup",
		ResponseType: &types.ValidIngredientGroup{},
		InputType:    &types.ValidIngredientGroupUpdateRequestInput{},
		OAuth2Scopes: []string{serviceAdmin},
	},
	"POST /api/v1/valid_ingredient_measurement_units/": {
		ID:           "CreateValidIngredientMeasurementUnit",
		Description:  "Creates a ValidIngredientMeasurementUnit",
		ResponseType: &types.ValidIngredientMeasurementUnit{},
		InputType:    &types.ValidIngredientMeasurementUnitCreationRequestInput{},
		OAuth2Scopes: []string{serviceAdmin},
	},
	"GET /api/v1/valid_ingredient_measurement_units/": {
		ID:           "GetValidIngredientMeasurementUnits",
		Description:  "Fetches a ValidIngredientMeasurementUnits",
		ResponseType: &types.ValidIngredientMeasurementUnit{},
		ListRoute:    true,
		OAuth2Scopes: []string{householdMember},
	},
	"GET /api/v1/valid_ingredient_measurement_units/by_ingredient/{validIngredientID}/": {
		ID:           "GetValidIngredientMeasurementUnitsByIngredient",
		Description:  "Fetches a ValidIngredientMeasurementUnitsByIngredient",
		ResponseType: &types.ValidIngredientMeasurementUnit{},
		ListRoute:    true,
		OAuth2Scopes: []string{householdMember},
	},
	"GET /api/v1/valid_ingredient_measurement_units/by_measurement_unit/{validMeasurementUnitID}/": {
		ID:           "GetValidIngredientMeasurementUnitsByMeasurementUnit",
		Description:  "Fetches a ValidIngredientMeasurementUnitsByMeasurementUnit",
		ResponseType: &types.ValidIngredientMeasurementUnit{},
		ListRoute:    true,
		OAuth2Scopes: []string{householdMember},
	},
	"GET /api/v1/valid_ingredient_measurement_units/{validIngredientMeasurementUnitID}/": {
		ID:           "GetValidIngredientMeasurementUnit",
		Description:  "Fetches a ValidIngredientMeasurementUnit",
		ResponseType: &types.ValidIngredientMeasurementUnit{},
		OAuth2Scopes: []string{householdMember},
	},
	"PUT /api/v1/valid_ingredient_measurement_units/{validIngredientMeasurementUnitID}/": {
		ID:           "UpdateValidIngredientMeasurementUnit",
		Description:  "Updates a ValidIngredientMeasurementUnit",
		ResponseType: &types.ValidIngredientMeasurementUnit{},
		InputType:    &types.ValidIngredientMeasurementUnitUpdateRequestInput{},
		OAuth2Scopes: []string{serviceAdmin},
	},
	"DELETE /api/v1/valid_ingredient_measurement_units/{validIngredientMeasurementUnitID}/": {
		ID:           "ArchiveValidIngredientMeasurementUnit",
		Description:  "Archives a ValidIngredientMeasurementUnit",
		ResponseType: &types.ValidIngredientMeasurementUnit{},
		OAuth2Scopes: []string{serviceAdmin},
	},
	"GET /api/v1/valid_ingredient_preparations/": {
		ID:           "GetValidIngredientPreparations",
		Description:  "Fetches a ValidIngredientPreparations",
		ResponseType: &types.ValidIngredientPreparation{},
		ListRoute:    true,
		OAuth2Scopes: []string{householdMember},
	},
	"POST /api/v1/valid_ingredient_preparations/": {
		ID:           "CreateValidIngredientPreparation",
		Description:  "Creates a ValidIngredientPreparation",
		ResponseType: &types.ValidIngredientPreparation{},
		InputType:    &types.ValidIngredientPreparationCreationRequestInput{},
		OAuth2Scopes: []string{serviceAdmin},
	},
	"GET /api/v1/valid_ingredient_preparations/by_ingredient/{validIngredientID}/": {
		ID:           "GetValidIngredientPreparationsByIngredient",
		Description:  "Fetches a ValidIngredientPreparationsByIngredient",
		ResponseType: &types.ValidIngredientPreparation{},
		ListRoute:    true,
		OAuth2Scopes: []string{householdMember},
	},
	"GET /api/v1/valid_ingredient_preparations/by_preparation/{validPreparationID}/": {
		ID:           "GetValidIngredientPreparationsByPreparation",
		Description:  "Fetches a ValidIngredientPreparationsByPreparation",
		ResponseType: &types.ValidIngredientPreparation{},
		ListRoute:    true,
		OAuth2Scopes: []string{householdMember},
	},
	"GET /api/v1/valid_ingredient_preparations/{validIngredientPreparationID}/": {
		ID:           "GetValidIngredientPreparation",
		Description:  "Fetches a ValidIngredientPreparation",
		ResponseType: &types.ValidIngredientPreparation{},
		OAuth2Scopes: []string{householdMember},
	},
	"PUT /api/v1/valid_ingredient_preparations/{validIngredientPreparationID}/": {
		ID:           "UpdateValidIngredientPreparation",
		Description:  "Updates a ValidIngredientPreparation",
		ResponseType: &types.ValidIngredientPreparation{},
		InputType:    &types.ValidIngredientPreparationUpdateRequestInput{},
		OAuth2Scopes: []string{serviceAdmin},
	},
	"DELETE /api/v1/valid_ingredient_preparations/{validIngredientPreparationID}/": {
		ID:           "ArchiveValidIngredientPreparation",
		Description:  "Archives a ValidIngredientPreparation",
		ResponseType: &types.ValidIngredientPreparation{},
		OAuth2Scopes: []string{serviceAdmin},
	},
	"POST /api/v1/valid_ingredient_state_ingredients/": {
		ID:           "CreateValidIngredientStateIngredient",
		Description:  "Creates a ValidIngredientStateIngredient",
		ResponseType: &types.ValidIngredientStateIngredient{},
		InputType:    &types.ValidIngredientStateIngredientCreationRequestInput{},
		OAuth2Scopes: []string{serviceAdmin},
	},
	"GET /api/v1/valid_ingredient_state_ingredients/": {
		ID:           "GetValidIngredientStateIngredients",
		Description:  "Fetches a ValidIngredientStateIngredients",
		ResponseType: &types.ValidIngredientStateIngredient{},
		ListRoute:    true,
		OAuth2Scopes: []string{householdMember},
	},
	"GET /api/v1/valid_ingredient_state_ingredients/by_ingredient/{validIngredientID}/": {
		ID:           "GetValidIngredientStateIngredientsByIngredient",
		Description:  "Fetches a ValidIngredientStateIngredientsByIngredient",
		ResponseType: &types.ValidIngredientStateIngredient{},
		ListRoute:    true,
		OAuth2Scopes: []string{householdMember},
	},
	"GET /api/v1/valid_ingredient_state_ingredients/by_ingredient_state/{validIngredientStateID}/": {
		ID:           "GetValidIngredientStateIngredientsByIngredientState",
		Description:  "Fetches a ValidIngredientStateIngredientsByIngredientState",
		ResponseType: &types.ValidIngredientStateIngredient{},
		ListRoute:    true,
		OAuth2Scopes: []string{householdMember},
	},
	"GET /api/v1/valid_ingredient_state_ingredients/{validIngredientStateIngredientID}/": {
		ID:           "GetValidIngredientStateIngredient",
		Description:  "Fetches a ValidIngredientStateIngredient",
		ResponseType: &types.ValidIngredientStateIngredient{},
		OAuth2Scopes: []string{householdMember},
	},
	"PUT /api/v1/valid_ingredient_state_ingredients/{validIngredientStateIngredientID}/": {
		ID:           "UpdateValidIngredientStateIngredient",
		Description:  "Updates a ValidIngredientStateIngredient",
		ResponseType: &types.ValidIngredientStateIngredient{},
		InputType:    &types.ValidIngredientStateIngredientUpdateRequestInput{},
		OAuth2Scopes: []string{serviceAdmin},
	},
	"DELETE /api/v1/valid_ingredient_state_ingredients/{validIngredientStateIngredientID}/": {
		ID:           "ArchiveValidIngredientStateIngredient",
		Description:  "Archives a ValidIngredientStateIngredient",
		ResponseType: &types.ValidIngredientStateIngredient{},
		OAuth2Scopes: []string{serviceAdmin},
	},
	"POST /api/v1/valid_ingredient_states/": {
		ID:           "CreateValidIngredientState",
		Description:  "Creates a ValidIngredientState",
		ResponseType: &types.ValidIngredientState{},
		InputType:    &types.ValidIngredientStateCreationRequestInput{},
		OAuth2Scopes: []string{serviceAdmin},
	},
	"GET /api/v1/valid_ingredient_states/": {
		ID:           "GetValidIngredientStates",
		Description:  "Fetches a ValidIngredientStates",
		ResponseType: &types.ValidIngredientState{},
		ListRoute:    true,
		OAuth2Scopes: []string{householdMember},
	},
	"GET /api/v1/valid_ingredient_states/search": {
		ID:           "SearchForValidIngredientStates",
		Description:  "Searches for ValidIngredientStates",
		SearchRoute:  true,
		ResponseType: &types.ValidIngredientState{},
		OAuth2Scopes: []string{householdMember},
	},
	"PUT /api/v1/valid_ingredient_states/{validIngredientStateID}/": {
		ID:           "UpdateValidIngredientState",
		Description:  "Updates a ValidIngredientState",
		ResponseType: &types.ValidIngredientState{},
		InputType:    &types.ValidIngredientStateUpdateRequestInput{},
		OAuth2Scopes: []string{serviceAdmin},
	},
	"DELETE /api/v1/valid_ingredient_states/{validIngredientStateID}/": {
		ID:           "ArchiveValidIngredientState",
		Description:  "Archives a ValidIngredientState",
		ResponseType: &types.ValidIngredientState{},
		OAuth2Scopes: []string{serviceAdmin},
	},
	"GET /api/v1/valid_ingredient_states/{validIngredientStateID}/": {
		ID:           "GetValidIngredientState",
		Description:  "Fetches a ValidIngredientState",
		ResponseType: &types.ValidIngredientState{},
		OAuth2Scopes: []string{householdMember},
	},
	"POST /api/v1/valid_ingredients/": {
		ID:           "CreateValidIngredient",
		Description:  "Creates a ValidIngredient",
		ResponseType: &types.ValidIngredient{},
		InputType:    &types.ValidIngredientCreationRequestInput{},
		OAuth2Scopes: []string{serviceAdmin},
	},
	"GET /api/v1/valid_ingredients/": {
		ID:           "GetValidIngredients",
		Description:  "Fetches a ValidIngredients",
		ResponseType: &types.ValidIngredient{},
		ListRoute:    true,
		OAuth2Scopes: []string{householdMember},
	},
	"GET /api/v1/valid_ingredients/by_preparation/{validPreparationID}/": {
		ID:           "SearchValidIngredientsByPreparation",
		Description:  "Searches for ValidIngredients by a ValidPreparation ID",
		ListRoute:    true,
		SearchRoute:  true,
		ResponseType: &types.ValidIngredient{},
		OAuth2Scopes: []string{householdMember},
	},
	"GET /api/v1/valid_ingredients/random": {
		ID:           "GetRandomValidIngredient",
		Description:  "Fetches a RandomValidIngredient",
		ResponseType: &types.ValidIngredient{},
		OAuth2Scopes: []string{householdMember},
	},
	"GET /api/v1/valid_ingredients/search": {
		ID:           "SearchForValidIngredients",
		Description:  "Searches for ValidIngredients",
		SearchRoute:  true,
		ResponseType: &types.ValidIngredient{},
		OAuth2Scopes: []string{householdMember},
	},
	"PUT /api/v1/valid_ingredients/{validIngredientID}/": {
		ID:           "UpdateValidIngredient",
		Description:  "Updates a ValidIngredient",
		ResponseType: &types.ValidIngredient{},
		InputType:    &types.ValidIngredientUpdateRequestInput{},
		OAuth2Scopes: []string{serviceAdmin},
	},
	"DELETE /api/v1/valid_ingredients/{validIngredientID}/": {
		ID:           "ArchiveValidIngredient",
		Description:  "Archives a ValidIngredient",
		ResponseType: &types.ValidIngredient{},
		OAuth2Scopes: []string{serviceAdmin},
	},
	"GET /api/v1/valid_ingredients/{validIngredientID}/": {
		ID:           "GetValidIngredient",
		Description:  "Fetches a ValidIngredient",
		ResponseType: &types.ValidIngredient{},
		OAuth2Scopes: []string{householdMember},
	},
	"GET /api/v1/valid_instruments/": {
		ID:           "GetValidInstruments",
		Description:  "Fetches a ValidInstruments",
		ResponseType: &types.ValidInstrument{},
		ListRoute:    true,
		OAuth2Scopes: []string{householdMember},
	},
	"POST /api/v1/valid_instruments/": {
		ID:           "CreateValidInstrument",
		Description:  "Creates a ValidInstrument",
		ResponseType: &types.ValidInstrument{},
		InputType:    &types.ValidInstrumentCreationRequestInput{},
		OAuth2Scopes: []string{serviceAdmin},
	},
	"GET /api/v1/valid_instruments/random": {
		ID:           "GetRandomValidInstrument",
		Description:  "Fetches a RandomValidInstrument",
		ResponseType: &types.ValidInstrument{},
		OAuth2Scopes: []string{householdMember},
	},
	"GET /api/v1/valid_instruments/search": {
		ID:           "SearchForValidInstruments",
		Description:  "Searches for ValidInstruments",
		SearchRoute:  true,
		ResponseType: &types.ValidInstrument{},
		OAuth2Scopes: []string{householdMember},
	},
	"DELETE /api/v1/valid_instruments/{validInstrumentID}/": {
		ID:           "ArchiveValidInstrument",
		Description:  "Archives a ValidInstrument",
		ResponseType: &types.ValidInstrument{},
		OAuth2Scopes: []string{serviceAdmin},
	},
	"GET /api/v1/valid_instruments/{validInstrumentID}/": {
		ID:           "GetValidInstrument",
		Description:  "Fetches a ValidInstrument",
		ResponseType: &types.ValidInstrument{},
		OAuth2Scopes: []string{householdMember},
	},
	"PUT /api/v1/valid_instruments/{validInstrumentID}/": {
		ID:           "UpdateValidInstrument",
		Description:  "Updates a ValidInstrument",
		ResponseType: &types.ValidInstrument{},
		InputType:    &types.ValidInstrumentUpdateRequestInput{},
		OAuth2Scopes: []string{serviceAdmin},
	},
	"POST /api/v1/valid_measurement_conversions/": {
		ID:           "CreateValidMeasurementUnitConversion",
		Description:  "Creates a ValidMeasurementUnitConversion",
		ResponseType: &types.ValidMeasurementUnitConversion{},
		InputType:    &types.ValidMeasurementUnitConversionCreationRequestInput{},
		OAuth2Scopes: []string{serviceAdmin},
	},
	"GET /api/v1/valid_measurement_conversions/from_unit/{validMeasurementUnitID}": {
		ID:           "GetValidMeasurementUnitConversionsFromUnit",
		Description:  "Fetches a ValidMeasurementUnitConversionsFromUnit",
		ListRoute:    true,
		ResponseType: []types.ValidMeasurementUnitConversion{},
		OAuth2Scopes: []string{householdMember},
	},
	"GET /api/v1/valid_measurement_conversions/to_unit/{validMeasurementUnitID}": {
		ID:           "GetValidMeasurementUnitConversionsToUnit",
		Description:  "Fetches a ValidMeasurementUnitConversionsToUnit",
		ListRoute:    true,
		ResponseType: []types.ValidMeasurementUnitConversion{},
		OAuth2Scopes: []string{householdMember},
	},
	"PUT /api/v1/valid_measurement_conversions/{validMeasurementUnitConversionID}/": {
		ID:           "UpdateValidMeasurementUnitConversion",
		Description:  "Updates a ValidMeasurementUnitConversion",
		ResponseType: &types.ValidMeasurementUnitConversion{},
		InputType:    &types.ValidMeasurementUnitConversionUpdateRequestInput{},
		OAuth2Scopes: []string{serviceAdmin},
	},
	"DELETE /api/v1/valid_measurement_conversions/{validMeasurementUnitConversionID}/": {
		ID:           "ArchiveValidMeasurementUnitConversion",
		Description:  "Archives a ValidMeasurementUnitConversion",
		ResponseType: &types.ValidMeasurementUnitConversion{},
		OAuth2Scopes: []string{serviceAdmin},
	},
	"GET /api/v1/valid_measurement_conversions/{validMeasurementUnitConversionID}/": {
		ID:           "GetValidMeasurementUnitConversion",
		Description:  "Fetches a ValidMeasurementUnitConversion",
		ResponseType: &types.ValidMeasurementUnitConversion{},
		OAuth2Scopes: []string{householdMember},
	},
	"POST /api/v1/valid_measurement_units/": {
		ID:           "CreateValidMeasurementUnit",
		Description:  "Creates a ValidMeasurementUnit",
		ResponseType: &types.ValidMeasurementUnit{},
		InputType:    &types.ValidMeasurementUnitCreationRequestInput{},
		OAuth2Scopes: []string{serviceAdmin},
	},
	"GET /api/v1/valid_measurement_units/": {
		ID:           "GetValidMeasurementUnits",
		Description:  "Fetches a ValidMeasurementUnits",
		ResponseType: &types.ValidMeasurementUnit{},
		ListRoute:    true,
		OAuth2Scopes: []string{householdMember},
	},
	"GET /api/v1/valid_measurement_units/by_ingredient/{validIngredientID}": {
		ID:           "SearchValidMeasurementUnitsByIngredient",
		Description:  "Searches for ValidMeasurementUnits by a ValidIngredient ID",
		ResponseType: &types.ValidMeasurementUnit{},
		ListRoute:    true,
		SearchRoute:  true,
		OAuth2Scopes: []string{householdMember},
	},
	"GET /api/v1/valid_measurement_units/search": {
		ID:           "SearchForValidMeasurementUnits",
		Description:  "Searches for ValidMeasurementUnits",
		SearchRoute:  true,
		ResponseType: &types.ValidMeasurementUnit{},
		OAuth2Scopes: []string{householdMember},
	},
	"GET /api/v1/valid_measurement_units/{validMeasurementUnitID}/": {
		ID:           "GetValidMeasurementUnit",
		Description:  "Fetches a ValidMeasurementUnit",
		ResponseType: &types.ValidMeasurementUnit{},
		OAuth2Scopes: []string{householdMember},
	},
	"PUT /api/v1/valid_measurement_units/{validMeasurementUnitID}/": {
		ID:           "UpdateValidMeasurementUnit",
		Description:  "Updates a ValidMeasurementUnit",
		ResponseType: &types.ValidMeasurementUnit{},
		InputType:    &types.ValidMeasurementUnitUpdateRequestInput{},
		OAuth2Scopes: []string{serviceAdmin},
	},
	"DELETE /api/v1/valid_measurement_units/{validMeasurementUnitID}/": {
		ID:           "ArchiveValidMeasurementUnit",
		Description:  "Archives a ValidMeasurementUnit",
		ResponseType: &types.ValidMeasurementUnit{},
		OAuth2Scopes: []string{serviceAdmin},
	},
	"GET /api/v1/valid_preparation_instruments/": {
		ID:           "GetValidPreparationInstruments",
		Description:  "Fetches a ValidPreparationInstruments",
		ResponseType: &types.ValidPreparationInstrument{},
		ListRoute:    true,
		OAuth2Scopes: []string{householdMember},
	},
	"POST /api/v1/valid_preparation_instruments/": {
		ID:           "CreateValidPreparationInstrument",
		Description:  "Creates a ValidPreparationInstrument",
		ResponseType: &types.ValidPreparationInstrument{},
		InputType:    &types.ValidPreparationInstrumentCreationRequestInput{},
		OAuth2Scopes: []string{serviceAdmin},
	},
	"GET /api/v1/valid_preparation_instruments/by_instrument/{validInstrumentID}/": {
		ID:           "GetValidPreparationInstrumentsByInstrument",
		Description:  "Fetches a ValidPreparationInstrumentsByInstrument",
		ResponseType: &types.ValidPreparationInstrument{},
		ListRoute:    true,
		OAuth2Scopes: []string{householdMember},
	},
	"GET /api/v1/valid_preparation_instruments/by_preparation/{validPreparationID}/": {
		ID:           "GetValidPreparationInstrumentsByPreparation",
		Description:  "Fetches a ValidPreparationInstrumentsByPreparation",
		ResponseType: &types.ValidPreparationInstrument{},
		ListRoute:    true,
		OAuth2Scopes: []string{householdMember},
	},
	"DELETE /api/v1/valid_preparation_instruments/{validPreparationInstrumentID}/": {
		ID:           "ArchiveValidPreparationInstrument",
		Description:  "Archives a ValidPreparationInstrument",
		ResponseType: &types.ValidPreparationInstrument{},
		OAuth2Scopes: []string{serviceAdmin},
	},
	"GET /api/v1/valid_preparation_instruments/{validPreparationInstrumentID}/": {
		ID:           "GetValidPreparationInstrument",
		Description:  "Fetches a ValidPreparationInstrument",
		ResponseType: &types.ValidPreparationInstrument{},
		OAuth2Scopes: []string{householdMember},
	},
	"PUT /api/v1/valid_preparation_instruments/{validPreparationInstrumentID}/": {
		ID:           "UpdateValidPreparationInstrument",
		Description:  "Updates a ValidPreparationInstrument",
		ResponseType: &types.ValidPreparationInstrument{},
		InputType:    &types.ValidPreparationInstrumentUpdateRequestInput{},
		OAuth2Scopes: []string{serviceAdmin},
	},
	"POST /api/v1/valid_preparation_vessels/": {
		ID:           "CreateValidPreparationVessel",
		Description:  "Creates a ValidPreparationVessel",
		ResponseType: &types.ValidPreparationVessel{},
		InputType:    &types.ValidPreparationVesselCreationRequestInput{},
		OAuth2Scopes: []string{serviceAdmin},
	},
	"GET /api/v1/valid_preparation_vessels/": {
		ID:           "GetValidPreparationVessels",
		Description:  "Fetches a ValidPreparationVessels",
		ResponseType: &types.ValidPreparationVessel{},
		ListRoute:    true,
		OAuth2Scopes: []string{householdMember},
	},
	"GET /api/v1/valid_preparation_vessels/by_preparation/{validPreparationID}/": {
		ID:           "GetValidPreparationVesselsByPreparation",
		Description:  "Fetches a ValidPreparationVesselsByPreparation",
		ResponseType: &types.ValidPreparationVessel{},
		ListRoute:    true,
		OAuth2Scopes: []string{householdMember},
	},
	"GET /api/v1/valid_preparation_vessels/by_vessel/{validVesselID}/": {
		ID:           "GetValidPreparationVesselsByVessel",
		Description:  "Fetches a ValidPreparationVesselsByVessel",
		ResponseType: &types.ValidPreparationVessel{},
		ListRoute:    true,
		OAuth2Scopes: []string{householdMember},
	},
	"PUT /api/v1/valid_preparation_vessels/{validPreparationVesselID}/": {
		ID:           "UpdateValidPreparationVessel",
		Description:  "Updates a ValidPreparationVessel",
		ResponseType: &types.ValidPreparationVessel{},
		InputType:    &types.ValidPreparationVesselUpdateRequestInput{},
		OAuth2Scopes: []string{serviceAdmin},
	},
	"DELETE /api/v1/valid_preparation_vessels/{validPreparationVesselID}/": {
		ID:           "ArchiveValidPreparationVessel",
		Description:  "Archives a ValidPreparationVessel",
		ResponseType: &types.ValidPreparationVessel{},
		OAuth2Scopes: []string{serviceAdmin},
	},
	"GET /api/v1/valid_preparation_vessels/{validPreparationVesselID}/": {
		ID:           "GetValidPreparationVessel",
		Description:  "Fetches a ValidPreparationVessel",
		ResponseType: &types.ValidPreparationVessel{},
		OAuth2Scopes: []string{householdMember},
	},
	"GET /api/v1/valid_preparations/": {
		ID:           "GetValidPreparations",
		Description:  "Fetches a ValidPreparations",
		ResponseType: &types.ValidPreparation{},
		ListRoute:    true,
		OAuth2Scopes: []string{householdMember},
	},
	"POST /api/v1/valid_preparations/": {
		ID:           "CreateValidPreparation",
		Description:  "Creates a ValidPreparation",
		ResponseType: &types.ValidPreparation{},
		InputType:    &types.ValidPreparationCreationRequestInput{},
		OAuth2Scopes: []string{serviceAdmin},
	},
	"GET /api/v1/valid_preparations/random": {
		ID:           "GetRandomValidPreparation",
		Description:  "Fetches a RandomValidPreparation",
		ResponseType: &types.ValidPreparation{},
		OAuth2Scopes: []string{householdMember},
	},
	"GET /api/v1/valid_preparations/search": {
		ID:           "SearchForValidPreparations",
		Description:  "Searches for ValidPreparations",
		SearchRoute:  true,
		ResponseType: &types.ValidPreparation{},
		OAuth2Scopes: []string{householdMember},
	},
	"PUT /api/v1/valid_preparations/{validPreparationID}/": {
		ID:           "UpdateValidPreparation",
		Description:  "Updates a ValidPreparation",
		ResponseType: &types.ValidPreparation{},
		InputType:    &types.ValidPreparationUpdateRequestInput{},
		OAuth2Scopes: []string{serviceAdmin},
	},
	"DELETE /api/v1/valid_preparations/{validPreparationID}/": {
		ID:           "ArchiveValidPreparation",
		Description:  "Archives a ValidPreparation",
		ResponseType: &types.ValidPreparation{},
		OAuth2Scopes: []string{serviceAdmin},
	},
	"GET /api/v1/valid_preparations/{validPreparationID}/": {
		ID:           "GetValidPreparation",
		Description:  "Fetches a ValidPreparation",
		ResponseType: &types.ValidPreparation{},
		OAuth2Scopes: []string{householdMember},
	},
	"POST /api/v1/valid_vessels/": {
		ID:           "CreateValidVessel",
		Description:  "Creates a ValidVessel",
		ResponseType: &types.ValidVessel{},
		InputType:    &types.ValidVesselCreationRequestInput{},
		OAuth2Scopes: []string{serviceAdmin},
	},
	"GET /api/v1/valid_vessels/": {
		ID:           "GetValidVessels",
		Description:  "Fetches a ValidVessels",
		ResponseType: &types.ValidVessel{},
		ListRoute:    true,
		OAuth2Scopes: []string{householdMember},
	},
	"GET /api/v1/valid_vessels/random": {
		ID:           "GetRandomValidVessel",
		Description:  "Fetches a RandomValidVessel",
		ResponseType: &types.ValidVessel{},
		OAuth2Scopes: []string{householdMember},
	},
	"GET /api/v1/valid_vessels/search": {
		ID:           "SearchForValidVessels",
		Description:  "Searches for ValidVessels",
		SearchRoute:  true,
		ResponseType: &types.ValidVessel{},
		OAuth2Scopes: []string{householdMember},
	},
	"GET /api/v1/valid_vessels/{validVesselID}/": {
		ID:           "GetValidVessel",
		Description:  "Fetches a ValidVessel",
		ResponseType: &types.ValidVessel{},
		OAuth2Scopes: []string{householdMember},
	},
	"PUT /api/v1/valid_vessels/{validVesselID}/": {
		ID:           "UpdateValidVessel",
		Description:  "Updates a ValidVessel",
		ResponseType: &types.ValidVessel{},
		InputType:    &types.ValidVesselUpdateRequestInput{},
		OAuth2Scopes: []string{serviceAdmin},
	},
	"DELETE /api/v1/valid_vessels/{validVesselID}/": {
		ID:           "ArchiveValidVessel",
		Description:  "Archives a ValidVessel",
		ResponseType: &types.ValidVessel{},
		OAuth2Scopes: []string{serviceAdmin},
	},
	"GET /api/v1/webhooks/": {
		ID:           "GetWebhooks",
		Description:  "Fetches a Webhooks",
		ResponseType: &types.Webhook{},
		ListRoute:    true,
		OAuth2Scopes: []string{householdMember},
	},
	"POST /api/v1/webhooks/": {
		ID:           "CreateWebhook",
		Description:  "Creates a Webhook",
		ResponseType: &types.Webhook{},
		InputType:    &types.WebhookCreationRequestInput{},
		OAuth2Scopes: []string{householdAdmin},
	},
	"GET /api/v1/webhooks/{webhookID}/": {
		ID:           "GetWebhook",
		Description:  "Fetches a Webhook",
		ResponseType: &types.Webhook{},
		OAuth2Scopes: []string{householdMember},
	},
	"DELETE /api/v1/webhooks/{webhookID}/": {
		ID:           "ArchiveWebhook",
		Description:  "Archives a Webhook",
		ResponseType: &types.Webhook{},
		OAuth2Scopes: []string{householdAdmin},
	},
	"POST /api/v1/webhooks/{webhookID}/trigger_events": {
		ID:           "CreateWebhookTriggerEvent",
		Description:  "Creates a WebhookTriggerEvent",
		ResponseType: &types.WebhookTriggerEvent{},
		InputType:    &types.WebhookTriggerEventCreationRequestInput{},
		OAuth2Scopes: []string{householdAdmin},
	},
	"DELETE /api/v1/webhooks/{webhookID}/trigger_events/{webhookTriggerEventID}/": {
		ID:           "ArchiveWebhookTriggerEvent",
		Description:  "Archives a WebhookTriggerEvent",
		ResponseType: &types.WebhookTriggerEvent{},
		OAuth2Scopes: []string{householdAdmin},
	},
	"POST /api/v1/workers/finalize_meal_plans": {
		ID:           "RunFinalizeMealPlanWorker",
		Description:  "Runs the Finalize Meal Plans worker",
		ResponseType: &types.FinalizeMealPlansResponse{},
		InputType:    &types.FinalizeMealPlansRequest{},
		OAuth2Scopes: []string{serviceAdmin},
	},
	"POST /api/v1/workers/meal_plan_grocery_list_init": {
		ID:           "RunMealPlanGroceryListInitializerWorker",
		Description:  "Runs the meal plan grocery list initialization worker",
		ResponseType: &types.InitializeMealPlanGroceryListResponse{},
		InputType:    &types.InitializeMealPlanGroceryListRequest{},
		OAuth2Scopes: []string{serviceAdmin},
	},
	"POST /api/v1/workers/meal_plan_tasks": {
		ID:           "RunMealPlanTaskCreatorWorker",
		Description:  "Runs the meal plan task creator worker",
		ResponseType: &types.CreateMealPlanTasksResponse{},
		InputType:    &types.CreateMealPlanTasksRequest{},
		OAuth2Scopes: []string{serviceAdmin},
	},
	"GET /auth/status": {
		ID:           "GetAuthStatus",
		Description:  "Fetches a AuthStatus",
		ResponseType: &types.UserStatusResponse{},
		OAuth2Scopes: []string{householdMember},
		// no input type for this route
	},
	"GET /auth/{auth_provider}": {
		// we don't really have control over this route
	},
	"GET /auth/{auth_provider}/callback": {
		// we don't really have control over this route
	},
	"GET /oauth2/authorize": {
		// we don't really have control over this route
	},
	"POST /oauth2/token": {
		// we don't really have control over this route
	},
	"POST /users/": {
		ID:           "CreateUser",
		Description:  "Creates a new user",
		ResponseType: &types.UserCreationResponse{},
		InputType:    &types.UserRegistrationInput{},
	},
	"POST /users/email_address/verify": {
		ID:           "VerifyEmailAddress",
		ResponseType: &types.User{},
		InputType:    &types.EmailAddressVerificationRequestInput{},
	},
	"POST /users/login": {
		ID:           "Login",
		ResponseType: &types.UserStatusResponse{},
		InputType:    &types.UserLoginInput{},
	},
	"POST /users/login/admin": {
		ID:           "AdminLogin",
		ResponseType: &types.UserStatusResponse{},
		InputType:    &types.UserLoginInput{},
	},
	"POST /users/login/jwt": {
		ID:           "LoginForToken",
		ResponseType: &types.TokenResponse{},
		InputType:    &types.UserLoginInput{},
	},
	"POST /users/login/jwt/admin": {
		ID:           "AdminLoginForToken",
		ResponseType: &types.TokenResponse{},
		InputType:    &types.UserLoginInput{},
	},
	"POST /users/logout": {
		ID:           "Logout",
		ResponseType: &types.UserStatusResponse{},
	},
	"POST /users/password/reset": {
		ID:           "RequestPasswordResetToken",
		ResponseType: &types.PasswordResetToken{},
		InputType:    &types.PasswordResetTokenCreationRequestInput{},
	},
	"POST /users/password/reset/redeem": {
		ID:           "RedeemPasswordResetToken",
		Description:  "Redeems a password reset token",
		ResponseType: &types.User{},
		InputType:    &types.PasswordResetTokenRedemptionRequestInput{},
	},
	"POST /users/totp_secret/verify": {
		ID:           "VerifyTOTPSecret",
		ResponseType: &types.User{},
		InputType:    &types.TOTPSecretVerificationInput{},
	},
	"POST /users/username/reminder": {
		ID:           "RequestUsernameReminder",
		ResponseType: &types.User{},
		InputType:    &types.UsernameReminderRequestInput{},
	},
}
