# See: https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# See: https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/resource/
resources:
  - namespace.yaml
  - ../../components/api_server
  # - ../../components/jobs/db_cleaner

# See: https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/patches/
patches: []

commonLabels:
  app.kubernetes.io/name: dinner-done-better

configMapGenerator:
  - name: dinner-done-better-service-api-config
    namespace: localdev
    files:
      - config.json

  - name: dinner-done-better-job-db-cleaner-config
    namespace: localdev
    files:
      - config.json
