# See: https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# See: https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/resource/
resources:
  - namespace.yaml
  - ../../components/api_server
  - ../../components/jobs/db_cleaner
  - ../../components/jobs/email_prober
  - ../../components/jobs/meal_plan_finalizer
#  - ../../components/jobs/meal_plan_grocery_list_initializer
#  - ../../components/jobs/meal_plan_task_creator
#  - ../../components/jobs/search_data_index_scheduler

# See: https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/patches/
patches: []

commonLabels:
  app.kubernetes.io/name: dinner-done-better

configMapGenerator:
  - name: dinner-done-better-service-api-config
    namespace: localdev
    files:
      - config.json

  - name: dinner-done-better-job-db-cleaner-config
    namespace: localdev
    files:
      - config.json

  - name: dinner-done-better-job-email-prober-config
    namespace: localdev
    files:
      - config.json

  - name: dinner-done-better-job-meal-plan-finalizer-config
    namespace: localdev
    files:
      - config.json

  - name: dinner-done-better-job-meal-plan-grocery-list-init-config
    namespace: localdev
    files:
      - config.json

  - name: dinner-done-better-job-meal-plan-task-creator-config
    namespace: localdev
    files:
      - config.json

  - name: dinner-done-better-job-search-data-index-scheduler-config
    namespace: localdev
    files:
      - config.json

