// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v6.33.1
// source: analytics/analytics_service.proto

/* eslint-disable */
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from '@grpc/grpc-js';
import {
  TrackAnonymousEventRequest,
  TrackAnonymousEventResponse,
  TrackEventRequest,
  TrackEventResponse,
} from './analytics_service_types';

export const protobufPackage = 'analytics';

export type AnalyticsServiceService = typeof AnalyticsServiceService;
export const AnalyticsServiceService = {
  trackEvent: {
    path: '/analytics.AnalyticsService/TrackEvent' as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: TrackEventRequest): Buffer => Buffer.from(TrackEventRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): TrackEventRequest => TrackEventRequest.decode(value),
    responseSerialize: (value: TrackEventResponse): Buffer => Buffer.from(TrackEventResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): TrackEventResponse => TrackEventResponse.decode(value),
  },
  trackAnonymousEvent: {
    path: '/analytics.AnalyticsService/TrackAnonymousEvent' as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: TrackAnonymousEventRequest): Buffer =>
      Buffer.from(TrackAnonymousEventRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): TrackAnonymousEventRequest => TrackAnonymousEventRequest.decode(value),
    responseSerialize: (value: TrackAnonymousEventResponse): Buffer =>
      Buffer.from(TrackAnonymousEventResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): TrackAnonymousEventResponse => TrackAnonymousEventResponse.decode(value),
  },
} as const;

export interface AnalyticsServiceServer extends UntypedServiceImplementation {
  trackEvent: handleUnaryCall<TrackEventRequest, TrackEventResponse>;
  trackAnonymousEvent: handleUnaryCall<TrackAnonymousEventRequest, TrackAnonymousEventResponse>;
}

export interface AnalyticsServiceClient extends Client {
  trackEvent(
    request: TrackEventRequest,
    callback: (error: ServiceError | null, response: TrackEventResponse) => void,
  ): ClientUnaryCall;
  trackEvent(
    request: TrackEventRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: TrackEventResponse) => void,
  ): ClientUnaryCall;
  trackEvent(
    request: TrackEventRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: TrackEventResponse) => void,
  ): ClientUnaryCall;
  trackAnonymousEvent(
    request: TrackAnonymousEventRequest,
    callback: (error: ServiceError | null, response: TrackAnonymousEventResponse) => void,
  ): ClientUnaryCall;
  trackAnonymousEvent(
    request: TrackAnonymousEventRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: TrackAnonymousEventResponse) => void,
  ): ClientUnaryCall;
  trackAnonymousEvent(
    request: TrackAnonymousEventRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: TrackAnonymousEventResponse) => void,
  ): ClientUnaryCall;
}

export const AnalyticsServiceClient = makeGenericClientConstructor(
  AnalyticsServiceService,
  'analytics.AnalyticsService',
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): AnalyticsServiceClient;
  service: typeof AnalyticsServiceService;
  serviceName: string;
};
