// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v6.33.1
// source: identity/identity_service.proto

/* eslint-disable */
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type ClientWritableStream,
  type handleClientStreamingCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from '@grpc/grpc-js';
import { UploadRequest } from '../uploaded_media/uploaded_media_messages';
import {
  AcceptAccountInvitationRequest,
  AcceptAccountInvitationResponse,
  AdminSetPasswordChangeRequiredRequest,
  AdminSetPasswordChangeRequiredResponse,
  AdminUpdateUserStatusRequest,
  AdminUpdateUserStatusResponse,
  ArchiveAccountRequest,
  ArchiveAccountResponse,
  ArchiveUserMembershipRequest,
  ArchiveUserMembershipResponse,
  ArchiveUserRequest,
  ArchiveUserResponse,
  CancelAccountInvitationRequest,
  CancelAccountInvitationResponse,
  CreateAccountInvitationRequest,
  CreateAccountInvitationResponse,
  CreateAccountRequest,
  CreateAccountResponse,
  CreateUserRequest,
  CreateUserResponse,
  GetAccountInvitationRequest,
  GetAccountInvitationResponse,
  GetAccountRequest,
  GetAccountResponse,
  GetAccountsForUserRequest,
  GetAccountsForUserResponse,
  GetAccountsRequest,
  GetAccountsResponse,
  GetReceivedAccountInvitationsRequest,
  GetReceivedAccountInvitationsResponse,
  GetSentAccountInvitationsRequest,
  GetSentAccountInvitationsResponse,
  GetUserRequest,
  GetUserResponse,
  GetUsersForAccountRequest,
  GetUsersForAccountResponse,
  GetUsersRequest,
  GetUsersResponse,
  RejectAccountInvitationRequest,
  RejectAccountInvitationResponse,
  SearchForUsersRequest,
  SearchForUsersResponse,
  SetDefaultAccountRequest,
  SetDefaultAccountResponse,
  TransferAccountOwnershipRequest,
  TransferAccountOwnershipResponse,
  UpdateAccountMemberPermissionsRequest,
  UpdateAccountMemberPermissionsResponse,
  UpdateAccountRequest,
  UpdateAccountResponse,
  UpdateUserDetailsRequest,
  UpdateUserDetailsResponse,
  UpdateUserEmailAddressRequest,
  UpdateUserEmailAddressResponse,
  UpdateUserUsernameRequest,
  UpdateUserUsernameResponse,
  UploadUserAvatarResponse,
} from './identity_service_types';

export const protobufPackage = 'identity';

export type IdentityServiceService = typeof IdentityServiceService;
export const IdentityServiceService = {
  adminSetPasswordChangeRequired: {
    path: '/identity.IdentityService/AdminSetPasswordChangeRequired' as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: AdminSetPasswordChangeRequiredRequest): Buffer =>
      Buffer.from(AdminSetPasswordChangeRequiredRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): AdminSetPasswordChangeRequiredRequest =>
      AdminSetPasswordChangeRequiredRequest.decode(value),
    responseSerialize: (value: AdminSetPasswordChangeRequiredResponse): Buffer =>
      Buffer.from(AdminSetPasswordChangeRequiredResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): AdminSetPasswordChangeRequiredResponse =>
      AdminSetPasswordChangeRequiredResponse.decode(value),
  },
  adminUpdateUserStatus: {
    path: '/identity.IdentityService/AdminUpdateUserStatus' as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: AdminUpdateUserStatusRequest): Buffer =>
      Buffer.from(AdminUpdateUserStatusRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): AdminUpdateUserStatusRequest => AdminUpdateUserStatusRequest.decode(value),
    responseSerialize: (value: AdminUpdateUserStatusResponse): Buffer =>
      Buffer.from(AdminUpdateUserStatusResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): AdminUpdateUserStatusResponse => AdminUpdateUserStatusResponse.decode(value),
  },
  acceptAccountInvitation: {
    path: '/identity.IdentityService/AcceptAccountInvitation' as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: AcceptAccountInvitationRequest): Buffer =>
      Buffer.from(AcceptAccountInvitationRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): AcceptAccountInvitationRequest => AcceptAccountInvitationRequest.decode(value),
    responseSerialize: (value: AcceptAccountInvitationResponse): Buffer =>
      Buffer.from(AcceptAccountInvitationResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): AcceptAccountInvitationResponse =>
      AcceptAccountInvitationResponse.decode(value),
  },
  archiveAccount: {
    path: '/identity.IdentityService/ArchiveAccount' as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: ArchiveAccountRequest): Buffer =>
      Buffer.from(ArchiveAccountRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): ArchiveAccountRequest => ArchiveAccountRequest.decode(value),
    responseSerialize: (value: ArchiveAccountResponse): Buffer =>
      Buffer.from(ArchiveAccountResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): ArchiveAccountResponse => ArchiveAccountResponse.decode(value),
  },
  archiveUserMembership: {
    path: '/identity.IdentityService/ArchiveUserMembership' as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: ArchiveUserMembershipRequest): Buffer =>
      Buffer.from(ArchiveUserMembershipRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): ArchiveUserMembershipRequest => ArchiveUserMembershipRequest.decode(value),
    responseSerialize: (value: ArchiveUserMembershipResponse): Buffer =>
      Buffer.from(ArchiveUserMembershipResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): ArchiveUserMembershipResponse => ArchiveUserMembershipResponse.decode(value),
  },
  archiveUser: {
    path: '/identity.IdentityService/ArchiveUser' as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: ArchiveUserRequest): Buffer => Buffer.from(ArchiveUserRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): ArchiveUserRequest => ArchiveUserRequest.decode(value),
    responseSerialize: (value: ArchiveUserResponse): Buffer => Buffer.from(ArchiveUserResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): ArchiveUserResponse => ArchiveUserResponse.decode(value),
  },
  cancelAccountInvitation: {
    path: '/identity.IdentityService/CancelAccountInvitation' as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: CancelAccountInvitationRequest): Buffer =>
      Buffer.from(CancelAccountInvitationRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): CancelAccountInvitationRequest => CancelAccountInvitationRequest.decode(value),
    responseSerialize: (value: CancelAccountInvitationResponse): Buffer =>
      Buffer.from(CancelAccountInvitationResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): CancelAccountInvitationResponse =>
      CancelAccountInvitationResponse.decode(value),
  },
  createAccount: {
    path: '/identity.IdentityService/CreateAccount' as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: CreateAccountRequest): Buffer => Buffer.from(CreateAccountRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): CreateAccountRequest => CreateAccountRequest.decode(value),
    responseSerialize: (value: CreateAccountResponse): Buffer =>
      Buffer.from(CreateAccountResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): CreateAccountResponse => CreateAccountResponse.decode(value),
  },
  createAccountInvitation: {
    path: '/identity.IdentityService/CreateAccountInvitation' as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: CreateAccountInvitationRequest): Buffer =>
      Buffer.from(CreateAccountInvitationRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): CreateAccountInvitationRequest => CreateAccountInvitationRequest.decode(value),
    responseSerialize: (value: CreateAccountInvitationResponse): Buffer =>
      Buffer.from(CreateAccountInvitationResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): CreateAccountInvitationResponse =>
      CreateAccountInvitationResponse.decode(value),
  },
  createUser: {
    path: '/identity.IdentityService/CreateUser' as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: CreateUserRequest): Buffer => Buffer.from(CreateUserRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): CreateUserRequest => CreateUserRequest.decode(value),
    responseSerialize: (value: CreateUserResponse): Buffer => Buffer.from(CreateUserResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): CreateUserResponse => CreateUserResponse.decode(value),
  },
  getAccount: {
    path: '/identity.IdentityService/GetAccount' as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: GetAccountRequest): Buffer => Buffer.from(GetAccountRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetAccountRequest => GetAccountRequest.decode(value),
    responseSerialize: (value: GetAccountResponse): Buffer => Buffer.from(GetAccountResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): GetAccountResponse => GetAccountResponse.decode(value),
  },
  getAccountInvitation: {
    path: '/identity.IdentityService/GetAccountInvitation' as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: GetAccountInvitationRequest): Buffer =>
      Buffer.from(GetAccountInvitationRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetAccountInvitationRequest => GetAccountInvitationRequest.decode(value),
    responseSerialize: (value: GetAccountInvitationResponse): Buffer =>
      Buffer.from(GetAccountInvitationResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): GetAccountInvitationResponse => GetAccountInvitationResponse.decode(value),
  },
  getAccounts: {
    path: '/identity.IdentityService/GetAccounts' as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: GetAccountsRequest): Buffer => Buffer.from(GetAccountsRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetAccountsRequest => GetAccountsRequest.decode(value),
    responseSerialize: (value: GetAccountsResponse): Buffer => Buffer.from(GetAccountsResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): GetAccountsResponse => GetAccountsResponse.decode(value),
  },
  getAccountsForUser: {
    path: '/identity.IdentityService/GetAccountsForUser' as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: GetAccountsForUserRequest): Buffer =>
      Buffer.from(GetAccountsForUserRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetAccountsForUserRequest => GetAccountsForUserRequest.decode(value),
    responseSerialize: (value: GetAccountsForUserResponse): Buffer =>
      Buffer.from(GetAccountsForUserResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): GetAccountsForUserResponse => GetAccountsForUserResponse.decode(value),
  },
  getReceivedAccountInvitations: {
    path: '/identity.IdentityService/GetReceivedAccountInvitations' as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: GetReceivedAccountInvitationsRequest): Buffer =>
      Buffer.from(GetReceivedAccountInvitationsRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetReceivedAccountInvitationsRequest =>
      GetReceivedAccountInvitationsRequest.decode(value),
    responseSerialize: (value: GetReceivedAccountInvitationsResponse): Buffer =>
      Buffer.from(GetReceivedAccountInvitationsResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): GetReceivedAccountInvitationsResponse =>
      GetReceivedAccountInvitationsResponse.decode(value),
  },
  getSentAccountInvitations: {
    path: '/identity.IdentityService/GetSentAccountInvitations' as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: GetSentAccountInvitationsRequest): Buffer =>
      Buffer.from(GetSentAccountInvitationsRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetSentAccountInvitationsRequest =>
      GetSentAccountInvitationsRequest.decode(value),
    responseSerialize: (value: GetSentAccountInvitationsResponse): Buffer =>
      Buffer.from(GetSentAccountInvitationsResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): GetSentAccountInvitationsResponse =>
      GetSentAccountInvitationsResponse.decode(value),
  },
  getUser: {
    path: '/identity.IdentityService/GetUser' as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: GetUserRequest): Buffer => Buffer.from(GetUserRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetUserRequest => GetUserRequest.decode(value),
    responseSerialize: (value: GetUserResponse): Buffer => Buffer.from(GetUserResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): GetUserResponse => GetUserResponse.decode(value),
  },
  rejectAccountInvitation: {
    path: '/identity.IdentityService/RejectAccountInvitation' as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: RejectAccountInvitationRequest): Buffer =>
      Buffer.from(RejectAccountInvitationRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): RejectAccountInvitationRequest => RejectAccountInvitationRequest.decode(value),
    responseSerialize: (value: RejectAccountInvitationResponse): Buffer =>
      Buffer.from(RejectAccountInvitationResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): RejectAccountInvitationResponse =>
      RejectAccountInvitationResponse.decode(value),
  },
  getUsers: {
    path: '/identity.IdentityService/GetUsers' as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: GetUsersRequest): Buffer => Buffer.from(GetUsersRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetUsersRequest => GetUsersRequest.decode(value),
    responseSerialize: (value: GetUsersResponse): Buffer => Buffer.from(GetUsersResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): GetUsersResponse => GetUsersResponse.decode(value),
  },
  getUsersForAccount: {
    path: '/identity.IdentityService/GetUsersForAccount' as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: GetUsersForAccountRequest): Buffer =>
      Buffer.from(GetUsersForAccountRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetUsersForAccountRequest => GetUsersForAccountRequest.decode(value),
    responseSerialize: (value: GetUsersForAccountResponse): Buffer =>
      Buffer.from(GetUsersForAccountResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): GetUsersForAccountResponse => GetUsersForAccountResponse.decode(value),
  },
  searchForUsers: {
    path: '/identity.IdentityService/SearchForUsers' as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: SearchForUsersRequest): Buffer =>
      Buffer.from(SearchForUsersRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): SearchForUsersRequest => SearchForUsersRequest.decode(value),
    responseSerialize: (value: SearchForUsersResponse): Buffer =>
      Buffer.from(SearchForUsersResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): SearchForUsersResponse => SearchForUsersResponse.decode(value),
  },
  setDefaultAccount: {
    path: '/identity.IdentityService/SetDefaultAccount' as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: SetDefaultAccountRequest): Buffer =>
      Buffer.from(SetDefaultAccountRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): SetDefaultAccountRequest => SetDefaultAccountRequest.decode(value),
    responseSerialize: (value: SetDefaultAccountResponse): Buffer =>
      Buffer.from(SetDefaultAccountResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): SetDefaultAccountResponse => SetDefaultAccountResponse.decode(value),
  },
  transferAccountOwnership: {
    path: '/identity.IdentityService/TransferAccountOwnership' as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: TransferAccountOwnershipRequest): Buffer =>
      Buffer.from(TransferAccountOwnershipRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): TransferAccountOwnershipRequest =>
      TransferAccountOwnershipRequest.decode(value),
    responseSerialize: (value: TransferAccountOwnershipResponse): Buffer =>
      Buffer.from(TransferAccountOwnershipResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): TransferAccountOwnershipResponse =>
      TransferAccountOwnershipResponse.decode(value),
  },
  updateAccount: {
    path: '/identity.IdentityService/UpdateAccount' as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: UpdateAccountRequest): Buffer => Buffer.from(UpdateAccountRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): UpdateAccountRequest => UpdateAccountRequest.decode(value),
    responseSerialize: (value: UpdateAccountResponse): Buffer =>
      Buffer.from(UpdateAccountResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): UpdateAccountResponse => UpdateAccountResponse.decode(value),
  },
  updateAccountMemberPermissions: {
    path: '/identity.IdentityService/UpdateAccountMemberPermissions' as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: UpdateAccountMemberPermissionsRequest): Buffer =>
      Buffer.from(UpdateAccountMemberPermissionsRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): UpdateAccountMemberPermissionsRequest =>
      UpdateAccountMemberPermissionsRequest.decode(value),
    responseSerialize: (value: UpdateAccountMemberPermissionsResponse): Buffer =>
      Buffer.from(UpdateAccountMemberPermissionsResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): UpdateAccountMemberPermissionsResponse =>
      UpdateAccountMemberPermissionsResponse.decode(value),
  },
  updateUserDetails: {
    path: '/identity.IdentityService/UpdateUserDetails' as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: UpdateUserDetailsRequest): Buffer =>
      Buffer.from(UpdateUserDetailsRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): UpdateUserDetailsRequest => UpdateUserDetailsRequest.decode(value),
    responseSerialize: (value: UpdateUserDetailsResponse): Buffer =>
      Buffer.from(UpdateUserDetailsResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): UpdateUserDetailsResponse => UpdateUserDetailsResponse.decode(value),
  },
  updateUserEmailAddress: {
    path: '/identity.IdentityService/UpdateUserEmailAddress' as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: UpdateUserEmailAddressRequest): Buffer =>
      Buffer.from(UpdateUserEmailAddressRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): UpdateUserEmailAddressRequest => UpdateUserEmailAddressRequest.decode(value),
    responseSerialize: (value: UpdateUserEmailAddressResponse): Buffer =>
      Buffer.from(UpdateUserEmailAddressResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): UpdateUserEmailAddressResponse =>
      UpdateUserEmailAddressResponse.decode(value),
  },
  updateUserUsername: {
    path: '/identity.IdentityService/UpdateUserUsername' as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: UpdateUserUsernameRequest): Buffer =>
      Buffer.from(UpdateUserUsernameRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): UpdateUserUsernameRequest => UpdateUserUsernameRequest.decode(value),
    responseSerialize: (value: UpdateUserUsernameResponse): Buffer =>
      Buffer.from(UpdateUserUsernameResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): UpdateUserUsernameResponse => UpdateUserUsernameResponse.decode(value),
  },
  uploadUserAvatar: {
    path: '/identity.IdentityService/UploadUserAvatar' as const,
    requestStream: true as const,
    responseStream: false as const,
    requestSerialize: (value: UploadRequest): Buffer => Buffer.from(UploadRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): UploadRequest => UploadRequest.decode(value),
    responseSerialize: (value: UploadUserAvatarResponse): Buffer =>
      Buffer.from(UploadUserAvatarResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): UploadUserAvatarResponse => UploadUserAvatarResponse.decode(value),
  },
} as const;

export interface IdentityServiceServer extends UntypedServiceImplementation {
  adminSetPasswordChangeRequired: handleUnaryCall<
    AdminSetPasswordChangeRequiredRequest,
    AdminSetPasswordChangeRequiredResponse
  >;
  adminUpdateUserStatus: handleUnaryCall<AdminUpdateUserStatusRequest, AdminUpdateUserStatusResponse>;
  acceptAccountInvitation: handleUnaryCall<AcceptAccountInvitationRequest, AcceptAccountInvitationResponse>;
  archiveAccount: handleUnaryCall<ArchiveAccountRequest, ArchiveAccountResponse>;
  archiveUserMembership: handleUnaryCall<ArchiveUserMembershipRequest, ArchiveUserMembershipResponse>;
  archiveUser: handleUnaryCall<ArchiveUserRequest, ArchiveUserResponse>;
  cancelAccountInvitation: handleUnaryCall<CancelAccountInvitationRequest, CancelAccountInvitationResponse>;
  createAccount: handleUnaryCall<CreateAccountRequest, CreateAccountResponse>;
  createAccountInvitation: handleUnaryCall<CreateAccountInvitationRequest, CreateAccountInvitationResponse>;
  createUser: handleUnaryCall<CreateUserRequest, CreateUserResponse>;
  getAccount: handleUnaryCall<GetAccountRequest, GetAccountResponse>;
  getAccountInvitation: handleUnaryCall<GetAccountInvitationRequest, GetAccountInvitationResponse>;
  getAccounts: handleUnaryCall<GetAccountsRequest, GetAccountsResponse>;
  getAccountsForUser: handleUnaryCall<GetAccountsForUserRequest, GetAccountsForUserResponse>;
  getReceivedAccountInvitations: handleUnaryCall<
    GetReceivedAccountInvitationsRequest,
    GetReceivedAccountInvitationsResponse
  >;
  getSentAccountInvitations: handleUnaryCall<GetSentAccountInvitationsRequest, GetSentAccountInvitationsResponse>;
  getUser: handleUnaryCall<GetUserRequest, GetUserResponse>;
  rejectAccountInvitation: handleUnaryCall<RejectAccountInvitationRequest, RejectAccountInvitationResponse>;
  getUsers: handleUnaryCall<GetUsersRequest, GetUsersResponse>;
  getUsersForAccount: handleUnaryCall<GetUsersForAccountRequest, GetUsersForAccountResponse>;
  searchForUsers: handleUnaryCall<SearchForUsersRequest, SearchForUsersResponse>;
  setDefaultAccount: handleUnaryCall<SetDefaultAccountRequest, SetDefaultAccountResponse>;
  transferAccountOwnership: handleUnaryCall<TransferAccountOwnershipRequest, TransferAccountOwnershipResponse>;
  updateAccount: handleUnaryCall<UpdateAccountRequest, UpdateAccountResponse>;
  updateAccountMemberPermissions: handleUnaryCall<
    UpdateAccountMemberPermissionsRequest,
    UpdateAccountMemberPermissionsResponse
  >;
  updateUserDetails: handleUnaryCall<UpdateUserDetailsRequest, UpdateUserDetailsResponse>;
  updateUserEmailAddress: handleUnaryCall<UpdateUserEmailAddressRequest, UpdateUserEmailAddressResponse>;
  updateUserUsername: handleUnaryCall<UpdateUserUsernameRequest, UpdateUserUsernameResponse>;
  uploadUserAvatar: handleClientStreamingCall<UploadRequest, UploadUserAvatarResponse>;
}

export interface IdentityServiceClient extends Client {
  adminSetPasswordChangeRequired(
    request: AdminSetPasswordChangeRequiredRequest,
    callback: (error: ServiceError | null, response: AdminSetPasswordChangeRequiredResponse) => void,
  ): ClientUnaryCall;
  adminSetPasswordChangeRequired(
    request: AdminSetPasswordChangeRequiredRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: AdminSetPasswordChangeRequiredResponse) => void,
  ): ClientUnaryCall;
  adminSetPasswordChangeRequired(
    request: AdminSetPasswordChangeRequiredRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: AdminSetPasswordChangeRequiredResponse) => void,
  ): ClientUnaryCall;
  adminUpdateUserStatus(
    request: AdminUpdateUserStatusRequest,
    callback: (error: ServiceError | null, response: AdminUpdateUserStatusResponse) => void,
  ): ClientUnaryCall;
  adminUpdateUserStatus(
    request: AdminUpdateUserStatusRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: AdminUpdateUserStatusResponse) => void,
  ): ClientUnaryCall;
  adminUpdateUserStatus(
    request: AdminUpdateUserStatusRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: AdminUpdateUserStatusResponse) => void,
  ): ClientUnaryCall;
  acceptAccountInvitation(
    request: AcceptAccountInvitationRequest,
    callback: (error: ServiceError | null, response: AcceptAccountInvitationResponse) => void,
  ): ClientUnaryCall;
  acceptAccountInvitation(
    request: AcceptAccountInvitationRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: AcceptAccountInvitationResponse) => void,
  ): ClientUnaryCall;
  acceptAccountInvitation(
    request: AcceptAccountInvitationRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: AcceptAccountInvitationResponse) => void,
  ): ClientUnaryCall;
  archiveAccount(
    request: ArchiveAccountRequest,
    callback: (error: ServiceError | null, response: ArchiveAccountResponse) => void,
  ): ClientUnaryCall;
  archiveAccount(
    request: ArchiveAccountRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: ArchiveAccountResponse) => void,
  ): ClientUnaryCall;
  archiveAccount(
    request: ArchiveAccountRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: ArchiveAccountResponse) => void,
  ): ClientUnaryCall;
  archiveUserMembership(
    request: ArchiveUserMembershipRequest,
    callback: (error: ServiceError | null, response: ArchiveUserMembershipResponse) => void,
  ): ClientUnaryCall;
  archiveUserMembership(
    request: ArchiveUserMembershipRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: ArchiveUserMembershipResponse) => void,
  ): ClientUnaryCall;
  archiveUserMembership(
    request: ArchiveUserMembershipRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: ArchiveUserMembershipResponse) => void,
  ): ClientUnaryCall;
  archiveUser(
    request: ArchiveUserRequest,
    callback: (error: ServiceError | null, response: ArchiveUserResponse) => void,
  ): ClientUnaryCall;
  archiveUser(
    request: ArchiveUserRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: ArchiveUserResponse) => void,
  ): ClientUnaryCall;
  archiveUser(
    request: ArchiveUserRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: ArchiveUserResponse) => void,
  ): ClientUnaryCall;
  cancelAccountInvitation(
    request: CancelAccountInvitationRequest,
    callback: (error: ServiceError | null, response: CancelAccountInvitationResponse) => void,
  ): ClientUnaryCall;
  cancelAccountInvitation(
    request: CancelAccountInvitationRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: CancelAccountInvitationResponse) => void,
  ): ClientUnaryCall;
  cancelAccountInvitation(
    request: CancelAccountInvitationRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: CancelAccountInvitationResponse) => void,
  ): ClientUnaryCall;
  createAccount(
    request: CreateAccountRequest,
    callback: (error: ServiceError | null, response: CreateAccountResponse) => void,
  ): ClientUnaryCall;
  createAccount(
    request: CreateAccountRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: CreateAccountResponse) => void,
  ): ClientUnaryCall;
  createAccount(
    request: CreateAccountRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: CreateAccountResponse) => void,
  ): ClientUnaryCall;
  createAccountInvitation(
    request: CreateAccountInvitationRequest,
    callback: (error: ServiceError | null, response: CreateAccountInvitationResponse) => void,
  ): ClientUnaryCall;
  createAccountInvitation(
    request: CreateAccountInvitationRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: CreateAccountInvitationResponse) => void,
  ): ClientUnaryCall;
  createAccountInvitation(
    request: CreateAccountInvitationRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: CreateAccountInvitationResponse) => void,
  ): ClientUnaryCall;
  createUser(
    request: CreateUserRequest,
    callback: (error: ServiceError | null, response: CreateUserResponse) => void,
  ): ClientUnaryCall;
  createUser(
    request: CreateUserRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: CreateUserResponse) => void,
  ): ClientUnaryCall;
  createUser(
    request: CreateUserRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: CreateUserResponse) => void,
  ): ClientUnaryCall;
  getAccount(
    request: GetAccountRequest,
    callback: (error: ServiceError | null, response: GetAccountResponse) => void,
  ): ClientUnaryCall;
  getAccount(
    request: GetAccountRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GetAccountResponse) => void,
  ): ClientUnaryCall;
  getAccount(
    request: GetAccountRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GetAccountResponse) => void,
  ): ClientUnaryCall;
  getAccountInvitation(
    request: GetAccountInvitationRequest,
    callback: (error: ServiceError | null, response: GetAccountInvitationResponse) => void,
  ): ClientUnaryCall;
  getAccountInvitation(
    request: GetAccountInvitationRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GetAccountInvitationResponse) => void,
  ): ClientUnaryCall;
  getAccountInvitation(
    request: GetAccountInvitationRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GetAccountInvitationResponse) => void,
  ): ClientUnaryCall;
  getAccounts(
    request: GetAccountsRequest,
    callback: (error: ServiceError | null, response: GetAccountsResponse) => void,
  ): ClientUnaryCall;
  getAccounts(
    request: GetAccountsRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GetAccountsResponse) => void,
  ): ClientUnaryCall;
  getAccounts(
    request: GetAccountsRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GetAccountsResponse) => void,
  ): ClientUnaryCall;
  getAccountsForUser(
    request: GetAccountsForUserRequest,
    callback: (error: ServiceError | null, response: GetAccountsForUserResponse) => void,
  ): ClientUnaryCall;
  getAccountsForUser(
    request: GetAccountsForUserRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GetAccountsForUserResponse) => void,
  ): ClientUnaryCall;
  getAccountsForUser(
    request: GetAccountsForUserRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GetAccountsForUserResponse) => void,
  ): ClientUnaryCall;
  getReceivedAccountInvitations(
    request: GetReceivedAccountInvitationsRequest,
    callback: (error: ServiceError | null, response: GetReceivedAccountInvitationsResponse) => void,
  ): ClientUnaryCall;
  getReceivedAccountInvitations(
    request: GetReceivedAccountInvitationsRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GetReceivedAccountInvitationsResponse) => void,
  ): ClientUnaryCall;
  getReceivedAccountInvitations(
    request: GetReceivedAccountInvitationsRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GetReceivedAccountInvitationsResponse) => void,
  ): ClientUnaryCall;
  getSentAccountInvitations(
    request: GetSentAccountInvitationsRequest,
    callback: (error: ServiceError | null, response: GetSentAccountInvitationsResponse) => void,
  ): ClientUnaryCall;
  getSentAccountInvitations(
    request: GetSentAccountInvitationsRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GetSentAccountInvitationsResponse) => void,
  ): ClientUnaryCall;
  getSentAccountInvitations(
    request: GetSentAccountInvitationsRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GetSentAccountInvitationsResponse) => void,
  ): ClientUnaryCall;
  getUser(
    request: GetUserRequest,
    callback: (error: ServiceError | null, response: GetUserResponse) => void,
  ): ClientUnaryCall;
  getUser(
    request: GetUserRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GetUserResponse) => void,
  ): ClientUnaryCall;
  getUser(
    request: GetUserRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GetUserResponse) => void,
  ): ClientUnaryCall;
  rejectAccountInvitation(
    request: RejectAccountInvitationRequest,
    callback: (error: ServiceError | null, response: RejectAccountInvitationResponse) => void,
  ): ClientUnaryCall;
  rejectAccountInvitation(
    request: RejectAccountInvitationRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: RejectAccountInvitationResponse) => void,
  ): ClientUnaryCall;
  rejectAccountInvitation(
    request: RejectAccountInvitationRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: RejectAccountInvitationResponse) => void,
  ): ClientUnaryCall;
  getUsers(
    request: GetUsersRequest,
    callback: (error: ServiceError | null, response: GetUsersResponse) => void,
  ): ClientUnaryCall;
  getUsers(
    request: GetUsersRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GetUsersResponse) => void,
  ): ClientUnaryCall;
  getUsers(
    request: GetUsersRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GetUsersResponse) => void,
  ): ClientUnaryCall;
  getUsersForAccount(
    request: GetUsersForAccountRequest,
    callback: (error: ServiceError | null, response: GetUsersForAccountResponse) => void,
  ): ClientUnaryCall;
  getUsersForAccount(
    request: GetUsersForAccountRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GetUsersForAccountResponse) => void,
  ): ClientUnaryCall;
  getUsersForAccount(
    request: GetUsersForAccountRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GetUsersForAccountResponse) => void,
  ): ClientUnaryCall;
  searchForUsers(
    request: SearchForUsersRequest,
    callback: (error: ServiceError | null, response: SearchForUsersResponse) => void,
  ): ClientUnaryCall;
  searchForUsers(
    request: SearchForUsersRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: SearchForUsersResponse) => void,
  ): ClientUnaryCall;
  searchForUsers(
    request: SearchForUsersRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: SearchForUsersResponse) => void,
  ): ClientUnaryCall;
  setDefaultAccount(
    request: SetDefaultAccountRequest,
    callback: (error: ServiceError | null, response: SetDefaultAccountResponse) => void,
  ): ClientUnaryCall;
  setDefaultAccount(
    request: SetDefaultAccountRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: SetDefaultAccountResponse) => void,
  ): ClientUnaryCall;
  setDefaultAccount(
    request: SetDefaultAccountRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: SetDefaultAccountResponse) => void,
  ): ClientUnaryCall;
  transferAccountOwnership(
    request: TransferAccountOwnershipRequest,
    callback: (error: ServiceError | null, response: TransferAccountOwnershipResponse) => void,
  ): ClientUnaryCall;
  transferAccountOwnership(
    request: TransferAccountOwnershipRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: TransferAccountOwnershipResponse) => void,
  ): ClientUnaryCall;
  transferAccountOwnership(
    request: TransferAccountOwnershipRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: TransferAccountOwnershipResponse) => void,
  ): ClientUnaryCall;
  updateAccount(
    request: UpdateAccountRequest,
    callback: (error: ServiceError | null, response: UpdateAccountResponse) => void,
  ): ClientUnaryCall;
  updateAccount(
    request: UpdateAccountRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: UpdateAccountResponse) => void,
  ): ClientUnaryCall;
  updateAccount(
    request: UpdateAccountRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: UpdateAccountResponse) => void,
  ): ClientUnaryCall;
  updateAccountMemberPermissions(
    request: UpdateAccountMemberPermissionsRequest,
    callback: (error: ServiceError | null, response: UpdateAccountMemberPermissionsResponse) => void,
  ): ClientUnaryCall;
  updateAccountMemberPermissions(
    request: UpdateAccountMemberPermissionsRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: UpdateAccountMemberPermissionsResponse) => void,
  ): ClientUnaryCall;
  updateAccountMemberPermissions(
    request: UpdateAccountMemberPermissionsRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: UpdateAccountMemberPermissionsResponse) => void,
  ): ClientUnaryCall;
  updateUserDetails(
    request: UpdateUserDetailsRequest,
    callback: (error: ServiceError | null, response: UpdateUserDetailsResponse) => void,
  ): ClientUnaryCall;
  updateUserDetails(
    request: UpdateUserDetailsRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: UpdateUserDetailsResponse) => void,
  ): ClientUnaryCall;
  updateUserDetails(
    request: UpdateUserDetailsRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: UpdateUserDetailsResponse) => void,
  ): ClientUnaryCall;
  updateUserEmailAddress(
    request: UpdateUserEmailAddressRequest,
    callback: (error: ServiceError | null, response: UpdateUserEmailAddressResponse) => void,
  ): ClientUnaryCall;
  updateUserEmailAddress(
    request: UpdateUserEmailAddressRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: UpdateUserEmailAddressResponse) => void,
  ): ClientUnaryCall;
  updateUserEmailAddress(
    request: UpdateUserEmailAddressRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: UpdateUserEmailAddressResponse) => void,
  ): ClientUnaryCall;
  updateUserUsername(
    request: UpdateUserUsernameRequest,
    callback: (error: ServiceError | null, response: UpdateUserUsernameResponse) => void,
  ): ClientUnaryCall;
  updateUserUsername(
    request: UpdateUserUsernameRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: UpdateUserUsernameResponse) => void,
  ): ClientUnaryCall;
  updateUserUsername(
    request: UpdateUserUsernameRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: UpdateUserUsernameResponse) => void,
  ): ClientUnaryCall;
  uploadUserAvatar(
    callback: (error: ServiceError | null, response: UploadUserAvatarResponse) => void,
  ): ClientWritableStream<UploadRequest>;
  uploadUserAvatar(
    metadata: Metadata,
    callback: (error: ServiceError | null, response: UploadUserAvatarResponse) => void,
  ): ClientWritableStream<UploadRequest>;
  uploadUserAvatar(
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: UploadUserAvatarResponse) => void,
  ): ClientWritableStream<UploadRequest>;
  uploadUserAvatar(
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: UploadUserAvatarResponse) => void,
  ): ClientWritableStream<UploadRequest>;
}

export const IdentityServiceClient = makeGenericClientConstructor(
  IdentityServiceService,
  'identity.IdentityService',
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): IdentityServiceClient;
  service: typeof IdentityServiceService;
  serviceName: string;
};
