package main

import "github.com/prixfixeco/api_server/pkg/types"

var (
	validInstruments = []*types.ValidInstrumentCreationRequestInput{
		{
			Name:        "knife",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "knife",
			Variant:     "serrated",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "utility knife",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "steak knife",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "carving knife",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "carving fork",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "cleaver",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "chinese cleaver",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "paring knife",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "boning knife",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "chef's knife",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "santoku knife",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "bread knife",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "cutting board",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "pizza slicer",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "pizza stone",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "fat separator",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "sifter",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "sieve",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "can opener",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "measuring cups",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "measuring cup",
			Variant:     "1/8 cup",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "measuring cup",
			Variant:     "1/4 cup",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "measuring cup",
			Variant:     "1/3 cup",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "measuring cup",
			Variant:     "1/2 cup",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "measuring cup",
			Variant:     "1 cup",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "measuring spoons",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "measuring spoon",
			Variant:     "1/8 teaspoon",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "measuring spoon",
			Variant:     "1/4 teaspoon",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "measuring spoon",
			Variant:     "1/2 teaspoon",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "measuring spoon",
			Variant:     "1 teaspoon",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "measuring spoon",
			Variant:     "1/8 tablespoon",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "measuring spoon",
			Variant:     "1/4 tablespoon",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "measuring spoon",
			Variant:     "1/2 tablespoon",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "measuring spoon",
			Variant:     "1 tablespoon",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "measuring bowl",
			Variant:     "large",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "measuring bowl",
			Variant:     "medium",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "measuring bowl",
			Variant:     "small",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "colander",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "vegetable peeler",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "potato masher",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "potato ricer",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "dough hook",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "meat tenderizer",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "food mill",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "whisk",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "whisk",
			Variant:     "flat",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "salad spinner",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "grater",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "shears",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "citrus juicer",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "juicer",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "garlic press",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "skillet",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "skillet",
			Variant:     "14\"",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "skillet",
			Variant:     "12\"",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "skillet",
			Variant:     "10\"",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "skillet",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "skillet",
			Variant:     "cast iron",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "grill pan",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "grill pan",
			Variant:     "cast iron",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "saute pan",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "saute pan",
			Variant:     "6 quart",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "saute pan",
			Variant:     "4 quart",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "saute pan",
			Variant:     "3 quart",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "saute pan",
			Variant:     "2 quart",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "sauce pan",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "sauce pan",
			Variant:     "6 quart",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "sauce pan",
			Variant:     "5 quart",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "sauce pan",
			Variant:     "4 quart",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "sauce pan",
			Variant:     "3 quart",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "sauce pan",
			Variant:     "2 quart",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "wok",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "cassoulet",
			Variant:     "3 quart",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "ramekin",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "steamer",
			Variant:     "8 quart",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "steamer",
			Variant:     "5 quart",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "steamer",
			Variant:     "3 quart",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "stockpot",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "stockpot",
			Variant:     "8 quart",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "stockpot",
			Variant:     "12 quart",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "stockpot",
			Variant:     "16 quart",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "stockpot",
			Variant:     "32 quart",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "dutch oven",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "baking sheet",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "muffin pan",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "casserole dish",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "broiler pan",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "spatula",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "rubber/silicone spatula",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "scooper",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "scooper",
			Variant:     "large",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "ice scoop",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "spoon",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "fork",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "butter knife",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "slotted spoon",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "tongs",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "ladle",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "oven mitt",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "trivet",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "splatter guard",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "thermometer",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "immersion blender",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "refrigerator",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "stove",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "oven",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "scale",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "blender",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "towel",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "ice cube tray",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "mandoline",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "microplane",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "food processor",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "spice blender",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "mortar & pestle",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "molcajete",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "apple corer",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "apple slicer",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "baster",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "blow torch",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "bottle opener",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "mixing bowl",
			Variant:     "large",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "mixing bowl",
			Variant:     "medium",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "mixing bowl",
			Variant:     "small",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "pie cutter",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "cheese cutter",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "cheese knife",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "conical sieve",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "cookie cutter",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "dough scraper",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "egg piercer",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "egg separator",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "egg slicer",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "egg timer",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "fish scaler",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "fish spatula",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "funnel",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "honey dipper",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "lame",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "lobster pick",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "meat grinder",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "pasta machine",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "melon baller",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "milk frother",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "nutcracker",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "pastry bag",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "pastry blender",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "pastry brush",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "pepper grinder",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "pot holder",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "rolling pin",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "roller docker",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "basket skimmer",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "candy thermometer",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "drum sieve",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "stand mixer",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "hand mixer",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "freezer",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "tea kettle",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
		{
			Name:        "zester",
			Variant:     "",
			Description: "",
			IconPath:    "",
		},
	}
)
