package main

import (
	"context"

	"github.com/prixfixeco/api_server/internal/database"
	"github.com/prixfixeco/api_server/pkg/types"

	"github.com/segmentio/ksuid"
)

var validIngredientCollection = struct {
	ChickenBreast,
	Water,
	Onion,
	Garlic,
	BlackPepper,
	OliveOil,
	Coffee,
	Pasta,
	Tomato,
	Mozzarella *types.ValidIngredientDatabaseCreationInput
}{
	ChickenBreast: &types.ValidIngredientDatabaseCreationInput{
		ID:                       ksuid.New().String(),
		Name:                     "chicken breast",
		Description:              "",
		Warning:                  "",
		IconPath:                 "",
		ContainsDairy:            false,
		ContainsPeanut:           false,
		ContainsTreeNut:          false,
		ContainsEgg:              false,
		ContainsWheat:            false,
		ContainsShellfish:        false,
		ContainsSesame:           false,
		ContainsFish:             false,
		ContainsGluten:           false,
		AnimalFlesh:              true,
		IsMeasuredVolumetrically: false,
		ContainsSoy:              false,
	},
	Water: &types.ValidIngredientDatabaseCreationInput{
		ID:                       ksuid.New().String(),
		Name:                     "water",
		Description:              "",
		Warning:                  "",
		IconPath:                 "",
		ContainsDairy:            false,
		ContainsPeanut:           false,
		ContainsTreeNut:          false,
		ContainsEgg:              false,
		ContainsWheat:            false,
		ContainsShellfish:        false,
		ContainsSesame:           false,
		ContainsFish:             false,
		ContainsGluten:           false,
		AnimalFlesh:              false,
		IsMeasuredVolumetrically: false,
		IsLiquid:                 true,
		ContainsSoy:              false,
	},
	Onion: &types.ValidIngredientDatabaseCreationInput{
		ID:                       ksuid.New().String(),
		Name:                     "onion",
		Description:              "",
		Warning:                  "",
		IconPath:                 "",
		ContainsDairy:            false,
		ContainsPeanut:           false,
		ContainsTreeNut:          false,
		ContainsEgg:              false,
		ContainsWheat:            false,
		ContainsShellfish:        false,
		ContainsSesame:           false,
		ContainsFish:             false,
		ContainsGluten:           false,
		AnimalFlesh:              false,
		IsMeasuredVolumetrically: false,
		ContainsSoy:              false,
	},
	Garlic: &types.ValidIngredientDatabaseCreationInput{
		ID:                       ksuid.New().String(),
		Name:                     "garlic",
		Description:              "",
		Warning:                  "",
		IconPath:                 "",
		ContainsDairy:            false,
		ContainsPeanut:           false,
		ContainsTreeNut:          false,
		ContainsEgg:              false,
		ContainsWheat:            false,
		ContainsShellfish:        false,
		ContainsSesame:           false,
		ContainsFish:             false,
		ContainsGluten:           false,
		AnimalFlesh:              false,
		IsMeasuredVolumetrically: false,
		ContainsSoy:              false,
	},
	BlackPepper: &types.ValidIngredientDatabaseCreationInput{
		ID:                       ksuid.New().String(),
		Name:                     "black pepper",
		Description:              "",
		Warning:                  "",
		IconPath:                 "",
		ContainsDairy:            false,
		ContainsPeanut:           false,
		ContainsTreeNut:          false,
		ContainsEgg:              false,
		ContainsWheat:            false,
		ContainsShellfish:        false,
		ContainsSesame:           false,
		ContainsFish:             false,
		ContainsGluten:           false,
		AnimalFlesh:              false,
		IsMeasuredVolumetrically: false,
		ContainsSoy:              false,
	},
	OliveOil: &types.ValidIngredientDatabaseCreationInput{
		ID:                       ksuid.New().String(),
		Name:                     "olive oil",
		Description:              "",
		Warning:                  "",
		IconPath:                 "",
		ContainsDairy:            false,
		ContainsPeanut:           false,
		ContainsTreeNut:          false,
		ContainsEgg:              false,
		ContainsWheat:            false,
		ContainsShellfish:        false,
		ContainsSesame:           false,
		ContainsFish:             false,
		ContainsGluten:           false,
		AnimalFlesh:              false,
		IsMeasuredVolumetrically: true,
		IsLiquid:                 true,
		ContainsSoy:              false,
	},
	Coffee: &types.ValidIngredientDatabaseCreationInput{
		ID:                       ksuid.New().String(),
		Name:                     "brewed coffee",
		Description:              "",
		Warning:                  "",
		IconPath:                 "",
		ContainsDairy:            false,
		ContainsPeanut:           false,
		ContainsTreeNut:          false,
		ContainsEgg:              false,
		ContainsWheat:            false,
		ContainsShellfish:        false,
		ContainsSesame:           false,
		ContainsFish:             false,
		ContainsGluten:           false,
		AnimalFlesh:              false,
		IsMeasuredVolumetrically: true,
		IsLiquid:                 true,
		ContainsSoy:              false,
	},
	Pasta: &types.ValidIngredientDatabaseCreationInput{
		ID:                       ksuid.New().String(),
		Name:                     "pasta",
		Description:              "",
		Warning:                  "",
		IconPath:                 "",
		ContainsDairy:            false,
		ContainsPeanut:           false,
		ContainsTreeNut:          false,
		ContainsEgg:              false,
		ContainsWheat:            false,
		ContainsShellfish:        false,
		ContainsSesame:           false,
		ContainsFish:             false,
		ContainsGluten:           true,
		AnimalFlesh:              false,
		IsMeasuredVolumetrically: false,
		ContainsSoy:              false,
	},
	Tomato: &types.ValidIngredientDatabaseCreationInput{
		ID:                       ksuid.New().String(),
		Name:                     "tomato",
		Description:              "",
		Warning:                  "",
		IconPath:                 "",
		ContainsDairy:            false,
		ContainsPeanut:           false,
		ContainsTreeNut:          false,
		ContainsEgg:              false,
		ContainsWheat:            false,
		ContainsShellfish:        false,
		ContainsSesame:           false,
		ContainsFish:             false,
		ContainsGluten:           false,
		AnimalFlesh:              false,
		IsMeasuredVolumetrically: false,
		ContainsSoy:              false,
	},
	Mozzarella: &types.ValidIngredientDatabaseCreationInput{
		ID:                       ksuid.New().String(),
		Name:                     "mozzarella",
		Description:              "",
		Warning:                  "",
		IconPath:                 "",
		ContainsDairy:            false,
		ContainsPeanut:           false,
		ContainsTreeNut:          false,
		ContainsEgg:              false,
		ContainsWheat:            false,
		ContainsShellfish:        false,
		ContainsSesame:           false,
		ContainsFish:             false,
		ContainsGluten:           false,
		AnimalFlesh:              false,
		IsMeasuredVolumetrically: false,
		ContainsSoy:              false,
	},
}

func scaffoldValidIngredients(ctx context.Context, db database.DataManager) error {
	validIngredients := []*types.ValidIngredientDatabaseCreationInput{
		validIngredientCollection.ChickenBreast,
		validIngredientCollection.Water,
		validIngredientCollection.Onion,
		validIngredientCollection.Garlic,
		validIngredientCollection.BlackPepper,
		validIngredientCollection.OliveOil,
		validIngredientCollection.Coffee,
		validIngredientCollection.Pasta,
		validIngredientCollection.Tomato,
		validIngredientCollection.Mozzarella,
	}

	for _, input := range validIngredients {
		if _, err := db.CreateValidIngredient(ctx, input); err != nil {
			return err
		}
	}

	return nil
}
