package main

import "gitlab.com/prixfixe/prixfixe/pkg/types"

var (
	validIngredients = []*types.ValidIngredientCreationInput{
		{
			Name:              "water",
			Variant:           "",
			Description:       "",
			Warning:           "",
			ContainsEgg:       false,
			ContainsDairy:     false,
			ContainsPeanut:    false,
			ContainsTreeNut:   false,
			ContainsSoy:       false,
			ContainsWheat:     false,
			ContainsShellfish: false,
			ContainsSesame:    false,
			ContainsFish:      false,
			ContainsGluten:    false,
			AnimalFlesh:       false,
			AnimalDerived:     false,
			Volumetric:        false,
			IconPath:          "",
		},
		{
			Name:              "coffee beans",
			Variant:           "medium roast",
			Description:       "",
			Warning:           "",
			ContainsEgg:       false,
			ContainsDairy:     false,
			ContainsPeanut:    false,
			ContainsTreeNut:   false,
			ContainsSoy:       false,
			ContainsWheat:     false,
			ContainsShellfish: false,
			ContainsSesame:    false,
			ContainsFish:      false,
			ContainsGluten:    false,
			AnimalFlesh:       false,
			AnimalDerived:     false,
			Volumetric:        false,
			IconPath:          "",
		},
		{
			Name:              "beef",
			Variant:           "",
			Description:       "",
			Warning:           "",
			ContainsEgg:       false,
			ContainsDairy:     false,
			ContainsPeanut:    false,
			ContainsTreeNut:   false,
			ContainsSoy:       false,
			ContainsWheat:     false,
			ContainsShellfish: false,
			ContainsSesame:    false,
			ContainsFish:      false,
			ContainsGluten:    false,
			AnimalFlesh:       true,
			AnimalDerived:     true,
			Volumetric:        false,
			IconPath:          "",
		},
		{
			Name:              "pork",
			Variant:           "",
			Description:       "",
			Warning:           "",
			ContainsEgg:       false,
			ContainsDairy:     false,
			ContainsPeanut:    false,
			ContainsTreeNut:   false,
			ContainsSoy:       false,
			ContainsWheat:     false,
			ContainsShellfish: false,
			ContainsSesame:    false,
			ContainsFish:      false,
			ContainsGluten:    false,
			AnimalFlesh:       true,
			AnimalDerived:     true,
			Volumetric:        false,
			IconPath:          "",
		},
		{
			Name:              "chicken",
			Variant:           "",
			Description:       "",
			Warning:           "",
			ContainsEgg:       false,
			ContainsDairy:     false,
			ContainsPeanut:    false,
			ContainsTreeNut:   false,
			ContainsSoy:       false,
			ContainsWheat:     false,
			ContainsShellfish: false,
			ContainsSesame:    false,
			ContainsFish:      false,
			ContainsGluten:    false,
			AnimalFlesh:       true,
			AnimalDerived:     true,
			Volumetric:        false,
			IconPath:          "",
		},
		{
			Name:              "bacon",
			Variant:           "",
			Description:       "",
			Warning:           "",
			ContainsEgg:       false,
			ContainsDairy:     false,
			ContainsPeanut:    false,
			ContainsTreeNut:   false,
			ContainsSoy:       false,
			ContainsWheat:     false,
			ContainsShellfish: false,
			ContainsSesame:    false,
			ContainsFish:      false,
			ContainsGluten:    false,
			AnimalFlesh:       true,
			AnimalDerived:     true,
			Volumetric:        false,
			IconPath:          "",
		},
		{
			Name:              "chorizo",
			Variant:           "",
			Description:       "",
			Warning:           "",
			ContainsEgg:       false,
			ContainsDairy:     false,
			ContainsPeanut:    false,
			ContainsTreeNut:   false,
			ContainsSoy:       false,
			ContainsWheat:     false,
			ContainsShellfish: false,
			ContainsSesame:    false,
			ContainsFish:      false,
			ContainsGluten:    false,
			AnimalFlesh:       true,
			AnimalDerived:     true,
			Volumetric:        false,
			IconPath:          "",
		},
		{
			Name:              "guanciale",
			Variant:           "",
			Description:       "",
			Warning:           "",
			ContainsEgg:       false,
			ContainsDairy:     false,
			ContainsPeanut:    false,
			ContainsTreeNut:   false,
			ContainsSoy:       false,
			ContainsWheat:     false,
			ContainsShellfish: false,
			ContainsSesame:    false,
			ContainsFish:      false,
			ContainsGluten:    false,
			AnimalFlesh:       true,
			AnimalDerived:     true,
			Volumetric:        false,
			IconPath:          "",
		},
		{
			Name:              "lap cheong",
			Variant:           "",
			Description:       "",
			Warning:           "",
			ContainsEgg:       false,
			ContainsDairy:     false,
			ContainsPeanut:    false,
			ContainsTreeNut:   false,
			ContainsSoy:       false,
			ContainsWheat:     false,
			ContainsShellfish: false,
			ContainsSesame:    false,
			ContainsFish:      false,
			ContainsGluten:    false,
			AnimalFlesh:       true,
			AnimalDerived:     true,
			Volumetric:        false,
			IconPath:          "",
		},
		{
			Name:              "mortadella",
			Variant:           "",
			Description:       "",
			Warning:           "",
			ContainsEgg:       false,
			ContainsDairy:     false,
			ContainsPeanut:    false,
			ContainsTreeNut:   false,
			ContainsSoy:       false,
			ContainsWheat:     false,
			ContainsShellfish: false,
			ContainsSesame:    false,
			ContainsFish:      false,
			ContainsGluten:    false,
			AnimalFlesh:       true,
			AnimalDerived:     true,
			Volumetric:        false,
			IconPath:          "",
		},
		{
			Name:              "pancetta",
			Variant:           "",
			Description:       "",
			Warning:           "",
			ContainsEgg:       false,
			ContainsDairy:     false,
			ContainsPeanut:    false,
			ContainsTreeNut:   false,
			ContainsSoy:       false,
			ContainsWheat:     false,
			ContainsShellfish: false,
			ContainsSesame:    false,
			ContainsFish:      false,
			ContainsGluten:    false,
			AnimalFlesh:       true,
			AnimalDerived:     true,
			Volumetric:        false,
			IconPath:          "",
		},
		{
			Name:              "pepperoni",
			Variant:           "",
			Description:       "",
			Warning:           "",
			ContainsEgg:       false,
			ContainsDairy:     false,
			ContainsPeanut:    false,
			ContainsTreeNut:   false,
			ContainsSoy:       false,
			ContainsWheat:     false,
			ContainsShellfish: false,
			ContainsSesame:    false,
			ContainsFish:      false,
			ContainsGluten:    false,
			AnimalFlesh:       true,
			AnimalDerived:     true,
			Volumetric:        false,
			IconPath:          "",
		},
		{
			Name:              "prosciutto",
			Variant:           "",
			Description:       "",
			Warning:           "",
			ContainsEgg:       false,
			ContainsDairy:     false,
			ContainsPeanut:    false,
			ContainsTreeNut:   false,
			ContainsSoy:       false,
			ContainsWheat:     false,
			ContainsShellfish: false,
			ContainsSesame:    false,
			ContainsFish:      false,
			ContainsGluten:    false,
			AnimalFlesh:       true,
			AnimalDerived:     true,
			Volumetric:        false,
			IconPath:          "",
		},
		{
			Name:              "soppressata",
			Variant:           "",
			Description:       "",
			Warning:           "",
			ContainsEgg:       false,
			ContainsDairy:     false,
			ContainsPeanut:    false,
			ContainsTreeNut:   false,
			ContainsSoy:       false,
			ContainsWheat:     false,
			ContainsShellfish: false,
			ContainsSesame:    false,
			ContainsFish:      false,
			ContainsGluten:    false,
			AnimalFlesh:       true,
			AnimalDerived:     true,
			Volumetric:        false,
			IconPath:          "",
		},
	}
)
