---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dinner-done-better-landing-deployment
  labels:
    app: dinner-done-better-landing
    app.kubernetes.io/name: dinner-done-better-landing-app
spec:
  selector:
    matchLabels:
      app: dinner-done-better-landing
      app.kubernetes.io/name: dinner-done-better-landing-app
  replicas: 1
  template:
    metadata:
      labels:
        app: dinner-done-better-landing
        app.kubernetes.io/name: dinner-done-better-landing-app
    spec:
      containers:
        - name: dinner-done-better-landing
          image: dinner-done-better-landing
          imagePullPolicy: IfNotPresent
          env:
            - name: "RUNNING_IN_KUBERNETES"
              value: "true"
          ports:
            - containerPort: 10000
              name: http
---
