// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        v5.29.3
// source: dumping_ground.proto

package messages

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AdminUpdateUserStatus
type AdminUpdateUserStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminUpdateUserStatusRequest) Reset() {
	*x = AdminUpdateUserStatusRequest{}
	mi := &file_dumping_ground_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUpdateUserStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUpdateUserStatusRequest) ProtoMessage() {}

func (x *AdminUpdateUserStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dumping_ground_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUpdateUserStatusRequest.ProtoReflect.Descriptor instead.
func (*AdminUpdateUserStatusRequest) Descriptor() ([]byte, []int) {
	return file_dumping_ground_proto_rawDescGZIP(), []int{0}
}

type AdminUpdateUserStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminUpdateUserStatusResponse) Reset() {
	*x = AdminUpdateUserStatusResponse{}
	mi := &file_dumping_ground_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUpdateUserStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUpdateUserStatusResponse) ProtoMessage() {}

func (x *AdminUpdateUserStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dumping_ground_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUpdateUserStatusResponse.ProtoReflect.Descriptor instead.
func (*AdminUpdateUserStatusResponse) Descriptor() ([]byte, []int) {
	return file_dumping_ground_proto_rawDescGZIP(), []int{1}
}

// AggregateUserDataReport
type AggregateUserDataReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AggregateUserDataReportRequest) Reset() {
	*x = AggregateUserDataReportRequest{}
	mi := &file_dumping_ground_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggregateUserDataReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregateUserDataReportRequest) ProtoMessage() {}

func (x *AggregateUserDataReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dumping_ground_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregateUserDataReportRequest.ProtoReflect.Descriptor instead.
func (*AggregateUserDataReportRequest) Descriptor() ([]byte, []int) {
	return file_dumping_ground_proto_rawDescGZIP(), []int{2}
}

type AggregateUserDataReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AggregateUserDataReportResponse) Reset() {
	*x = AggregateUserDataReportResponse{}
	mi := &file_dumping_ground_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggregateUserDataReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregateUserDataReportResponse) ProtoMessage() {}

func (x *AggregateUserDataReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dumping_ground_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregateUserDataReportResponse.ProtoReflect.Descriptor instead.
func (*AggregateUserDataReportResponse) Descriptor() ([]byte, []int) {
	return file_dumping_ground_proto_rawDescGZIP(), []int{3}
}

// DestroyAllUserData
type DestroyAllUserDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyAllUserDataRequest) Reset() {
	*x = DestroyAllUserDataRequest{}
	mi := &file_dumping_ground_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyAllUserDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyAllUserDataRequest) ProtoMessage() {}

func (x *DestroyAllUserDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dumping_ground_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyAllUserDataRequest.ProtoReflect.Descriptor instead.
func (*DestroyAllUserDataRequest) Descriptor() ([]byte, []int) {
	return file_dumping_ground_proto_rawDescGZIP(), []int{4}
}

type DestroyAllUserDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyAllUserDataResponse) Reset() {
	*x = DestroyAllUserDataResponse{}
	mi := &file_dumping_ground_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyAllUserDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyAllUserDataResponse) ProtoMessage() {}

func (x *DestroyAllUserDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dumping_ground_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyAllUserDataResponse.ProtoReflect.Descriptor instead.
func (*DestroyAllUserDataResponse) Descriptor() ([]byte, []int) {
	return file_dumping_ground_proto_rawDescGZIP(), []int{5}
}

// FetchUserDataReport
type FetchUserDataReportRequest struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	UserDataAggregationReportID string                 `protobuf:"bytes,1,opt,name=userDataAggregationReportID,proto3" json:"userDataAggregationReportID,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *FetchUserDataReportRequest) Reset() {
	*x = FetchUserDataReportRequest{}
	mi := &file_dumping_ground_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchUserDataReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchUserDataReportRequest) ProtoMessage() {}

func (x *FetchUserDataReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dumping_ground_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchUserDataReportRequest.ProtoReflect.Descriptor instead.
func (*FetchUserDataReportRequest) Descriptor() ([]byte, []int) {
	return file_dumping_ground_proto_rawDescGZIP(), []int{6}
}

func (x *FetchUserDataReportRequest) GetUserDataAggregationReportID() string {
	if x != nil {
		return x.UserDataAggregationReportID
	}
	return ""
}

type FetchUserDataReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchUserDataReportResponse) Reset() {
	*x = FetchUserDataReportResponse{}
	mi := &file_dumping_ground_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchUserDataReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchUserDataReportResponse) ProtoMessage() {}

func (x *FetchUserDataReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dumping_ground_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchUserDataReportResponse.ProtoReflect.Descriptor instead.
func (*FetchUserDataReportResponse) Descriptor() ([]byte, []int) {
	return file_dumping_ground_proto_rawDescGZIP(), []int{7}
}

// PublishArbitraryQueueMessage
type PublishArbitraryQueueMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishArbitraryQueueMessageRequest) Reset() {
	*x = PublishArbitraryQueueMessageRequest{}
	mi := &file_dumping_ground_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishArbitraryQueueMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishArbitraryQueueMessageRequest) ProtoMessage() {}

func (x *PublishArbitraryQueueMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dumping_ground_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishArbitraryQueueMessageRequest.ProtoReflect.Descriptor instead.
func (*PublishArbitraryQueueMessageRequest) Descriptor() ([]byte, []int) {
	return file_dumping_ground_proto_rawDescGZIP(), []int{8}
}

type PublishArbitraryQueueMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishArbitraryQueueMessageResponse) Reset() {
	*x = PublishArbitraryQueueMessageResponse{}
	mi := &file_dumping_ground_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishArbitraryQueueMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishArbitraryQueueMessageResponse) ProtoMessage() {}

func (x *PublishArbitraryQueueMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dumping_ground_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishArbitraryQueueMessageResponse.ProtoReflect.Descriptor instead.
func (*PublishArbitraryQueueMessageResponse) Descriptor() ([]byte, []int) {
	return file_dumping_ground_proto_rawDescGZIP(), []int{9}
}

type DataDeletionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Successful    bool                   `protobuf:"varint,1,opt,name=Successful,proto3" json:"Successful,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataDeletionResponse) Reset() {
	*x = DataDeletionResponse{}
	mi := &file_dumping_ground_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataDeletionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataDeletionResponse) ProtoMessage() {}

func (x *DataDeletionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dumping_ground_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataDeletionResponse.ProtoReflect.Descriptor instead.
func (*DataDeletionResponse) Descriptor() ([]byte, []int) {
	return file_dumping_ground_proto_rawDescGZIP(), []int{10}
}

func (x *DataDeletionResponse) GetSuccessful() bool {
	if x != nil {
		return x.Successful
	}
	return false
}

type MissingVote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventID       string                 `protobuf:"bytes,1,opt,name=EventID,proto3" json:"EventID,omitempty"`
	OptionID      string                 `protobuf:"bytes,2,opt,name=OptionID,proto3" json:"OptionID,omitempty"`
	UserID        string                 `protobuf:"bytes,3,opt,name=UserID,proto3" json:"UserID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MissingVote) Reset() {
	*x = MissingVote{}
	mi := &file_dumping_ground_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MissingVote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MissingVote) ProtoMessage() {}

func (x *MissingVote) ProtoReflect() protoreflect.Message {
	mi := &file_dumping_ground_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MissingVote.ProtoReflect.Descriptor instead.
func (*MissingVote) Descriptor() ([]byte, []int) {
	return file_dumping_ground_proto_rawDescGZIP(), []int{11}
}

func (x *MissingVote) GetEventID() string {
	if x != nil {
		return x.EventID
	}
	return ""
}

func (x *MissingVote) GetOptionID() string {
	if x != nil {
		return x.OptionID
	}
	return ""
}

func (x *MissingVote) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

type NamedID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NamedID) Reset() {
	*x = NamedID{}
	mi := &file_dumping_ground_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NamedID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamedID) ProtoMessage() {}

func (x *NamedID) ProtoReflect() protoreflect.Message {
	mi := &file_dumping_ground_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamedID.ProtoReflect.Descriptor instead.
func (*NamedID) Descriptor() ([]byte, []int) {
	return file_dumping_ground_proto_rawDescGZIP(), []int{12}
}

func (x *NamedID) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *NamedID) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ResponseDetails struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CurrentAccountID string                 `protobuf:"bytes,1,opt,name=CurrentAccountID,proto3" json:"CurrentAccountID,omitempty"`
	TraceID          string                 `protobuf:"bytes,2,opt,name=TraceID,proto3" json:"TraceID,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ResponseDetails) Reset() {
	*x = ResponseDetails{}
	mi := &file_dumping_ground_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseDetails) ProtoMessage() {}

func (x *ResponseDetails) ProtoReflect() protoreflect.Message {
	mi := &file_dumping_ground_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseDetails.ProtoReflect.Descriptor instead.
func (*ResponseDetails) Descriptor() ([]byte, []int) {
	return file_dumping_ground_proto_rawDescGZIP(), []int{13}
}

func (x *ResponseDetails) GetCurrentAccountID() string {
	if x != nil {
		return x.CurrentAccountID
	}
	return ""
}

func (x *ResponseDetails) GetTraceID() string {
	if x != nil {
		return x.TraceID
	}
	return ""
}

type UserDataCollectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReportID      string                 `protobuf:"bytes,1,opt,name=ReportID,proto3" json:"ReportID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserDataCollectionResponse) Reset() {
	*x = UserDataCollectionResponse{}
	mi := &file_dumping_ground_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDataCollectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDataCollectionResponse) ProtoMessage() {}

func (x *UserDataCollectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dumping_ground_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDataCollectionResponse.ProtoReflect.Descriptor instead.
func (*UserDataCollectionResponse) Descriptor() ([]byte, []int) {
	return file_dumping_ground_proto_rawDescGZIP(), []int{14}
}

func (x *UserDataCollectionResponse) GetReportID() string {
	if x != nil {
		return x.ReportID
	}
	return ""
}

type UserStatusResponse struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	UserID                   string                 `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	AccountStatus            string                 `protobuf:"bytes,2,opt,name=AccountStatus,proto3" json:"AccountStatus,omitempty"`
	AccountStatusExplanation string                 `protobuf:"bytes,3,opt,name=AccountStatusExplanation,proto3" json:"AccountStatusExplanation,omitempty"`
	ActiveAccount            string                 `protobuf:"bytes,4,opt,name=ActiveAccount,proto3" json:"ActiveAccount,omitempty"`
	UserIsAuthenticated      bool                   `protobuf:"varint,5,opt,name=UserIsAuthenticated,proto3" json:"UserIsAuthenticated,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *UserStatusResponse) Reset() {
	*x = UserStatusResponse{}
	mi := &file_dumping_ground_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserStatusResponse) ProtoMessage() {}

func (x *UserStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dumping_ground_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserStatusResponse.ProtoReflect.Descriptor instead.
func (*UserStatusResponse) Descriptor() ([]byte, []int) {
	return file_dumping_ground_proto_rawDescGZIP(), []int{15}
}

func (x *UserStatusResponse) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *UserStatusResponse) GetAccountStatus() string {
	if x != nil {
		return x.AccountStatus
	}
	return ""
}

func (x *UserStatusResponse) GetAccountStatusExplanation() string {
	if x != nil {
		return x.AccountStatusExplanation
	}
	return ""
}

func (x *UserStatusResponse) GetActiveAccount() string {
	if x != nil {
		return x.ActiveAccount
	}
	return ""
}

func (x *UserStatusResponse) GetUserIsAuthenticated() bool {
	if x != nil {
		return x.UserIsAuthenticated
	}
	return false
}

var File_dumping_ground_proto protoreflect.FileDescriptor

var file_dumping_ground_proto_rawDesc = string([]byte{
	0x0a, 0x14, 0x64, 0x75, 0x6d, 0x70, 0x69, 0x6e, 0x67, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x65, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x22, 0x1e,
	0x0a, 0x1c, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65,
	0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x1f,
	0x0a, 0x1d, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65,
	0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x20, 0x0a, 0x1e, 0x41, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x21, 0x0a, 0x1f, 0x41, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65, 0x55, 0x73,
	0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1b, 0x0a, 0x19, 0x44, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x41,
	0x6c, 0x6c, 0x55, 0x73, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x1c, 0x0a, 0x1a, 0x44, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x41, 0x6c, 0x6c, 0x55,
	0x73, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x5e, 0x0a, 0x1a, 0x46, 0x65, 0x74, 0x63, 0x68, 0x55, 0x73, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61,
	0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x40, 0x0a,
	0x1b, 0x75, 0x73, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x41, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x1b, 0x75, 0x73, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x41, 0x67, 0x67, 0x72,
	0x65, 0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x49, 0x44, 0x22,
	0x1d, 0x0a, 0x1b, 0x46, 0x65, 0x74, 0x63, 0x68, 0x55, 0x73, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61,
	0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x25,
	0x0a, 0x23, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x41, 0x72, 0x62, 0x69, 0x74, 0x72, 0x61,
	0x72, 0x79, 0x51, 0x75, 0x65, 0x75, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x26, 0x0a, 0x24, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68,
	0x41, 0x72, 0x62, 0x69, 0x74, 0x72, 0x61, 0x72, 0x79, 0x51, 0x75, 0x65, 0x75, 0x65, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x36, 0x0a,
	0x14, 0x44, 0x61, 0x74, 0x61, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x66, 0x75, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x53, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x66, 0x75, 0x6c, 0x22, 0x5b, 0x0a, 0x0b, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6e, 0x67,
	0x56, 0x6f, 0x74, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x12, 0x1a,
	0x0a, 0x08, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x44, 0x22, 0x2d, 0x0a, 0x07, 0x4e, 0x61, 0x6d, 0x65, 0x64, 0x49, 0x44, 0x12, 0x0e, 0x0a,
	0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x12, 0x0a,
	0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d,
	0x65, 0x22, 0x57, 0x0a, 0x0f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x73, 0x12, 0x2a, 0x0a, 0x10, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x41,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10,
	0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x44,
	0x12, 0x18, 0x0a, 0x07, 0x54, 0x72, 0x61, 0x63, 0x65, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x54, 0x72, 0x61, 0x63, 0x65, 0x49, 0x44, 0x22, 0x38, 0x0a, 0x1a, 0x55, 0x73,
	0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x52, 0x65, 0x70, 0x6f,
	0x72, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x52, 0x65, 0x70, 0x6f,
	0x72, 0x74, 0x49, 0x44, 0x22, 0xe6, 0x01, 0x0a, 0x12, 0x55, 0x73, 0x65, 0x72, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x44, 0x12, 0x24, 0x0a, 0x0d, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x41, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x3a, 0x0a, 0x18, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x45, 0x78, 0x70, 0x6c, 0x61, 0x6e,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x18, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x45, 0x78, 0x70, 0x6c, 0x61, 0x6e,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x24, 0x0a, 0x0d, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x41,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x41, 0x63,
	0x74, 0x69, 0x76, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x30, 0x0a, 0x13, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x73, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74,
	0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x13, 0x55, 0x73, 0x65, 0x72, 0x49, 0x73,
	0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x65, 0x64, 0x42, 0x3c, 0x5a,
	0x3a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x69, 0x6e, 0x6e,
	0x65, 0x72, 0x64, 0x6f, 0x6e, 0x65, 0x62, 0x65, 0x74, 0x74, 0x65, 0x72, 0x2f, 0x62, 0x61, 0x63,
	0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x67, 0x72,
	0x70, 0x63, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
})

var (
	file_dumping_ground_proto_rawDescOnce sync.Once
	file_dumping_ground_proto_rawDescData []byte
)

func file_dumping_ground_proto_rawDescGZIP() []byte {
	file_dumping_ground_proto_rawDescOnce.Do(func() {
		file_dumping_ground_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dumping_ground_proto_rawDesc), len(file_dumping_ground_proto_rawDesc)))
	})
	return file_dumping_ground_proto_rawDescData
}

var file_dumping_ground_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_dumping_ground_proto_goTypes = []any{
	(*AdminUpdateUserStatusRequest)(nil),         // 0: eating.AdminUpdateUserStatusRequest
	(*AdminUpdateUserStatusResponse)(nil),        // 1: eating.AdminUpdateUserStatusResponse
	(*AggregateUserDataReportRequest)(nil),       // 2: eating.AggregateUserDataReportRequest
	(*AggregateUserDataReportResponse)(nil),      // 3: eating.AggregateUserDataReportResponse
	(*DestroyAllUserDataRequest)(nil),            // 4: eating.DestroyAllUserDataRequest
	(*DestroyAllUserDataResponse)(nil),           // 5: eating.DestroyAllUserDataResponse
	(*FetchUserDataReportRequest)(nil),           // 6: eating.FetchUserDataReportRequest
	(*FetchUserDataReportResponse)(nil),          // 7: eating.FetchUserDataReportResponse
	(*PublishArbitraryQueueMessageRequest)(nil),  // 8: eating.PublishArbitraryQueueMessageRequest
	(*PublishArbitraryQueueMessageResponse)(nil), // 9: eating.PublishArbitraryQueueMessageResponse
	(*DataDeletionResponse)(nil),                 // 10: eating.DataDeletionResponse
	(*MissingVote)(nil),                          // 11: eating.MissingVote
	(*NamedID)(nil),                              // 12: eating.NamedID
	(*ResponseDetails)(nil),                      // 13: eating.ResponseDetails
	(*UserDataCollectionResponse)(nil),           // 14: eating.UserDataCollectionResponse
	(*UserStatusResponse)(nil),                   // 15: eating.UserStatusResponse
}
var file_dumping_ground_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dumping_ground_proto_init() }
func file_dumping_ground_proto_init() {
	if File_dumping_ground_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dumping_ground_proto_rawDesc), len(file_dumping_ground_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dumping_ground_proto_goTypes,
		DependencyIndexes: file_dumping_ground_proto_depIdxs,
		MessageInfos:      file_dumping_ground_proto_msgTypes,
	}.Build()
	File_dumping_ground_proto = out.File
	file_dumping_ground_proto_goTypes = nil
	file_dumping_ground_proto_depIdxs = nil
}
