---
# See: https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# See: https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/resource/
resources:
  - namespace.yaml
  - ../../../kustomize/components/webapp
  - ../../../kustomize/components/admin
  - ../../../kustomize/components/landing

# See: https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/patches/
patches: []

labels:
  - pairs:
      deployed_by: skaffold

generatorOptions:
  disableNameSuffixHash: true
  labels:
    deployed_by: skaffold
    generated_by: skaffold
  annotations:
    deployed_by: skaffold
    generated_by: skaffold
