package components

import (
	"fmt"
	"reflect"
	"strings"
	"time"

	"github.com/dinnerdonebetter/backend/cmd/services/admin/design"
	g "maragu.dev/gomponents"
	ghtml "maragu.dev/gomponents/html"
)

// File generated by AI effectively

// FieldRenderer is a function type that takes a field value and returns a gomponents node
type FieldRenderer func(value any) g.Node

// RowLinkGenerator is a function type that takes an item and returns a URL path for navigation
type RowLinkGenerator[T any] func(item T) string

// TableOptions holds configuration options for the table
type TableOptions[T any] struct {
	// FieldRenderers maps field names to custom rendering functions
	FieldRenderers map[string]FieldRenderer

	// Fields specifies the order of fields in the table.
	// If nil or empty, uses automatic ordering (ID first, timestamps last).
	// Only fields listed here will be displayed.
	Fields []string

	// FieldReplacements maps field names to custom display names.
	// If a field name is not in this map, the automatic camelCaseToTitleCase conversion is used.
	FieldReplacements map[string]string

	// Palette allows customization of colors (uses standard palette if nil)
	Palette *design.Palette

	// TableID sets the HTML ID attribute for the table
	TableID string

	// CSSClasses allows adding custom CSS classes to the table
	CSSClasses string

	// RowLinkGenerator is an optional function that generates a URL path for each row.
	// When provided, each row becomes clickable and navigates to the returned URL.
	RowLinkGenerator RowLinkGenerator[T]
}

// DefaultFieldRenderer provides default rendering for common types
func DefaultFieldRenderer(value any) g.Node {
	if value == nil {
		return g.Text("-")
	}

	switch v := value.(type) {
	case time.Time:
		if v.IsZero() {
			return g.Text("-")
		}
		return g.Text(v.Format("2006-01-02 15:04:05"))
	case *time.Time:
		if v == nil || v.IsZero() {
			return g.Text("-")
		}
		return g.Text(v.Format("2006-01-02 15:04:05"))
	case string:
		if v == "" {
			return g.Text("-")
		}
		return g.Text(v)
	case *string:
		if v == nil || *v == "" {
			return g.Text("-")
		}
		return g.Text(*v)
	case fmt.Stringer:
		str := v.String()
		if str == "" {
			return g.Text("-")
		}
		return g.Text(str)
	default:
		return g.Text(fmt.Sprintf("%v", v))
	}
}

// extractFields uses reflection to get field information from a struct
func extractFields(item any) ([]fieldInfo, error) {
	var fields []fieldInfo

	v := reflect.ValueOf(item)
	if !v.IsValid() {
		return nil, fmt.Errorf("invalid value")
	}

	// Handle pointers
	if v.Kind() == reflect.Ptr {
		if v.IsNil() {
			return nil, fmt.Errorf("nil pointer")
		}
		v = v.Elem()
	}

	if v.Kind() != reflect.Struct {
		return nil, fmt.Errorf("expected struct or pointer to struct, got %s", v.Kind())
	}

	t := v.Type()

	for i := 0; i < t.NumField(); i++ {
		field := t.Field(i)

		// Skip unexported fields
		if !field.IsExported() {
			continue
		}

		// Create a display name (convert CamelCase to Title Case)
		displayName := camelCaseToTitleCase(field.Name)

		fields = append(fields, fieldInfo{
			Name:        field.Name,
			DisplayName: displayName,
			Type:        field.Type,
		})
	}

	return fields, nil
}

// applyFieldOrdering applies the specified field ordering to the fields slice.
// If customOrder is nil or empty, uses automatic ordering (ID first, timestamps last).
// If customOrder is provided, only fields in that list will be included, in that order.
func applyFieldOrdering(fields []fieldInfo, customOrder []string, replacements map[string]string) []fieldInfo {
	// If no custom order specified, use automatic ordering
	if len(customOrder) == 0 {
		fields = sortFields(fields)
	} else {
		// Create a map of field name to field info for quick lookup
		fieldMap := make(map[string]fieldInfo)
		for _, field := range fields {
			fieldMap[field.Name] = field
		}

		// Build result in the specified order
		result := make([]fieldInfo, 0, len(customOrder))
		for _, name := range customOrder {
			if field, exists := fieldMap[name]; exists {
				result = append(result, field)
			}
		}
		fields = result
	}

	// Apply field replacements to display names
	if len(replacements) > 0 {
		for i := range fields {
			if customName, exists := replacements[fields[i].Name]; exists {
				fields[i].DisplayName = customName
			}
		}
	}

	return fields
}

// Table creates a generic HTML table from a slice of structs
func Table[T any](data []T, options *TableOptions[T]) (g.Node, error) {
	if options == nil {
		options = &TableOptions[T]{}
	}

	if len(data) == 0 {
		return createEmptyTable(options), nil
	}

	// Get palette (use standard if not provided)
	palette := options.Palette
	if palette == nil {
		palette = &design.StandardPalette
	}

	// Extract field information from the first item
	fields, err := extractFields(data[0])
	if err != nil {
		return nil, fmt.Errorf("failed to extract fields: %w", err)
	}

	// Apply field ordering and replacements
	fields = applyFieldOrdering(fields, options.Fields, options.FieldReplacements)

	if len(fields) == 0 {
		return createEmptyTable(options), nil
	}

	// Build table classes
	tableClasses := buildTableClasses(options.CSSClasses)

	tableAttrs := []g.Node{ghtml.Class(tableClasses)}
	if options.TableID != "" {
		tableAttrs = append(tableAttrs, ghtml.ID(options.TableID))
	}

	return ghtml.Table(
		append(tableAttrs,
			// Table header
			createTableHeader(fields, palette),
			// Table body
			createTableBody(data, fields, options, palette),
		)...,
	), nil
}

// fieldInfo holds information about a struct field
type fieldInfo struct {
	Name        string
	DisplayName string
	Type        reflect.Type
}

// sortFields sorts the fields with custom ordering:
// - ID field first
// - CreatedAt, LastUpdatedAt, ArchivedAt fields last (in that order)
// - All other fields in their original order in between
func sortFields(fields []fieldInfo) []fieldInfo {
	// Define priority fields
	priorityFirst := "ID"
	priorityLast := []string{"CreatedAt", "LastUpdatedAt", "ArchivedAt"}

	// Create a map for quick lookup of priority last fields
	lastFieldsMap := make(map[string]int)
	for i, name := range priorityLast {
		lastFieldsMap[name] = i
	}

	// Separate fields into categories
	var idField []fieldInfo
	var regularFields []fieldInfo
	lastFields := make([]fieldInfo, len(priorityLast))
	lastFieldsFound := make([]bool, len(priorityLast))

	for _, field := range fields {
		if field.Name == priorityFirst {
			idField = append(idField, field)
		} else if idx, isLast := lastFieldsMap[field.Name]; isLast {
			lastFields[idx] = field
			lastFieldsFound[idx] = true
		} else {
			regularFields = append(regularFields, field)
		}
	}

	// Build the result slice in order
	result := make([]fieldInfo, 0, len(fields))

	// Add ID first
	result = append(result, idField...)

	// Add regular fields
	result = append(result, regularFields...)

	// Add last fields that were found (in priority order)
	for i, found := range lastFieldsFound {
		if found {
			result = append(result, lastFields[i])
		}
	}

	return result
}

// createTableHeader creates the table header row
func createTableHeader(fields []fieldInfo, palette *design.Palette) g.Node {
	var headerCells []g.Node

	for _, field := range fields {
		headerCells = append(headerCells,
			ghtml.Th(
				ghtml.Class(fmt.Sprintf("px-4 py-2 text-left text-sm font-semibold %s uppercase tracking-wide border-b-2 %s bg-gray-50",
					design.TextColor(design.Color{Value: "gray-800"}), // Darker text for better contrast
					design.BorderColor(palette.Primary),               // Primary color border for accent
				)),
				g.Text(field.DisplayName),
			),
		)
	}

	return ghtml.THead(
		ghtml.Class("bg-gray-50"),
		ghtml.Tr(headerCells...),
	)
}

// createTableBody creates the table body with data rows
func createTableBody[T any](data []T, fields []fieldInfo, options *TableOptions[T], palette *design.Palette) g.Node {
	var rows []g.Node

	for i, item := range data {
		var cells []g.Node

		v := reflect.ValueOf(item)
		if v.Kind() == reflect.Ptr {
			if v.IsNil() {
				continue // Skip nil pointers
			}
			v = v.Elem()
		}

		for _, field := range fields {
			fieldValue := v.FieldByName(field.Name)
			if !fieldValue.IsValid() {
				cells = append(cells, createTableCell(nil, field.Name, options, palette))
				continue
			}

			var cellValue any
			if fieldValue.CanInterface() {
				cellValue = fieldValue.Interface()
			}

			cells = append(cells, createTableCell(cellValue, field.Name, options, palette))
		}

		// Alternate row colors with better contrast
		rowClass := "bg-white hover:bg-blue-50"
		if i%2 == 1 {
			rowClass = "bg-gray-50 hover:bg-blue-50"
		}

		// If RowLinkGenerator is provided, make the row clickable with HTMX
		var linkURL string
		if options.RowLinkGenerator != nil {
			linkURL = options.RowLinkGenerator(item)
			if linkURL != "" {
				// Add cursor-pointer to the row class when clickable
				rowClass += " cursor-pointer"
			}
		}

		// Build the row with or without HTMX navigation
		if linkURL != "" {
			rows = append(rows, ghtml.Tr(
				ghtml.Class(fmt.Sprintf("%s transition-colors duration-150", rowClass)),
				// HTMX attributes for navigation
				g.Attr("hx-get", linkURL),
				g.Attr("hx-target", "body"),
				g.Attr("hx-swap", "innerHTML"),
				g.Attr("hx-push-url", "true"),
				// Styling and accessibility
				g.Attr("style", "cursor: pointer;"),
				g.Attr("title", "Click to view details"),
				g.Attr("role", "button"),
				g.Attr("tabindex", "0"),
				g.Group(cells),
			))
		} else {
			rows = append(rows, ghtml.Tr(
				ghtml.Class(fmt.Sprintf("%s transition-colors duration-150", rowClass)),
				g.Group(cells),
			))
		}
	}

	return ghtml.TBody(
		ghtml.Class("bg-white divide-y divide-gray-200"),
		g.Group(rows),
	)
}

// createTableCell creates a single table cell
func createTableCell[T any](value any, fieldName string, options *TableOptions[T], palette *design.Palette) g.Node {
	var content g.Node

	// Use custom renderer if available
	if options.FieldRenderers != nil {
		if renderer, exists := options.FieldRenderers[fieldName]; exists {
			content = renderer(value)
		} else {
			content = DefaultFieldRenderer(value)
		}
	} else {
		content = DefaultFieldRenderer(value)
	}

	return ghtml.Td(
		ghtml.Class("px-4 py-3 whitespace-nowrap text-sm text-gray-900"),
		content,
	)
}

// createEmptyTable creates a table with a "no data" message
func createEmptyTable[T any](options *TableOptions[T]) g.Node {
	tableClasses := buildTableClasses(options.CSSClasses)

	tableAttrs := []g.Node{ghtml.Class(tableClasses)}
	if options.TableID != "" {
		tableAttrs = append(tableAttrs, ghtml.ID(options.TableID))
	}

	return ghtml.Table(
		append(tableAttrs,
			ghtml.TBody(
				ghtml.Tr(
					ghtml.Td(
						ghtml.Class("px-4 py-12 text-center text-sm text-gray-500 bg-gray-50"),
						ghtml.ColSpan("100%"),
						g.Text("No data available"),
					),
				),
			),
		)...,
	)
}

// buildTableClasses constructs the CSS classes for the table
func buildTableClasses(customClasses string) string {
	baseClasses := "min-w-full divide-y divide-gray-200 shadow-lg rounded-lg overflow-hidden border border-gray-200"
	if customClasses != "" {
		return fmt.Sprintf("%s %s", baseClasses, customClasses)
	}
	return baseClasses
}

// commonInitialisms is a list of common initialisms that should not be split
// Add additional initialisms here as needed
var commonInitialisms = []string{
	"ID",
	"API",
	"URI",
	"URL",
	"HTTP",
	"HTTPS",
	"JSON",
	"XML",
	"SQL",
	"DB",
	"CPU",
	"RAM",
	"UUID",
	"HTML",
	"CSS",
	"JS",
	"UI",
	"UX",
	"OS",
}

// camelCaseToTitleCase converts CamelCase to Title Case with spaces
// It handles common initialisms (like ID, API, etc.) as single units
func camelCaseToTitleCase(s string) string {
	if s == "" {
		return s
	}

	// Check for initialisms at the start of the string
	for _, initialism := range commonInitialisms {
		if strings.HasPrefix(s, initialism) {
			// If the string is exactly the initialism, return it as-is
			if len(s) == len(initialism) {
				return initialism
			}
			// If there's more after the initialism, process the rest
			rest := camelCaseToTitleCase(s[len(initialism):])
			if rest != "" {
				return initialism + " " + rest
			}
			return initialism
		}
	}

	var result strings.Builder
	result.WriteByte(s[0])

	for i := 1; i < len(s); i++ {
		// Check if we're at the start of an initialism
		foundInitialism := false
		for _, initialism := range commonInitialisms {
			if i+len(initialism) <= len(s) && s[i:i+len(initialism)] == initialism {
				result.WriteByte(' ')
				result.WriteString(initialism)
				i += len(initialism) - 1 // -1 because the loop will increment
				foundInitialism = true
				break
			}
		}

		if !foundInitialism {
			if s[i] >= 'A' && s[i] <= 'Z' {
				result.WriteByte(' ')
			}
			result.WriteByte(s[i])
		}
	}

	return result.String()
}
