// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v6.33.1
// source: comments/comments_service.proto

/* eslint-disable */
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from '@grpc/grpc-js';
import {
  ArchiveCommentRequest,
  ArchiveCommentResponse,
  CreateCommentRequest,
  CreateCommentResponse,
  GetCommentsForReferenceRequest,
  GetCommentsForReferenceResponse,
  UpdateCommentRequest,
  UpdateCommentResponse,
} from './comments_service_types';

export const protobufPackage = 'comments';

export type CommentsServiceService = typeof CommentsServiceService;
export const CommentsServiceService = {
  createComment: {
    path: '/comments.CommentsService/CreateComment' as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: CreateCommentRequest): Buffer => Buffer.from(CreateCommentRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): CreateCommentRequest => CreateCommentRequest.decode(value),
    responseSerialize: (value: CreateCommentResponse): Buffer =>
      Buffer.from(CreateCommentResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): CreateCommentResponse => CreateCommentResponse.decode(value),
  },
  archiveComment: {
    path: '/comments.CommentsService/ArchiveComment' as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: ArchiveCommentRequest): Buffer =>
      Buffer.from(ArchiveCommentRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): ArchiveCommentRequest => ArchiveCommentRequest.decode(value),
    responseSerialize: (value: ArchiveCommentResponse): Buffer =>
      Buffer.from(ArchiveCommentResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): ArchiveCommentResponse => ArchiveCommentResponse.decode(value),
  },
  getCommentsForReference: {
    path: '/comments.CommentsService/GetCommentsForReference' as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: GetCommentsForReferenceRequest): Buffer =>
      Buffer.from(GetCommentsForReferenceRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetCommentsForReferenceRequest => GetCommentsForReferenceRequest.decode(value),
    responseSerialize: (value: GetCommentsForReferenceResponse): Buffer =>
      Buffer.from(GetCommentsForReferenceResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): GetCommentsForReferenceResponse =>
      GetCommentsForReferenceResponse.decode(value),
  },
  updateComment: {
    path: '/comments.CommentsService/UpdateComment' as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: UpdateCommentRequest): Buffer => Buffer.from(UpdateCommentRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): UpdateCommentRequest => UpdateCommentRequest.decode(value),
    responseSerialize: (value: UpdateCommentResponse): Buffer =>
      Buffer.from(UpdateCommentResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): UpdateCommentResponse => UpdateCommentResponse.decode(value),
  },
} as const;

export interface CommentsServiceServer extends UntypedServiceImplementation {
  createComment: handleUnaryCall<CreateCommentRequest, CreateCommentResponse>;
  archiveComment: handleUnaryCall<ArchiveCommentRequest, ArchiveCommentResponse>;
  getCommentsForReference: handleUnaryCall<GetCommentsForReferenceRequest, GetCommentsForReferenceResponse>;
  updateComment: handleUnaryCall<UpdateCommentRequest, UpdateCommentResponse>;
}

export interface CommentsServiceClient extends Client {
  createComment(
    request: CreateCommentRequest,
    callback: (error: ServiceError | null, response: CreateCommentResponse) => void,
  ): ClientUnaryCall;
  createComment(
    request: CreateCommentRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: CreateCommentResponse) => void,
  ): ClientUnaryCall;
  createComment(
    request: CreateCommentRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: CreateCommentResponse) => void,
  ): ClientUnaryCall;
  archiveComment(
    request: ArchiveCommentRequest,
    callback: (error: ServiceError | null, response: ArchiveCommentResponse) => void,
  ): ClientUnaryCall;
  archiveComment(
    request: ArchiveCommentRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: ArchiveCommentResponse) => void,
  ): ClientUnaryCall;
  archiveComment(
    request: ArchiveCommentRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: ArchiveCommentResponse) => void,
  ): ClientUnaryCall;
  getCommentsForReference(
    request: GetCommentsForReferenceRequest,
    callback: (error: ServiceError | null, response: GetCommentsForReferenceResponse) => void,
  ): ClientUnaryCall;
  getCommentsForReference(
    request: GetCommentsForReferenceRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GetCommentsForReferenceResponse) => void,
  ): ClientUnaryCall;
  getCommentsForReference(
    request: GetCommentsForReferenceRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GetCommentsForReferenceResponse) => void,
  ): ClientUnaryCall;
  updateComment(
    request: UpdateCommentRequest,
    callback: (error: ServiceError | null, response: UpdateCommentResponse) => void,
  ): ClientUnaryCall;
  updateComment(
    request: UpdateCommentRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: UpdateCommentResponse) => void,
  ): ClientUnaryCall;
  updateComment(
    request: UpdateCommentRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: UpdateCommentResponse) => void,
  ): ClientUnaryCall;
}

export const CommentsServiceClient = makeGenericClientConstructor(
  CommentsServiceService,
  'comments.CommentsService',
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): CommentsServiceClient;
  service: typeof CommentsServiceService;
  serviceName: string;
};
