// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v6.33.1
// source: auth/auth_messages.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from '@bufbuild/protobuf/wire';
import { Timestamp } from '../google/protobuf/timestamp';

export const protobufPackage = 'auth';

export interface ChangeActiveAccountInput {
  accountId: string;
}

export interface PasswordResetToken {
  createdAt: Date | undefined;
  expiresAt: Date | undefined;
  redeemedAt: Date | undefined;
  lastUpdatedAt: Date | undefined;
  id: string;
  token: string;
  belongsToUser: string;
}

export interface PasswordUpdateInput {
  newPassword: string;
  currentPassword: string;
  totpToken: string;
}

export interface TOTPSecretRefreshInput {
  currentPassword: string;
  totpToken: string;
}

export interface TOTPSecretVerificationInput {
  totpToken: string;
  userId: string;
}

export interface UserLoginInput {
  username: string;
  password: string;
  totpToken: string;
  desiredAccountId: string;
}

export interface UserSession {
  id: string;
  clientIp: string;
  userAgent: string;
  deviceName: string;
  loginMethod: string;
  createdAt: Date | undefined;
  lastActiveAt: Date | undefined;
  expiresAt: Date | undefined;
  isCurrent: boolean;
}

function createBaseChangeActiveAccountInput(): ChangeActiveAccountInput {
  return { accountId: '' };
}

export const ChangeActiveAccountInput: MessageFns<ChangeActiveAccountInput> = {
  encode(message: ChangeActiveAccountInput, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.accountId !== '') {
      writer.uint32(10).string(message.accountId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ChangeActiveAccountInput {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChangeActiveAccountInput();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.accountId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ChangeActiveAccountInput {
    return {
      accountId: isSet(object.accountId)
        ? globalThis.String(object.accountId)
        : isSet(object.account_id)
          ? globalThis.String(object.account_id)
          : '',
    };
  },

  toJSON(message: ChangeActiveAccountInput): unknown {
    const obj: any = {};
    if (message.accountId !== '') {
      obj.accountId = message.accountId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ChangeActiveAccountInput>, I>>(base?: I): ChangeActiveAccountInput {
    return ChangeActiveAccountInput.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ChangeActiveAccountInput>, I>>(object: I): ChangeActiveAccountInput {
    const message = createBaseChangeActiveAccountInput();
    message.accountId = object.accountId ?? '';
    return message;
  },
};

function createBasePasswordResetToken(): PasswordResetToken {
  return {
    createdAt: undefined,
    expiresAt: undefined,
    redeemedAt: undefined,
    lastUpdatedAt: undefined,
    id: '',
    token: '',
    belongsToUser: '',
  };
}

export const PasswordResetToken: MessageFns<PasswordResetToken> = {
  encode(message: PasswordResetToken, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.createdAt !== undefined) {
      Timestamp.encode(toTimestamp(message.createdAt), writer.uint32(10).fork()).join();
    }
    if (message.expiresAt !== undefined) {
      Timestamp.encode(toTimestamp(message.expiresAt), writer.uint32(18).fork()).join();
    }
    if (message.redeemedAt !== undefined) {
      Timestamp.encode(toTimestamp(message.redeemedAt), writer.uint32(26).fork()).join();
    }
    if (message.lastUpdatedAt !== undefined) {
      Timestamp.encode(toTimestamp(message.lastUpdatedAt), writer.uint32(34).fork()).join();
    }
    if (message.id !== '') {
      writer.uint32(42).string(message.id);
    }
    if (message.token !== '') {
      writer.uint32(50).string(message.token);
    }
    if (message.belongsToUser !== '') {
      writer.uint32(58).string(message.belongsToUser);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PasswordResetToken {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePasswordResetToken();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.createdAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.expiresAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.redeemedAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.lastUpdatedAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.token = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.belongsToUser = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PasswordResetToken {
    return {
      createdAt: isSet(object.createdAt)
        ? fromJsonTimestamp(object.createdAt)
        : isSet(object.created_at)
          ? fromJsonTimestamp(object.created_at)
          : undefined,
      expiresAt: isSet(object.expiresAt)
        ? fromJsonTimestamp(object.expiresAt)
        : isSet(object.expires_at)
          ? fromJsonTimestamp(object.expires_at)
          : undefined,
      redeemedAt: isSet(object.redeemedAt)
        ? fromJsonTimestamp(object.redeemedAt)
        : isSet(object.redeemed_at)
          ? fromJsonTimestamp(object.redeemed_at)
          : undefined,
      lastUpdatedAt: isSet(object.lastUpdatedAt)
        ? fromJsonTimestamp(object.lastUpdatedAt)
        : isSet(object.last_updated_at)
          ? fromJsonTimestamp(object.last_updated_at)
          : undefined,
      id: isSet(object.id) ? globalThis.String(object.id) : '',
      token: isSet(object.token) ? globalThis.String(object.token) : '',
      belongsToUser: isSet(object.belongsToUser)
        ? globalThis.String(object.belongsToUser)
        : isSet(object.belongs_to_user)
          ? globalThis.String(object.belongs_to_user)
          : '',
    };
  },

  toJSON(message: PasswordResetToken): unknown {
    const obj: any = {};
    if (message.createdAt !== undefined) {
      obj.createdAt = message.createdAt.toISOString();
    }
    if (message.expiresAt !== undefined) {
      obj.expiresAt = message.expiresAt.toISOString();
    }
    if (message.redeemedAt !== undefined) {
      obj.redeemedAt = message.redeemedAt.toISOString();
    }
    if (message.lastUpdatedAt !== undefined) {
      obj.lastUpdatedAt = message.lastUpdatedAt.toISOString();
    }
    if (message.id !== '') {
      obj.id = message.id;
    }
    if (message.token !== '') {
      obj.token = message.token;
    }
    if (message.belongsToUser !== '') {
      obj.belongsToUser = message.belongsToUser;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PasswordResetToken>, I>>(base?: I): PasswordResetToken {
    return PasswordResetToken.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PasswordResetToken>, I>>(object: I): PasswordResetToken {
    const message = createBasePasswordResetToken();
    message.createdAt = object.createdAt ?? undefined;
    message.expiresAt = object.expiresAt ?? undefined;
    message.redeemedAt = object.redeemedAt ?? undefined;
    message.lastUpdatedAt = object.lastUpdatedAt ?? undefined;
    message.id = object.id ?? '';
    message.token = object.token ?? '';
    message.belongsToUser = object.belongsToUser ?? '';
    return message;
  },
};

function createBasePasswordUpdateInput(): PasswordUpdateInput {
  return { newPassword: '', currentPassword: '', totpToken: '' };
}

export const PasswordUpdateInput: MessageFns<PasswordUpdateInput> = {
  encode(message: PasswordUpdateInput, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.newPassword !== '') {
      writer.uint32(10).string(message.newPassword);
    }
    if (message.currentPassword !== '') {
      writer.uint32(18).string(message.currentPassword);
    }
    if (message.totpToken !== '') {
      writer.uint32(26).string(message.totpToken);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PasswordUpdateInput {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePasswordUpdateInput();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.newPassword = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.currentPassword = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.totpToken = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PasswordUpdateInput {
    return {
      newPassword: isSet(object.newPassword)
        ? globalThis.String(object.newPassword)
        : isSet(object.new_password)
          ? globalThis.String(object.new_password)
          : '',
      currentPassword: isSet(object.currentPassword)
        ? globalThis.String(object.currentPassword)
        : isSet(object.current_password)
          ? globalThis.String(object.current_password)
          : '',
      totpToken: isSet(object.totpToken)
        ? globalThis.String(object.totpToken)
        : isSet(object.totp_token)
          ? globalThis.String(object.totp_token)
          : '',
    };
  },

  toJSON(message: PasswordUpdateInput): unknown {
    const obj: any = {};
    if (message.newPassword !== '') {
      obj.newPassword = message.newPassword;
    }
    if (message.currentPassword !== '') {
      obj.currentPassword = message.currentPassword;
    }
    if (message.totpToken !== '') {
      obj.totpToken = message.totpToken;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PasswordUpdateInput>, I>>(base?: I): PasswordUpdateInput {
    return PasswordUpdateInput.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PasswordUpdateInput>, I>>(object: I): PasswordUpdateInput {
    const message = createBasePasswordUpdateInput();
    message.newPassword = object.newPassword ?? '';
    message.currentPassword = object.currentPassword ?? '';
    message.totpToken = object.totpToken ?? '';
    return message;
  },
};

function createBaseTOTPSecretRefreshInput(): TOTPSecretRefreshInput {
  return { currentPassword: '', totpToken: '' };
}

export const TOTPSecretRefreshInput: MessageFns<TOTPSecretRefreshInput> = {
  encode(message: TOTPSecretRefreshInput, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.currentPassword !== '') {
      writer.uint32(10).string(message.currentPassword);
    }
    if (message.totpToken !== '') {
      writer.uint32(18).string(message.totpToken);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TOTPSecretRefreshInput {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTOTPSecretRefreshInput();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.currentPassword = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.totpToken = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TOTPSecretRefreshInput {
    return {
      currentPassword: isSet(object.currentPassword)
        ? globalThis.String(object.currentPassword)
        : isSet(object.current_password)
          ? globalThis.String(object.current_password)
          : '',
      totpToken: isSet(object.totpToken)
        ? globalThis.String(object.totpToken)
        : isSet(object.totp_token)
          ? globalThis.String(object.totp_token)
          : '',
    };
  },

  toJSON(message: TOTPSecretRefreshInput): unknown {
    const obj: any = {};
    if (message.currentPassword !== '') {
      obj.currentPassword = message.currentPassword;
    }
    if (message.totpToken !== '') {
      obj.totpToken = message.totpToken;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TOTPSecretRefreshInput>, I>>(base?: I): TOTPSecretRefreshInput {
    return TOTPSecretRefreshInput.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TOTPSecretRefreshInput>, I>>(object: I): TOTPSecretRefreshInput {
    const message = createBaseTOTPSecretRefreshInput();
    message.currentPassword = object.currentPassword ?? '';
    message.totpToken = object.totpToken ?? '';
    return message;
  },
};

function createBaseTOTPSecretVerificationInput(): TOTPSecretVerificationInput {
  return { totpToken: '', userId: '' };
}

export const TOTPSecretVerificationInput: MessageFns<TOTPSecretVerificationInput> = {
  encode(message: TOTPSecretVerificationInput, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.totpToken !== '') {
      writer.uint32(10).string(message.totpToken);
    }
    if (message.userId !== '') {
      writer.uint32(18).string(message.userId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TOTPSecretVerificationInput {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTOTPSecretVerificationInput();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.totpToken = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TOTPSecretVerificationInput {
    return {
      totpToken: isSet(object.totpToken)
        ? globalThis.String(object.totpToken)
        : isSet(object.totp_token)
          ? globalThis.String(object.totp_token)
          : '',
      userId: isSet(object.userId)
        ? globalThis.String(object.userId)
        : isSet(object.user_id)
          ? globalThis.String(object.user_id)
          : '',
    };
  },

  toJSON(message: TOTPSecretVerificationInput): unknown {
    const obj: any = {};
    if (message.totpToken !== '') {
      obj.totpToken = message.totpToken;
    }
    if (message.userId !== '') {
      obj.userId = message.userId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TOTPSecretVerificationInput>, I>>(base?: I): TOTPSecretVerificationInput {
    return TOTPSecretVerificationInput.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TOTPSecretVerificationInput>, I>>(object: I): TOTPSecretVerificationInput {
    const message = createBaseTOTPSecretVerificationInput();
    message.totpToken = object.totpToken ?? '';
    message.userId = object.userId ?? '';
    return message;
  },
};

function createBaseUserLoginInput(): UserLoginInput {
  return { username: '', password: '', totpToken: '', desiredAccountId: '' };
}

export const UserLoginInput: MessageFns<UserLoginInput> = {
  encode(message: UserLoginInput, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.username !== '') {
      writer.uint32(10).string(message.username);
    }
    if (message.password !== '') {
      writer.uint32(18).string(message.password);
    }
    if (message.totpToken !== '') {
      writer.uint32(26).string(message.totpToken);
    }
    if (message.desiredAccountId !== '') {
      writer.uint32(34).string(message.desiredAccountId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UserLoginInput {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUserLoginInput();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.username = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.password = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.totpToken = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.desiredAccountId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UserLoginInput {
    return {
      username: isSet(object.username) ? globalThis.String(object.username) : '',
      password: isSet(object.password) ? globalThis.String(object.password) : '',
      totpToken: isSet(object.totpToken)
        ? globalThis.String(object.totpToken)
        : isSet(object.totp_token)
          ? globalThis.String(object.totp_token)
          : '',
      desiredAccountId: isSet(object.desiredAccountId)
        ? globalThis.String(object.desiredAccountId)
        : isSet(object.desired_account_id)
          ? globalThis.String(object.desired_account_id)
          : '',
    };
  },

  toJSON(message: UserLoginInput): unknown {
    const obj: any = {};
    if (message.username !== '') {
      obj.username = message.username;
    }
    if (message.password !== '') {
      obj.password = message.password;
    }
    if (message.totpToken !== '') {
      obj.totpToken = message.totpToken;
    }
    if (message.desiredAccountId !== '') {
      obj.desiredAccountId = message.desiredAccountId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UserLoginInput>, I>>(base?: I): UserLoginInput {
    return UserLoginInput.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UserLoginInput>, I>>(object: I): UserLoginInput {
    const message = createBaseUserLoginInput();
    message.username = object.username ?? '';
    message.password = object.password ?? '';
    message.totpToken = object.totpToken ?? '';
    message.desiredAccountId = object.desiredAccountId ?? '';
    return message;
  },
};

function createBaseUserSession(): UserSession {
  return {
    id: '',
    clientIp: '',
    userAgent: '',
    deviceName: '',
    loginMethod: '',
    createdAt: undefined,
    lastActiveAt: undefined,
    expiresAt: undefined,
    isCurrent: false,
  };
}

export const UserSession: MessageFns<UserSession> = {
  encode(message: UserSession, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== '') {
      writer.uint32(10).string(message.id);
    }
    if (message.clientIp !== '') {
      writer.uint32(18).string(message.clientIp);
    }
    if (message.userAgent !== '') {
      writer.uint32(26).string(message.userAgent);
    }
    if (message.deviceName !== '') {
      writer.uint32(34).string(message.deviceName);
    }
    if (message.loginMethod !== '') {
      writer.uint32(42).string(message.loginMethod);
    }
    if (message.createdAt !== undefined) {
      Timestamp.encode(toTimestamp(message.createdAt), writer.uint32(50).fork()).join();
    }
    if (message.lastActiveAt !== undefined) {
      Timestamp.encode(toTimestamp(message.lastActiveAt), writer.uint32(58).fork()).join();
    }
    if (message.expiresAt !== undefined) {
      Timestamp.encode(toTimestamp(message.expiresAt), writer.uint32(66).fork()).join();
    }
    if (message.isCurrent !== false) {
      writer.uint32(72).bool(message.isCurrent);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UserSession {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUserSession();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.clientIp = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.userAgent = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.deviceName = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.loginMethod = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.createdAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.lastActiveAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.expiresAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.isCurrent = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UserSession {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : '',
      clientIp: isSet(object.clientIp)
        ? globalThis.String(object.clientIp)
        : isSet(object.client_ip)
          ? globalThis.String(object.client_ip)
          : '',
      userAgent: isSet(object.userAgent)
        ? globalThis.String(object.userAgent)
        : isSet(object.user_agent)
          ? globalThis.String(object.user_agent)
          : '',
      deviceName: isSet(object.deviceName)
        ? globalThis.String(object.deviceName)
        : isSet(object.device_name)
          ? globalThis.String(object.device_name)
          : '',
      loginMethod: isSet(object.loginMethod)
        ? globalThis.String(object.loginMethod)
        : isSet(object.login_method)
          ? globalThis.String(object.login_method)
          : '',
      createdAt: isSet(object.createdAt)
        ? fromJsonTimestamp(object.createdAt)
        : isSet(object.created_at)
          ? fromJsonTimestamp(object.created_at)
          : undefined,
      lastActiveAt: isSet(object.lastActiveAt)
        ? fromJsonTimestamp(object.lastActiveAt)
        : isSet(object.last_active_at)
          ? fromJsonTimestamp(object.last_active_at)
          : undefined,
      expiresAt: isSet(object.expiresAt)
        ? fromJsonTimestamp(object.expiresAt)
        : isSet(object.expires_at)
          ? fromJsonTimestamp(object.expires_at)
          : undefined,
      isCurrent: isSet(object.isCurrent)
        ? globalThis.Boolean(object.isCurrent)
        : isSet(object.is_current)
          ? globalThis.Boolean(object.is_current)
          : false,
    };
  },

  toJSON(message: UserSession): unknown {
    const obj: any = {};
    if (message.id !== '') {
      obj.id = message.id;
    }
    if (message.clientIp !== '') {
      obj.clientIp = message.clientIp;
    }
    if (message.userAgent !== '') {
      obj.userAgent = message.userAgent;
    }
    if (message.deviceName !== '') {
      obj.deviceName = message.deviceName;
    }
    if (message.loginMethod !== '') {
      obj.loginMethod = message.loginMethod;
    }
    if (message.createdAt !== undefined) {
      obj.createdAt = message.createdAt.toISOString();
    }
    if (message.lastActiveAt !== undefined) {
      obj.lastActiveAt = message.lastActiveAt.toISOString();
    }
    if (message.expiresAt !== undefined) {
      obj.expiresAt = message.expiresAt.toISOString();
    }
    if (message.isCurrent !== false) {
      obj.isCurrent = message.isCurrent;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UserSession>, I>>(base?: I): UserSession {
    return UserSession.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UserSession>, I>>(object: I): UserSession {
    const message = createBaseUserSession();
    message.id = object.id ?? '';
    message.clientIp = object.clientIp ?? '';
    message.userAgent = object.userAgent ?? '';
    message.deviceName = object.deviceName ?? '';
    message.loginMethod = object.loginMethod ?? '';
    message.createdAt = object.createdAt ?? undefined;
    message.lastActiveAt = object.lastActiveAt ?? undefined;
    message.expiresAt = object.expiresAt ?? undefined;
    message.isCurrent = object.isCurrent ?? false;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends {}
        ? { [K in keyof T]?: DeepPartial<T[K]> }
        : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === 'string') {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
