// Code generated by mockery. DO NOT EDIT.

package mock

import (
	context "context"

	identity "github.com/dinnerdonebetter/backend/internal/domain/identity"
	filtering "github.com/dinnerdonebetter/backend/internal/platform/database/filtering"

	mock "github.com/stretchr/testify/mock"
)

// IdentityDataManager is an autogenerated mock type for the IdentityDataManager type
type IdentityDataManager struct {
	mock.Mock
}

type IdentityDataManager_Expecter struct {
	mock *mock.Mock
}

func (_m *IdentityDataManager) EXPECT() *IdentityDataManager_Expecter {
	return &IdentityDataManager_Expecter{mock: &_m.Mock}
}

// AcceptAccountInvitation provides a mock function with given fields: ctx, accountID, accountInvitationID, input
func (_m *IdentityDataManager) AcceptAccountInvitation(ctx context.Context, accountID string, accountInvitationID string, input *identity.AccountInvitationUpdateRequestInput) error {
	ret := _m.Called(ctx, accountID, accountInvitationID, input)

	if len(ret) == 0 {
		panic("no return value specified for AcceptAccountInvitation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *identity.AccountInvitationUpdateRequestInput) error); ok {
		r0 = rf(ctx, accountID, accountInvitationID, input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IdentityDataManager_AcceptAccountInvitation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AcceptAccountInvitation'
type IdentityDataManager_AcceptAccountInvitation_Call struct {
	*mock.Call
}

// AcceptAccountInvitation is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID string
//   - accountInvitationID string
//   - input *identity.AccountInvitationUpdateRequestInput
func (_e *IdentityDataManager_Expecter) AcceptAccountInvitation(ctx interface{}, accountID interface{}, accountInvitationID interface{}, input interface{}) *IdentityDataManager_AcceptAccountInvitation_Call {
	return &IdentityDataManager_AcceptAccountInvitation_Call{Call: _e.mock.On("AcceptAccountInvitation", ctx, accountID, accountInvitationID, input)}
}

func (_c *IdentityDataManager_AcceptAccountInvitation_Call) Run(run func(ctx context.Context, accountID string, accountInvitationID string, input *identity.AccountInvitationUpdateRequestInput)) *IdentityDataManager_AcceptAccountInvitation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(*identity.AccountInvitationUpdateRequestInput))
	})
	return _c
}

func (_c *IdentityDataManager_AcceptAccountInvitation_Call) Return(_a0 error) *IdentityDataManager_AcceptAccountInvitation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IdentityDataManager_AcceptAccountInvitation_Call) RunAndReturn(run func(context.Context, string, string, *identity.AccountInvitationUpdateRequestInput) error) *IdentityDataManager_AcceptAccountInvitation_Call {
	_c.Call.Return(run)
	return _c
}

// AdminUpdateUserStatus provides a mock function with given fields: ctx, input
func (_m *IdentityDataManager) AdminUpdateUserStatus(ctx context.Context, input *identity.UserAccountStatusUpdateInput) error {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for AdminUpdateUserStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *identity.UserAccountStatusUpdateInput) error); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IdentityDataManager_AdminUpdateUserStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AdminUpdateUserStatus'
type IdentityDataManager_AdminUpdateUserStatus_Call struct {
	*mock.Call
}

// AdminUpdateUserStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - input *identity.UserAccountStatusUpdateInput
func (_e *IdentityDataManager_Expecter) AdminUpdateUserStatus(ctx interface{}, input interface{}) *IdentityDataManager_AdminUpdateUserStatus_Call {
	return &IdentityDataManager_AdminUpdateUserStatus_Call{Call: _e.mock.On("AdminUpdateUserStatus", ctx, input)}
}

func (_c *IdentityDataManager_AdminUpdateUserStatus_Call) Run(run func(ctx context.Context, input *identity.UserAccountStatusUpdateInput)) *IdentityDataManager_AdminUpdateUserStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*identity.UserAccountStatusUpdateInput))
	})
	return _c
}

func (_c *IdentityDataManager_AdminUpdateUserStatus_Call) Return(_a0 error) *IdentityDataManager_AdminUpdateUserStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IdentityDataManager_AdminUpdateUserStatus_Call) RunAndReturn(run func(context.Context, *identity.UserAccountStatusUpdateInput) error) *IdentityDataManager_AdminUpdateUserStatus_Call {
	_c.Call.Return(run)
	return _c
}

// ArchiveAccount provides a mock function with given fields: ctx, accountID, ownerID
func (_m *IdentityDataManager) ArchiveAccount(ctx context.Context, accountID string, ownerID string) error {
	ret := _m.Called(ctx, accountID, ownerID)

	if len(ret) == 0 {
		panic("no return value specified for ArchiveAccount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, accountID, ownerID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IdentityDataManager_ArchiveAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ArchiveAccount'
type IdentityDataManager_ArchiveAccount_Call struct {
	*mock.Call
}

// ArchiveAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID string
//   - ownerID string
func (_e *IdentityDataManager_Expecter) ArchiveAccount(ctx interface{}, accountID interface{}, ownerID interface{}) *IdentityDataManager_ArchiveAccount_Call {
	return &IdentityDataManager_ArchiveAccount_Call{Call: _e.mock.On("ArchiveAccount", ctx, accountID, ownerID)}
}

func (_c *IdentityDataManager_ArchiveAccount_Call) Run(run func(ctx context.Context, accountID string, ownerID string)) *IdentityDataManager_ArchiveAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *IdentityDataManager_ArchiveAccount_Call) Return(_a0 error) *IdentityDataManager_ArchiveAccount_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IdentityDataManager_ArchiveAccount_Call) RunAndReturn(run func(context.Context, string, string) error) *IdentityDataManager_ArchiveAccount_Call {
	_c.Call.Return(run)
	return _c
}

// ArchiveUser provides a mock function with given fields: ctx, userID
func (_m *IdentityDataManager) ArchiveUser(ctx context.Context, userID string) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ArchiveUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IdentityDataManager_ArchiveUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ArchiveUser'
type IdentityDataManager_ArchiveUser_Call struct {
	*mock.Call
}

// ArchiveUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *IdentityDataManager_Expecter) ArchiveUser(ctx interface{}, userID interface{}) *IdentityDataManager_ArchiveUser_Call {
	return &IdentityDataManager_ArchiveUser_Call{Call: _e.mock.On("ArchiveUser", ctx, userID)}
}

func (_c *IdentityDataManager_ArchiveUser_Call) Run(run func(ctx context.Context, userID string)) *IdentityDataManager_ArchiveUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *IdentityDataManager_ArchiveUser_Call) Return(_a0 error) *IdentityDataManager_ArchiveUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IdentityDataManager_ArchiveUser_Call) RunAndReturn(run func(context.Context, string) error) *IdentityDataManager_ArchiveUser_Call {
	_c.Call.Return(run)
	return _c
}

// ArchiveUserMembership provides a mock function with given fields: ctx, userID, accountID
func (_m *IdentityDataManager) ArchiveUserMembership(ctx context.Context, userID string, accountID string) error {
	ret := _m.Called(ctx, userID, accountID)

	if len(ret) == 0 {
		panic("no return value specified for ArchiveUserMembership")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, accountID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IdentityDataManager_ArchiveUserMembership_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ArchiveUserMembership'
type IdentityDataManager_ArchiveUserMembership_Call struct {
	*mock.Call
}

// ArchiveUserMembership is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - accountID string
func (_e *IdentityDataManager_Expecter) ArchiveUserMembership(ctx interface{}, userID interface{}, accountID interface{}) *IdentityDataManager_ArchiveUserMembership_Call {
	return &IdentityDataManager_ArchiveUserMembership_Call{Call: _e.mock.On("ArchiveUserMembership", ctx, userID, accountID)}
}

func (_c *IdentityDataManager_ArchiveUserMembership_Call) Run(run func(ctx context.Context, userID string, accountID string)) *IdentityDataManager_ArchiveUserMembership_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *IdentityDataManager_ArchiveUserMembership_Call) Return(_a0 error) *IdentityDataManager_ArchiveUserMembership_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IdentityDataManager_ArchiveUserMembership_Call) RunAndReturn(run func(context.Context, string, string) error) *IdentityDataManager_ArchiveUserMembership_Call {
	_c.Call.Return(run)
	return _c
}

// CancelAccountInvitation provides a mock function with given fields: ctx, accountID, accountInvitationID, note
func (_m *IdentityDataManager) CancelAccountInvitation(ctx context.Context, accountID string, accountInvitationID string, note string) error {
	ret := _m.Called(ctx, accountID, accountInvitationID, note)

	if len(ret) == 0 {
		panic("no return value specified for CancelAccountInvitation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, accountID, accountInvitationID, note)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IdentityDataManager_CancelAccountInvitation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelAccountInvitation'
type IdentityDataManager_CancelAccountInvitation_Call struct {
	*mock.Call
}

// CancelAccountInvitation is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID string
//   - accountInvitationID string
//   - note string
func (_e *IdentityDataManager_Expecter) CancelAccountInvitation(ctx interface{}, accountID interface{}, accountInvitationID interface{}, note interface{}) *IdentityDataManager_CancelAccountInvitation_Call {
	return &IdentityDataManager_CancelAccountInvitation_Call{Call: _e.mock.On("CancelAccountInvitation", ctx, accountID, accountInvitationID, note)}
}

func (_c *IdentityDataManager_CancelAccountInvitation_Call) Run(run func(ctx context.Context, accountID string, accountInvitationID string, note string)) *IdentityDataManager_CancelAccountInvitation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *IdentityDataManager_CancelAccountInvitation_Call) Return(_a0 error) *IdentityDataManager_CancelAccountInvitation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IdentityDataManager_CancelAccountInvitation_Call) RunAndReturn(run func(context.Context, string, string, string) error) *IdentityDataManager_CancelAccountInvitation_Call {
	_c.Call.Return(run)
	return _c
}

// CreateAccount provides a mock function with given fields: ctx, input
func (_m *IdentityDataManager) CreateAccount(ctx context.Context, input *identity.AccountCreationRequestInput) (*identity.Account, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateAccount")
	}

	var r0 *identity.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *identity.AccountCreationRequestInput) (*identity.Account, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *identity.AccountCreationRequestInput) *identity.Account); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*identity.Account)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *identity.AccountCreationRequestInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IdentityDataManager_CreateAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAccount'
type IdentityDataManager_CreateAccount_Call struct {
	*mock.Call
}

// CreateAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - input *identity.AccountCreationRequestInput
func (_e *IdentityDataManager_Expecter) CreateAccount(ctx interface{}, input interface{}) *IdentityDataManager_CreateAccount_Call {
	return &IdentityDataManager_CreateAccount_Call{Call: _e.mock.On("CreateAccount", ctx, input)}
}

func (_c *IdentityDataManager_CreateAccount_Call) Run(run func(ctx context.Context, input *identity.AccountCreationRequestInput)) *IdentityDataManager_CreateAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*identity.AccountCreationRequestInput))
	})
	return _c
}

func (_c *IdentityDataManager_CreateAccount_Call) Return(_a0 *identity.Account, _a1 error) *IdentityDataManager_CreateAccount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IdentityDataManager_CreateAccount_Call) RunAndReturn(run func(context.Context, *identity.AccountCreationRequestInput) (*identity.Account, error)) *IdentityDataManager_CreateAccount_Call {
	_c.Call.Return(run)
	return _c
}

// CreateAccountInvitation provides a mock function with given fields: ctx, userID, accountID, input
func (_m *IdentityDataManager) CreateAccountInvitation(ctx context.Context, userID string, accountID string, input *identity.AccountInvitationCreationRequestInput) (*identity.AccountInvitation, error) {
	ret := _m.Called(ctx, userID, accountID, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateAccountInvitation")
	}

	var r0 *identity.AccountInvitation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *identity.AccountInvitationCreationRequestInput) (*identity.AccountInvitation, error)); ok {
		return rf(ctx, userID, accountID, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *identity.AccountInvitationCreationRequestInput) *identity.AccountInvitation); ok {
		r0 = rf(ctx, userID, accountID, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*identity.AccountInvitation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, *identity.AccountInvitationCreationRequestInput) error); ok {
		r1 = rf(ctx, userID, accountID, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IdentityDataManager_CreateAccountInvitation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAccountInvitation'
type IdentityDataManager_CreateAccountInvitation_Call struct {
	*mock.Call
}

// CreateAccountInvitation is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - accountID string
//   - input *identity.AccountInvitationCreationRequestInput
func (_e *IdentityDataManager_Expecter) CreateAccountInvitation(ctx interface{}, userID interface{}, accountID interface{}, input interface{}) *IdentityDataManager_CreateAccountInvitation_Call {
	return &IdentityDataManager_CreateAccountInvitation_Call{Call: _e.mock.On("CreateAccountInvitation", ctx, userID, accountID, input)}
}

func (_c *IdentityDataManager_CreateAccountInvitation_Call) Run(run func(ctx context.Context, userID string, accountID string, input *identity.AccountInvitationCreationRequestInput)) *IdentityDataManager_CreateAccountInvitation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(*identity.AccountInvitationCreationRequestInput))
	})
	return _c
}

func (_c *IdentityDataManager_CreateAccountInvitation_Call) Return(_a0 *identity.AccountInvitation, _a1 error) *IdentityDataManager_CreateAccountInvitation_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IdentityDataManager_CreateAccountInvitation_Call) RunAndReturn(run func(context.Context, string, string, *identity.AccountInvitationCreationRequestInput) (*identity.AccountInvitation, error)) *IdentityDataManager_CreateAccountInvitation_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUser provides a mock function with given fields: ctx, registrationInput
func (_m *IdentityDataManager) CreateUser(ctx context.Context, registrationInput *identity.UserRegistrationInput) (*identity.UserCreationResponse, error) {
	ret := _m.Called(ctx, registrationInput)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 *identity.UserCreationResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *identity.UserRegistrationInput) (*identity.UserCreationResponse, error)); ok {
		return rf(ctx, registrationInput)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *identity.UserRegistrationInput) *identity.UserCreationResponse); ok {
		r0 = rf(ctx, registrationInput)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*identity.UserCreationResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *identity.UserRegistrationInput) error); ok {
		r1 = rf(ctx, registrationInput)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IdentityDataManager_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type IdentityDataManager_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - registrationInput *identity.UserRegistrationInput
func (_e *IdentityDataManager_Expecter) CreateUser(ctx interface{}, registrationInput interface{}) *IdentityDataManager_CreateUser_Call {
	return &IdentityDataManager_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, registrationInput)}
}

func (_c *IdentityDataManager_CreateUser_Call) Run(run func(ctx context.Context, registrationInput *identity.UserRegistrationInput)) *IdentityDataManager_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*identity.UserRegistrationInput))
	})
	return _c
}

func (_c *IdentityDataManager_CreateUser_Call) Return(_a0 *identity.UserCreationResponse, _a1 error) *IdentityDataManager_CreateUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IdentityDataManager_CreateUser_Call) RunAndReturn(run func(context.Context, *identity.UserRegistrationInput) (*identity.UserCreationResponse, error)) *IdentityDataManager_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetAccount provides a mock function with given fields: ctx, accountID
func (_m *IdentityDataManager) GetAccount(ctx context.Context, accountID string) (*identity.Account, error) {
	ret := _m.Called(ctx, accountID)

	if len(ret) == 0 {
		panic("no return value specified for GetAccount")
	}

	var r0 *identity.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*identity.Account, error)); ok {
		return rf(ctx, accountID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *identity.Account); ok {
		r0 = rf(ctx, accountID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*identity.Account)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, accountID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IdentityDataManager_GetAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccount'
type IdentityDataManager_GetAccount_Call struct {
	*mock.Call
}

// GetAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID string
func (_e *IdentityDataManager_Expecter) GetAccount(ctx interface{}, accountID interface{}) *IdentityDataManager_GetAccount_Call {
	return &IdentityDataManager_GetAccount_Call{Call: _e.mock.On("GetAccount", ctx, accountID)}
}

func (_c *IdentityDataManager_GetAccount_Call) Run(run func(ctx context.Context, accountID string)) *IdentityDataManager_GetAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *IdentityDataManager_GetAccount_Call) Return(_a0 *identity.Account, _a1 error) *IdentityDataManager_GetAccount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IdentityDataManager_GetAccount_Call) RunAndReturn(run func(context.Context, string) (*identity.Account, error)) *IdentityDataManager_GetAccount_Call {
	_c.Call.Return(run)
	return _c
}

// GetAccountInvitation provides a mock function with given fields: ctx, accountID, accountInvitationID
func (_m *IdentityDataManager) GetAccountInvitation(ctx context.Context, accountID string, accountInvitationID string) (*identity.AccountInvitation, error) {
	ret := _m.Called(ctx, accountID, accountInvitationID)

	if len(ret) == 0 {
		panic("no return value specified for GetAccountInvitation")
	}

	var r0 *identity.AccountInvitation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*identity.AccountInvitation, error)); ok {
		return rf(ctx, accountID, accountInvitationID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *identity.AccountInvitation); ok {
		r0 = rf(ctx, accountID, accountInvitationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*identity.AccountInvitation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, accountID, accountInvitationID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IdentityDataManager_GetAccountInvitation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccountInvitation'
type IdentityDataManager_GetAccountInvitation_Call struct {
	*mock.Call
}

// GetAccountInvitation is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID string
//   - accountInvitationID string
func (_e *IdentityDataManager_Expecter) GetAccountInvitation(ctx interface{}, accountID interface{}, accountInvitationID interface{}) *IdentityDataManager_GetAccountInvitation_Call {
	return &IdentityDataManager_GetAccountInvitation_Call{Call: _e.mock.On("GetAccountInvitation", ctx, accountID, accountInvitationID)}
}

func (_c *IdentityDataManager_GetAccountInvitation_Call) Run(run func(ctx context.Context, accountID string, accountInvitationID string)) *IdentityDataManager_GetAccountInvitation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *IdentityDataManager_GetAccountInvitation_Call) Return(_a0 *identity.AccountInvitation, _a1 error) *IdentityDataManager_GetAccountInvitation_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IdentityDataManager_GetAccountInvitation_Call) RunAndReturn(run func(context.Context, string, string) (*identity.AccountInvitation, error)) *IdentityDataManager_GetAccountInvitation_Call {
	_c.Call.Return(run)
	return _c
}

// GetAccounts provides a mock function with given fields: ctx, userID, filter
func (_m *IdentityDataManager) GetAccounts(ctx context.Context, userID string, filter *filtering.QueryFilter) ([]*identity.Account, string, error) {
	ret := _m.Called(ctx, userID, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetAccounts")
	}

	var r0 []*identity.Account
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *filtering.QueryFilter) ([]*identity.Account, string, error)); ok {
		return rf(ctx, userID, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *filtering.QueryFilter) []*identity.Account); ok {
		r0 = rf(ctx, userID, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*identity.Account)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *filtering.QueryFilter) string); ok {
		r1 = rf(ctx, userID, filter)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, *filtering.QueryFilter) error); ok {
		r2 = rf(ctx, userID, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// IdentityDataManager_GetAccounts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccounts'
type IdentityDataManager_GetAccounts_Call struct {
	*mock.Call
}

// GetAccounts is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - filter *filtering.QueryFilter
func (_e *IdentityDataManager_Expecter) GetAccounts(ctx interface{}, userID interface{}, filter interface{}) *IdentityDataManager_GetAccounts_Call {
	return &IdentityDataManager_GetAccounts_Call{Call: _e.mock.On("GetAccounts", ctx, userID, filter)}
}

func (_c *IdentityDataManager_GetAccounts_Call) Run(run func(ctx context.Context, userID string, filter *filtering.QueryFilter)) *IdentityDataManager_GetAccounts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*filtering.QueryFilter))
	})
	return _c
}

func (_c *IdentityDataManager_GetAccounts_Call) Return(_a0 []*identity.Account, _a1 string, _a2 error) *IdentityDataManager_GetAccounts_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *IdentityDataManager_GetAccounts_Call) RunAndReturn(run func(context.Context, string, *filtering.QueryFilter) ([]*identity.Account, string, error)) *IdentityDataManager_GetAccounts_Call {
	_c.Call.Return(run)
	return _c
}

// GetReceivedAccountInvitations provides a mock function with given fields: ctx, userID, filter
func (_m *IdentityDataManager) GetReceivedAccountInvitations(ctx context.Context, userID string, filter *filtering.QueryFilter) ([]*identity.AccountInvitation, string, error) {
	ret := _m.Called(ctx, userID, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetReceivedAccountInvitations")
	}

	var r0 []*identity.AccountInvitation
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *filtering.QueryFilter) ([]*identity.AccountInvitation, string, error)); ok {
		return rf(ctx, userID, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *filtering.QueryFilter) []*identity.AccountInvitation); ok {
		r0 = rf(ctx, userID, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*identity.AccountInvitation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *filtering.QueryFilter) string); ok {
		r1 = rf(ctx, userID, filter)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, *filtering.QueryFilter) error); ok {
		r2 = rf(ctx, userID, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// IdentityDataManager_GetReceivedAccountInvitations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReceivedAccountInvitations'
type IdentityDataManager_GetReceivedAccountInvitations_Call struct {
	*mock.Call
}

// GetReceivedAccountInvitations is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - filter *filtering.QueryFilter
func (_e *IdentityDataManager_Expecter) GetReceivedAccountInvitations(ctx interface{}, userID interface{}, filter interface{}) *IdentityDataManager_GetReceivedAccountInvitations_Call {
	return &IdentityDataManager_GetReceivedAccountInvitations_Call{Call: _e.mock.On("GetReceivedAccountInvitations", ctx, userID, filter)}
}

func (_c *IdentityDataManager_GetReceivedAccountInvitations_Call) Run(run func(ctx context.Context, userID string, filter *filtering.QueryFilter)) *IdentityDataManager_GetReceivedAccountInvitations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*filtering.QueryFilter))
	})
	return _c
}

func (_c *IdentityDataManager_GetReceivedAccountInvitations_Call) Return(_a0 []*identity.AccountInvitation, _a1 string, _a2 error) *IdentityDataManager_GetReceivedAccountInvitations_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *IdentityDataManager_GetReceivedAccountInvitations_Call) RunAndReturn(run func(context.Context, string, *filtering.QueryFilter) ([]*identity.AccountInvitation, string, error)) *IdentityDataManager_GetReceivedAccountInvitations_Call {
	_c.Call.Return(run)
	return _c
}

// GetSentAccountInvitations provides a mock function with given fields: ctx, userID, filter
func (_m *IdentityDataManager) GetSentAccountInvitations(ctx context.Context, userID string, filter *filtering.QueryFilter) ([]*identity.AccountInvitation, string, error) {
	ret := _m.Called(ctx, userID, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetSentAccountInvitations")
	}

	var r0 []*identity.AccountInvitation
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *filtering.QueryFilter) ([]*identity.AccountInvitation, string, error)); ok {
		return rf(ctx, userID, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *filtering.QueryFilter) []*identity.AccountInvitation); ok {
		r0 = rf(ctx, userID, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*identity.AccountInvitation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *filtering.QueryFilter) string); ok {
		r1 = rf(ctx, userID, filter)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, *filtering.QueryFilter) error); ok {
		r2 = rf(ctx, userID, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// IdentityDataManager_GetSentAccountInvitations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSentAccountInvitations'
type IdentityDataManager_GetSentAccountInvitations_Call struct {
	*mock.Call
}

// GetSentAccountInvitations is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - filter *filtering.QueryFilter
func (_e *IdentityDataManager_Expecter) GetSentAccountInvitations(ctx interface{}, userID interface{}, filter interface{}) *IdentityDataManager_GetSentAccountInvitations_Call {
	return &IdentityDataManager_GetSentAccountInvitations_Call{Call: _e.mock.On("GetSentAccountInvitations", ctx, userID, filter)}
}

func (_c *IdentityDataManager_GetSentAccountInvitations_Call) Run(run func(ctx context.Context, userID string, filter *filtering.QueryFilter)) *IdentityDataManager_GetSentAccountInvitations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*filtering.QueryFilter))
	})
	return _c
}

func (_c *IdentityDataManager_GetSentAccountInvitations_Call) Return(_a0 []*identity.AccountInvitation, _a1 string, _a2 error) *IdentityDataManager_GetSentAccountInvitations_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *IdentityDataManager_GetSentAccountInvitations_Call) RunAndReturn(run func(context.Context, string, *filtering.QueryFilter) ([]*identity.AccountInvitation, string, error)) *IdentityDataManager_GetSentAccountInvitations_Call {
	_c.Call.Return(run)
	return _c
}

// GetUser provides a mock function with given fields: ctx, userID
func (_m *IdentityDataManager) GetUser(ctx context.Context, userID string) (*identity.User, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 *identity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*identity.User, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *identity.User); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*identity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IdentityDataManager_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type IdentityDataManager_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *IdentityDataManager_Expecter) GetUser(ctx interface{}, userID interface{}) *IdentityDataManager_GetUser_Call {
	return &IdentityDataManager_GetUser_Call{Call: _e.mock.On("GetUser", ctx, userID)}
}

func (_c *IdentityDataManager_GetUser_Call) Run(run func(ctx context.Context, userID string)) *IdentityDataManager_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *IdentityDataManager_GetUser_Call) Return(_a0 *identity.User, _a1 error) *IdentityDataManager_GetUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IdentityDataManager_GetUser_Call) RunAndReturn(run func(context.Context, string) (*identity.User, error)) *IdentityDataManager_GetUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUsers provides a mock function with given fields: ctx, filter
func (_m *IdentityDataManager) GetUsers(ctx context.Context, filter *filtering.QueryFilter) ([]*identity.User, string, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetUsers")
	}

	var r0 []*identity.User
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *filtering.QueryFilter) ([]*identity.User, string, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *filtering.QueryFilter) []*identity.User); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*identity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *filtering.QueryFilter) string); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, *filtering.QueryFilter) error); ok {
		r2 = rf(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// IdentityDataManager_GetUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUsers'
type IdentityDataManager_GetUsers_Call struct {
	*mock.Call
}

// GetUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - filter *filtering.QueryFilter
func (_e *IdentityDataManager_Expecter) GetUsers(ctx interface{}, filter interface{}) *IdentityDataManager_GetUsers_Call {
	return &IdentityDataManager_GetUsers_Call{Call: _e.mock.On("GetUsers", ctx, filter)}
}

func (_c *IdentityDataManager_GetUsers_Call) Run(run func(ctx context.Context, filter *filtering.QueryFilter)) *IdentityDataManager_GetUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*filtering.QueryFilter))
	})
	return _c
}

func (_c *IdentityDataManager_GetUsers_Call) Return(_a0 []*identity.User, _a1 string, _a2 error) *IdentityDataManager_GetUsers_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *IdentityDataManager_GetUsers_Call) RunAndReturn(run func(context.Context, *filtering.QueryFilter) ([]*identity.User, string, error)) *IdentityDataManager_GetUsers_Call {
	_c.Call.Return(run)
	return _c
}

// RejectAccountInvitation provides a mock function with given fields: ctx, accountID, accountInvitationID, input
func (_m *IdentityDataManager) RejectAccountInvitation(ctx context.Context, accountID string, accountInvitationID string, input *identity.AccountInvitationUpdateRequestInput) error {
	ret := _m.Called(ctx, accountID, accountInvitationID, input)

	if len(ret) == 0 {
		panic("no return value specified for RejectAccountInvitation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *identity.AccountInvitationUpdateRequestInput) error); ok {
		r0 = rf(ctx, accountID, accountInvitationID, input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IdentityDataManager_RejectAccountInvitation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RejectAccountInvitation'
type IdentityDataManager_RejectAccountInvitation_Call struct {
	*mock.Call
}

// RejectAccountInvitation is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID string
//   - accountInvitationID string
//   - input *identity.AccountInvitationUpdateRequestInput
func (_e *IdentityDataManager_Expecter) RejectAccountInvitation(ctx interface{}, accountID interface{}, accountInvitationID interface{}, input interface{}) *IdentityDataManager_RejectAccountInvitation_Call {
	return &IdentityDataManager_RejectAccountInvitation_Call{Call: _e.mock.On("RejectAccountInvitation", ctx, accountID, accountInvitationID, input)}
}

func (_c *IdentityDataManager_RejectAccountInvitation_Call) Run(run func(ctx context.Context, accountID string, accountInvitationID string, input *identity.AccountInvitationUpdateRequestInput)) *IdentityDataManager_RejectAccountInvitation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(*identity.AccountInvitationUpdateRequestInput))
	})
	return _c
}

func (_c *IdentityDataManager_RejectAccountInvitation_Call) Return(_a0 error) *IdentityDataManager_RejectAccountInvitation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IdentityDataManager_RejectAccountInvitation_Call) RunAndReturn(run func(context.Context, string, string, *identity.AccountInvitationUpdateRequestInput) error) *IdentityDataManager_RejectAccountInvitation_Call {
	_c.Call.Return(run)
	return _c
}

// SearchForUsers provides a mock function with given fields: ctx, query, useSearchService, filter
func (_m *IdentityDataManager) SearchForUsers(ctx context.Context, query string, useSearchService bool, filter *filtering.QueryFilter) ([]*identity.User, string, error) {
	ret := _m.Called(ctx, query, useSearchService, filter)

	if len(ret) == 0 {
		panic("no return value specified for SearchForUsers")
	}

	var r0 []*identity.User
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, bool, *filtering.QueryFilter) ([]*identity.User, string, error)); ok {
		return rf(ctx, query, useSearchService, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, bool, *filtering.QueryFilter) []*identity.User); ok {
		r0 = rf(ctx, query, useSearchService, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*identity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, bool, *filtering.QueryFilter) string); ok {
		r1 = rf(ctx, query, useSearchService, filter)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, bool, *filtering.QueryFilter) error); ok {
		r2 = rf(ctx, query, useSearchService, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// IdentityDataManager_SearchForUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchForUsers'
type IdentityDataManager_SearchForUsers_Call struct {
	*mock.Call
}

// SearchForUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - useSearchService bool
//   - filter *filtering.QueryFilter
func (_e *IdentityDataManager_Expecter) SearchForUsers(ctx interface{}, query interface{}, useSearchService interface{}, filter interface{}) *IdentityDataManager_SearchForUsers_Call {
	return &IdentityDataManager_SearchForUsers_Call{Call: _e.mock.On("SearchForUsers", ctx, query, useSearchService, filter)}
}

func (_c *IdentityDataManager_SearchForUsers_Call) Run(run func(ctx context.Context, query string, useSearchService bool, filter *filtering.QueryFilter)) *IdentityDataManager_SearchForUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(bool), args[3].(*filtering.QueryFilter))
	})
	return _c
}

func (_c *IdentityDataManager_SearchForUsers_Call) Return(_a0 []*identity.User, _a1 string, _a2 error) *IdentityDataManager_SearchForUsers_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *IdentityDataManager_SearchForUsers_Call) RunAndReturn(run func(context.Context, string, bool, *filtering.QueryFilter) ([]*identity.User, string, error)) *IdentityDataManager_SearchForUsers_Call {
	_c.Call.Return(run)
	return _c
}

// SetDefaultAccount provides a mock function with given fields: ctx, userID, accountID
func (_m *IdentityDataManager) SetDefaultAccount(ctx context.Context, userID string, accountID string) error {
	ret := _m.Called(ctx, userID, accountID)

	if len(ret) == 0 {
		panic("no return value specified for SetDefaultAccount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, accountID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IdentityDataManager_SetDefaultAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetDefaultAccount'
type IdentityDataManager_SetDefaultAccount_Call struct {
	*mock.Call
}

// SetDefaultAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - accountID string
func (_e *IdentityDataManager_Expecter) SetDefaultAccount(ctx interface{}, userID interface{}, accountID interface{}) *IdentityDataManager_SetDefaultAccount_Call {
	return &IdentityDataManager_SetDefaultAccount_Call{Call: _e.mock.On("SetDefaultAccount", ctx, userID, accountID)}
}

func (_c *IdentityDataManager_SetDefaultAccount_Call) Run(run func(ctx context.Context, userID string, accountID string)) *IdentityDataManager_SetDefaultAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *IdentityDataManager_SetDefaultAccount_Call) Return(_a0 error) *IdentityDataManager_SetDefaultAccount_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IdentityDataManager_SetDefaultAccount_Call) RunAndReturn(run func(context.Context, string, string) error) *IdentityDataManager_SetDefaultAccount_Call {
	_c.Call.Return(run)
	return _c
}

// TransferAccountOwnership provides a mock function with given fields: ctx, accountID, input
func (_m *IdentityDataManager) TransferAccountOwnership(ctx context.Context, accountID string, input *identity.AccountOwnershipTransferInput) error {
	ret := _m.Called(ctx, accountID, input)

	if len(ret) == 0 {
		panic("no return value specified for TransferAccountOwnership")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *identity.AccountOwnershipTransferInput) error); ok {
		r0 = rf(ctx, accountID, input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IdentityDataManager_TransferAccountOwnership_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TransferAccountOwnership'
type IdentityDataManager_TransferAccountOwnership_Call struct {
	*mock.Call
}

// TransferAccountOwnership is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID string
//   - input *identity.AccountOwnershipTransferInput
func (_e *IdentityDataManager_Expecter) TransferAccountOwnership(ctx interface{}, accountID interface{}, input interface{}) *IdentityDataManager_TransferAccountOwnership_Call {
	return &IdentityDataManager_TransferAccountOwnership_Call{Call: _e.mock.On("TransferAccountOwnership", ctx, accountID, input)}
}

func (_c *IdentityDataManager_TransferAccountOwnership_Call) Run(run func(ctx context.Context, accountID string, input *identity.AccountOwnershipTransferInput)) *IdentityDataManager_TransferAccountOwnership_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*identity.AccountOwnershipTransferInput))
	})
	return _c
}

func (_c *IdentityDataManager_TransferAccountOwnership_Call) Return(_a0 error) *IdentityDataManager_TransferAccountOwnership_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IdentityDataManager_TransferAccountOwnership_Call) RunAndReturn(run func(context.Context, string, *identity.AccountOwnershipTransferInput) error) *IdentityDataManager_TransferAccountOwnership_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateAccount provides a mock function with given fields: ctx, accountID, input
func (_m *IdentityDataManager) UpdateAccount(ctx context.Context, accountID string, input *identity.AccountUpdateRequestInput) error {
	ret := _m.Called(ctx, accountID, input)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAccount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *identity.AccountUpdateRequestInput) error); ok {
		r0 = rf(ctx, accountID, input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IdentityDataManager_UpdateAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAccount'
type IdentityDataManager_UpdateAccount_Call struct {
	*mock.Call
}

// UpdateAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID string
//   - input *identity.AccountUpdateRequestInput
func (_e *IdentityDataManager_Expecter) UpdateAccount(ctx interface{}, accountID interface{}, input interface{}) *IdentityDataManager_UpdateAccount_Call {
	return &IdentityDataManager_UpdateAccount_Call{Call: _e.mock.On("UpdateAccount", ctx, accountID, input)}
}

func (_c *IdentityDataManager_UpdateAccount_Call) Run(run func(ctx context.Context, accountID string, input *identity.AccountUpdateRequestInput)) *IdentityDataManager_UpdateAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*identity.AccountUpdateRequestInput))
	})
	return _c
}

func (_c *IdentityDataManager_UpdateAccount_Call) Return(_a0 error) *IdentityDataManager_UpdateAccount_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IdentityDataManager_UpdateAccount_Call) RunAndReturn(run func(context.Context, string, *identity.AccountUpdateRequestInput) error) *IdentityDataManager_UpdateAccount_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateAccountMemberPermissions provides a mock function with given fields: ctx, userID, accountID, input
func (_m *IdentityDataManager) UpdateAccountMemberPermissions(ctx context.Context, userID string, accountID string, input *identity.ModifyUserPermissionsInput) error {
	ret := _m.Called(ctx, userID, accountID, input)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAccountMemberPermissions")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *identity.ModifyUserPermissionsInput) error); ok {
		r0 = rf(ctx, userID, accountID, input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IdentityDataManager_UpdateAccountMemberPermissions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAccountMemberPermissions'
type IdentityDataManager_UpdateAccountMemberPermissions_Call struct {
	*mock.Call
}

// UpdateAccountMemberPermissions is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - accountID string
//   - input *identity.ModifyUserPermissionsInput
func (_e *IdentityDataManager_Expecter) UpdateAccountMemberPermissions(ctx interface{}, userID interface{}, accountID interface{}, input interface{}) *IdentityDataManager_UpdateAccountMemberPermissions_Call {
	return &IdentityDataManager_UpdateAccountMemberPermissions_Call{Call: _e.mock.On("UpdateAccountMemberPermissions", ctx, userID, accountID, input)}
}

func (_c *IdentityDataManager_UpdateAccountMemberPermissions_Call) Run(run func(ctx context.Context, userID string, accountID string, input *identity.ModifyUserPermissionsInput)) *IdentityDataManager_UpdateAccountMemberPermissions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(*identity.ModifyUserPermissionsInput))
	})
	return _c
}

func (_c *IdentityDataManager_UpdateAccountMemberPermissions_Call) Return(_a0 error) *IdentityDataManager_UpdateAccountMemberPermissions_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IdentityDataManager_UpdateAccountMemberPermissions_Call) RunAndReturn(run func(context.Context, string, string, *identity.ModifyUserPermissionsInput) error) *IdentityDataManager_UpdateAccountMemberPermissions_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUserDetails provides a mock function with given fields: ctx, userID, input
func (_m *IdentityDataManager) UpdateUserDetails(ctx context.Context, userID string, input *identity.UserDetailsUpdateRequestInput) error {
	ret := _m.Called(ctx, userID, input)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserDetails")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *identity.UserDetailsUpdateRequestInput) error); ok {
		r0 = rf(ctx, userID, input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IdentityDataManager_UpdateUserDetails_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserDetails'
type IdentityDataManager_UpdateUserDetails_Call struct {
	*mock.Call
}

// UpdateUserDetails is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - input *identity.UserDetailsUpdateRequestInput
func (_e *IdentityDataManager_Expecter) UpdateUserDetails(ctx interface{}, userID interface{}, input interface{}) *IdentityDataManager_UpdateUserDetails_Call {
	return &IdentityDataManager_UpdateUserDetails_Call{Call: _e.mock.On("UpdateUserDetails", ctx, userID, input)}
}

func (_c *IdentityDataManager_UpdateUserDetails_Call) Run(run func(ctx context.Context, userID string, input *identity.UserDetailsUpdateRequestInput)) *IdentityDataManager_UpdateUserDetails_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*identity.UserDetailsUpdateRequestInput))
	})
	return _c
}

func (_c *IdentityDataManager_UpdateUserDetails_Call) Return(_a0 error) *IdentityDataManager_UpdateUserDetails_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IdentityDataManager_UpdateUserDetails_Call) RunAndReturn(run func(context.Context, string, *identity.UserDetailsUpdateRequestInput) error) *IdentityDataManager_UpdateUserDetails_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUserEmailAddress provides a mock function with given fields: ctx, userID, newEmail
func (_m *IdentityDataManager) UpdateUserEmailAddress(ctx context.Context, userID string, newEmail string) error {
	ret := _m.Called(ctx, userID, newEmail)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserEmailAddress")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, newEmail)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IdentityDataManager_UpdateUserEmailAddress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserEmailAddress'
type IdentityDataManager_UpdateUserEmailAddress_Call struct {
	*mock.Call
}

// UpdateUserEmailAddress is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - newEmail string
func (_e *IdentityDataManager_Expecter) UpdateUserEmailAddress(ctx interface{}, userID interface{}, newEmail interface{}) *IdentityDataManager_UpdateUserEmailAddress_Call {
	return &IdentityDataManager_UpdateUserEmailAddress_Call{Call: _e.mock.On("UpdateUserEmailAddress", ctx, userID, newEmail)}
}

func (_c *IdentityDataManager_UpdateUserEmailAddress_Call) Run(run func(ctx context.Context, userID string, newEmail string)) *IdentityDataManager_UpdateUserEmailAddress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *IdentityDataManager_UpdateUserEmailAddress_Call) Return(_a0 error) *IdentityDataManager_UpdateUserEmailAddress_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IdentityDataManager_UpdateUserEmailAddress_Call) RunAndReturn(run func(context.Context, string, string) error) *IdentityDataManager_UpdateUserEmailAddress_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUserUsername provides a mock function with given fields: ctx, userID, newUsername
func (_m *IdentityDataManager) UpdateUserUsername(ctx context.Context, userID string, newUsername string) error {
	ret := _m.Called(ctx, userID, newUsername)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserUsername")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, newUsername)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IdentityDataManager_UpdateUserUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserUsername'
type IdentityDataManager_UpdateUserUsername_Call struct {
	*mock.Call
}

// UpdateUserUsername is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - newUsername string
func (_e *IdentityDataManager_Expecter) UpdateUserUsername(ctx interface{}, userID interface{}, newUsername interface{}) *IdentityDataManager_UpdateUserUsername_Call {
	return &IdentityDataManager_UpdateUserUsername_Call{Call: _e.mock.On("UpdateUserUsername", ctx, userID, newUsername)}
}

func (_c *IdentityDataManager_UpdateUserUsername_Call) Run(run func(ctx context.Context, userID string, newUsername string)) *IdentityDataManager_UpdateUserUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *IdentityDataManager_UpdateUserUsername_Call) Return(_a0 error) *IdentityDataManager_UpdateUserUsername_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IdentityDataManager_UpdateUserUsername_Call) RunAndReturn(run func(context.Context, string, string) error) *IdentityDataManager_UpdateUserUsername_Call {
	_c.Call.Return(run)
	return _c
}

// UploadUserAvatar provides a mock function with given fields: ctx, userID, base64EncodedImageData
func (_m *IdentityDataManager) UploadUserAvatar(ctx context.Context, userID string, base64EncodedImageData string) error {
	ret := _m.Called(ctx, userID, base64EncodedImageData)

	if len(ret) == 0 {
		panic("no return value specified for UploadUserAvatar")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, base64EncodedImageData)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IdentityDataManager_UploadUserAvatar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadUserAvatar'
type IdentityDataManager_UploadUserAvatar_Call struct {
	*mock.Call
}

// UploadUserAvatar is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - base64EncodedImageData string
func (_e *IdentityDataManager_Expecter) UploadUserAvatar(ctx interface{}, userID interface{}, base64EncodedImageData interface{}) *IdentityDataManager_UploadUserAvatar_Call {
	return &IdentityDataManager_UploadUserAvatar_Call{Call: _e.mock.On("UploadUserAvatar", ctx, userID, base64EncodedImageData)}
}

func (_c *IdentityDataManager_UploadUserAvatar_Call) Run(run func(ctx context.Context, userID string, base64EncodedImageData string)) *IdentityDataManager_UploadUserAvatar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *IdentityDataManager_UploadUserAvatar_Call) Return(_a0 error) *IdentityDataManager_UploadUserAvatar_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IdentityDataManager_UploadUserAvatar_Call) RunAndReturn(run func(context.Context, string, string) error) *IdentityDataManager_UploadUserAvatar_Call {
	_c.Call.Return(run)
	return _c
}

// NewIdentityDataManager creates a new instance of IdentityDataManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIdentityDataManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *IdentityDataManager {
	mock := &IdentityDataManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
