---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: dinner-done-better-job-meal-plan-grocery-list-init
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: meal-plan-grocery-list-init
            image: dinner-done-better-job-meal-plan-grocery-list-init
            imagePullPolicy: IfNotPresent
            env:
              - name: "CONFIGURATION_FILEPATH"
                value: "/etc/service-config.json"
              - name: "DINNER_DONE_BETTER_DATA_CHANGES_TOPIC_NAME"
                value: "data_changes"
            volumeMounts:
            - name: "config"
              mountPath: "/etc/service-config.json"
              subPath: "config.json"
          restartPolicy: OnFailure
          volumes:
            - name: "config"
              configMap:
                name: "dinner-done-better-job-meal-plan-grocery-list-init-config"
---
