// Code generated by gen_typescript. DO NOT EDIT.

import { NumberRange, NumberRangeWithOptionalMax, OptionalNumberRange } from './main';
import {
  RecipePrepTaskStep,
  RecipePrepTaskStepCreationRequestInput,
  RecipePrepTaskStepUpdateRequestInput,
  RecipePrepTaskStepWithinRecipeCreationRequestInput,
} from './recipePrepTaskSteps';

export interface IRecipePrepTask {
  createdAt: NonNullable<string>;
  storageTemperatureInCelsius: NonNullable<NumberRange>;
  timeBufferBeforeRecipeInSeconds: NonNullable<NumberRangeWithOptionalMax>;
  archivedAt?: string;
  lastUpdatedAt?: string;
  id: NonNullable<string>;
  storageType: NonNullable<string>;
  belongsToRecipe: NonNullable<string>;
  explicitStorageInstructions: NonNullable<string>;
  notes: NonNullable<string>;
  name: NonNullable<string>;
  description: NonNullable<string>;
  recipeSteps: NonNullable<Array<RecipePrepTaskStep>>;
  optional: NonNullable<boolean>;
}

export class RecipePrepTask implements IRecipePrepTask {
  createdAt: NonNullable<string> = '1970-01-01T00:00:00Z';
  storageTemperatureInCelsius: NonNullable<NumberRange> = { min: 0, max: 0 };
  timeBufferBeforeRecipeInSeconds: NonNullable<NumberRangeWithOptionalMax> = { min: 0 };
  archivedAt?: string;
  lastUpdatedAt?: string;
  id: NonNullable<string> = '';
  storageType: NonNullable<string> = '';
  belongsToRecipe: NonNullable<string> = '';
  explicitStorageInstructions: NonNullable<string> = '';
  notes: NonNullable<string> = '';
  name: NonNullable<string> = '';
  description: NonNullable<string> = '';
  recipeSteps: NonNullable<Array<RecipePrepTaskStep>> = [];
  optional: NonNullable<boolean> = false;

  constructor(input: Partial<RecipePrepTask> = {}) {
    this.createdAt = input.createdAt ?? '1970-01-01T00:00:00Z';
    this.storageTemperatureInCelsius = input.storageTemperatureInCelsius ?? { min: 0, max: 0 };
    this.timeBufferBeforeRecipeInSeconds = input.timeBufferBeforeRecipeInSeconds ?? { min: 0 };
    this.archivedAt = input.archivedAt;
    this.lastUpdatedAt = input.lastUpdatedAt;
    this.id = input.id ?? '';
    this.storageType = input.storageType ?? '';
    this.belongsToRecipe = input.belongsToRecipe ?? '';
    this.explicitStorageInstructions = input.explicitStorageInstructions ?? '';
    this.notes = input.notes ?? '';
    this.name = input.name ?? '';
    this.description = input.description ?? '';
    this.recipeSteps = input.recipeSteps ?? [];
    this.optional = input.optional ?? false;
  }
}

export interface IRecipePrepTaskCreationRequestInput {
  storageTemperatureInCelsius: NonNullable<NumberRange>;
  timeBufferBeforeRecipeInSeconds: NonNullable<NumberRangeWithOptionalMax>;
  storageType: NonNullable<string>;
  explicitStorageInstructions: NonNullable<string>;
  notes: NonNullable<string>;
  name: NonNullable<string>;
  description: NonNullable<string>;
  belongsToRecipe: NonNullable<string>;
  recipeSteps: NonNullable<Array<RecipePrepTaskStepCreationRequestInput>>;
  optional: NonNullable<boolean>;
}

export class RecipePrepTaskCreationRequestInput implements IRecipePrepTaskCreationRequestInput {
  storageTemperatureInCelsius: NonNullable<NumberRange> = { min: 0, max: 0 };
  timeBufferBeforeRecipeInSeconds: NonNullable<NumberRangeWithOptionalMax> = { min: 0 };
  storageType: NonNullable<string> = '';
  explicitStorageInstructions: NonNullable<string> = '';
  notes: NonNullable<string> = '';
  name: NonNullable<string> = '';
  description: NonNullable<string> = '';
  belongsToRecipe: NonNullable<string> = '';
  recipeSteps: NonNullable<Array<RecipePrepTaskStepCreationRequestInput>> = [];
  optional: NonNullable<boolean> = false;

  constructor(input: Partial<RecipePrepTaskCreationRequestInput> = {}) {
    this.storageTemperatureInCelsius = input.storageTemperatureInCelsius ?? { min: 0, max: 0 };
    this.timeBufferBeforeRecipeInSeconds = input.timeBufferBeforeRecipeInSeconds ?? { min: 0 };
    this.storageType = input.storageType ?? '';
    this.explicitStorageInstructions = input.explicitStorageInstructions ?? '';
    this.notes = input.notes ?? '';
    this.name = input.name ?? '';
    this.description = input.description ?? '';
    this.belongsToRecipe = input.belongsToRecipe ?? '';
    this.recipeSteps = input.recipeSteps ?? [];
    this.optional = input.optional ?? false;
  }
}

export interface IRecipePrepTaskWithinRecipeCreationRequestInput {
  storageTemperatureInCelsius: NonNullable<NumberRange>;
  timeBufferBeforeRecipeInSeconds: NonNullable<NumberRangeWithOptionalMax>;
  storageType: NonNullable<string>;
  name: NonNullable<string>;
  description: NonNullable<string>;
  explicitStorageInstructions: NonNullable<string>;
  notes: NonNullable<string>;
  belongsToRecipe: NonNullable<string>;
  recipeSteps: NonNullable<Array<RecipePrepTaskStepWithinRecipeCreationRequestInput>>;
  optional: NonNullable<boolean>;
}

export class RecipePrepTaskWithinRecipeCreationRequestInput implements IRecipePrepTaskWithinRecipeCreationRequestInput {
  storageTemperatureInCelsius: NonNullable<NumberRange> = { min: 0, max: 0 };
  timeBufferBeforeRecipeInSeconds: NonNullable<NumberRangeWithOptionalMax> = { min: 0 };
  storageType: NonNullable<string> = '';
  name: NonNullable<string> = '';
  description: NonNullable<string> = '';
  explicitStorageInstructions: NonNullable<string> = '';
  notes: NonNullable<string> = '';
  belongsToRecipe: NonNullable<string> = '';
  recipeSteps: NonNullable<Array<RecipePrepTaskStepWithinRecipeCreationRequestInput>> = [];
  optional: NonNullable<boolean> = false;

  constructor(input: Partial<RecipePrepTaskWithinRecipeCreationRequestInput> = {}) {
    this.storageTemperatureInCelsius = input.storageTemperatureInCelsius ?? { min: 0, max: 0 };
    this.timeBufferBeforeRecipeInSeconds = input.timeBufferBeforeRecipeInSeconds ?? { min: 0 };
    this.storageType = input.storageType ?? '';
    this.name = input.name ?? '';
    this.description = input.description ?? '';
    this.explicitStorageInstructions = input.explicitStorageInstructions ?? '';
    this.notes = input.notes ?? '';
    this.belongsToRecipe = input.belongsToRecipe ?? '';
    this.recipeSteps = input.recipeSteps ?? [];
    this.optional = input.optional ?? false;
  }
}

export interface IRecipePrepTaskUpdateRequestInput {
  notes?: string;
  explicitStorageInstructions?: string;
  storageType?: string;
  name?: string;
  optional?: boolean;
  description?: string;
  storageTemperatureInCelsius: NonNullable<NumberRange>;
  timeBufferBeforeRecipeInSeconds: NonNullable<OptionalNumberRange>;
  belongsToRecipe?: string;
  recipeSteps: NonNullable<Array<RecipePrepTaskStepUpdateRequestInput>>;
}

export class RecipePrepTaskUpdateRequestInput implements IRecipePrepTaskUpdateRequestInput {
  notes?: string;
  explicitStorageInstructions?: string;
  storageType?: string;
  name?: string;
  optional?: boolean = false;
  description?: string;
  storageTemperatureInCelsius: NonNullable<NumberRange> = { min: 0, max: 0 };
  timeBufferBeforeRecipeInSeconds: NonNullable<OptionalNumberRange> = {};
  belongsToRecipe?: string;
  recipeSteps: NonNullable<Array<RecipePrepTaskStepUpdateRequestInput>> = [];

  constructor(input: Partial<RecipePrepTaskUpdateRequestInput> = {}) {
    this.notes = input.notes;
    this.explicitStorageInstructions = input.explicitStorageInstructions;
    this.storageType = input.storageType;
    this.name = input.name;
    this.optional = input.optional ?? false;
    this.description = input.description;
    this.storageTemperatureInCelsius = input.storageTemperatureInCelsius ?? { min: 0, max: 0 };
    this.timeBufferBeforeRecipeInSeconds = input.timeBufferBeforeRecipeInSeconds ?? {};
    this.belongsToRecipe = input.belongsToRecipe;
    this.recipeSteps = input.recipeSteps ?? [];
  }
}
