// Code generated by gen_typescript. DO NOT EDIT.

export interface IRecipePrepTaskStep {
  id: NonNullable<string>;
  belongsToRecipeStep: NonNullable<string>;
  belongsToRecipeStepTask: NonNullable<string>;
  satisfiesRecipeStep: NonNullable<boolean>;
}

export class RecipePrepTaskStep implements IRecipePrepTaskStep {
  id: NonNullable<string> = '';
  belongsToRecipeStep: NonNullable<string> = '';
  belongsToRecipeStepTask: NonNullable<string> = '';
  satisfiesRecipeStep: NonNullable<boolean> = false;

  constructor(input: Partial<RecipePrepTaskStep> = {}) {
    this.id = input.id ?? '';
    this.belongsToRecipeStep = input.belongsToRecipeStep ?? '';
    this.belongsToRecipeStepTask = input.belongsToRecipeStepTask ?? '';
    this.satisfiesRecipeStep = input.satisfiesRecipeStep ?? false;
  }
}

export interface IRecipePrepTaskStepWithinRecipeCreationRequestInput {
  belongsToRecipeStepIndex: NonNullable<number>;
  satisfiesRecipeStep: NonNullable<boolean>;
}

export class RecipePrepTaskStepWithinRecipeCreationRequestInput
  implements IRecipePrepTaskStepWithinRecipeCreationRequestInput
{
  belongsToRecipeStepIndex: NonNullable<number> = 0;
  satisfiesRecipeStep: NonNullable<boolean> = false;

  constructor(input: Partial<RecipePrepTaskStepWithinRecipeCreationRequestInput> = {}) {
    this.belongsToRecipeStepIndex = input.belongsToRecipeStepIndex ?? 0;
    this.satisfiesRecipeStep = input.satisfiesRecipeStep ?? false;
  }
}

export interface IRecipePrepTaskStepCreationRequestInput {
  belongsToRecipeStep: NonNullable<string>;
  satisfiesRecipeStep: NonNullable<boolean>;
}

export class RecipePrepTaskStepCreationRequestInput implements IRecipePrepTaskStepCreationRequestInput {
  belongsToRecipeStep: NonNullable<string> = '';
  satisfiesRecipeStep: NonNullable<boolean> = false;

  constructor(input: Partial<RecipePrepTaskStepCreationRequestInput> = {}) {
    this.belongsToRecipeStep = input.belongsToRecipeStep ?? '';
    this.satisfiesRecipeStep = input.satisfiesRecipeStep ?? false;
  }
}

export interface IRecipePrepTaskStepUpdateRequestInput {
  satisfiesRecipeStep?: boolean;
  belongsToRecipeStep?: string;
  belongsToRecipeStepTask?: string;
}

export class RecipePrepTaskStepUpdateRequestInput implements IRecipePrepTaskStepUpdateRequestInput {
  satisfiesRecipeStep?: boolean = false;
  belongsToRecipeStep?: string;
  belongsToRecipeStepTask?: string;

  constructor(input: Partial<RecipePrepTaskStepUpdateRequestInput> = {}) {
    this.satisfiesRecipeStep = input.satisfiesRecipeStep ?? false;
    this.belongsToRecipeStep = input.belongsToRecipeStep;
    this.belongsToRecipeStepTask = input.belongsToRecipeStepTask;
  }
}
