// Code generated by gen_typescript. DO NOT EDIT.

import { ServiceSetting } from './serviceSetting';

export interface IServiceSettingConfiguration {
  createdAt: NonNullable<string>;
  lastUpdatedAt?: string;
  archivedAt?: string;
  id: NonNullable<string>;
  value: NonNullable<string>;
  notes: NonNullable<string>;
  belongsToUser: NonNullable<string>;
  belongsToHousehold: NonNullable<string>;
  serviceSetting: NonNullable<ServiceSetting>;
}

export class ServiceSettingConfiguration implements IServiceSettingConfiguration {
  createdAt: NonNullable<string> = '1970-01-01T00:00:00Z';
  lastUpdatedAt?: string;
  archivedAt?: string;
  id: NonNullable<string> = '';
  value: NonNullable<string> = '';
  notes: NonNullable<string> = '';
  belongsToUser: NonNullable<string> = '';
  belongsToHousehold: NonNullable<string> = '';
  serviceSetting: NonNullable<ServiceSetting> = new ServiceSetting();

  constructor(input: Partial<ServiceSettingConfiguration> = {}) {
    this.createdAt = input.createdAt ?? '1970-01-01T00:00:00Z';
    this.lastUpdatedAt = input.lastUpdatedAt;
    this.archivedAt = input.archivedAt;
    this.id = input.id ?? '';
    this.value = input.value ?? '';
    this.notes = input.notes ?? '';
    this.belongsToUser = input.belongsToUser ?? '';
    this.belongsToHousehold = input.belongsToHousehold ?? '';
    this.serviceSetting = input.serviceSetting ?? new ServiceSetting();
  }
}

export interface IServiceSettingConfigurationCreationRequestInput {
  value: NonNullable<string>;
  notes: NonNullable<string>;
  serviceSettingID: NonNullable<string>;
  belongsToUser: NonNullable<string>;
  belongsToHousehold: NonNullable<string>;
}

export class ServiceSettingConfigurationCreationRequestInput
  implements IServiceSettingConfigurationCreationRequestInput
{
  value: NonNullable<string> = '';
  notes: NonNullable<string> = '';
  serviceSettingID: NonNullable<string> = '';
  belongsToUser: NonNullable<string> = '';
  belongsToHousehold: NonNullable<string> = '';

  constructor(input: Partial<ServiceSettingConfigurationCreationRequestInput> = {}) {
    this.value = input.value ?? '';
    this.notes = input.notes ?? '';
    this.serviceSettingID = input.serviceSettingID ?? '';
    this.belongsToUser = input.belongsToUser ?? '';
    this.belongsToHousehold = input.belongsToHousehold ?? '';
  }
}

export interface IServiceSettingConfigurationUpdateRequestInput {
  value?: string;
  notes?: string;
  serviceSettingID?: string;
  belongsToUser?: string;
  belongsToHousehold?: string;
}

export class ServiceSettingConfigurationUpdateRequestInput implements IServiceSettingConfigurationUpdateRequestInput {
  value?: string;
  notes?: string;
  serviceSettingID?: string;
  belongsToUser?: string;
  belongsToHousehold?: string;

  constructor(input: Partial<ServiceSettingConfigurationUpdateRequestInput> = {}) {
    this.value = input.value;
    this.notes = input.notes;
    this.serviceSettingID = input.serviceSettingID;
    this.belongsToUser = input.belongsToUser;
    this.belongsToHousehold = input.belongsToHousehold;
  }
}
