// Code generated by gen_typescript. DO NOT EDIT.

import { ValidIngredientStateAttributeType } from './_unions';

export interface IValidIngredientState {
  createdAt: NonNullable<string>;
  archivedAt?: string;
  lastUpdatedAt?: string;
  pastTense: NonNullable<string>;
  description: NonNullable<string>;
  iconPath: NonNullable<string>;
  id: NonNullable<string>;
  name: NonNullable<string>;
  attributeType: NonNullable<ValidIngredientStateAttributeType>;
  slug: NonNullable<string>;
}

export class ValidIngredientState implements IValidIngredientState {
  createdAt: NonNullable<string> = '1970-01-01T00:00:00Z';
  archivedAt?: string;
  lastUpdatedAt?: string;
  pastTense: NonNullable<string> = '';
  description: NonNullable<string> = '';
  iconPath: NonNullable<string> = '';
  id: NonNullable<string> = '';
  name: NonNullable<string> = '';
  attributeType: NonNullable<ValidIngredientStateAttributeType> = 'other';
  slug: NonNullable<string> = '';

  constructor(input: Partial<ValidIngredientState> = {}) {
    this.createdAt = input.createdAt ?? '1970-01-01T00:00:00Z';
    this.archivedAt = input.archivedAt;
    this.lastUpdatedAt = input.lastUpdatedAt;
    this.pastTense = input.pastTense ?? '';
    this.description = input.description ?? '';
    this.iconPath = input.iconPath ?? '';
    this.id = input.id ?? '';
    this.name = input.name ?? '';
    this.attributeType = input.attributeType ?? 'other';
    this.slug = input.slug ?? '';
  }
}

export interface IValidIngredientStateCreationRequestInput {
  name: NonNullable<string>;
  slug: NonNullable<string>;
  pastTense: NonNullable<string>;
  description: NonNullable<string>;
  attributeType: NonNullable<ValidIngredientStateAttributeType>;
  iconPath: NonNullable<string>;
}

export class ValidIngredientStateCreationRequestInput implements IValidIngredientStateCreationRequestInput {
  name: NonNullable<string> = '';
  slug: NonNullable<string> = '';
  pastTense: NonNullable<string> = '';
  description: NonNullable<string> = '';
  attributeType: NonNullable<ValidIngredientStateAttributeType> = 'other';
  iconPath: NonNullable<string> = '';

  constructor(input: Partial<ValidIngredientStateCreationRequestInput> = {}) {
    this.name = input.name ?? '';
    this.slug = input.slug ?? '';
    this.pastTense = input.pastTense ?? '';
    this.description = input.description ?? '';
    this.attributeType = input.attributeType ?? 'other';
    this.iconPath = input.iconPath ?? '';
  }
}

export interface IValidIngredientStateUpdateRequestInput {
  name?: string;
  slug?: string;
  pastTense?: string;
  description?: string;
  attributeType?: ValidIngredientStateAttributeType;
  iconPath?: string;
}

export class ValidIngredientStateUpdateRequestInput implements IValidIngredientStateUpdateRequestInput {
  name?: string;
  slug?: string;
  pastTense?: string;
  description?: string;
  attributeType?: ValidIngredientStateAttributeType = 'other';
  iconPath?: string;

  constructor(input: Partial<ValidIngredientStateUpdateRequestInput> = {}) {
    this.name = input.name;
    this.slug = input.slug;
    this.pastTense = input.pastTense;
    this.description = input.description;
    this.attributeType = input.attributeType ?? 'other';
    this.iconPath = input.iconPath;
  }
}
