// GENERATED CODE, DO NOT EDIT MANUALLY

import { NumberRange } from './number_range';

export interface IValidIngredient {
  slug: string;
  isAcid: boolean;
  isHeat: boolean;
  isLiquid: boolean;
  isSalt: boolean;
  shoppingSuggestions: string;
  containsTreeNut: boolean;
  containsEgg: boolean;
  containsShellfish: boolean;
  id: string;
  name: string;
  restrictToPreparations: boolean;
  isFat: boolean;
  storageTemperatureInCelsius: NumberRange;
  archivedAt: string;
  containsPeanut: boolean;
  containsSesame: boolean;
  createdAt: string;
  iconPath: string;
  animalDerived: boolean;
  containsGluten: boolean;
  containsWheat: boolean;
  isStarch: boolean;
  pluralName: string;
  animalFlesh: boolean;
  containsAlcohol: boolean;
  containsSoy: boolean;
  isFruit: boolean;
  storageInstructions: string;
  containsDairy: boolean;
  description: string;
  isGrain: boolean;
  isProtein: boolean;
  warning: string;
  containsFish: boolean;
  lastUpdatedAt: string;
}

export class ValidIngredient implements IValidIngredient {
  slug: string;
  isAcid: boolean;
  isHeat: boolean;
  isLiquid: boolean;
  isSalt: boolean;
  shoppingSuggestions: string;
  containsTreeNut: boolean;
  containsEgg: boolean;
  containsShellfish: boolean;
  id: string;
  name: string;
  restrictToPreparations: boolean;
  isFat: boolean;
  storageTemperatureInCelsius: NumberRange;
  archivedAt: string;
  containsPeanut: boolean;
  containsSesame: boolean;
  createdAt: string;
  iconPath: string;
  animalDerived: boolean;
  containsGluten: boolean;
  containsWheat: boolean;
  isStarch: boolean;
  pluralName: string;
  animalFlesh: boolean;
  containsAlcohol: boolean;
  containsSoy: boolean;
  isFruit: boolean;
  storageInstructions: string;
  containsDairy: boolean;
  description: string;
  isGrain: boolean;
  isProtein: boolean;
  warning: string;
  containsFish: boolean;
  lastUpdatedAt: string;
  constructor(input: Partial<ValidIngredient> = {}) {
    this.slug = input.slug || '';
    this.isAcid = input.isAcid || false;
    this.isHeat = input.isHeat || false;
    this.isLiquid = input.isLiquid || false;
    this.isSalt = input.isSalt || false;
    this.shoppingSuggestions = input.shoppingSuggestions || '';
    this.containsTreeNut = input.containsTreeNut || false;
    this.containsEgg = input.containsEgg || false;
    this.containsShellfish = input.containsShellfish || false;
    this.id = input.id || '';
    this.name = input.name || '';
    this.restrictToPreparations = input.restrictToPreparations || false;
    this.isFat = input.isFat || false;
    this.storageTemperatureInCelsius = input.storageTemperatureInCelsius || { min: 0, max: 0 };
    this.archivedAt = input.archivedAt || '';
    this.containsPeanut = input.containsPeanut || false;
    this.containsSesame = input.containsSesame || false;
    this.createdAt = input.createdAt || '';
    this.iconPath = input.iconPath || '';
    this.animalDerived = input.animalDerived || false;
    this.containsGluten = input.containsGluten || false;
    this.containsWheat = input.containsWheat || false;
    this.isStarch = input.isStarch || false;
    this.pluralName = input.pluralName || '';
    this.animalFlesh = input.animalFlesh || false;
    this.containsAlcohol = input.containsAlcohol || false;
    this.containsSoy = input.containsSoy || false;
    this.isFruit = input.isFruit || false;
    this.storageInstructions = input.storageInstructions || '';
    this.containsDairy = input.containsDairy || false;
    this.description = input.description || '';
    this.isGrain = input.isGrain || false;
    this.isProtein = input.isProtein || false;
    this.warning = input.warning || '';
    this.containsFish = input.containsFish || false;
    this.lastUpdatedAt = input.lastUpdatedAt || '';
  }
}
