// Code generated by gen_typescript. DO NOT EDIT.

import { ValidPreparation } from './validPreparations';
import { ValidVessel } from './validVessels';

export interface IValidPreparationVessel {
  createdAt: NonNullable<string>;
  lastUpdatedAt?: string;
  archivedAt?: string;
  id: NonNullable<string>;
  notes: NonNullable<string>;
  preparation: NonNullable<ValidPreparation>;
  instrument: NonNullable<ValidVessel>;
}

export class ValidPreparationVessel implements IValidPreparationVessel {
  createdAt: NonNullable<string> = '1970-01-01T00:00:00Z';
  lastUpdatedAt?: string;
  archivedAt?: string;
  id: NonNullable<string> = '';
  notes: NonNullable<string> = '';
  preparation: NonNullable<ValidPreparation> = new ValidPreparation();
  instrument: NonNullable<ValidVessel> = new ValidVessel();

  constructor(input: Partial<ValidPreparationVessel> = {}) {
    this.createdAt = input.createdAt ?? '1970-01-01T00:00:00Z';
    this.lastUpdatedAt = input.lastUpdatedAt;
    this.archivedAt = input.archivedAt;
    this.id = input.id ?? '';
    this.notes = input.notes ?? '';
    this.preparation = input.preparation ?? new ValidPreparation();
    this.instrument = input.instrument ?? new ValidVessel();
  }
}

export interface IValidPreparationVesselCreationRequestInput {
  notes: NonNullable<string>;
  validPreparationID: NonNullable<string>;
  validVesselID: NonNullable<string>;
}

export class ValidPreparationVesselCreationRequestInput implements IValidPreparationVesselCreationRequestInput {
  notes: NonNullable<string> = '';
  validPreparationID: NonNullable<string> = '';
  validVesselID: NonNullable<string> = '';

  constructor(input: Partial<ValidPreparationVesselCreationRequestInput> = {}) {
    this.notes = input.notes ?? '';
    this.validPreparationID = input.validPreparationID ?? '';
    this.validVesselID = input.validVesselID ?? '';
  }
}

export interface IValidPreparationVesselUpdateRequestInput {
  notes?: string;
  validPreparationID?: string;
  validVesselID?: string;
}

export class ValidPreparationVesselUpdateRequestInput implements IValidPreparationVesselUpdateRequestInput {
  notes?: string;
  validPreparationID?: string;
  validVesselID?: string;

  constructor(input: Partial<ValidPreparationVesselUpdateRequestInput> = {}) {
    this.notes = input.notes;
    this.validPreparationID = input.validPreparationID;
    this.validVesselID = input.validVesselID;
  }
}
