// Code generated by gen_typescript. DO NOT EDIT.

export interface IWebhook {
  createdAt: NonNullable<string>;
  archivedAt?: string;
  lastUpdatedAt?: string;
  name: NonNullable<string>;
  url: NonNullable<string>;
  method: NonNullable<string>;
  id: NonNullable<string>;
  belongsToHousehold: NonNullable<string>;
  contentType: NonNullable<string>;
  events: NonNullable<Array<WebhookTriggerEvent>>;
}

export class Webhook implements IWebhook {
  createdAt: NonNullable<string> = '1970-01-01T00:00:00Z';
  archivedAt?: string;
  lastUpdatedAt?: string;
  name: NonNullable<string> = '';
  url: NonNullable<string> = '';
  method: NonNullable<string> = '';
  id: NonNullable<string> = '';
  belongsToHousehold: NonNullable<string> = '';
  contentType: NonNullable<string> = '';
  events: NonNullable<Array<WebhookTriggerEvent>> = [];

  constructor(input: Partial<Webhook> = {}) {
    this.createdAt = input.createdAt ?? '1970-01-01T00:00:00Z';
    this.archivedAt = input.archivedAt;
    this.lastUpdatedAt = input.lastUpdatedAt;
    this.name = input.name ?? '';
    this.url = input.url ?? '';
    this.method = input.method ?? '';
    this.id = input.id ?? '';
    this.belongsToHousehold = input.belongsToHousehold ?? '';
    this.contentType = input.contentType ?? '';
    this.events = input.events ?? [];
  }
}

export interface IWebhookTriggerEvent {
  createdAt: NonNullable<string>;
  archivedAt?: string;
  id: NonNullable<string>;
  belongsToWebhook: NonNullable<string>;
  triggerEvent: NonNullable<string>;
}

export class WebhookTriggerEvent implements IWebhookTriggerEvent {
  createdAt: NonNullable<string> = '1970-01-01T00:00:00Z';
  archivedAt?: string;
  id: NonNullable<string> = '';
  belongsToWebhook: NonNullable<string> = '';
  triggerEvent: NonNullable<string> = '';

  constructor(input: Partial<WebhookTriggerEvent> = {}) {
    this.createdAt = input.createdAt ?? '1970-01-01T00:00:00Z';
    this.archivedAt = input.archivedAt;
    this.id = input.id ?? '';
    this.belongsToWebhook = input.belongsToWebhook ?? '';
    this.triggerEvent = input.triggerEvent ?? '';
  }
}

export interface IWebhookCreationRequestInput {
  name: NonNullable<string>;
  contentType: NonNullable<string>;
  url: NonNullable<string>;
  method: NonNullable<string>;
  events: NonNullable<Array<string>>;
}

export class WebhookCreationRequestInput implements IWebhookCreationRequestInput {
  name: NonNullable<string> = '';
  contentType: NonNullable<string> = '';
  url: NonNullable<string> = '';
  method: NonNullable<string> = '';
  events: NonNullable<Array<string>> = [];

  constructor(input: Partial<WebhookCreationRequestInput> = {}) {
    this.name = input.name ?? '';
    this.contentType = input.contentType ?? '';
    this.url = input.url ?? '';
    this.method = input.method ?? '';
    this.events = input.events ?? [];
  }
}
