package recipes

type Repository interface {
	RecipeDataManager
	RecipeManagementDataManager
	RecipeMediaDataManager
	RecipePrepTaskDataManager
	RecipeRatingDataManager
	RecipeStepDataManager
	RecipeStepCompletionConditionDataManager
	RecipeStepIngredientDataManager
	RecipeStepVesselDataManager
	RecipeStepProductDataManager
	RecipeStepInstrumentDataManager
	UserIngredientPreferenceDataManager
	AccountInstrumentOwnershipDataManager
}
