---
apiVersion: v1
kind: ConfigMap
metadata:
  name: caddy-config
  namespace: prod
data:
  Caddyfile: |
    {
        acme_ca https://acme-v02.api.letsencrypt.org/directory
        acme_dns cloudflare {env.CLOUDFLARE_API_TOKEN}
    }

    api.dinnerdonebetter.com {
        reverse_proxy dinner-done-better-api-svc.prod.svc.cluster.local:8001 {
            flush_interval -1
            transport http {
                versions h2c 2
            }
        }
    }

    http-api.dinnerdonebetter.com {
        reverse_proxy dinner-done-better-api-svc.prod.svc.cluster.local:8000
    }

    admin.dinnerdonebetter.com {
        reverse_proxy dinner-done-better-admin-webapp-svc.prod.svc.cluster.local:8888
    }

    dinnerdonebetter.com, www.dinnerdonebetter.com {
        reverse_proxy dinner-done-better-consumer-webapp-svc.prod.svc.cluster.local:80
    }
