---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
  - ../../../kustomize/components/consumer_webapp
  - ../../../kustomize/components/admin_webapp

images:
  - name: dinner-done-better-consumer-webapp
    newName: us-central1-docker.pkg.dev/dinner-done-better-prod/containers/dinner-done-better-consumer-webapp
    newTag: latest

  - name: dinner-done-better-admin-webapp
    newName: us-central1-docker.pkg.dev/dinner-done-better-prod/containers/dinner-done-better-admin-webapp
    newTag: latest

patches:
  ### Consumer Webapp - env vars from Terraform secrets
  - patch: |-
      - op: add
        path: "/spec/template/spec/containers/0/env/-"
        value:
          name: GRPC_API_SERVER_URL
          value: "api.dinnerdonebetter.com:443"
      - op: add
        path: "/spec/template/spec/containers/0/env/-"
        value:
          name: HTTP_API_SERVER_URL
          value: "https://http-api.dinnerdonebetter.com"
      - op: add
        path: "/spec/template/spec/containers/0/env/-"
        value:
          name: OAUTH2_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: dinner-done-better-consumer-webapp-secrets
              key: OAUTH2_CLIENT_ID
      - op: add
        path: "/spec/template/spec/containers/0/env/-"
        value:
          name: OAUTH2_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: dinner-done-better-consumer-webapp-secrets
              key: OAUTH2_CLIENT_SECRET
      - op: add
        path: "/spec/template/spec/containers/0/env/-"
        value:
          name: COOKIE_NAME
          valueFrom:
            secretKeyRef:
              name: dinner-done-better-consumer-webapp-secrets
              key: COOKIE_NAME
      - op: add
        path: "/spec/template/spec/containers/0/env/-"
        value:
          name: COOKIE_DOMAIN
          valueFrom:
            secretKeyRef:
              name: dinner-done-better-consumer-webapp-secrets
              key: COOKIE_DOMAIN
      - op: add
        path: "/spec/template/spec/containers/0/env/-"
        value:
          name: COOKIE_ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: dinner-done-better-consumer-webapp-secrets
              key: COOKIE_ENCRYPTION_KEY
      - op: add
        path: "/spec/template/spec/containers/0/env/-"
        value:
          name: AASA_TEAM_ID
          value: "K8R2Q5UWQS"
      - op: add
        path: "/spec/template/spec/containers/0/env/-"
        value:
          name: AASA_BUNDLE_ID
          value: "com.dinnerdonebetter.ios"
      - op: add
        path: "/spec/template/spec/containers/0/env/-"
        value:
          name: PUBLIC_AVATAR_MEDIA_URL_PREFIX
          value: "https://media.dinnerdonebetter.com/avatars"
    target:
      version: v1
      kind: Deployment
      name: dinner-done-better-consumer-webapp-deployment

  ### Admin Webapp - env vars from Terraform secrets
  - patch: |-
      - op: add
        path: "/spec/template/spec/containers/0/env/-"
        value:
          name: GRPC_API_SERVER_URL
          value: "api.dinnerdonebetter.com:443"
      - op: add
        path: "/spec/template/spec/containers/0/env/-"
        value:
          name: HTTP_API_SERVER_URL
          value: "https://http-api.dinnerdonebetter.com"
      - op: add
        path: "/spec/template/spec/containers/0/env/-"
        value:
          name: OAUTH2_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: dinner-done-better-admin-webapp-config
              key: OAUTH2_CLIENT_ID
      - op: add
        path: "/spec/template/spec/containers/0/env/-"
        value:
          name: OAUTH2_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: dinner-done-better-admin-webapp-config
              key: OAUTH2_CLIENT_SECRET
      - op: add
        path: "/spec/template/spec/containers/0/env/-"
        value:
          name: COOKIE_NAME
          valueFrom:
            secretKeyRef:
              name: dinner-done-better-admin-webapp-config
              key: COOKIE_NAME
      - op: add
        path: "/spec/template/spec/containers/0/env/-"
        value:
          name: COOKIE_DOMAIN
          valueFrom:
            secretKeyRef:
              name: dinner-done-better-admin-webapp-config
              key: COOKIE_DOMAIN
      - op: add
        path: "/spec/template/spec/containers/0/env/-"
        value:
          name: COOKIE_ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: dinner-done-better-admin-webapp-config
              key: COOKIE_ENCRYPTION_KEY
    target:
      version: v1
      kind: Deployment
      name: dinner-done-better-admin-webapp-deployment

labels:
  - pairs:
      app.kubernetes.io/name: dinner-done-better-frontend
      deployed_by: skaffold
