package grpc

import (
	"database/sql"
	"errors"
	"testing"

	"github.com/dinnerdonebetter/backend/internal/domain/notifications"
	notificationsfakes "github.com/dinnerdonebetter/backend/internal/domain/notifications/fakes"
	grpcfiltering "github.com/dinnerdonebetter/backend/internal/grpc/generated/filtering"
	notificationssvc "github.com/dinnerdonebetter/backend/internal/grpc/generated/services/notifications"
	"github.com/dinnerdonebetter/backend/internal/platform/database/filtering"
	"github.com/dinnerdonebetter/backend/internal/platform/reflection"
	"github.com/dinnerdonebetter/backend/internal/platform/testutils"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/mock"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

func TestServiceImpl_RegisterDeviceToken(t *testing.T) {
	t.Parallel()

	t.Run("success", func(t *testing.T) {
		t.Parallel()

		ctx := t.Context()
		service, mockRepo := buildTestService(t)

		fakeToken := notificationsfakes.BuildFakeUserDeviceToken()

		mockRepo.On(reflection.GetMethodName(mockRepo.CreateUserDeviceToken), testutils.ContextMatcher, testutils.MatchType[*notifications.UserDeviceTokenDatabaseCreationInput]()).Return(fakeToken, nil)

		request := &notificationssvc.RegisterDeviceTokenRequest{
			Input: &notificationssvc.UserDeviceTokenCreationRequestInput{
				DeviceToken: fakeToken.DeviceToken,
				Platform:    fakeToken.Platform,
			},
		}

		response, err := service.RegisterDeviceToken(ctx, request)

		assert.NoError(t, err)
		assert.NotNil(t, response)
		assert.NotNil(t, response.ResponseDetails)
		assert.NotNil(t, response.Created)
		assert.Equal(t, fakeToken.DeviceToken, response.Created.DeviceToken)
		assert.Equal(t, fakeToken.Platform, response.Created.Platform)
		// ID is generated by handler, so we just check it's set
		assert.NotEmpty(t, response.Created.Id)

		mock.AssertExpectationsForObjects(t, mockRepo)
	})

	t.Run("session context error", func(t *testing.T) {
		t.Parallel()

		ctx := t.Context()
		service := buildTestServiceWithSessionError(t)

		request := &notificationssvc.RegisterDeviceTokenRequest{
			Input: &notificationssvc.UserDeviceTokenCreationRequestInput{
				DeviceToken: "token",
				Platform:    notifications.UserDeviceTokenPlatformIOS,
			},
		}

		response, err := service.RegisterDeviceToken(ctx, request)

		assert.Error(t, err)
		assert.Nil(t, response)
		assert.Equal(t, codes.Unauthenticated, status.Code(err))
	})

	t.Run("nil input", func(t *testing.T) {
		t.Parallel()

		ctx := t.Context()
		service, _ := buildTestService(t)

		request := &notificationssvc.RegisterDeviceTokenRequest{}

		response, err := service.RegisterDeviceToken(ctx, request)

		assert.Error(t, err)
		assert.Nil(t, response)
		assert.Equal(t, codes.InvalidArgument, status.Code(err))
	})

	t.Run("repository error", func(t *testing.T) {
		t.Parallel()

		ctx := t.Context()
		service, mockRepo := buildTestService(t)

		mockRepo.On(reflection.GetMethodName(mockRepo.CreateUserDeviceToken), testutils.ContextMatcher, testutils.MatchType[*notifications.UserDeviceTokenDatabaseCreationInput]()).Return((*notifications.UserDeviceToken)(nil), errors.New("repository error"))

		request := &notificationssvc.RegisterDeviceTokenRequest{
			Input: &notificationssvc.UserDeviceTokenCreationRequestInput{
				DeviceToken: "token",
				Platform:    notifications.UserDeviceTokenPlatformIOS,
			},
		}

		response, err := service.RegisterDeviceToken(ctx, request)

		assert.Error(t, err)
		assert.Nil(t, response)
		assert.Equal(t, codes.Internal, status.Code(err))

		mock.AssertExpectationsForObjects(t, mockRepo)
	})
}

func TestServiceImpl_GetUserDeviceToken(t *testing.T) {
	t.Parallel()

	t.Run("success", func(t *testing.T) {
		t.Parallel()

		ctx := t.Context()
		service, mockRepo := buildTestService(t)

		fakeToken := notificationsfakes.BuildFakeUserDeviceToken()
		tokenID := fakeToken.ID
		userID := "test-user-id"

		mockRepo.On(reflection.GetMethodName(mockRepo.GetUserDeviceToken), testutils.ContextMatcher, userID, tokenID).Return(fakeToken, nil)

		request := &notificationssvc.GetUserDeviceTokenRequest{
			UserDeviceTokenId: tokenID,
		}

		response, err := service.GetUserDeviceToken(ctx, request)

		assert.NoError(t, err)
		assert.NotNil(t, response)
		assert.NotNil(t, response.ResponseDetails)
		assert.NotNil(t, response.Result)
		assert.Equal(t, fakeToken.ID, response.Result.Id)
		assert.Equal(t, fakeToken.DeviceToken, response.Result.DeviceToken)

		mock.AssertExpectationsForObjects(t, mockRepo)
	})

	t.Run("session context error", func(t *testing.T) {
		t.Parallel()

		ctx := t.Context()
		service := buildTestServiceWithSessionError(t)

		request := &notificationssvc.GetUserDeviceTokenRequest{
			UserDeviceTokenId: "test-token-id",
		}

		response, err := service.GetUserDeviceToken(ctx, request)

		assert.Error(t, err)
		assert.Nil(t, response)
		assert.Equal(t, codes.Unauthenticated, status.Code(err))
	})

	t.Run("not found", func(t *testing.T) {
		t.Parallel()

		ctx := t.Context()
		service, mockRepo := buildTestService(t)

		tokenID := "nonexistent-token"
		userID := "test-user-id"

		mockRepo.On(reflection.GetMethodName(mockRepo.GetUserDeviceToken), testutils.ContextMatcher, userID, tokenID).Return((*notifications.UserDeviceToken)(nil), sql.ErrNoRows)

		request := &notificationssvc.GetUserDeviceTokenRequest{
			UserDeviceTokenId: tokenID,
		}

		response, err := service.GetUserDeviceToken(ctx, request)

		assert.Error(t, err)
		assert.Nil(t, response)
		assert.Equal(t, codes.NotFound, status.Code(err))

		mock.AssertExpectationsForObjects(t, mockRepo)
	})
}

func TestServiceImpl_GetUserDeviceTokens(t *testing.T) {
	t.Parallel()

	t.Run("success", func(t *testing.T) {
		t.Parallel()

		ctx := t.Context()
		service, mockRepo := buildTestService(t)

		fakeTokens := notificationsfakes.BuildFakeUserDeviceTokensList()
		userID := "test-user-id"
		pageSize := uint8(20)
		filter := &filtering.QueryFilter{
			MaxResponseSize: &pageSize,
		}

		mockRepo.On(reflection.GetMethodName(mockRepo.GetUserDeviceTokens), testutils.ContextMatcher, userID, testutils.QueryFilterMatcher, (*string)(nil)).Return(fakeTokens, nil)

		grpcPageSize := uint32(*filter.MaxResponseSize)
		request := &notificationssvc.GetUserDeviceTokensRequest{
			Filter: &grpcfiltering.QueryFilter{
				MaxResponseSize: &grpcPageSize,
			},
		}

		response, err := service.GetUserDeviceTokens(ctx, request)

		assert.NoError(t, err)
		assert.NotNil(t, response)
		assert.NotNil(t, response.ResponseDetails)
		assert.Len(t, response.Results, len(fakeTokens.Data))

		mock.AssertExpectationsForObjects(t, mockRepo)
	})

	t.Run("session context error", func(t *testing.T) {
		t.Parallel()

		ctx := t.Context()
		service := buildTestServiceWithSessionError(t)

		grpcPageSize := uint32(20)
		request := &notificationssvc.GetUserDeviceTokensRequest{
			Filter: &grpcfiltering.QueryFilter{
				MaxResponseSize: &grpcPageSize,
			},
		}

		response, err := service.GetUserDeviceTokens(ctx, request)

		assert.Error(t, err)
		assert.Nil(t, response)
		assert.Equal(t, codes.Unauthenticated, status.Code(err))
	})
}

func TestServiceImpl_ArchiveUserDeviceToken(t *testing.T) {
	t.Parallel()

	t.Run("success", func(t *testing.T) {
		t.Parallel()

		ctx := t.Context()
		service, mockRepo := buildTestService(t)

		tokenID := notificationsfakes.BuildFakeID()
		userID := "test-user-id"

		mockRepo.On(reflection.GetMethodName(mockRepo.ArchiveUserDeviceToken), testutils.ContextMatcher, userID, tokenID).Return(nil)

		request := &notificationssvc.ArchiveUserDeviceTokenRequest{
			UserDeviceTokenId: tokenID,
		}

		response, err := service.ArchiveUserDeviceToken(ctx, request)

		assert.NoError(t, err)
		assert.NotNil(t, response)
		assert.NotNil(t, response.ResponseDetails)

		mock.AssertExpectationsForObjects(t, mockRepo)
	})

	t.Run("session context error", func(t *testing.T) {
		t.Parallel()

		ctx := t.Context()
		service := buildTestServiceWithSessionError(t)

		request := &notificationssvc.ArchiveUserDeviceTokenRequest{
			UserDeviceTokenId: "test-token-id",
		}

		response, err := service.ArchiveUserDeviceToken(ctx, request)

		assert.Error(t, err)
		assert.Nil(t, response)
		assert.Equal(t, codes.Unauthenticated, status.Code(err))
	})

	t.Run("not found", func(t *testing.T) {
		t.Parallel()

		ctx := t.Context()
		service, mockRepo := buildTestService(t)

		tokenID := "nonexistent-token"
		userID := "test-user-id"

		mockRepo.On(reflection.GetMethodName(mockRepo.ArchiveUserDeviceToken), testutils.ContextMatcher, userID, tokenID).Return(sql.ErrNoRows)

		request := &notificationssvc.ArchiveUserDeviceTokenRequest{
			UserDeviceTokenId: tokenID,
		}

		response, err := service.ArchiveUserDeviceToken(ctx, request)

		assert.Error(t, err)
		assert.Nil(t, response)
		assert.Equal(t, codes.NotFound, status.Code(err))

		mock.AssertExpectationsForObjects(t, mockRepo)
	})
}
