// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v6.33.1
// source: uploaded_media/uploaded_media_service.proto

/* eslint-disable */
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type ClientWritableStream,
  type handleClientStreamingCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from '@grpc/grpc-js';
import { UploadRequest, UploadResponse } from './uploaded_media_messages';
import {
  ArchiveUploadedMediaRequest,
  ArchiveUploadedMediaResponse,
  CreateUploadedMediaRequest,
  CreateUploadedMediaResponse,
  GetUploadedMediaForUserRequest,
  GetUploadedMediaForUserResponse,
  GetUploadedMediaRequest,
  GetUploadedMediaResponse,
  GetUploadedMediaWithIDsRequest,
  GetUploadedMediaWithIDsResponse,
  UpdateUploadedMediaRequest,
  UpdateUploadedMediaResponse,
} from './uploaded_media_service_types';

export const protobufPackage = 'uploaded_media';

export type UploadedMediaServiceService = typeof UploadedMediaServiceService;
export const UploadedMediaServiceService = {
  upload: {
    path: '/uploaded_media.UploadedMediaService/Upload' as const,
    requestStream: true as const,
    responseStream: false as const,
    requestSerialize: (value: UploadRequest): Buffer => Buffer.from(UploadRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): UploadRequest => UploadRequest.decode(value),
    responseSerialize: (value: UploadResponse): Buffer => Buffer.from(UploadResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): UploadResponse => UploadResponse.decode(value),
  },
  createUploadedMedia: {
    path: '/uploaded_media.UploadedMediaService/CreateUploadedMedia' as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: CreateUploadedMediaRequest): Buffer =>
      Buffer.from(CreateUploadedMediaRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): CreateUploadedMediaRequest => CreateUploadedMediaRequest.decode(value),
    responseSerialize: (value: CreateUploadedMediaResponse): Buffer =>
      Buffer.from(CreateUploadedMediaResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): CreateUploadedMediaResponse => CreateUploadedMediaResponse.decode(value),
  },
  getUploadedMedia: {
    path: '/uploaded_media.UploadedMediaService/GetUploadedMedia' as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: GetUploadedMediaRequest): Buffer =>
      Buffer.from(GetUploadedMediaRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetUploadedMediaRequest => GetUploadedMediaRequest.decode(value),
    responseSerialize: (value: GetUploadedMediaResponse): Buffer =>
      Buffer.from(GetUploadedMediaResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): GetUploadedMediaResponse => GetUploadedMediaResponse.decode(value),
  },
  getUploadedMediaWithIDs: {
    path: '/uploaded_media.UploadedMediaService/GetUploadedMediaWithIDs' as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: GetUploadedMediaWithIDsRequest): Buffer =>
      Buffer.from(GetUploadedMediaWithIDsRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetUploadedMediaWithIDsRequest => GetUploadedMediaWithIDsRequest.decode(value),
    responseSerialize: (value: GetUploadedMediaWithIDsResponse): Buffer =>
      Buffer.from(GetUploadedMediaWithIDsResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): GetUploadedMediaWithIDsResponse =>
      GetUploadedMediaWithIDsResponse.decode(value),
  },
  getUploadedMediaForUser: {
    path: '/uploaded_media.UploadedMediaService/GetUploadedMediaForUser' as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: GetUploadedMediaForUserRequest): Buffer =>
      Buffer.from(GetUploadedMediaForUserRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetUploadedMediaForUserRequest => GetUploadedMediaForUserRequest.decode(value),
    responseSerialize: (value: GetUploadedMediaForUserResponse): Buffer =>
      Buffer.from(GetUploadedMediaForUserResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): GetUploadedMediaForUserResponse =>
      GetUploadedMediaForUserResponse.decode(value),
  },
  updateUploadedMedia: {
    path: '/uploaded_media.UploadedMediaService/UpdateUploadedMedia' as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: UpdateUploadedMediaRequest): Buffer =>
      Buffer.from(UpdateUploadedMediaRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): UpdateUploadedMediaRequest => UpdateUploadedMediaRequest.decode(value),
    responseSerialize: (value: UpdateUploadedMediaResponse): Buffer =>
      Buffer.from(UpdateUploadedMediaResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): UpdateUploadedMediaResponse => UpdateUploadedMediaResponse.decode(value),
  },
  archiveUploadedMedia: {
    path: '/uploaded_media.UploadedMediaService/ArchiveUploadedMedia' as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: ArchiveUploadedMediaRequest): Buffer =>
      Buffer.from(ArchiveUploadedMediaRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): ArchiveUploadedMediaRequest => ArchiveUploadedMediaRequest.decode(value),
    responseSerialize: (value: ArchiveUploadedMediaResponse): Buffer =>
      Buffer.from(ArchiveUploadedMediaResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): ArchiveUploadedMediaResponse => ArchiveUploadedMediaResponse.decode(value),
  },
} as const;

export interface UploadedMediaServiceServer extends UntypedServiceImplementation {
  upload: handleClientStreamingCall<UploadRequest, UploadResponse>;
  createUploadedMedia: handleUnaryCall<CreateUploadedMediaRequest, CreateUploadedMediaResponse>;
  getUploadedMedia: handleUnaryCall<GetUploadedMediaRequest, GetUploadedMediaResponse>;
  getUploadedMediaWithIDs: handleUnaryCall<GetUploadedMediaWithIDsRequest, GetUploadedMediaWithIDsResponse>;
  getUploadedMediaForUser: handleUnaryCall<GetUploadedMediaForUserRequest, GetUploadedMediaForUserResponse>;
  updateUploadedMedia: handleUnaryCall<UpdateUploadedMediaRequest, UpdateUploadedMediaResponse>;
  archiveUploadedMedia: handleUnaryCall<ArchiveUploadedMediaRequest, ArchiveUploadedMediaResponse>;
}

export interface UploadedMediaServiceClient extends Client {
  upload(callback: (error: ServiceError | null, response: UploadResponse) => void): ClientWritableStream<UploadRequest>;
  upload(
    metadata: Metadata,
    callback: (error: ServiceError | null, response: UploadResponse) => void,
  ): ClientWritableStream<UploadRequest>;
  upload(
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: UploadResponse) => void,
  ): ClientWritableStream<UploadRequest>;
  upload(
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: UploadResponse) => void,
  ): ClientWritableStream<UploadRequest>;
  createUploadedMedia(
    request: CreateUploadedMediaRequest,
    callback: (error: ServiceError | null, response: CreateUploadedMediaResponse) => void,
  ): ClientUnaryCall;
  createUploadedMedia(
    request: CreateUploadedMediaRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: CreateUploadedMediaResponse) => void,
  ): ClientUnaryCall;
  createUploadedMedia(
    request: CreateUploadedMediaRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: CreateUploadedMediaResponse) => void,
  ): ClientUnaryCall;
  getUploadedMedia(
    request: GetUploadedMediaRequest,
    callback: (error: ServiceError | null, response: GetUploadedMediaResponse) => void,
  ): ClientUnaryCall;
  getUploadedMedia(
    request: GetUploadedMediaRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GetUploadedMediaResponse) => void,
  ): ClientUnaryCall;
  getUploadedMedia(
    request: GetUploadedMediaRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GetUploadedMediaResponse) => void,
  ): ClientUnaryCall;
  getUploadedMediaWithIDs(
    request: GetUploadedMediaWithIDsRequest,
    callback: (error: ServiceError | null, response: GetUploadedMediaWithIDsResponse) => void,
  ): ClientUnaryCall;
  getUploadedMediaWithIDs(
    request: GetUploadedMediaWithIDsRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GetUploadedMediaWithIDsResponse) => void,
  ): ClientUnaryCall;
  getUploadedMediaWithIDs(
    request: GetUploadedMediaWithIDsRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GetUploadedMediaWithIDsResponse) => void,
  ): ClientUnaryCall;
  getUploadedMediaForUser(
    request: GetUploadedMediaForUserRequest,
    callback: (error: ServiceError | null, response: GetUploadedMediaForUserResponse) => void,
  ): ClientUnaryCall;
  getUploadedMediaForUser(
    request: GetUploadedMediaForUserRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GetUploadedMediaForUserResponse) => void,
  ): ClientUnaryCall;
  getUploadedMediaForUser(
    request: GetUploadedMediaForUserRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GetUploadedMediaForUserResponse) => void,
  ): ClientUnaryCall;
  updateUploadedMedia(
    request: UpdateUploadedMediaRequest,
    callback: (error: ServiceError | null, response: UpdateUploadedMediaResponse) => void,
  ): ClientUnaryCall;
  updateUploadedMedia(
    request: UpdateUploadedMediaRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: UpdateUploadedMediaResponse) => void,
  ): ClientUnaryCall;
  updateUploadedMedia(
    request: UpdateUploadedMediaRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: UpdateUploadedMediaResponse) => void,
  ): ClientUnaryCall;
  archiveUploadedMedia(
    request: ArchiveUploadedMediaRequest,
    callback: (error: ServiceError | null, response: ArchiveUploadedMediaResponse) => void,
  ): ClientUnaryCall;
  archiveUploadedMedia(
    request: ArchiveUploadedMediaRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: ArchiveUploadedMediaResponse) => void,
  ): ClientUnaryCall;
  archiveUploadedMedia(
    request: ArchiveUploadedMediaRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: ArchiveUploadedMediaResponse) => void,
  ): ClientUnaryCall;
}

export const UploadedMediaServiceClient = makeGenericClientConstructor(
  UploadedMediaServiceService,
  'uploaded_media.UploadedMediaService',
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): UploadedMediaServiceClient;
  service: typeof UploadedMediaServiceService;
  serviceName: string;
};
