// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v6.33.1
// source: uploaded_media/uploaded_media.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from '@bufbuild/protobuf/wire';
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type ClientWritableStream,
  type handleClientStreamingCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from '@grpc/grpc-js';
import { ResponseDetails } from '../common';
import { Pagination, QueryFilter } from '../filtering';
import { Timestamp } from '../google/protobuf/timestamp';

export const protobufPackage = 'uploaded_media';

export enum UploadedMediaMimeType {
  UPLOADED_MEDIA_MIME_TYPE_UNSPECIFIED = 0,
  UPLOADED_MEDIA_MIME_TYPE_IMAGE_PNG = 1,
  UPLOADED_MEDIA_MIME_TYPE_IMAGE_JPEG = 2,
  UPLOADED_MEDIA_MIME_TYPE_IMAGE_GIF = 3,
  UPLOADED_MEDIA_MIME_TYPE_VIDEO_MP4 = 4,
  UNRECOGNIZED = -1,
}

export function uploadedMediaMimeTypeFromJSON(object: any): UploadedMediaMimeType {
  switch (object) {
    case 0:
    case 'UPLOADED_MEDIA_MIME_TYPE_UNSPECIFIED':
      return UploadedMediaMimeType.UPLOADED_MEDIA_MIME_TYPE_UNSPECIFIED;
    case 1:
    case 'UPLOADED_MEDIA_MIME_TYPE_IMAGE_PNG':
      return UploadedMediaMimeType.UPLOADED_MEDIA_MIME_TYPE_IMAGE_PNG;
    case 2:
    case 'UPLOADED_MEDIA_MIME_TYPE_IMAGE_JPEG':
      return UploadedMediaMimeType.UPLOADED_MEDIA_MIME_TYPE_IMAGE_JPEG;
    case 3:
    case 'UPLOADED_MEDIA_MIME_TYPE_IMAGE_GIF':
      return UploadedMediaMimeType.UPLOADED_MEDIA_MIME_TYPE_IMAGE_GIF;
    case 4:
    case 'UPLOADED_MEDIA_MIME_TYPE_VIDEO_MP4':
      return UploadedMediaMimeType.UPLOADED_MEDIA_MIME_TYPE_VIDEO_MP4;
    case -1:
    case 'UNRECOGNIZED':
    default:
      return UploadedMediaMimeType.UNRECOGNIZED;
  }
}

export function uploadedMediaMimeTypeToJSON(object: UploadedMediaMimeType): string {
  switch (object) {
    case UploadedMediaMimeType.UPLOADED_MEDIA_MIME_TYPE_UNSPECIFIED:
      return 'UPLOADED_MEDIA_MIME_TYPE_UNSPECIFIED';
    case UploadedMediaMimeType.UPLOADED_MEDIA_MIME_TYPE_IMAGE_PNG:
      return 'UPLOADED_MEDIA_MIME_TYPE_IMAGE_PNG';
    case UploadedMediaMimeType.UPLOADED_MEDIA_MIME_TYPE_IMAGE_JPEG:
      return 'UPLOADED_MEDIA_MIME_TYPE_IMAGE_JPEG';
    case UploadedMediaMimeType.UPLOADED_MEDIA_MIME_TYPE_IMAGE_GIF:
      return 'UPLOADED_MEDIA_MIME_TYPE_IMAGE_GIF';
    case UploadedMediaMimeType.UPLOADED_MEDIA_MIME_TYPE_VIDEO_MP4:
      return 'UPLOADED_MEDIA_MIME_TYPE_VIDEO_MP4';
    case UploadedMediaMimeType.UNRECOGNIZED:
    default:
      return 'UNRECOGNIZED';
  }
}

export interface DataCollection {
  uploadedMedia: { [key: string]: UploadedMedia };
}

export interface DataCollection_UploadedMediaEntry {
  key: string;
  value: UploadedMedia | undefined;
}

export interface UploadRequest {
  metadata?: UploadMetadata | undefined;
  chunk?: Uint8Array | undefined;
}

export interface UploadMetadata {
  bucket: string;
  objectName: string;
  contentType: string;
}

export interface UploadResponse {
  objectUrl: string;
  sizeBytes: number;
}

export interface UploadedMedia {
  createdAt: Date | undefined;
  archivedAt: Date | undefined;
  lastUpdatedAt: Date | undefined;
  id: string;
  storagePath: string;
  mimeType: UploadedMediaMimeType;
  createdByUser: string;
}

export interface UploadedMediaCreationRequestInput {
  storagePath: string;
  mimeType: UploadedMediaMimeType;
}

export interface UploadedMediaUpdateRequestInput {
  storagePath?: string | undefined;
  mimeType?: UploadedMediaMimeType | undefined;
}

/** CreateUploadedMedia */
export interface CreateUploadedMediaRequest {
  input: UploadedMediaCreationRequestInput | undefined;
}

export interface CreateUploadedMediaResponse {
  responseDetails: ResponseDetails | undefined;
  created: UploadedMedia | undefined;
}

/** GetUploadedMedia */
export interface GetUploadedMediaRequest {
  uploadedMediaId: string;
}

export interface GetUploadedMediaResponse {
  responseDetails: ResponseDetails | undefined;
  result: UploadedMedia | undefined;
}

/** GetUploadedMediaWithIDs */
export interface GetUploadedMediaWithIDsRequest {
  ids: string[];
}

export interface GetUploadedMediaWithIDsResponse {
  responseDetails: ResponseDetails | undefined;
  results: UploadedMedia[];
}

/** GetUploadedMediaForUser */
export interface GetUploadedMediaForUserRequest {
  userId: string;
  filter: QueryFilter | undefined;
}

export interface GetUploadedMediaForUserResponse {
  responseDetails: ResponseDetails | undefined;
  pagination: Pagination | undefined;
  results: UploadedMedia[];
}

/** UpdateUploadedMedia */
export interface UpdateUploadedMediaRequest {
  uploadedMediaId: string;
  input: UploadedMediaUpdateRequestInput | undefined;
}

export interface UpdateUploadedMediaResponse {
  responseDetails: ResponseDetails | undefined;
  updated: UploadedMedia | undefined;
}

/** ArchiveUploadedMedia */
export interface ArchiveUploadedMediaRequest {
  uploadedMediaId: string;
}

export interface ArchiveUploadedMediaResponse {
  responseDetails: ResponseDetails | undefined;
}

function createBaseDataCollection(): DataCollection {
  return { uploadedMedia: {} };
}

export const DataCollection: MessageFns<DataCollection> = {
  encode(message: DataCollection, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    globalThis.Object.entries(message.uploadedMedia).forEach(([key, value]: [string, UploadedMedia]) => {
      DataCollection_UploadedMediaEntry.encode({ key: key as any, value }, writer.uint32(10).fork()).join();
    });
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DataCollection {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDataCollection();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          const entry1 = DataCollection_UploadedMediaEntry.decode(reader, reader.uint32());
          if (entry1.value !== undefined) {
            message.uploadedMedia[entry1.key] = entry1.value;
          }
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DataCollection {
    return {
      uploadedMedia: isObject(object.uploadedMedia)
        ? (globalThis.Object.entries(object.uploadedMedia) as [string, any][]).reduce(
            (acc: { [key: string]: UploadedMedia }, [key, value]: [string, any]) => {
              acc[key] = UploadedMedia.fromJSON(value);
              return acc;
            },
            {},
          )
        : isObject(object.uploaded_media)
          ? (globalThis.Object.entries(object.uploaded_media) as [string, any][]).reduce(
              (acc: { [key: string]: UploadedMedia }, [key, value]: [string, any]) => {
                acc[key] = UploadedMedia.fromJSON(value);
                return acc;
              },
              {},
            )
          : {},
    };
  },

  toJSON(message: DataCollection): unknown {
    const obj: any = {};
    if (message.uploadedMedia) {
      const entries = globalThis.Object.entries(message.uploadedMedia) as [string, UploadedMedia][];
      if (entries.length > 0) {
        obj.uploadedMedia = {};
        entries.forEach(([k, v]) => {
          obj.uploadedMedia[k] = UploadedMedia.toJSON(v);
        });
      }
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DataCollection>, I>>(base?: I): DataCollection {
    return DataCollection.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DataCollection>, I>>(object: I): DataCollection {
    const message = createBaseDataCollection();
    message.uploadedMedia = (globalThis.Object.entries(object.uploadedMedia ?? {}) as [string, UploadedMedia][]).reduce(
      (acc: { [key: string]: UploadedMedia }, [key, value]: [string, UploadedMedia]) => {
        if (value !== undefined) {
          acc[key] = UploadedMedia.fromPartial(value);
        }
        return acc;
      },
      {},
    );
    return message;
  },
};

function createBaseDataCollection_UploadedMediaEntry(): DataCollection_UploadedMediaEntry {
  return { key: '', value: undefined };
}

export const DataCollection_UploadedMediaEntry: MessageFns<DataCollection_UploadedMediaEntry> = {
  encode(message: DataCollection_UploadedMediaEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== '') {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== undefined) {
      UploadedMedia.encode(message.value, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DataCollection_UploadedMediaEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDataCollection_UploadedMediaEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = UploadedMedia.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DataCollection_UploadedMediaEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : '',
      value: isSet(object.value) ? UploadedMedia.fromJSON(object.value) : undefined,
    };
  },

  toJSON(message: DataCollection_UploadedMediaEntry): unknown {
    const obj: any = {};
    if (message.key !== '') {
      obj.key = message.key;
    }
    if (message.value !== undefined) {
      obj.value = UploadedMedia.toJSON(message.value);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DataCollection_UploadedMediaEntry>, I>>(
    base?: I,
  ): DataCollection_UploadedMediaEntry {
    return DataCollection_UploadedMediaEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DataCollection_UploadedMediaEntry>, I>>(
    object: I,
  ): DataCollection_UploadedMediaEntry {
    const message = createBaseDataCollection_UploadedMediaEntry();
    message.key = object.key ?? '';
    message.value =
      object.value !== undefined && object.value !== null ? UploadedMedia.fromPartial(object.value) : undefined;
    return message;
  },
};

function createBaseUploadRequest(): UploadRequest {
  return { metadata: undefined, chunk: undefined };
}

export const UploadRequest: MessageFns<UploadRequest> = {
  encode(message: UploadRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.metadata !== undefined) {
      UploadMetadata.encode(message.metadata, writer.uint32(10).fork()).join();
    }
    if (message.chunk !== undefined) {
      writer.uint32(18).bytes(message.chunk);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UploadRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUploadRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.metadata = UploadMetadata.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.chunk = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UploadRequest {
    return {
      metadata: isSet(object.metadata) ? UploadMetadata.fromJSON(object.metadata) : undefined,
      chunk: isSet(object.chunk) ? bytesFromBase64(object.chunk) : undefined,
    };
  },

  toJSON(message: UploadRequest): unknown {
    const obj: any = {};
    if (message.metadata !== undefined) {
      obj.metadata = UploadMetadata.toJSON(message.metadata);
    }
    if (message.chunk !== undefined) {
      obj.chunk = base64FromBytes(message.chunk);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UploadRequest>, I>>(base?: I): UploadRequest {
    return UploadRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UploadRequest>, I>>(object: I): UploadRequest {
    const message = createBaseUploadRequest();
    message.metadata =
      object.metadata !== undefined && object.metadata !== null
        ? UploadMetadata.fromPartial(object.metadata)
        : undefined;
    message.chunk = object.chunk ?? undefined;
    return message;
  },
};

function createBaseUploadMetadata(): UploadMetadata {
  return { bucket: '', objectName: '', contentType: '' };
}

export const UploadMetadata: MessageFns<UploadMetadata> = {
  encode(message: UploadMetadata, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.bucket !== '') {
      writer.uint32(10).string(message.bucket);
    }
    if (message.objectName !== '') {
      writer.uint32(18).string(message.objectName);
    }
    if (message.contentType !== '') {
      writer.uint32(26).string(message.contentType);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UploadMetadata {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUploadMetadata();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.bucket = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.objectName = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.contentType = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UploadMetadata {
    return {
      bucket: isSet(object.bucket) ? globalThis.String(object.bucket) : '',
      objectName: isSet(object.objectName)
        ? globalThis.String(object.objectName)
        : isSet(object.object_name)
          ? globalThis.String(object.object_name)
          : '',
      contentType: isSet(object.contentType)
        ? globalThis.String(object.contentType)
        : isSet(object.content_type)
          ? globalThis.String(object.content_type)
          : '',
    };
  },

  toJSON(message: UploadMetadata): unknown {
    const obj: any = {};
    if (message.bucket !== '') {
      obj.bucket = message.bucket;
    }
    if (message.objectName !== '') {
      obj.objectName = message.objectName;
    }
    if (message.contentType !== '') {
      obj.contentType = message.contentType;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UploadMetadata>, I>>(base?: I): UploadMetadata {
    return UploadMetadata.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UploadMetadata>, I>>(object: I): UploadMetadata {
    const message = createBaseUploadMetadata();
    message.bucket = object.bucket ?? '';
    message.objectName = object.objectName ?? '';
    message.contentType = object.contentType ?? '';
    return message;
  },
};

function createBaseUploadResponse(): UploadResponse {
  return { objectUrl: '', sizeBytes: 0 };
}

export const UploadResponse: MessageFns<UploadResponse> = {
  encode(message: UploadResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.objectUrl !== '') {
      writer.uint32(10).string(message.objectUrl);
    }
    if (message.sizeBytes !== 0) {
      writer.uint32(16).int64(message.sizeBytes);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UploadResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUploadResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.objectUrl = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.sizeBytes = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UploadResponse {
    return {
      objectUrl: isSet(object.objectUrl)
        ? globalThis.String(object.objectUrl)
        : isSet(object.object_url)
          ? globalThis.String(object.object_url)
          : '',
      sizeBytes: isSet(object.sizeBytes)
        ? globalThis.Number(object.sizeBytes)
        : isSet(object.size_bytes)
          ? globalThis.Number(object.size_bytes)
          : 0,
    };
  },

  toJSON(message: UploadResponse): unknown {
    const obj: any = {};
    if (message.objectUrl !== '') {
      obj.objectUrl = message.objectUrl;
    }
    if (message.sizeBytes !== 0) {
      obj.sizeBytes = Math.round(message.sizeBytes);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UploadResponse>, I>>(base?: I): UploadResponse {
    return UploadResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UploadResponse>, I>>(object: I): UploadResponse {
    const message = createBaseUploadResponse();
    message.objectUrl = object.objectUrl ?? '';
    message.sizeBytes = object.sizeBytes ?? 0;
    return message;
  },
};

function createBaseUploadedMedia(): UploadedMedia {
  return {
    createdAt: undefined,
    archivedAt: undefined,
    lastUpdatedAt: undefined,
    id: '',
    storagePath: '',
    mimeType: 0,
    createdByUser: '',
  };
}

export const UploadedMedia: MessageFns<UploadedMedia> = {
  encode(message: UploadedMedia, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.createdAt !== undefined) {
      Timestamp.encode(toTimestamp(message.createdAt), writer.uint32(10).fork()).join();
    }
    if (message.archivedAt !== undefined) {
      Timestamp.encode(toTimestamp(message.archivedAt), writer.uint32(18).fork()).join();
    }
    if (message.lastUpdatedAt !== undefined) {
      Timestamp.encode(toTimestamp(message.lastUpdatedAt), writer.uint32(26).fork()).join();
    }
    if (message.id !== '') {
      writer.uint32(34).string(message.id);
    }
    if (message.storagePath !== '') {
      writer.uint32(42).string(message.storagePath);
    }
    if (message.mimeType !== 0) {
      writer.uint32(48).int32(message.mimeType);
    }
    if (message.createdByUser !== '') {
      writer.uint32(58).string(message.createdByUser);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UploadedMedia {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUploadedMedia();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.createdAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.archivedAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.lastUpdatedAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.storagePath = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.mimeType = reader.int32() as any;
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.createdByUser = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UploadedMedia {
    return {
      createdAt: isSet(object.createdAt)
        ? fromJsonTimestamp(object.createdAt)
        : isSet(object.created_at)
          ? fromJsonTimestamp(object.created_at)
          : undefined,
      archivedAt: isSet(object.archivedAt)
        ? fromJsonTimestamp(object.archivedAt)
        : isSet(object.archived_at)
          ? fromJsonTimestamp(object.archived_at)
          : undefined,
      lastUpdatedAt: isSet(object.lastUpdatedAt)
        ? fromJsonTimestamp(object.lastUpdatedAt)
        : isSet(object.last_updated_at)
          ? fromJsonTimestamp(object.last_updated_at)
          : undefined,
      id: isSet(object.id) ? globalThis.String(object.id) : '',
      storagePath: isSet(object.storagePath)
        ? globalThis.String(object.storagePath)
        : isSet(object.storage_path)
          ? globalThis.String(object.storage_path)
          : '',
      mimeType: isSet(object.mimeType)
        ? uploadedMediaMimeTypeFromJSON(object.mimeType)
        : isSet(object.mime_type)
          ? uploadedMediaMimeTypeFromJSON(object.mime_type)
          : 0,
      createdByUser: isSet(object.createdByUser)
        ? globalThis.String(object.createdByUser)
        : isSet(object.created_by_user)
          ? globalThis.String(object.created_by_user)
          : '',
    };
  },

  toJSON(message: UploadedMedia): unknown {
    const obj: any = {};
    if (message.createdAt !== undefined) {
      obj.createdAt = message.createdAt.toISOString();
    }
    if (message.archivedAt !== undefined) {
      obj.archivedAt = message.archivedAt.toISOString();
    }
    if (message.lastUpdatedAt !== undefined) {
      obj.lastUpdatedAt = message.lastUpdatedAt.toISOString();
    }
    if (message.id !== '') {
      obj.id = message.id;
    }
    if (message.storagePath !== '') {
      obj.storagePath = message.storagePath;
    }
    if (message.mimeType !== 0) {
      obj.mimeType = uploadedMediaMimeTypeToJSON(message.mimeType);
    }
    if (message.createdByUser !== '') {
      obj.createdByUser = message.createdByUser;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UploadedMedia>, I>>(base?: I): UploadedMedia {
    return UploadedMedia.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UploadedMedia>, I>>(object: I): UploadedMedia {
    const message = createBaseUploadedMedia();
    message.createdAt = object.createdAt ?? undefined;
    message.archivedAt = object.archivedAt ?? undefined;
    message.lastUpdatedAt = object.lastUpdatedAt ?? undefined;
    message.id = object.id ?? '';
    message.storagePath = object.storagePath ?? '';
    message.mimeType = object.mimeType ?? 0;
    message.createdByUser = object.createdByUser ?? '';
    return message;
  },
};

function createBaseUploadedMediaCreationRequestInput(): UploadedMediaCreationRequestInput {
  return { storagePath: '', mimeType: 0 };
}

export const UploadedMediaCreationRequestInput: MessageFns<UploadedMediaCreationRequestInput> = {
  encode(message: UploadedMediaCreationRequestInput, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.storagePath !== '') {
      writer.uint32(10).string(message.storagePath);
    }
    if (message.mimeType !== 0) {
      writer.uint32(16).int32(message.mimeType);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UploadedMediaCreationRequestInput {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUploadedMediaCreationRequestInput();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.storagePath = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.mimeType = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UploadedMediaCreationRequestInput {
    return {
      storagePath: isSet(object.storagePath)
        ? globalThis.String(object.storagePath)
        : isSet(object.storage_path)
          ? globalThis.String(object.storage_path)
          : '',
      mimeType: isSet(object.mimeType)
        ? uploadedMediaMimeTypeFromJSON(object.mimeType)
        : isSet(object.mime_type)
          ? uploadedMediaMimeTypeFromJSON(object.mime_type)
          : 0,
    };
  },

  toJSON(message: UploadedMediaCreationRequestInput): unknown {
    const obj: any = {};
    if (message.storagePath !== '') {
      obj.storagePath = message.storagePath;
    }
    if (message.mimeType !== 0) {
      obj.mimeType = uploadedMediaMimeTypeToJSON(message.mimeType);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UploadedMediaCreationRequestInput>, I>>(
    base?: I,
  ): UploadedMediaCreationRequestInput {
    return UploadedMediaCreationRequestInput.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UploadedMediaCreationRequestInput>, I>>(
    object: I,
  ): UploadedMediaCreationRequestInput {
    const message = createBaseUploadedMediaCreationRequestInput();
    message.storagePath = object.storagePath ?? '';
    message.mimeType = object.mimeType ?? 0;
    return message;
  },
};

function createBaseUploadedMediaUpdateRequestInput(): UploadedMediaUpdateRequestInput {
  return { storagePath: undefined, mimeType: undefined };
}

export const UploadedMediaUpdateRequestInput: MessageFns<UploadedMediaUpdateRequestInput> = {
  encode(message: UploadedMediaUpdateRequestInput, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.storagePath !== undefined) {
      writer.uint32(10).string(message.storagePath);
    }
    if (message.mimeType !== undefined) {
      writer.uint32(16).int32(message.mimeType);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UploadedMediaUpdateRequestInput {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUploadedMediaUpdateRequestInput();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.storagePath = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.mimeType = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UploadedMediaUpdateRequestInput {
    return {
      storagePath: isSet(object.storagePath)
        ? globalThis.String(object.storagePath)
        : isSet(object.storage_path)
          ? globalThis.String(object.storage_path)
          : undefined,
      mimeType: isSet(object.mimeType)
        ? uploadedMediaMimeTypeFromJSON(object.mimeType)
        : isSet(object.mime_type)
          ? uploadedMediaMimeTypeFromJSON(object.mime_type)
          : undefined,
    };
  },

  toJSON(message: UploadedMediaUpdateRequestInput): unknown {
    const obj: any = {};
    if (message.storagePath !== undefined) {
      obj.storagePath = message.storagePath;
    }
    if (message.mimeType !== undefined) {
      obj.mimeType = uploadedMediaMimeTypeToJSON(message.mimeType);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UploadedMediaUpdateRequestInput>, I>>(base?: I): UploadedMediaUpdateRequestInput {
    return UploadedMediaUpdateRequestInput.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UploadedMediaUpdateRequestInput>, I>>(
    object: I,
  ): UploadedMediaUpdateRequestInput {
    const message = createBaseUploadedMediaUpdateRequestInput();
    message.storagePath = object.storagePath ?? undefined;
    message.mimeType = object.mimeType ?? undefined;
    return message;
  },
};

function createBaseCreateUploadedMediaRequest(): CreateUploadedMediaRequest {
  return { input: undefined };
}

export const CreateUploadedMediaRequest: MessageFns<CreateUploadedMediaRequest> = {
  encode(message: CreateUploadedMediaRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.input !== undefined) {
      UploadedMediaCreationRequestInput.encode(message.input, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateUploadedMediaRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateUploadedMediaRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.input = UploadedMediaCreationRequestInput.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateUploadedMediaRequest {
    return { input: isSet(object.input) ? UploadedMediaCreationRequestInput.fromJSON(object.input) : undefined };
  },

  toJSON(message: CreateUploadedMediaRequest): unknown {
    const obj: any = {};
    if (message.input !== undefined) {
      obj.input = UploadedMediaCreationRequestInput.toJSON(message.input);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateUploadedMediaRequest>, I>>(base?: I): CreateUploadedMediaRequest {
    return CreateUploadedMediaRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateUploadedMediaRequest>, I>>(object: I): CreateUploadedMediaRequest {
    const message = createBaseCreateUploadedMediaRequest();
    message.input =
      object.input !== undefined && object.input !== null
        ? UploadedMediaCreationRequestInput.fromPartial(object.input)
        : undefined;
    return message;
  },
};

function createBaseCreateUploadedMediaResponse(): CreateUploadedMediaResponse {
  return { responseDetails: undefined, created: undefined };
}

export const CreateUploadedMediaResponse: MessageFns<CreateUploadedMediaResponse> = {
  encode(message: CreateUploadedMediaResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.responseDetails !== undefined) {
      ResponseDetails.encode(message.responseDetails, writer.uint32(10).fork()).join();
    }
    if (message.created !== undefined) {
      UploadedMedia.encode(message.created, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateUploadedMediaResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateUploadedMediaResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.responseDetails = ResponseDetails.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.created = UploadedMedia.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateUploadedMediaResponse {
    return {
      responseDetails: isSet(object.responseDetails)
        ? ResponseDetails.fromJSON(object.responseDetails)
        : isSet(object.response_details)
          ? ResponseDetails.fromJSON(object.response_details)
          : undefined,
      created: isSet(object.created) ? UploadedMedia.fromJSON(object.created) : undefined,
    };
  },

  toJSON(message: CreateUploadedMediaResponse): unknown {
    const obj: any = {};
    if (message.responseDetails !== undefined) {
      obj.responseDetails = ResponseDetails.toJSON(message.responseDetails);
    }
    if (message.created !== undefined) {
      obj.created = UploadedMedia.toJSON(message.created);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateUploadedMediaResponse>, I>>(base?: I): CreateUploadedMediaResponse {
    return CreateUploadedMediaResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateUploadedMediaResponse>, I>>(object: I): CreateUploadedMediaResponse {
    const message = createBaseCreateUploadedMediaResponse();
    message.responseDetails =
      object.responseDetails !== undefined && object.responseDetails !== null
        ? ResponseDetails.fromPartial(object.responseDetails)
        : undefined;
    message.created =
      object.created !== undefined && object.created !== null ? UploadedMedia.fromPartial(object.created) : undefined;
    return message;
  },
};

function createBaseGetUploadedMediaRequest(): GetUploadedMediaRequest {
  return { uploadedMediaId: '' };
}

export const GetUploadedMediaRequest: MessageFns<GetUploadedMediaRequest> = {
  encode(message: GetUploadedMediaRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.uploadedMediaId !== '') {
      writer.uint32(10).string(message.uploadedMediaId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetUploadedMediaRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetUploadedMediaRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.uploadedMediaId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetUploadedMediaRequest {
    return {
      uploadedMediaId: isSet(object.uploadedMediaId)
        ? globalThis.String(object.uploadedMediaId)
        : isSet(object.uploaded_media_id)
          ? globalThis.String(object.uploaded_media_id)
          : '',
    };
  },

  toJSON(message: GetUploadedMediaRequest): unknown {
    const obj: any = {};
    if (message.uploadedMediaId !== '') {
      obj.uploadedMediaId = message.uploadedMediaId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetUploadedMediaRequest>, I>>(base?: I): GetUploadedMediaRequest {
    return GetUploadedMediaRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetUploadedMediaRequest>, I>>(object: I): GetUploadedMediaRequest {
    const message = createBaseGetUploadedMediaRequest();
    message.uploadedMediaId = object.uploadedMediaId ?? '';
    return message;
  },
};

function createBaseGetUploadedMediaResponse(): GetUploadedMediaResponse {
  return { responseDetails: undefined, result: undefined };
}

export const GetUploadedMediaResponse: MessageFns<GetUploadedMediaResponse> = {
  encode(message: GetUploadedMediaResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.responseDetails !== undefined) {
      ResponseDetails.encode(message.responseDetails, writer.uint32(10).fork()).join();
    }
    if (message.result !== undefined) {
      UploadedMedia.encode(message.result, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetUploadedMediaResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetUploadedMediaResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.responseDetails = ResponseDetails.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.result = UploadedMedia.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetUploadedMediaResponse {
    return {
      responseDetails: isSet(object.responseDetails)
        ? ResponseDetails.fromJSON(object.responseDetails)
        : isSet(object.response_details)
          ? ResponseDetails.fromJSON(object.response_details)
          : undefined,
      result: isSet(object.result) ? UploadedMedia.fromJSON(object.result) : undefined,
    };
  },

  toJSON(message: GetUploadedMediaResponse): unknown {
    const obj: any = {};
    if (message.responseDetails !== undefined) {
      obj.responseDetails = ResponseDetails.toJSON(message.responseDetails);
    }
    if (message.result !== undefined) {
      obj.result = UploadedMedia.toJSON(message.result);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetUploadedMediaResponse>, I>>(base?: I): GetUploadedMediaResponse {
    return GetUploadedMediaResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetUploadedMediaResponse>, I>>(object: I): GetUploadedMediaResponse {
    const message = createBaseGetUploadedMediaResponse();
    message.responseDetails =
      object.responseDetails !== undefined && object.responseDetails !== null
        ? ResponseDetails.fromPartial(object.responseDetails)
        : undefined;
    message.result =
      object.result !== undefined && object.result !== null ? UploadedMedia.fromPartial(object.result) : undefined;
    return message;
  },
};

function createBaseGetUploadedMediaWithIDsRequest(): GetUploadedMediaWithIDsRequest {
  return { ids: [] };
}

export const GetUploadedMediaWithIDsRequest: MessageFns<GetUploadedMediaWithIDsRequest> = {
  encode(message: GetUploadedMediaWithIDsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.ids) {
      writer.uint32(10).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetUploadedMediaWithIDsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetUploadedMediaWithIDsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.ids.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetUploadedMediaWithIDsRequest {
    return { ids: globalThis.Array.isArray(object?.ids) ? object.ids.map((e: any) => globalThis.String(e)) : [] };
  },

  toJSON(message: GetUploadedMediaWithIDsRequest): unknown {
    const obj: any = {};
    if (message.ids?.length) {
      obj.ids = message.ids;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetUploadedMediaWithIDsRequest>, I>>(base?: I): GetUploadedMediaWithIDsRequest {
    return GetUploadedMediaWithIDsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetUploadedMediaWithIDsRequest>, I>>(
    object: I,
  ): GetUploadedMediaWithIDsRequest {
    const message = createBaseGetUploadedMediaWithIDsRequest();
    message.ids = object.ids?.map((e) => e) || [];
    return message;
  },
};

function createBaseGetUploadedMediaWithIDsResponse(): GetUploadedMediaWithIDsResponse {
  return { responseDetails: undefined, results: [] };
}

export const GetUploadedMediaWithIDsResponse: MessageFns<GetUploadedMediaWithIDsResponse> = {
  encode(message: GetUploadedMediaWithIDsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.responseDetails !== undefined) {
      ResponseDetails.encode(message.responseDetails, writer.uint32(10).fork()).join();
    }
    for (const v of message.results) {
      UploadedMedia.encode(v!, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetUploadedMediaWithIDsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetUploadedMediaWithIDsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.responseDetails = ResponseDetails.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.results.push(UploadedMedia.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetUploadedMediaWithIDsResponse {
    return {
      responseDetails: isSet(object.responseDetails)
        ? ResponseDetails.fromJSON(object.responseDetails)
        : isSet(object.response_details)
          ? ResponseDetails.fromJSON(object.response_details)
          : undefined,
      results: globalThis.Array.isArray(object?.results)
        ? object.results.map((e: any) => UploadedMedia.fromJSON(e))
        : [],
    };
  },

  toJSON(message: GetUploadedMediaWithIDsResponse): unknown {
    const obj: any = {};
    if (message.responseDetails !== undefined) {
      obj.responseDetails = ResponseDetails.toJSON(message.responseDetails);
    }
    if (message.results?.length) {
      obj.results = message.results.map((e) => UploadedMedia.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetUploadedMediaWithIDsResponse>, I>>(base?: I): GetUploadedMediaWithIDsResponse {
    return GetUploadedMediaWithIDsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetUploadedMediaWithIDsResponse>, I>>(
    object: I,
  ): GetUploadedMediaWithIDsResponse {
    const message = createBaseGetUploadedMediaWithIDsResponse();
    message.responseDetails =
      object.responseDetails !== undefined && object.responseDetails !== null
        ? ResponseDetails.fromPartial(object.responseDetails)
        : undefined;
    message.results = object.results?.map((e) => UploadedMedia.fromPartial(e)) || [];
    return message;
  },
};

function createBaseGetUploadedMediaForUserRequest(): GetUploadedMediaForUserRequest {
  return { userId: '', filter: undefined };
}

export const GetUploadedMediaForUserRequest: MessageFns<GetUploadedMediaForUserRequest> = {
  encode(message: GetUploadedMediaForUserRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== '') {
      writer.uint32(10).string(message.userId);
    }
    if (message.filter !== undefined) {
      QueryFilter.encode(message.filter, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetUploadedMediaForUserRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetUploadedMediaForUserRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.filter = QueryFilter.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetUploadedMediaForUserRequest {
    return {
      userId: isSet(object.userId)
        ? globalThis.String(object.userId)
        : isSet(object.user_id)
          ? globalThis.String(object.user_id)
          : '',
      filter: isSet(object.filter) ? QueryFilter.fromJSON(object.filter) : undefined,
    };
  },

  toJSON(message: GetUploadedMediaForUserRequest): unknown {
    const obj: any = {};
    if (message.userId !== '') {
      obj.userId = message.userId;
    }
    if (message.filter !== undefined) {
      obj.filter = QueryFilter.toJSON(message.filter);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetUploadedMediaForUserRequest>, I>>(base?: I): GetUploadedMediaForUserRequest {
    return GetUploadedMediaForUserRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetUploadedMediaForUserRequest>, I>>(
    object: I,
  ): GetUploadedMediaForUserRequest {
    const message = createBaseGetUploadedMediaForUserRequest();
    message.userId = object.userId ?? '';
    message.filter =
      object.filter !== undefined && object.filter !== null ? QueryFilter.fromPartial(object.filter) : undefined;
    return message;
  },
};

function createBaseGetUploadedMediaForUserResponse(): GetUploadedMediaForUserResponse {
  return { responseDetails: undefined, pagination: undefined, results: [] };
}

export const GetUploadedMediaForUserResponse: MessageFns<GetUploadedMediaForUserResponse> = {
  encode(message: GetUploadedMediaForUserResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.responseDetails !== undefined) {
      ResponseDetails.encode(message.responseDetails, writer.uint32(10).fork()).join();
    }
    if (message.pagination !== undefined) {
      Pagination.encode(message.pagination, writer.uint32(18).fork()).join();
    }
    for (const v of message.results) {
      UploadedMedia.encode(v!, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetUploadedMediaForUserResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetUploadedMediaForUserResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.responseDetails = ResponseDetails.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.pagination = Pagination.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.results.push(UploadedMedia.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetUploadedMediaForUserResponse {
    return {
      responseDetails: isSet(object.responseDetails)
        ? ResponseDetails.fromJSON(object.responseDetails)
        : isSet(object.response_details)
          ? ResponseDetails.fromJSON(object.response_details)
          : undefined,
      pagination: isSet(object.pagination) ? Pagination.fromJSON(object.pagination) : undefined,
      results: globalThis.Array.isArray(object?.results)
        ? object.results.map((e: any) => UploadedMedia.fromJSON(e))
        : [],
    };
  },

  toJSON(message: GetUploadedMediaForUserResponse): unknown {
    const obj: any = {};
    if (message.responseDetails !== undefined) {
      obj.responseDetails = ResponseDetails.toJSON(message.responseDetails);
    }
    if (message.pagination !== undefined) {
      obj.pagination = Pagination.toJSON(message.pagination);
    }
    if (message.results?.length) {
      obj.results = message.results.map((e) => UploadedMedia.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetUploadedMediaForUserResponse>, I>>(base?: I): GetUploadedMediaForUserResponse {
    return GetUploadedMediaForUserResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetUploadedMediaForUserResponse>, I>>(
    object: I,
  ): GetUploadedMediaForUserResponse {
    const message = createBaseGetUploadedMediaForUserResponse();
    message.responseDetails =
      object.responseDetails !== undefined && object.responseDetails !== null
        ? ResponseDetails.fromPartial(object.responseDetails)
        : undefined;
    message.pagination =
      object.pagination !== undefined && object.pagination !== null
        ? Pagination.fromPartial(object.pagination)
        : undefined;
    message.results = object.results?.map((e) => UploadedMedia.fromPartial(e)) || [];
    return message;
  },
};

function createBaseUpdateUploadedMediaRequest(): UpdateUploadedMediaRequest {
  return { uploadedMediaId: '', input: undefined };
}

export const UpdateUploadedMediaRequest: MessageFns<UpdateUploadedMediaRequest> = {
  encode(message: UpdateUploadedMediaRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.uploadedMediaId !== '') {
      writer.uint32(10).string(message.uploadedMediaId);
    }
    if (message.input !== undefined) {
      UploadedMediaUpdateRequestInput.encode(message.input, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateUploadedMediaRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateUploadedMediaRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.uploadedMediaId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.input = UploadedMediaUpdateRequestInput.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateUploadedMediaRequest {
    return {
      uploadedMediaId: isSet(object.uploadedMediaId)
        ? globalThis.String(object.uploadedMediaId)
        : isSet(object.uploaded_media_id)
          ? globalThis.String(object.uploaded_media_id)
          : '',
      input: isSet(object.input) ? UploadedMediaUpdateRequestInput.fromJSON(object.input) : undefined,
    };
  },

  toJSON(message: UpdateUploadedMediaRequest): unknown {
    const obj: any = {};
    if (message.uploadedMediaId !== '') {
      obj.uploadedMediaId = message.uploadedMediaId;
    }
    if (message.input !== undefined) {
      obj.input = UploadedMediaUpdateRequestInput.toJSON(message.input);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpdateUploadedMediaRequest>, I>>(base?: I): UpdateUploadedMediaRequest {
    return UpdateUploadedMediaRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpdateUploadedMediaRequest>, I>>(object: I): UpdateUploadedMediaRequest {
    const message = createBaseUpdateUploadedMediaRequest();
    message.uploadedMediaId = object.uploadedMediaId ?? '';
    message.input =
      object.input !== undefined && object.input !== null
        ? UploadedMediaUpdateRequestInput.fromPartial(object.input)
        : undefined;
    return message;
  },
};

function createBaseUpdateUploadedMediaResponse(): UpdateUploadedMediaResponse {
  return { responseDetails: undefined, updated: undefined };
}

export const UpdateUploadedMediaResponse: MessageFns<UpdateUploadedMediaResponse> = {
  encode(message: UpdateUploadedMediaResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.responseDetails !== undefined) {
      ResponseDetails.encode(message.responseDetails, writer.uint32(10).fork()).join();
    }
    if (message.updated !== undefined) {
      UploadedMedia.encode(message.updated, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateUploadedMediaResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateUploadedMediaResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.responseDetails = ResponseDetails.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.updated = UploadedMedia.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateUploadedMediaResponse {
    return {
      responseDetails: isSet(object.responseDetails)
        ? ResponseDetails.fromJSON(object.responseDetails)
        : isSet(object.response_details)
          ? ResponseDetails.fromJSON(object.response_details)
          : undefined,
      updated: isSet(object.updated) ? UploadedMedia.fromJSON(object.updated) : undefined,
    };
  },

  toJSON(message: UpdateUploadedMediaResponse): unknown {
    const obj: any = {};
    if (message.responseDetails !== undefined) {
      obj.responseDetails = ResponseDetails.toJSON(message.responseDetails);
    }
    if (message.updated !== undefined) {
      obj.updated = UploadedMedia.toJSON(message.updated);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpdateUploadedMediaResponse>, I>>(base?: I): UpdateUploadedMediaResponse {
    return UpdateUploadedMediaResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpdateUploadedMediaResponse>, I>>(object: I): UpdateUploadedMediaResponse {
    const message = createBaseUpdateUploadedMediaResponse();
    message.responseDetails =
      object.responseDetails !== undefined && object.responseDetails !== null
        ? ResponseDetails.fromPartial(object.responseDetails)
        : undefined;
    message.updated =
      object.updated !== undefined && object.updated !== null ? UploadedMedia.fromPartial(object.updated) : undefined;
    return message;
  },
};

function createBaseArchiveUploadedMediaRequest(): ArchiveUploadedMediaRequest {
  return { uploadedMediaId: '' };
}

export const ArchiveUploadedMediaRequest: MessageFns<ArchiveUploadedMediaRequest> = {
  encode(message: ArchiveUploadedMediaRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.uploadedMediaId !== '') {
      writer.uint32(10).string(message.uploadedMediaId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ArchiveUploadedMediaRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseArchiveUploadedMediaRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.uploadedMediaId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ArchiveUploadedMediaRequest {
    return {
      uploadedMediaId: isSet(object.uploadedMediaId)
        ? globalThis.String(object.uploadedMediaId)
        : isSet(object.uploaded_media_id)
          ? globalThis.String(object.uploaded_media_id)
          : '',
    };
  },

  toJSON(message: ArchiveUploadedMediaRequest): unknown {
    const obj: any = {};
    if (message.uploadedMediaId !== '') {
      obj.uploadedMediaId = message.uploadedMediaId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ArchiveUploadedMediaRequest>, I>>(base?: I): ArchiveUploadedMediaRequest {
    return ArchiveUploadedMediaRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ArchiveUploadedMediaRequest>, I>>(object: I): ArchiveUploadedMediaRequest {
    const message = createBaseArchiveUploadedMediaRequest();
    message.uploadedMediaId = object.uploadedMediaId ?? '';
    return message;
  },
};

function createBaseArchiveUploadedMediaResponse(): ArchiveUploadedMediaResponse {
  return { responseDetails: undefined };
}

export const ArchiveUploadedMediaResponse: MessageFns<ArchiveUploadedMediaResponse> = {
  encode(message: ArchiveUploadedMediaResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.responseDetails !== undefined) {
      ResponseDetails.encode(message.responseDetails, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ArchiveUploadedMediaResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseArchiveUploadedMediaResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.responseDetails = ResponseDetails.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ArchiveUploadedMediaResponse {
    return {
      responseDetails: isSet(object.responseDetails)
        ? ResponseDetails.fromJSON(object.responseDetails)
        : isSet(object.response_details)
          ? ResponseDetails.fromJSON(object.response_details)
          : undefined,
    };
  },

  toJSON(message: ArchiveUploadedMediaResponse): unknown {
    const obj: any = {};
    if (message.responseDetails !== undefined) {
      obj.responseDetails = ResponseDetails.toJSON(message.responseDetails);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ArchiveUploadedMediaResponse>, I>>(base?: I): ArchiveUploadedMediaResponse {
    return ArchiveUploadedMediaResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ArchiveUploadedMediaResponse>, I>>(object: I): ArchiveUploadedMediaResponse {
    const message = createBaseArchiveUploadedMediaResponse();
    message.responseDetails =
      object.responseDetails !== undefined && object.responseDetails !== null
        ? ResponseDetails.fromPartial(object.responseDetails)
        : undefined;
    return message;
  },
};

export type UploadedMediaServiceService = typeof UploadedMediaServiceService;
export const UploadedMediaServiceService = {
  upload: {
    path: '/uploaded_media.UploadedMediaService/Upload' as const,
    requestStream: true as const,
    responseStream: false as const,
    requestSerialize: (value: UploadRequest): Buffer => Buffer.from(UploadRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): UploadRequest => UploadRequest.decode(value),
    responseSerialize: (value: UploadResponse): Buffer => Buffer.from(UploadResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): UploadResponse => UploadResponse.decode(value),
  },
  createUploadedMedia: {
    path: '/uploaded_media.UploadedMediaService/CreateUploadedMedia' as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: CreateUploadedMediaRequest): Buffer =>
      Buffer.from(CreateUploadedMediaRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): CreateUploadedMediaRequest => CreateUploadedMediaRequest.decode(value),
    responseSerialize: (value: CreateUploadedMediaResponse): Buffer =>
      Buffer.from(CreateUploadedMediaResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): CreateUploadedMediaResponse => CreateUploadedMediaResponse.decode(value),
  },
  getUploadedMedia: {
    path: '/uploaded_media.UploadedMediaService/GetUploadedMedia' as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: GetUploadedMediaRequest): Buffer =>
      Buffer.from(GetUploadedMediaRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetUploadedMediaRequest => GetUploadedMediaRequest.decode(value),
    responseSerialize: (value: GetUploadedMediaResponse): Buffer =>
      Buffer.from(GetUploadedMediaResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): GetUploadedMediaResponse => GetUploadedMediaResponse.decode(value),
  },
  getUploadedMediaWithIDs: {
    path: '/uploaded_media.UploadedMediaService/GetUploadedMediaWithIDs' as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: GetUploadedMediaWithIDsRequest): Buffer =>
      Buffer.from(GetUploadedMediaWithIDsRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetUploadedMediaWithIDsRequest => GetUploadedMediaWithIDsRequest.decode(value),
    responseSerialize: (value: GetUploadedMediaWithIDsResponse): Buffer =>
      Buffer.from(GetUploadedMediaWithIDsResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): GetUploadedMediaWithIDsResponse =>
      GetUploadedMediaWithIDsResponse.decode(value),
  },
  getUploadedMediaForUser: {
    path: '/uploaded_media.UploadedMediaService/GetUploadedMediaForUser' as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: GetUploadedMediaForUserRequest): Buffer =>
      Buffer.from(GetUploadedMediaForUserRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetUploadedMediaForUserRequest => GetUploadedMediaForUserRequest.decode(value),
    responseSerialize: (value: GetUploadedMediaForUserResponse): Buffer =>
      Buffer.from(GetUploadedMediaForUserResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): GetUploadedMediaForUserResponse =>
      GetUploadedMediaForUserResponse.decode(value),
  },
  updateUploadedMedia: {
    path: '/uploaded_media.UploadedMediaService/UpdateUploadedMedia' as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: UpdateUploadedMediaRequest): Buffer =>
      Buffer.from(UpdateUploadedMediaRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): UpdateUploadedMediaRequest => UpdateUploadedMediaRequest.decode(value),
    responseSerialize: (value: UpdateUploadedMediaResponse): Buffer =>
      Buffer.from(UpdateUploadedMediaResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): UpdateUploadedMediaResponse => UpdateUploadedMediaResponse.decode(value),
  },
  archiveUploadedMedia: {
    path: '/uploaded_media.UploadedMediaService/ArchiveUploadedMedia' as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: ArchiveUploadedMediaRequest): Buffer =>
      Buffer.from(ArchiveUploadedMediaRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): ArchiveUploadedMediaRequest => ArchiveUploadedMediaRequest.decode(value),
    responseSerialize: (value: ArchiveUploadedMediaResponse): Buffer =>
      Buffer.from(ArchiveUploadedMediaResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): ArchiveUploadedMediaResponse => ArchiveUploadedMediaResponse.decode(value),
  },
} as const;

export interface UploadedMediaServiceServer extends UntypedServiceImplementation {
  upload: handleClientStreamingCall<UploadRequest, UploadResponse>;
  createUploadedMedia: handleUnaryCall<CreateUploadedMediaRequest, CreateUploadedMediaResponse>;
  getUploadedMedia: handleUnaryCall<GetUploadedMediaRequest, GetUploadedMediaResponse>;
  getUploadedMediaWithIDs: handleUnaryCall<GetUploadedMediaWithIDsRequest, GetUploadedMediaWithIDsResponse>;
  getUploadedMediaForUser: handleUnaryCall<GetUploadedMediaForUserRequest, GetUploadedMediaForUserResponse>;
  updateUploadedMedia: handleUnaryCall<UpdateUploadedMediaRequest, UpdateUploadedMediaResponse>;
  archiveUploadedMedia: handleUnaryCall<ArchiveUploadedMediaRequest, ArchiveUploadedMediaResponse>;
}

export interface UploadedMediaServiceClient extends Client {
  upload(callback: (error: ServiceError | null, response: UploadResponse) => void): ClientWritableStream<UploadRequest>;
  upload(
    metadata: Metadata,
    callback: (error: ServiceError | null, response: UploadResponse) => void,
  ): ClientWritableStream<UploadRequest>;
  upload(
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: UploadResponse) => void,
  ): ClientWritableStream<UploadRequest>;
  upload(
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: UploadResponse) => void,
  ): ClientWritableStream<UploadRequest>;
  createUploadedMedia(
    request: CreateUploadedMediaRequest,
    callback: (error: ServiceError | null, response: CreateUploadedMediaResponse) => void,
  ): ClientUnaryCall;
  createUploadedMedia(
    request: CreateUploadedMediaRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: CreateUploadedMediaResponse) => void,
  ): ClientUnaryCall;
  createUploadedMedia(
    request: CreateUploadedMediaRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: CreateUploadedMediaResponse) => void,
  ): ClientUnaryCall;
  getUploadedMedia(
    request: GetUploadedMediaRequest,
    callback: (error: ServiceError | null, response: GetUploadedMediaResponse) => void,
  ): ClientUnaryCall;
  getUploadedMedia(
    request: GetUploadedMediaRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GetUploadedMediaResponse) => void,
  ): ClientUnaryCall;
  getUploadedMedia(
    request: GetUploadedMediaRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GetUploadedMediaResponse) => void,
  ): ClientUnaryCall;
  getUploadedMediaWithIDs(
    request: GetUploadedMediaWithIDsRequest,
    callback: (error: ServiceError | null, response: GetUploadedMediaWithIDsResponse) => void,
  ): ClientUnaryCall;
  getUploadedMediaWithIDs(
    request: GetUploadedMediaWithIDsRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GetUploadedMediaWithIDsResponse) => void,
  ): ClientUnaryCall;
  getUploadedMediaWithIDs(
    request: GetUploadedMediaWithIDsRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GetUploadedMediaWithIDsResponse) => void,
  ): ClientUnaryCall;
  getUploadedMediaForUser(
    request: GetUploadedMediaForUserRequest,
    callback: (error: ServiceError | null, response: GetUploadedMediaForUserResponse) => void,
  ): ClientUnaryCall;
  getUploadedMediaForUser(
    request: GetUploadedMediaForUserRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GetUploadedMediaForUserResponse) => void,
  ): ClientUnaryCall;
  getUploadedMediaForUser(
    request: GetUploadedMediaForUserRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GetUploadedMediaForUserResponse) => void,
  ): ClientUnaryCall;
  updateUploadedMedia(
    request: UpdateUploadedMediaRequest,
    callback: (error: ServiceError | null, response: UpdateUploadedMediaResponse) => void,
  ): ClientUnaryCall;
  updateUploadedMedia(
    request: UpdateUploadedMediaRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: UpdateUploadedMediaResponse) => void,
  ): ClientUnaryCall;
  updateUploadedMedia(
    request: UpdateUploadedMediaRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: UpdateUploadedMediaResponse) => void,
  ): ClientUnaryCall;
  archiveUploadedMedia(
    request: ArchiveUploadedMediaRequest,
    callback: (error: ServiceError | null, response: ArchiveUploadedMediaResponse) => void,
  ): ClientUnaryCall;
  archiveUploadedMedia(
    request: ArchiveUploadedMediaRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: ArchiveUploadedMediaResponse) => void,
  ): ClientUnaryCall;
  archiveUploadedMedia(
    request: ArchiveUploadedMediaRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: ArchiveUploadedMediaResponse) => void,
  ): ClientUnaryCall;
}

export const UploadedMediaServiceClient = makeGenericClientConstructor(
  UploadedMediaServiceService,
  'uploaded_media.UploadedMediaService',
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): UploadedMediaServiceClient;
  service: typeof UploadedMediaServiceService;
  serviceName: string;
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from(globalThis.Buffer.from(b64, 'base64'));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return globalThis.Buffer.from(arr).toString('base64');
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(''));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends {}
        ? { [K in keyof T]?: DeepPartial<T[K]> }
        : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === 'string') {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error('Value is larger than Number.MAX_SAFE_INTEGER');
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error('Value is smaller than Number.MIN_SAFE_INTEGER');
  }
  return num;
}

function isObject(value: any): boolean {
  return typeof value === 'object' && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
