// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v6.33.1
// source: uploaded_media/uploaded_media_messages.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from '@bufbuild/protobuf/wire';
import { Timestamp } from '../google/protobuf/timestamp';

export const protobufPackage = 'uploaded_media';

export enum UploadedMediaMimeType {
  UPLOADED_MEDIA_MIME_TYPE_UNSPECIFIED = 0,
  UPLOADED_MEDIA_MIME_TYPE_IMAGE_PNG = 1,
  UPLOADED_MEDIA_MIME_TYPE_IMAGE_JPEG = 2,
  UPLOADED_MEDIA_MIME_TYPE_IMAGE_GIF = 3,
  UPLOADED_MEDIA_MIME_TYPE_VIDEO_MP4 = 4,
  UNRECOGNIZED = -1,
}

export function uploadedMediaMimeTypeFromJSON(object: any): UploadedMediaMimeType {
  switch (object) {
    case 0:
    case 'UPLOADED_MEDIA_MIME_TYPE_UNSPECIFIED':
      return UploadedMediaMimeType.UPLOADED_MEDIA_MIME_TYPE_UNSPECIFIED;
    case 1:
    case 'UPLOADED_MEDIA_MIME_TYPE_IMAGE_PNG':
      return UploadedMediaMimeType.UPLOADED_MEDIA_MIME_TYPE_IMAGE_PNG;
    case 2:
    case 'UPLOADED_MEDIA_MIME_TYPE_IMAGE_JPEG':
      return UploadedMediaMimeType.UPLOADED_MEDIA_MIME_TYPE_IMAGE_JPEG;
    case 3:
    case 'UPLOADED_MEDIA_MIME_TYPE_IMAGE_GIF':
      return UploadedMediaMimeType.UPLOADED_MEDIA_MIME_TYPE_IMAGE_GIF;
    case 4:
    case 'UPLOADED_MEDIA_MIME_TYPE_VIDEO_MP4':
      return UploadedMediaMimeType.UPLOADED_MEDIA_MIME_TYPE_VIDEO_MP4;
    case -1:
    case 'UNRECOGNIZED':
    default:
      return UploadedMediaMimeType.UNRECOGNIZED;
  }
}

export function uploadedMediaMimeTypeToJSON(object: UploadedMediaMimeType): string {
  switch (object) {
    case UploadedMediaMimeType.UPLOADED_MEDIA_MIME_TYPE_UNSPECIFIED:
      return 'UPLOADED_MEDIA_MIME_TYPE_UNSPECIFIED';
    case UploadedMediaMimeType.UPLOADED_MEDIA_MIME_TYPE_IMAGE_PNG:
      return 'UPLOADED_MEDIA_MIME_TYPE_IMAGE_PNG';
    case UploadedMediaMimeType.UPLOADED_MEDIA_MIME_TYPE_IMAGE_JPEG:
      return 'UPLOADED_MEDIA_MIME_TYPE_IMAGE_JPEG';
    case UploadedMediaMimeType.UPLOADED_MEDIA_MIME_TYPE_IMAGE_GIF:
      return 'UPLOADED_MEDIA_MIME_TYPE_IMAGE_GIF';
    case UploadedMediaMimeType.UPLOADED_MEDIA_MIME_TYPE_VIDEO_MP4:
      return 'UPLOADED_MEDIA_MIME_TYPE_VIDEO_MP4';
    case UploadedMediaMimeType.UNRECOGNIZED:
    default:
      return 'UNRECOGNIZED';
  }
}

export interface DataCollection {
  uploadedMedia: { [key: string]: UploadedMedia };
}

export interface DataCollection_UploadedMediaEntry {
  key: string;
  value: UploadedMedia | undefined;
}

export interface UploadRequest {
  metadata?: UploadMetadata | undefined;
  chunk?: Uint8Array | undefined;
}

export interface UploadMetadata {
  bucket: string;
  objectName: string;
  contentType: string;
}

export interface UploadResponse {
  objectUrl: string;
  sizeBytes: number;
}

export interface UploadedMedia {
  createdAt: Date | undefined;
  archivedAt: Date | undefined;
  lastUpdatedAt: Date | undefined;
  id: string;
  storagePath: string;
  mimeType: UploadedMediaMimeType;
  createdByUser: string;
}

export interface UploadedMediaCreationRequestInput {
  storagePath: string;
  mimeType: UploadedMediaMimeType;
}

export interface UploadedMediaUpdateRequestInput {
  storagePath?: string | undefined;
  mimeType?: UploadedMediaMimeType | undefined;
}

function createBaseDataCollection(): DataCollection {
  return { uploadedMedia: {} };
}

export const DataCollection: MessageFns<DataCollection> = {
  encode(message: DataCollection, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    globalThis.Object.entries(message.uploadedMedia).forEach(([key, value]: [string, UploadedMedia]) => {
      DataCollection_UploadedMediaEntry.encode({ key: key as any, value }, writer.uint32(10).fork()).join();
    });
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DataCollection {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDataCollection();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          const entry1 = DataCollection_UploadedMediaEntry.decode(reader, reader.uint32());
          if (entry1.value !== undefined) {
            message.uploadedMedia[entry1.key] = entry1.value;
          }
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DataCollection {
    return {
      uploadedMedia: isObject(object.uploadedMedia)
        ? (globalThis.Object.entries(object.uploadedMedia) as [string, any][]).reduce(
            (acc: { [key: string]: UploadedMedia }, [key, value]: [string, any]) => {
              acc[key] = UploadedMedia.fromJSON(value);
              return acc;
            },
            {},
          )
        : isObject(object.uploaded_media)
          ? (globalThis.Object.entries(object.uploaded_media) as [string, any][]).reduce(
              (acc: { [key: string]: UploadedMedia }, [key, value]: [string, any]) => {
                acc[key] = UploadedMedia.fromJSON(value);
                return acc;
              },
              {},
            )
          : {},
    };
  },

  toJSON(message: DataCollection): unknown {
    const obj: any = {};
    if (message.uploadedMedia) {
      const entries = globalThis.Object.entries(message.uploadedMedia) as [string, UploadedMedia][];
      if (entries.length > 0) {
        obj.uploadedMedia = {};
        entries.forEach(([k, v]) => {
          obj.uploadedMedia[k] = UploadedMedia.toJSON(v);
        });
      }
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DataCollection>, I>>(base?: I): DataCollection {
    return DataCollection.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DataCollection>, I>>(object: I): DataCollection {
    const message = createBaseDataCollection();
    message.uploadedMedia = (globalThis.Object.entries(object.uploadedMedia ?? {}) as [string, UploadedMedia][]).reduce(
      (acc: { [key: string]: UploadedMedia }, [key, value]: [string, UploadedMedia]) => {
        if (value !== undefined) {
          acc[key] = UploadedMedia.fromPartial(value);
        }
        return acc;
      },
      {},
    );
    return message;
  },
};

function createBaseDataCollection_UploadedMediaEntry(): DataCollection_UploadedMediaEntry {
  return { key: '', value: undefined };
}

export const DataCollection_UploadedMediaEntry: MessageFns<DataCollection_UploadedMediaEntry> = {
  encode(message: DataCollection_UploadedMediaEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== '') {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== undefined) {
      UploadedMedia.encode(message.value, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DataCollection_UploadedMediaEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDataCollection_UploadedMediaEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = UploadedMedia.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DataCollection_UploadedMediaEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : '',
      value: isSet(object.value) ? UploadedMedia.fromJSON(object.value) : undefined,
    };
  },

  toJSON(message: DataCollection_UploadedMediaEntry): unknown {
    const obj: any = {};
    if (message.key !== '') {
      obj.key = message.key;
    }
    if (message.value !== undefined) {
      obj.value = UploadedMedia.toJSON(message.value);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DataCollection_UploadedMediaEntry>, I>>(
    base?: I,
  ): DataCollection_UploadedMediaEntry {
    return DataCollection_UploadedMediaEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DataCollection_UploadedMediaEntry>, I>>(
    object: I,
  ): DataCollection_UploadedMediaEntry {
    const message = createBaseDataCollection_UploadedMediaEntry();
    message.key = object.key ?? '';
    message.value =
      object.value !== undefined && object.value !== null ? UploadedMedia.fromPartial(object.value) : undefined;
    return message;
  },
};

function createBaseUploadRequest(): UploadRequest {
  return { metadata: undefined, chunk: undefined };
}

export const UploadRequest: MessageFns<UploadRequest> = {
  encode(message: UploadRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.metadata !== undefined) {
      UploadMetadata.encode(message.metadata, writer.uint32(10).fork()).join();
    }
    if (message.chunk !== undefined) {
      writer.uint32(18).bytes(message.chunk);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UploadRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUploadRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.metadata = UploadMetadata.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.chunk = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UploadRequest {
    return {
      metadata: isSet(object.metadata) ? UploadMetadata.fromJSON(object.metadata) : undefined,
      chunk: isSet(object.chunk) ? bytesFromBase64(object.chunk) : undefined,
    };
  },

  toJSON(message: UploadRequest): unknown {
    const obj: any = {};
    if (message.metadata !== undefined) {
      obj.metadata = UploadMetadata.toJSON(message.metadata);
    }
    if (message.chunk !== undefined) {
      obj.chunk = base64FromBytes(message.chunk);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UploadRequest>, I>>(base?: I): UploadRequest {
    return UploadRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UploadRequest>, I>>(object: I): UploadRequest {
    const message = createBaseUploadRequest();
    message.metadata =
      object.metadata !== undefined && object.metadata !== null
        ? UploadMetadata.fromPartial(object.metadata)
        : undefined;
    message.chunk = object.chunk ?? undefined;
    return message;
  },
};

function createBaseUploadMetadata(): UploadMetadata {
  return { bucket: '', objectName: '', contentType: '' };
}

export const UploadMetadata: MessageFns<UploadMetadata> = {
  encode(message: UploadMetadata, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.bucket !== '') {
      writer.uint32(10).string(message.bucket);
    }
    if (message.objectName !== '') {
      writer.uint32(18).string(message.objectName);
    }
    if (message.contentType !== '') {
      writer.uint32(26).string(message.contentType);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UploadMetadata {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUploadMetadata();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.bucket = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.objectName = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.contentType = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UploadMetadata {
    return {
      bucket: isSet(object.bucket) ? globalThis.String(object.bucket) : '',
      objectName: isSet(object.objectName)
        ? globalThis.String(object.objectName)
        : isSet(object.object_name)
          ? globalThis.String(object.object_name)
          : '',
      contentType: isSet(object.contentType)
        ? globalThis.String(object.contentType)
        : isSet(object.content_type)
          ? globalThis.String(object.content_type)
          : '',
    };
  },

  toJSON(message: UploadMetadata): unknown {
    const obj: any = {};
    if (message.bucket !== '') {
      obj.bucket = message.bucket;
    }
    if (message.objectName !== '') {
      obj.objectName = message.objectName;
    }
    if (message.contentType !== '') {
      obj.contentType = message.contentType;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UploadMetadata>, I>>(base?: I): UploadMetadata {
    return UploadMetadata.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UploadMetadata>, I>>(object: I): UploadMetadata {
    const message = createBaseUploadMetadata();
    message.bucket = object.bucket ?? '';
    message.objectName = object.objectName ?? '';
    message.contentType = object.contentType ?? '';
    return message;
  },
};

function createBaseUploadResponse(): UploadResponse {
  return { objectUrl: '', sizeBytes: 0 };
}

export const UploadResponse: MessageFns<UploadResponse> = {
  encode(message: UploadResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.objectUrl !== '') {
      writer.uint32(10).string(message.objectUrl);
    }
    if (message.sizeBytes !== 0) {
      writer.uint32(16).int64(message.sizeBytes);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UploadResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUploadResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.objectUrl = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.sizeBytes = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UploadResponse {
    return {
      objectUrl: isSet(object.objectUrl)
        ? globalThis.String(object.objectUrl)
        : isSet(object.object_url)
          ? globalThis.String(object.object_url)
          : '',
      sizeBytes: isSet(object.sizeBytes)
        ? globalThis.Number(object.sizeBytes)
        : isSet(object.size_bytes)
          ? globalThis.Number(object.size_bytes)
          : 0,
    };
  },

  toJSON(message: UploadResponse): unknown {
    const obj: any = {};
    if (message.objectUrl !== '') {
      obj.objectUrl = message.objectUrl;
    }
    if (message.sizeBytes !== 0) {
      obj.sizeBytes = Math.round(message.sizeBytes);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UploadResponse>, I>>(base?: I): UploadResponse {
    return UploadResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UploadResponse>, I>>(object: I): UploadResponse {
    const message = createBaseUploadResponse();
    message.objectUrl = object.objectUrl ?? '';
    message.sizeBytes = object.sizeBytes ?? 0;
    return message;
  },
};

function createBaseUploadedMedia(): UploadedMedia {
  return {
    createdAt: undefined,
    archivedAt: undefined,
    lastUpdatedAt: undefined,
    id: '',
    storagePath: '',
    mimeType: 0,
    createdByUser: '',
  };
}

export const UploadedMedia: MessageFns<UploadedMedia> = {
  encode(message: UploadedMedia, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.createdAt !== undefined) {
      Timestamp.encode(toTimestamp(message.createdAt), writer.uint32(10).fork()).join();
    }
    if (message.archivedAt !== undefined) {
      Timestamp.encode(toTimestamp(message.archivedAt), writer.uint32(18).fork()).join();
    }
    if (message.lastUpdatedAt !== undefined) {
      Timestamp.encode(toTimestamp(message.lastUpdatedAt), writer.uint32(26).fork()).join();
    }
    if (message.id !== '') {
      writer.uint32(34).string(message.id);
    }
    if (message.storagePath !== '') {
      writer.uint32(42).string(message.storagePath);
    }
    if (message.mimeType !== 0) {
      writer.uint32(48).int32(message.mimeType);
    }
    if (message.createdByUser !== '') {
      writer.uint32(58).string(message.createdByUser);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UploadedMedia {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUploadedMedia();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.createdAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.archivedAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.lastUpdatedAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.storagePath = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.mimeType = reader.int32() as any;
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.createdByUser = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UploadedMedia {
    return {
      createdAt: isSet(object.createdAt)
        ? fromJsonTimestamp(object.createdAt)
        : isSet(object.created_at)
          ? fromJsonTimestamp(object.created_at)
          : undefined,
      archivedAt: isSet(object.archivedAt)
        ? fromJsonTimestamp(object.archivedAt)
        : isSet(object.archived_at)
          ? fromJsonTimestamp(object.archived_at)
          : undefined,
      lastUpdatedAt: isSet(object.lastUpdatedAt)
        ? fromJsonTimestamp(object.lastUpdatedAt)
        : isSet(object.last_updated_at)
          ? fromJsonTimestamp(object.last_updated_at)
          : undefined,
      id: isSet(object.id) ? globalThis.String(object.id) : '',
      storagePath: isSet(object.storagePath)
        ? globalThis.String(object.storagePath)
        : isSet(object.storage_path)
          ? globalThis.String(object.storage_path)
          : '',
      mimeType: isSet(object.mimeType)
        ? uploadedMediaMimeTypeFromJSON(object.mimeType)
        : isSet(object.mime_type)
          ? uploadedMediaMimeTypeFromJSON(object.mime_type)
          : 0,
      createdByUser: isSet(object.createdByUser)
        ? globalThis.String(object.createdByUser)
        : isSet(object.created_by_user)
          ? globalThis.String(object.created_by_user)
          : '',
    };
  },

  toJSON(message: UploadedMedia): unknown {
    const obj: any = {};
    if (message.createdAt !== undefined) {
      obj.createdAt = message.createdAt.toISOString();
    }
    if (message.archivedAt !== undefined) {
      obj.archivedAt = message.archivedAt.toISOString();
    }
    if (message.lastUpdatedAt !== undefined) {
      obj.lastUpdatedAt = message.lastUpdatedAt.toISOString();
    }
    if (message.id !== '') {
      obj.id = message.id;
    }
    if (message.storagePath !== '') {
      obj.storagePath = message.storagePath;
    }
    if (message.mimeType !== 0) {
      obj.mimeType = uploadedMediaMimeTypeToJSON(message.mimeType);
    }
    if (message.createdByUser !== '') {
      obj.createdByUser = message.createdByUser;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UploadedMedia>, I>>(base?: I): UploadedMedia {
    return UploadedMedia.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UploadedMedia>, I>>(object: I): UploadedMedia {
    const message = createBaseUploadedMedia();
    message.createdAt = object.createdAt ?? undefined;
    message.archivedAt = object.archivedAt ?? undefined;
    message.lastUpdatedAt = object.lastUpdatedAt ?? undefined;
    message.id = object.id ?? '';
    message.storagePath = object.storagePath ?? '';
    message.mimeType = object.mimeType ?? 0;
    message.createdByUser = object.createdByUser ?? '';
    return message;
  },
};

function createBaseUploadedMediaCreationRequestInput(): UploadedMediaCreationRequestInput {
  return { storagePath: '', mimeType: 0 };
}

export const UploadedMediaCreationRequestInput: MessageFns<UploadedMediaCreationRequestInput> = {
  encode(message: UploadedMediaCreationRequestInput, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.storagePath !== '') {
      writer.uint32(10).string(message.storagePath);
    }
    if (message.mimeType !== 0) {
      writer.uint32(16).int32(message.mimeType);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UploadedMediaCreationRequestInput {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUploadedMediaCreationRequestInput();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.storagePath = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.mimeType = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UploadedMediaCreationRequestInput {
    return {
      storagePath: isSet(object.storagePath)
        ? globalThis.String(object.storagePath)
        : isSet(object.storage_path)
          ? globalThis.String(object.storage_path)
          : '',
      mimeType: isSet(object.mimeType)
        ? uploadedMediaMimeTypeFromJSON(object.mimeType)
        : isSet(object.mime_type)
          ? uploadedMediaMimeTypeFromJSON(object.mime_type)
          : 0,
    };
  },

  toJSON(message: UploadedMediaCreationRequestInput): unknown {
    const obj: any = {};
    if (message.storagePath !== '') {
      obj.storagePath = message.storagePath;
    }
    if (message.mimeType !== 0) {
      obj.mimeType = uploadedMediaMimeTypeToJSON(message.mimeType);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UploadedMediaCreationRequestInput>, I>>(
    base?: I,
  ): UploadedMediaCreationRequestInput {
    return UploadedMediaCreationRequestInput.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UploadedMediaCreationRequestInput>, I>>(
    object: I,
  ): UploadedMediaCreationRequestInput {
    const message = createBaseUploadedMediaCreationRequestInput();
    message.storagePath = object.storagePath ?? '';
    message.mimeType = object.mimeType ?? 0;
    return message;
  },
};

function createBaseUploadedMediaUpdateRequestInput(): UploadedMediaUpdateRequestInput {
  return { storagePath: undefined, mimeType: undefined };
}

export const UploadedMediaUpdateRequestInput: MessageFns<UploadedMediaUpdateRequestInput> = {
  encode(message: UploadedMediaUpdateRequestInput, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.storagePath !== undefined) {
      writer.uint32(10).string(message.storagePath);
    }
    if (message.mimeType !== undefined) {
      writer.uint32(16).int32(message.mimeType);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UploadedMediaUpdateRequestInput {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUploadedMediaUpdateRequestInput();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.storagePath = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.mimeType = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UploadedMediaUpdateRequestInput {
    return {
      storagePath: isSet(object.storagePath)
        ? globalThis.String(object.storagePath)
        : isSet(object.storage_path)
          ? globalThis.String(object.storage_path)
          : undefined,
      mimeType: isSet(object.mimeType)
        ? uploadedMediaMimeTypeFromJSON(object.mimeType)
        : isSet(object.mime_type)
          ? uploadedMediaMimeTypeFromJSON(object.mime_type)
          : undefined,
    };
  },

  toJSON(message: UploadedMediaUpdateRequestInput): unknown {
    const obj: any = {};
    if (message.storagePath !== undefined) {
      obj.storagePath = message.storagePath;
    }
    if (message.mimeType !== undefined) {
      obj.mimeType = uploadedMediaMimeTypeToJSON(message.mimeType);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UploadedMediaUpdateRequestInput>, I>>(base?: I): UploadedMediaUpdateRequestInput {
    return UploadedMediaUpdateRequestInput.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UploadedMediaUpdateRequestInput>, I>>(
    object: I,
  ): UploadedMediaUpdateRequestInput {
    const message = createBaseUploadedMediaUpdateRequestInput();
    message.storagePath = object.storagePath ?? undefined;
    message.mimeType = object.mimeType ?? undefined;
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from(globalThis.Buffer.from(b64, 'base64'));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return globalThis.Buffer.from(arr).toString('base64');
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(''));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends {}
        ? { [K in keyof T]?: DeepPartial<T[K]> }
        : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === 'string') {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error('Value is larger than Number.MAX_SAFE_INTEGER');
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error('Value is smaller than Number.MIN_SAFE_INTEGER');
  }
  return num;
}

function isObject(value: any): boolean {
  return typeof value === 'object' && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
