{
 "title": "Prixfixe Server Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "memory use",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "prixfixe_server_heap_alloc", "legendFormat": "heap alloc" }
   ]
  },
  {
   "title": "Counts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prixfixe_server_valid_instruments_count",
     "legendFormat": "valid instruments"
    },
    {
     "expr": "prixfixe_server_valid_ingredients_count",
     "legendFormat": "valid ingredients"
    },
    {
     "expr": "prixfixe_server_valid_ingredient_tags_count",
     "legendFormat": "valid ingredient tags"
    },
    {
     "expr": "prixfixe_server_ingredient_tag_mappings_count",
     "legendFormat": "ingredient tag mappings"
    },
    {
     "expr": "prixfixe_server_valid_preparations_count",
     "legendFormat": "valid preparations"
    },
    {
     "expr": "prixfixe_server_required_preparation_instruments_count",
     "legendFormat": "required preparation instruments"
    },
    {
     "expr": "prixfixe_server_valid_ingredient_preparations_count",
     "legendFormat": "valid ingredient preparations"
    },
    { "expr": "prixfixe_server_recipes_count", "legendFormat": "recipes" },
    {
     "expr": "prixfixe_server_recipe_tags_count",
     "legendFormat": "recipe tags"
    },
    {
     "expr": "prixfixe_server_recipe_steps_count",
     "legendFormat": "recipe steps"
    },
    {
     "expr": "prixfixe_server_recipe_step_preparations_count",
     "legendFormat": "recipe step preparations"
    },
    {
     "expr": "prixfixe_server_recipe_step_ingredients_count",
     "legendFormat": "recipe step ingredients"
    },
    {
     "expr": "prixfixe_server_recipe_iterations_count",
     "legendFormat": "recipe iterations"
    },
    {
     "expr": "prixfixe_server_recipe_iteration_steps_count",
     "legendFormat": "recipe iteration steps"
    },
    {
     "expr": "prixfixe_server_iteration_medias_count",
     "legendFormat": "iteration medias"
    },
    {
     "expr": "prixfixe_server_invitations_count",
     "legendFormat": "invitations"
    },
    { "expr": "prixfixe_server_reports_count", "legendFormat": "reports" },
    {
     "expr": "prixfixe_server_oauth2_clients_count",
     "legendFormat": "oauth2 clients"
    },
    { "expr": "prixfixe_server_users_count", "legendFormat": "users" },
    { "expr": "prixfixe_server_webhooks_count", "legendFormat": "webhooks" }
   ]
  },
  {
   "title": "time spent collecting metrics ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "prixfixe_server_metrics_aggregation_time",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Request Latency Quantiles",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "ms", "label": "Latency" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(prixfixe_server_opencensus_io_http_server_latency_bucket[5m])) by (job, le))",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(prixfixe_server_opencensus_io_http_server_latency_bucket[5m])) by (job, le))",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(prixfixe_server_opencensus_io_http_server_latency_bucket[5m])) by (job, le))",
     "legendFormat": "90th percentile"
    }
   ]
  },
  {
   "title": "next gc size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "prixfixe_server_next_gc",
     "legendFormat": "target heap size of the next GC cycle"
    }
   ]
  },
  {
   "title": "Request Count by Method",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(prixfixe_server_opencensus_io_http_server_request_count_by_method) by (http_method)",
     "legendFormat": "{{ http_method }}"
    }
   ]
  },
  {
   "title": "GC CPU%",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "percentunit", "label": "% of CPU used by gc" }
   ],
   "targets": [
    {
     "expr": "prixfixe_server_gc_cpu_fraction",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Response Codes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prixfixe_server_opencensus_io_http_server_response_count_by_status_code",
     "legendFormat": "{{ http_status }}"
    }
   ]
  }
 ]
}