# Per-service database password for the queue_test cronjob
- op: add
  path: "/spec/jobTemplate/spec/template/spec/containers/0/env/-"
  value:
    name: DINNER_DONE_BETTER_DATABASE_READ_CONNECTION_PASSWORD
    valueFrom:
      secretKeyRef:
        name: api-service-config
        key: DATABASE_QUEUE_TEST_PASSWORD
- op: add
  path: "/spec/jobTemplate/spec/template/spec/containers/0/env/-"
  value:
    name: DINNER_DONE_BETTER_DATABASE_WRITE_CONNECTION_PASSWORD
    valueFrom:
      secretKeyRef:
        name: api-service-config
        key: DATABASE_QUEUE_TEST_PASSWORD
