# Per-service database password for the db_cleaner cronjob
- op: add
  path: "/spec/jobTemplate/spec/template/spec/containers/0/env/-"
  value:
    name: DINNER_DONE_BETTER_DATABASE_READ_CONNECTION_PASSWORD
    valueFrom:
      secretKeyRef:
        name: api-service-config
        key: DATABASE_DB_CLEANER_PASSWORD
- op: add
  path: "/spec/jobTemplate/spec/template/spec/containers/0/env/-"
  value:
    name: DINNER_DONE_BETTER_DATABASE_WRITE_CONNECTION_PASSWORD
    valueFrom:
      secretKeyRef:
        name: api-service-config
        key: DATABASE_DB_CLEANER_PASSWORD
