# Per-service database password for the meal_plan_finalizer cronjob
- op: add
  path: "/spec/jobTemplate/spec/template/spec/containers/0/env/-"
  value:
    name: DINNER_DONE_BETTER_DATABASE_READ_CONNECTION_PASSWORD
    valueFrom:
      secretKeyRef:
        name: api-service-config
        key: DATABASE_MEAL_PLAN_FINALIZER_PASSWORD
- op: add
  path: "/spec/jobTemplate/spec/template/spec/containers/0/env/-"
  value:
    name: DINNER_DONE_BETTER_DATABASE_WRITE_CONNECTION_PASSWORD
    valueFrom:
      secretKeyRef:
        name: api-service-config
        key: DATABASE_MEAL_PLAN_FINALIZER_PASSWORD
