# Tracing span collection probability - explicitly set so it can be overridden in k8s without redeploying
- op: add
  path: "/spec/template/spec/containers/0/env/-"
  value:
    name: DINNER_DONE_BETTER_OBSERVABILITY_TRACING_TRACING_SPAN_COLLECTION_PROBABILITY
    value: "1"
