# Per-service database password for the async message handler deployment
- op: add
  path: "/spec/template/spec/containers/0/env/-"
  value:
    name: DINNER_DONE_BETTER_DATABASE_READ_CONNECTION_PASSWORD
    valueFrom:
      secretKeyRef:
        name: api-service-config
        key: DATABASE_ASYNC_MESSAGE_HANDLER_PASSWORD
- op: add
  path: "/spec/template/spec/containers/0/env/-"
  value:
    name: DINNER_DONE_BETTER_DATABASE_WRITE_CONNECTION_PASSWORD
    valueFrom:
      secretKeyRef:
        name: api-service-config
        key: DATABASE_ASYNC_MESSAGE_HANDLER_PASSWORD
