---
# Attach BackendConfig to gRPC port so health checks use HTTP port 8000
apiVersion: v1
kind: Service
metadata:
  name: dinner-done-better-api-svc
  annotations:
    cloud.google.com/backend-config: '{"ports": {"8001": "api-grpc-backendconfig"}}'
---