// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v6.33.1
// source: internal_ops/internal_ops_service_types.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from '@bufbuild/protobuf/wire';
import { ResponseDetails } from '../common';

export const protobufPackage = 'internalops';

export interface TestQueueMessageRequest {
  queueName: string;
}

export interface TestQueueMessageResponse {
  responseDetails: ResponseDetails | undefined;
  success: boolean;
  testId: string;
  roundTripMs: number;
}

function createBaseTestQueueMessageRequest(): TestQueueMessageRequest {
  return { queueName: '' };
}

export const TestQueueMessageRequest: MessageFns<TestQueueMessageRequest> = {
  encode(message: TestQueueMessageRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.queueName !== '') {
      writer.uint32(10).string(message.queueName);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TestQueueMessageRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTestQueueMessageRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.queueName = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TestQueueMessageRequest {
    return {
      queueName: isSet(object.queueName)
        ? globalThis.String(object.queueName)
        : isSet(object.queue_name)
          ? globalThis.String(object.queue_name)
          : '',
    };
  },

  toJSON(message: TestQueueMessageRequest): unknown {
    const obj: any = {};
    if (message.queueName !== '') {
      obj.queueName = message.queueName;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TestQueueMessageRequest>, I>>(base?: I): TestQueueMessageRequest {
    return TestQueueMessageRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TestQueueMessageRequest>, I>>(object: I): TestQueueMessageRequest {
    const message = createBaseTestQueueMessageRequest();
    message.queueName = object.queueName ?? '';
    return message;
  },
};

function createBaseTestQueueMessageResponse(): TestQueueMessageResponse {
  return { responseDetails: undefined, success: false, testId: '', roundTripMs: 0 };
}

export const TestQueueMessageResponse: MessageFns<TestQueueMessageResponse> = {
  encode(message: TestQueueMessageResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.responseDetails !== undefined) {
      ResponseDetails.encode(message.responseDetails, writer.uint32(10).fork()).join();
    }
    if (message.success !== false) {
      writer.uint32(16).bool(message.success);
    }
    if (message.testId !== '') {
      writer.uint32(26).string(message.testId);
    }
    if (message.roundTripMs !== 0) {
      writer.uint32(32).int64(message.roundTripMs);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TestQueueMessageResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTestQueueMessageResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.responseDetails = ResponseDetails.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.testId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.roundTripMs = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TestQueueMessageResponse {
    return {
      responseDetails: isSet(object.responseDetails)
        ? ResponseDetails.fromJSON(object.responseDetails)
        : isSet(object.response_details)
          ? ResponseDetails.fromJSON(object.response_details)
          : undefined,
      success: isSet(object.success) ? globalThis.Boolean(object.success) : false,
      testId: isSet(object.testId)
        ? globalThis.String(object.testId)
        : isSet(object.test_id)
          ? globalThis.String(object.test_id)
          : '',
      roundTripMs: isSet(object.roundTripMs)
        ? globalThis.Number(object.roundTripMs)
        : isSet(object.round_trip_ms)
          ? globalThis.Number(object.round_trip_ms)
          : 0,
    };
  },

  toJSON(message: TestQueueMessageResponse): unknown {
    const obj: any = {};
    if (message.responseDetails !== undefined) {
      obj.responseDetails = ResponseDetails.toJSON(message.responseDetails);
    }
    if (message.success !== false) {
      obj.success = message.success;
    }
    if (message.testId !== '') {
      obj.testId = message.testId;
    }
    if (message.roundTripMs !== 0) {
      obj.roundTripMs = Math.round(message.roundTripMs);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TestQueueMessageResponse>, I>>(base?: I): TestQueueMessageResponse {
    return TestQueueMessageResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TestQueueMessageResponse>, I>>(object: I): TestQueueMessageResponse {
    const message = createBaseTestQueueMessageResponse();
    message.responseDetails =
      object.responseDetails !== undefined && object.responseDetails !== null
        ? ResponseDetails.fromPartial(object.responseDetails)
        : undefined;
    message.success = object.success ?? false;
    message.testId = object.testId ?? '';
    message.roundTripMs = object.roundTripMs ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends {}
        ? { [K in keyof T]?: DeepPartial<T[K]> }
        : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error('Value is larger than Number.MAX_SAFE_INTEGER');
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error('Value is smaller than Number.MIN_SAFE_INTEGER');
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
