// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v6.33.1
// source: internal_ops/internal_ops_service.proto

/* eslint-disable */
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from '@grpc/grpc-js';
import { TestQueueMessageRequest, TestQueueMessageResponse } from './internal_ops_service_types';

export const protobufPackage = 'internalops';

export type InternalOperationsService = typeof InternalOperationsService;
export const InternalOperationsService = {
  testQueueMessage: {
    path: '/internalops.InternalOperations/TestQueueMessage' as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: TestQueueMessageRequest): Buffer =>
      Buffer.from(TestQueueMessageRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): TestQueueMessageRequest => TestQueueMessageRequest.decode(value),
    responseSerialize: (value: TestQueueMessageResponse): Buffer =>
      Buffer.from(TestQueueMessageResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): TestQueueMessageResponse => TestQueueMessageResponse.decode(value),
  },
} as const;

export interface InternalOperationsServer extends UntypedServiceImplementation {
  testQueueMessage: handleUnaryCall<TestQueueMessageRequest, TestQueueMessageResponse>;
}

export interface InternalOperationsClient extends Client {
  testQueueMessage(
    request: TestQueueMessageRequest,
    callback: (error: ServiceError | null, response: TestQueueMessageResponse) => void,
  ): ClientUnaryCall;
  testQueueMessage(
    request: TestQueueMessageRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: TestQueueMessageResponse) => void,
  ): ClientUnaryCall;
  testQueueMessage(
    request: TestQueueMessageRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: TestQueueMessageResponse) => void,
  ): ClientUnaryCall;
}

export const InternalOperationsClient = makeGenericClientConstructor(
  InternalOperationsService,
  'internalops.InternalOperations',
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): InternalOperationsClient;
  service: typeof InternalOperationsService;
  serviceName: string;
};
