package mealplanning

type Repository interface {
	MealDataManager
	MealPlanDataManager
	MealPlanEventDataManager
	MealPlanGroceryListItemDataManager
	MealPlanOptionDataManager
	MealPlanOptionVoteDataManager
	MealPlanTaskDataManager
	MealPlanningDataManager
	RecipeDataManager
	RecipeManagementDataManager
	RecipeMediaDataManager
	RecipePrepTaskDataManager
	RecipeRatingDataManager
	RecipeStepDataManager
	RecipeStepCompletionConditionDataManager
	RecipeStepIngredientDataManager
	RecipeStepVesselDataManager
	RecipeStepProductDataManager
	RecipeStepInstrumentDataManager
	UserIngredientPreferenceDataManager
}
