package authorization

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestAuthorizations(T *testing.T) {
	T.Parallel()

	T.Run("service user", func(t *testing.T) {
		t.Parallel()

		assert.False(t, CanCreateValidInstruments(serviceUserRoleName))
		assert.False(t, CanSeeValidInstruments(serviceUserRoleName))
		assert.False(t, CanSearchValidInstruments(serviceUserRoleName))
		assert.False(t, CanUpdateValidInstruments(serviceUserRoleName))
		assert.False(t, CanDeleteValidInstruments(serviceUserRoleName))
		assert.False(t, CanCreateValidPreparations(serviceUserRoleName))
		assert.False(t, CanSeeValidPreparations(serviceUserRoleName))
		assert.False(t, CanSearchValidPreparations(serviceUserRoleName))
		assert.False(t, CanUpdateValidPreparations(serviceUserRoleName))
		assert.False(t, CanDeleteValidPreparations(serviceUserRoleName))
		assert.False(t, CanCreateValidIngredients(serviceUserRoleName))
		assert.False(t, CanSeeValidIngredients(serviceUserRoleName))
		assert.False(t, CanSearchValidIngredients(serviceUserRoleName))
		assert.False(t, CanUpdateValidIngredients(serviceUserRoleName))
		assert.False(t, CanDeleteValidIngredients(serviceUserRoleName))
		assert.False(t, CanCreateValidIngredientPreparations(serviceUserRoleName))
		assert.False(t, CanSeeValidIngredientPreparations(serviceUserRoleName))
		assert.False(t, CanUpdateValidIngredientPreparations(serviceUserRoleName))
		assert.False(t, CanDeleteValidIngredientPreparations(serviceUserRoleName))
		assert.False(t, CanCreateValidPreparationInstruments(serviceUserRoleName))
		assert.False(t, CanSeeValidPreparationInstruments(serviceUserRoleName))
		assert.False(t, CanUpdateValidPreparationInstruments(serviceUserRoleName))
		assert.False(t, CanDeleteValidPreparationInstruments(serviceUserRoleName))
		assert.False(t, CanCreateRecipes(serviceUserRoleName))
		assert.False(t, CanSeeRecipes(serviceUserRoleName))
		assert.False(t, CanUpdateRecipes(serviceUserRoleName))
		assert.False(t, CanDeleteRecipes(serviceUserRoleName))
		assert.False(t, CanCreateRecipeSteps(serviceUserRoleName))
		assert.False(t, CanSeeRecipeSteps(serviceUserRoleName))
		assert.False(t, CanUpdateRecipeSteps(serviceUserRoleName))
		assert.False(t, CanDeleteRecipeSteps(serviceUserRoleName))
		assert.False(t, CanCreateRecipeStepIngredients(serviceUserRoleName))
		assert.False(t, CanSeeRecipeStepIngredients(serviceUserRoleName))
		assert.False(t, CanUpdateRecipeStepIngredients(serviceUserRoleName))
		assert.False(t, CanDeleteRecipeStepIngredients(serviceUserRoleName))
		assert.False(t, CanCreateRecipeStepProducts(serviceUserRoleName))
		assert.False(t, CanSeeRecipeStepProducts(serviceUserRoleName))
		assert.False(t, CanUpdateRecipeStepProducts(serviceUserRoleName))
		assert.False(t, CanDeleteRecipeStepProducts(serviceUserRoleName))
		assert.False(t, CanCreateInvitations(serviceUserRoleName))
		assert.False(t, CanSeeInvitations(serviceUserRoleName))
		assert.False(t, CanUpdateInvitations(serviceUserRoleName))
		assert.False(t, CanDeleteInvitations(serviceUserRoleName))
		assert.False(t, CanCreateReports(serviceUserRoleName))
		assert.False(t, CanSeeReports(serviceUserRoleName))
		assert.False(t, CanUpdateReports(serviceUserRoleName))
		assert.False(t, CanDeleteReports(serviceUserRoleName))
	})

	T.Run("service admin", func(t *testing.T) {
		t.Parallel()

		assert.True(t, CanCreateValidInstruments(serviceAdminRoleName))
		assert.True(t, CanSeeValidInstruments(serviceAdminRoleName))
		assert.True(t, CanSearchValidInstruments(serviceAdminRoleName))
		assert.True(t, CanUpdateValidInstruments(serviceAdminRoleName))
		assert.True(t, CanDeleteValidInstruments(serviceAdminRoleName))
		assert.True(t, CanCreateValidPreparations(serviceAdminRoleName))
		assert.True(t, CanSeeValidPreparations(serviceAdminRoleName))
		assert.True(t, CanSearchValidPreparations(serviceAdminRoleName))
		assert.True(t, CanUpdateValidPreparations(serviceAdminRoleName))
		assert.True(t, CanDeleteValidPreparations(serviceAdminRoleName))
		assert.True(t, CanCreateValidIngredients(serviceAdminRoleName))
		assert.True(t, CanSeeValidIngredients(serviceAdminRoleName))
		assert.True(t, CanSearchValidIngredients(serviceAdminRoleName))
		assert.True(t, CanUpdateValidIngredients(serviceAdminRoleName))
		assert.True(t, CanDeleteValidIngredients(serviceAdminRoleName))
		assert.True(t, CanCreateValidIngredientPreparations(serviceAdminRoleName))
		assert.True(t, CanSeeValidIngredientPreparations(serviceAdminRoleName))
		assert.True(t, CanUpdateValidIngredientPreparations(serviceAdminRoleName))
		assert.True(t, CanDeleteValidIngredientPreparations(serviceAdminRoleName))
		assert.True(t, CanCreateValidPreparationInstruments(serviceAdminRoleName))
		assert.True(t, CanSeeValidPreparationInstruments(serviceAdminRoleName))
		assert.True(t, CanUpdateValidPreparationInstruments(serviceAdminRoleName))
		assert.True(t, CanDeleteValidPreparationInstruments(serviceAdminRoleName))
		assert.True(t, CanCreateRecipes(serviceAdminRoleName))
		assert.True(t, CanSeeRecipes(serviceAdminRoleName))
		assert.True(t, CanUpdateRecipes(serviceAdminRoleName))
		assert.True(t, CanDeleteRecipes(serviceAdminRoleName))
		assert.True(t, CanCreateRecipeSteps(serviceAdminRoleName))
		assert.True(t, CanSeeRecipeSteps(serviceAdminRoleName))
		assert.True(t, CanUpdateRecipeSteps(serviceAdminRoleName))
		assert.True(t, CanDeleteRecipeSteps(serviceAdminRoleName))
		assert.True(t, CanCreateRecipeStepIngredients(serviceAdminRoleName))
		assert.True(t, CanSeeRecipeStepIngredients(serviceAdminRoleName))
		assert.True(t, CanUpdateRecipeStepIngredients(serviceAdminRoleName))
		assert.True(t, CanDeleteRecipeStepIngredients(serviceAdminRoleName))
		assert.True(t, CanCreateRecipeStepProducts(serviceAdminRoleName))
		assert.True(t, CanSeeRecipeStepProducts(serviceAdminRoleName))
		assert.True(t, CanUpdateRecipeStepProducts(serviceAdminRoleName))
		assert.True(t, CanDeleteRecipeStepProducts(serviceAdminRoleName))
		assert.True(t, CanCreateInvitations(serviceAdminRoleName))
		assert.True(t, CanSeeInvitations(serviceAdminRoleName))
		assert.True(t, CanUpdateInvitations(serviceAdminRoleName))
		assert.True(t, CanDeleteInvitations(serviceAdminRoleName))
		assert.True(t, CanCreateReports(serviceAdminRoleName))
		assert.True(t, CanSeeReports(serviceAdminRoleName))
		assert.True(t, CanUpdateReports(serviceAdminRoleName))
		assert.True(t, CanDeleteReports(serviceAdminRoleName))
	})

	T.Run("household admin", func(t *testing.T) {
		t.Parallel()

		assert.True(t, CanCreateValidInstruments(householdAdminRoleName))
		assert.True(t, CanSeeValidInstruments(householdAdminRoleName))
		assert.True(t, CanSearchValidInstruments(householdAdminRoleName))
		assert.True(t, CanUpdateValidInstruments(householdAdminRoleName))
		assert.True(t, CanDeleteValidInstruments(householdAdminRoleName))
		assert.True(t, CanCreateValidPreparations(householdAdminRoleName))
		assert.True(t, CanSeeValidPreparations(householdAdminRoleName))
		assert.True(t, CanSearchValidPreparations(householdAdminRoleName))
		assert.True(t, CanUpdateValidPreparations(householdAdminRoleName))
		assert.True(t, CanDeleteValidPreparations(householdAdminRoleName))
		assert.True(t, CanCreateValidIngredients(householdAdminRoleName))
		assert.True(t, CanSeeValidIngredients(householdAdminRoleName))
		assert.True(t, CanSearchValidIngredients(householdAdminRoleName))
		assert.True(t, CanUpdateValidIngredients(householdAdminRoleName))
		assert.True(t, CanDeleteValidIngredients(householdAdminRoleName))
		assert.True(t, CanCreateValidIngredientPreparations(householdAdminRoleName))
		assert.True(t, CanSeeValidIngredientPreparations(householdAdminRoleName))
		assert.True(t, CanUpdateValidIngredientPreparations(householdAdminRoleName))
		assert.True(t, CanDeleteValidIngredientPreparations(householdAdminRoleName))
		assert.True(t, CanCreateValidPreparationInstruments(householdAdminRoleName))
		assert.True(t, CanSeeValidPreparationInstruments(householdAdminRoleName))
		assert.True(t, CanUpdateValidPreparationInstruments(householdAdminRoleName))
		assert.True(t, CanDeleteValidPreparationInstruments(householdAdminRoleName))
		assert.True(t, CanCreateRecipes(householdAdminRoleName))
		assert.True(t, CanSeeRecipes(householdAdminRoleName))
		assert.True(t, CanUpdateRecipes(householdAdminRoleName))
		assert.True(t, CanDeleteRecipes(householdAdminRoleName))
		assert.True(t, CanCreateRecipeSteps(householdAdminRoleName))
		assert.True(t, CanSeeRecipeSteps(householdAdminRoleName))
		assert.True(t, CanUpdateRecipeSteps(householdAdminRoleName))
		assert.True(t, CanDeleteRecipeSteps(householdAdminRoleName))
		assert.True(t, CanCreateRecipeStepIngredients(householdAdminRoleName))
		assert.True(t, CanSeeRecipeStepIngredients(householdAdminRoleName))
		assert.True(t, CanUpdateRecipeStepIngredients(householdAdminRoleName))
		assert.True(t, CanDeleteRecipeStepIngredients(householdAdminRoleName))
		assert.True(t, CanCreateRecipeStepProducts(householdAdminRoleName))
		assert.True(t, CanSeeRecipeStepProducts(householdAdminRoleName))
		assert.True(t, CanUpdateRecipeStepProducts(householdAdminRoleName))
		assert.True(t, CanDeleteRecipeStepProducts(householdAdminRoleName))
		assert.True(t, CanCreateInvitations(householdAdminRoleName))
		assert.True(t, CanSeeInvitations(householdAdminRoleName))
		assert.True(t, CanUpdateInvitations(householdAdminRoleName))
		assert.True(t, CanDeleteInvitations(householdAdminRoleName))
		assert.True(t, CanCreateReports(householdAdminRoleName))
		assert.True(t, CanSeeReports(householdAdminRoleName))
		assert.True(t, CanUpdateReports(householdAdminRoleName))
		assert.True(t, CanDeleteReports(householdAdminRoleName))
	})

	T.Run("household member", func(t *testing.T) {
		t.Parallel()

		assert.True(t, CanCreateValidInstruments(householdMemberRoleName))
		assert.True(t, CanSeeValidInstruments(householdMemberRoleName))
		assert.True(t, CanSearchValidInstruments(householdMemberRoleName))
		assert.True(t, CanUpdateValidInstruments(householdMemberRoleName))
		assert.True(t, CanDeleteValidInstruments(householdMemberRoleName))
		assert.True(t, CanCreateValidPreparations(householdMemberRoleName))
		assert.True(t, CanSeeValidPreparations(householdMemberRoleName))
		assert.True(t, CanSearchValidPreparations(householdMemberRoleName))
		assert.True(t, CanUpdateValidPreparations(householdMemberRoleName))
		assert.True(t, CanDeleteValidPreparations(householdMemberRoleName))
		assert.True(t, CanCreateValidIngredients(householdMemberRoleName))
		assert.True(t, CanSeeValidIngredients(householdMemberRoleName))
		assert.True(t, CanSearchValidIngredients(householdMemberRoleName))
		assert.True(t, CanUpdateValidIngredients(householdMemberRoleName))
		assert.True(t, CanDeleteValidIngredients(householdMemberRoleName))
		assert.True(t, CanCreateValidIngredientPreparations(householdMemberRoleName))
		assert.True(t, CanSeeValidIngredientPreparations(householdMemberRoleName))
		assert.True(t, CanUpdateValidIngredientPreparations(householdMemberRoleName))
		assert.True(t, CanDeleteValidIngredientPreparations(householdMemberRoleName))
		assert.True(t, CanCreateValidPreparationInstruments(householdMemberRoleName))
		assert.True(t, CanSeeValidPreparationInstruments(householdMemberRoleName))
		assert.True(t, CanUpdateValidPreparationInstruments(householdMemberRoleName))
		assert.True(t, CanDeleteValidPreparationInstruments(householdMemberRoleName))
		assert.True(t, CanCreateRecipes(householdMemberRoleName))
		assert.True(t, CanSeeRecipes(householdMemberRoleName))
		assert.True(t, CanUpdateRecipes(householdMemberRoleName))
		assert.True(t, CanDeleteRecipes(householdMemberRoleName))
		assert.True(t, CanCreateRecipeSteps(householdMemberRoleName))
		assert.True(t, CanSeeRecipeSteps(householdMemberRoleName))
		assert.True(t, CanUpdateRecipeSteps(householdMemberRoleName))
		assert.True(t, CanDeleteRecipeSteps(householdMemberRoleName))
		assert.True(t, CanCreateRecipeStepIngredients(householdMemberRoleName))
		assert.True(t, CanSeeRecipeStepIngredients(householdMemberRoleName))
		assert.True(t, CanUpdateRecipeStepIngredients(householdMemberRoleName))
		assert.True(t, CanDeleteRecipeStepIngredients(householdMemberRoleName))
		assert.True(t, CanCreateRecipeStepProducts(householdMemberRoleName))
		assert.True(t, CanSeeRecipeStepProducts(householdMemberRoleName))
		assert.True(t, CanUpdateRecipeStepProducts(householdMemberRoleName))
		assert.True(t, CanDeleteRecipeStepProducts(householdMemberRoleName))
		assert.True(t, CanCreateInvitations(householdMemberRoleName))
		assert.True(t, CanSeeInvitations(householdMemberRoleName))
		assert.True(t, CanUpdateInvitations(householdMemberRoleName))
		assert.True(t, CanDeleteInvitations(householdMemberRoleName))
		assert.True(t, CanCreateReports(householdMemberRoleName))
		assert.True(t, CanSeeReports(householdMemberRoleName))
		assert.True(t, CanUpdateReports(householdMemberRoleName))
		assert.True(t, CanDeleteReports(householdMemberRoleName))
	})
}
