---
# See: https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# See: https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/resource/
resources:
  - namespace.yaml
  - ../../../kustomize/components/api_server
  - ../../../kustomize/components/workers

# See: https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/patches/
patches: []

labels:
  - pairs:
      app.kubernetes.io/name: dinner-done-better-backend
      deployed_by: skaffold

configMapGenerator:
  - name: dinner-done-better-service-api-config
    namespace: localdev
    files:
      - config.json=configs/api_service_config.json

  - name: dinner-done-better-job-db-cleaner-config
    namespace: localdev
    files:
      - config.json=configs/job_db_cleaner_config.json

  - name: dinner-done-better-job-meal-plan-finalizer-config
    namespace: localdev
    files:
      - config.json=configs/job_meal_plan_finalizer_config.json

  - name: dinner-done-better-job-meal-plan-grocery-list-init-config
    namespace: localdev
    files:
      - config.json=configs/job_meal_plan_grocery_list_initializer_config.json

  - name: dinner-done-better-job-meal-plan-task-creator-config
    namespace: localdev
    files:
      - config.json=configs/job_meal_plan_task_creator_config.json

  - name: dinner-done-better-job-search-data-index-scheduler-config
    namespace: localdev
    files:
      - config.json=configs/job_search_data_index_scheduler_config.json

generatorOptions:
  disableNameSuffixHash: true
  labels:
    generated_by: skaffold
    deployed_by: skaffold
  annotations:
    generated_by: skaffold
    deployed_by: skaffold
