---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: dinner-done-better-cronjob-meal-plan-finalizer
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: meal-plan-finalizer
            image: dinner-done-better-cronjob-meal-plan-finalizer
            imagePullPolicy: IfNotPresent
            env:
              - name: "CONFIGURATION_FILEPATH"
                value: "/etc/service-config.json"
              - name: "DINNER_DONE_BETTER_DATA_CHANGES_TOPIC_NAME"
                value: "data_changes"
            volumeMounts:
            - name: "config"
              mountPath: "/etc/service-config.json"
              subPath: "config.json"
            - name: logs
              mountPath: /var/log/dinnerdonebetter
          restartPolicy: OnFailure
          volumes:
            - name: "config"
              configMap:
                name: "dinner-done-better-cronjob-meal-plan-finalizer-config"
            # this volume is where we write logs to, and where we read logs from in the collector.
            - name: logs
              emptyDir:
                sizeLimit: 500Mi
---
