---
receivers:
  otlp:
    protocols:
      http:
        endpoint: "0.0.0.0:4318"
      grpc:
        endpoint: "0.0.0.0:4317"

exporters:
  debug:

  # metrics
  prometheus:
    endpoint: "0.0.0.0:8889"

  # tracing
  otlp:
    endpoint: jaeger:4317
    tls:
      insecure: true

  # logs
  otlphttp:
    endpoint: http://loki:3100/otlp

processors:
  batch:

  resource:
    attributes:
      - action: insert
        key: service_name
        from_attribute: service.name

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
    logs:
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [otlphttp]
