version: "3.8"
services:
  # worker_queue:
  #   logging:
  #     driver: none
  #   hostname: worker_queue
  #   image: redis:7-bullseye
  #   container_name: redis
  #   ports:
  #     - '6379:6379'
  #   command: [ "redis-server", "--cluster-enabled yes" ]
  postgres:
      hostname: "pgdatabase"
      container_name: "database"
      image: postgres:17
      environment:
          POSTGRES_DB: 'dinner-done-better'
          POSTGRES_PASSWORD: 'hunter2'
          POSTGRES_USER: 'dbuser'
      logging:
          driver: none
      ports:
          - '5432:5432'
  api_server:
    container_name: "api_server"
    links:
      - postgres
    environment:
      USE_NOOP_LOGGER: 'nope'
      CONFIGURATION_FILEPATH: '/etc/config'
    ports:
      - '8000:8000'
    build:
      dockerfile: '../server.Dockerfile'
    volumes:
      - source: '../config_files/service-config.json'
        target: '/etc/config'
        type: 'bind'
      - source: '../../'
        target: '/go/src/github.com/dinnerdonebetter/backend'
        type: 'bind'