---
# See: https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# See: https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/resource/
resources:
  - namespace.yaml
  - external_dns.yaml
  - ingress.yaml
  - otel_collector.yaml
  - cert_issuer.yaml # the LetsEncrypt definition that will issue our cert
  - cert_secret.yaml # the secret where the cert will get stored
  - certificate.yaml # the certificate request itself for the issuer to fulfill

generatorOptions:
  disableNameSuffixHash: true
  labels:
    deployed_by: skaffold
    generated_by: skaffold
  annotations:
    deployed_by: skaffold
    generated_by: skaffold

patches:
  - patch: |-
      - op: add
        path: "/spec/template/spec/containers/0/env/-"
        value:
          name: PROMETHEUS_USERNAME
          valueFrom:
            secretKeyRef:
              name: grafana-cloud-creds
              key: GRAFANA_CLOUD_PROMETHEUS_USERNAME
      - op: add
        path: "/spec/template/spec/containers/0/env/-"
        value:
          name: PROMETHEUS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: grafana-cloud-creds
              key: GRAFANA_CLOUD_PROMETHEUS_PASSWORD
      - op: add
        path: "/spec/template/spec/containers/0/env/-"
        value:
          name: LOKI_USERNAME
          valueFrom:
            secretKeyRef:
              name: grafana-cloud-creds
              key: GRAFANA_CLOUD_LOKI_USERNAME
      - op: add
        path: "/spec/template/spec/containers/0/env/-"
        value:
          name: LOKI_PASSWORD
          valueFrom:
            secretKeyRef:
              name: grafana-cloud-creds
              key: GRAFANA_CLOUD_LOKI_PASSWORD
      - op: add
        path: "/spec/template/spec/containers/0/env/-"
        value:
          name: TEMPO_USERNAME
          valueFrom:
            secretKeyRef:
              name: grafana-cloud-creds
              key: GRAFANA_CLOUD_TEMPO_USERNAME
      - op: add
        path: "/spec/template/spec/containers/0/env/-"
        value:
          name: TEMPO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: grafana-cloud-creds
              key: GRAFANA_CLOUD_TEMPO_PASSWORD
    target:
      version: v1
      kind: Deployment
      name: opentelemetry-collector

configMapGenerator:
  - name: opentelemetry-collector-config
    namespace: dev
    files:
      - config.yaml=./configs/otel_collector_config.yaml

namespace: dev
---
