# See: https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# See: https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/resource/
resources:
  # - cert_manager.yaml
  - external_dns.yaml

generatorOptions:
  disableNameSuffixHash: true
  labels:
    type: generated
  annotations:
    note: generated

namespace: dev
