// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v6.33.1
// source: filtering.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from '@bufbuild/protobuf/wire';
import { Timestamp } from './google/protobuf/timestamp';

export const protobufPackage = 'filtering';

export interface QueryFilter {
  sortBy?: string | undefined;
  createdAfter?: Date | undefined;
  createdBefore?: Date | undefined;
  updatedAfter?: Date | undefined;
  updatedBefore?: Date | undefined;
  maxResponseSize?: number | undefined;
  includeArchived?: boolean | undefined;
  cursor?: string | undefined;
}

export interface Pagination {
  maxResponseSize: number;
  filteredCount: number;
  totalCount: number;
  cursor: string;
  previousCursor: string;
  appliedQueryFilter: QueryFilter | undefined;
}

function createBaseQueryFilter(): QueryFilter {
  return {
    sortBy: undefined,
    createdAfter: undefined,
    createdBefore: undefined,
    updatedAfter: undefined,
    updatedBefore: undefined,
    maxResponseSize: undefined,
    includeArchived: undefined,
    cursor: undefined,
  };
}

export const QueryFilter: MessageFns<QueryFilter> = {
  encode(message: QueryFilter, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.sortBy !== undefined) {
      writer.uint32(10).string(message.sortBy);
    }
    if (message.createdAfter !== undefined) {
      Timestamp.encode(toTimestamp(message.createdAfter), writer.uint32(26).fork()).join();
    }
    if (message.createdBefore !== undefined) {
      Timestamp.encode(toTimestamp(message.createdBefore), writer.uint32(34).fork()).join();
    }
    if (message.updatedAfter !== undefined) {
      Timestamp.encode(toTimestamp(message.updatedAfter), writer.uint32(42).fork()).join();
    }
    if (message.updatedBefore !== undefined) {
      Timestamp.encode(toTimestamp(message.updatedBefore), writer.uint32(50).fork()).join();
    }
    if (message.maxResponseSize !== undefined) {
      writer.uint32(56).uint32(message.maxResponseSize);
    }
    if (message.includeArchived !== undefined) {
      writer.uint32(64).bool(message.includeArchived);
    }
    if (message.cursor !== undefined) {
      writer.uint32(74).string(message.cursor);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryFilter {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryFilter();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.sortBy = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.createdAfter = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.createdBefore = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.updatedAfter = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.updatedBefore = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.maxResponseSize = reader.uint32();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.includeArchived = reader.bool();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.cursor = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryFilter {
    return {
      sortBy: isSet(object.sortBy)
        ? globalThis.String(object.sortBy)
        : isSet(object.sort_by)
          ? globalThis.String(object.sort_by)
          : undefined,
      createdAfter: isSet(object.createdAfter)
        ? fromJsonTimestamp(object.createdAfter)
        : isSet(object.created_after)
          ? fromJsonTimestamp(object.created_after)
          : undefined,
      createdBefore: isSet(object.createdBefore)
        ? fromJsonTimestamp(object.createdBefore)
        : isSet(object.created_before)
          ? fromJsonTimestamp(object.created_before)
          : undefined,
      updatedAfter: isSet(object.updatedAfter)
        ? fromJsonTimestamp(object.updatedAfter)
        : isSet(object.updated_after)
          ? fromJsonTimestamp(object.updated_after)
          : undefined,
      updatedBefore: isSet(object.updatedBefore)
        ? fromJsonTimestamp(object.updatedBefore)
        : isSet(object.updated_before)
          ? fromJsonTimestamp(object.updated_before)
          : undefined,
      maxResponseSize: isSet(object.maxResponseSize)
        ? globalThis.Number(object.maxResponseSize)
        : isSet(object.max_response_size)
          ? globalThis.Number(object.max_response_size)
          : undefined,
      includeArchived: isSet(object.includeArchived)
        ? globalThis.Boolean(object.includeArchived)
        : isSet(object.include_archived)
          ? globalThis.Boolean(object.include_archived)
          : undefined,
      cursor: isSet(object.cursor) ? globalThis.String(object.cursor) : undefined,
    };
  },

  toJSON(message: QueryFilter): unknown {
    const obj: any = {};
    if (message.sortBy !== undefined) {
      obj.sortBy = message.sortBy;
    }
    if (message.createdAfter !== undefined) {
      obj.createdAfter = message.createdAfter.toISOString();
    }
    if (message.createdBefore !== undefined) {
      obj.createdBefore = message.createdBefore.toISOString();
    }
    if (message.updatedAfter !== undefined) {
      obj.updatedAfter = message.updatedAfter.toISOString();
    }
    if (message.updatedBefore !== undefined) {
      obj.updatedBefore = message.updatedBefore.toISOString();
    }
    if (message.maxResponseSize !== undefined) {
      obj.maxResponseSize = Math.round(message.maxResponseSize);
    }
    if (message.includeArchived !== undefined) {
      obj.includeArchived = message.includeArchived;
    }
    if (message.cursor !== undefined) {
      obj.cursor = message.cursor;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryFilter>, I>>(base?: I): QueryFilter {
    return QueryFilter.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryFilter>, I>>(object: I): QueryFilter {
    const message = createBaseQueryFilter();
    message.sortBy = object.sortBy ?? undefined;
    message.createdAfter = object.createdAfter ?? undefined;
    message.createdBefore = object.createdBefore ?? undefined;
    message.updatedAfter = object.updatedAfter ?? undefined;
    message.updatedBefore = object.updatedBefore ?? undefined;
    message.maxResponseSize = object.maxResponseSize ?? undefined;
    message.includeArchived = object.includeArchived ?? undefined;
    message.cursor = object.cursor ?? undefined;
    return message;
  },
};

function createBasePagination(): Pagination {
  return {
    maxResponseSize: 0,
    filteredCount: 0,
    totalCount: 0,
    cursor: '',
    previousCursor: '',
    appliedQueryFilter: undefined,
  };
}

export const Pagination: MessageFns<Pagination> = {
  encode(message: Pagination, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.maxResponseSize !== 0) {
      writer.uint32(8).uint32(message.maxResponseSize);
    }
    if (message.filteredCount !== 0) {
      writer.uint32(16).uint64(message.filteredCount);
    }
    if (message.totalCount !== 0) {
      writer.uint32(24).uint64(message.totalCount);
    }
    if (message.cursor !== '') {
      writer.uint32(34).string(message.cursor);
    }
    if (message.previousCursor !== '') {
      writer.uint32(42).string(message.previousCursor);
    }
    if (message.appliedQueryFilter !== undefined) {
      QueryFilter.encode(message.appliedQueryFilter, writer.uint32(50).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Pagination {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePagination();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.maxResponseSize = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.filteredCount = longToNumber(reader.uint64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.totalCount = longToNumber(reader.uint64());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.cursor = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.previousCursor = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.appliedQueryFilter = QueryFilter.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Pagination {
    return {
      maxResponseSize: isSet(object.maxResponseSize)
        ? globalThis.Number(object.maxResponseSize)
        : isSet(object.max_response_size)
          ? globalThis.Number(object.max_response_size)
          : 0,
      filteredCount: isSet(object.filteredCount)
        ? globalThis.Number(object.filteredCount)
        : isSet(object.filtered_count)
          ? globalThis.Number(object.filtered_count)
          : 0,
      totalCount: isSet(object.totalCount)
        ? globalThis.Number(object.totalCount)
        : isSet(object.total_count)
          ? globalThis.Number(object.total_count)
          : 0,
      cursor: isSet(object.cursor) ? globalThis.String(object.cursor) : '',
      previousCursor: isSet(object.previousCursor)
        ? globalThis.String(object.previousCursor)
        : isSet(object.previous_cursor)
          ? globalThis.String(object.previous_cursor)
          : '',
      appliedQueryFilter: isSet(object.appliedQueryFilter)
        ? QueryFilter.fromJSON(object.appliedQueryFilter)
        : isSet(object.applied_query_filter)
          ? QueryFilter.fromJSON(object.applied_query_filter)
          : undefined,
    };
  },

  toJSON(message: Pagination): unknown {
    const obj: any = {};
    if (message.maxResponseSize !== 0) {
      obj.maxResponseSize = Math.round(message.maxResponseSize);
    }
    if (message.filteredCount !== 0) {
      obj.filteredCount = Math.round(message.filteredCount);
    }
    if (message.totalCount !== 0) {
      obj.totalCount = Math.round(message.totalCount);
    }
    if (message.cursor !== '') {
      obj.cursor = message.cursor;
    }
    if (message.previousCursor !== '') {
      obj.previousCursor = message.previousCursor;
    }
    if (message.appliedQueryFilter !== undefined) {
      obj.appliedQueryFilter = QueryFilter.toJSON(message.appliedQueryFilter);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Pagination>, I>>(base?: I): Pagination {
    return Pagination.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Pagination>, I>>(object: I): Pagination {
    const message = createBasePagination();
    message.maxResponseSize = object.maxResponseSize ?? 0;
    message.filteredCount = object.filteredCount ?? 0;
    message.totalCount = object.totalCount ?? 0;
    message.cursor = object.cursor ?? '';
    message.previousCursor = object.previousCursor ?? '';
    message.appliedQueryFilter =
      object.appliedQueryFilter !== undefined && object.appliedQueryFilter !== null
        ? QueryFilter.fromPartial(object.appliedQueryFilter)
        : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends {}
        ? { [K in keyof T]?: DeepPartial<T[K]> }
        : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === 'string') {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error('Value is larger than Number.MAX_SAFE_INTEGER');
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error('Value is smaller than Number.MIN_SAFE_INTEGER');
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
