{
 "title": "Prixfixe Service",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Users Count",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "users_count", "legendFormat": "count" }
   ]
  },
  {
   "title": "Households Count",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "households_count", "legendFormat": "count" }
   ]
  },
  {
   "title": "API Clients Count",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "api_clients_count", "legendFormat": "count" }
   ]
  },
  {
   "title": "Webhooks Count",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "webhooks_count", "legendFormat": "count" }
   ]
  }
 ]
}