# Admin webapp OAuth2 credentials (for DINNER_DONE_BETTER_API_SERVICE_OAUTH2_API_CLIENT_ID / _SECRET)
variable "ADMIN_WEBAPP_OAUTH2_CLIENT_ID" {}
variable "ADMIN_WEBAPP_OAUTH2_CLIENT_SECRET" {}

# Consumer webapp OAuth2 credentials (for DINNER_DONE_BETTER_API_SERVICE_OAUTH2_API_CLIENT_ID / _SECRET)
variable "CONSUMER_WEBAPP_OAUTH2_CLIENT_ID" {}
variable "CONSUMER_WEBAPP_OAUTH2_CLIENT_SECRET" {}

# MCP server OAuth2 credentials (for DINNER_DONE_BETTER_API_SERVICE_OAUTH2_API_CLIENT_ID / _SECRET)
variable "MCP_SERVICE_OAUTH2_CLIENT_ID" {}
variable "MCP_SERVICE_OAUTH2_CLIENT_SECRET" {}
