---
apiVersion: v1
kind: Service
metadata:
  name: dinner-done-better-mcp-server-svc
  labels:
    app: dinner-done-better-mcp-server
    app.kubernetes.io/name: dinner-done-better-mcp-server
spec:
  selector:
    app.kubernetes.io/name: dinner-done-better-mcp-server
  ports:
    - name: http
      port: 8888
      protocol: TCP
      targetPort: http
  type: ClusterIP
---
