// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v6.33.1
// source: issue_reports/issue_reports_service.proto

/* eslint-disable */
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from '@grpc/grpc-js';
import {
  ArchiveIssueReportRequest,
  ArchiveIssueReportResponse,
  CreateIssueReportRequest,
  CreateIssueReportResponse,
  GetIssueReportRequest,
  GetIssueReportResponse,
  GetIssueReportsForAccountRequest,
  GetIssueReportsForAccountResponse,
  GetIssueReportsForRecordRequest,
  GetIssueReportsForRecordResponse,
  GetIssueReportsForTableRequest,
  GetIssueReportsForTableResponse,
  GetIssueReportsRequest,
  GetIssueReportsResponse,
  UpdateIssueReportRequest,
  UpdateIssueReportResponse,
} from './issue_reports_service_types';

export const protobufPackage = 'issue_reports';

export type IssueReportsServiceService = typeof IssueReportsServiceService;
export const IssueReportsServiceService = {
  createIssueReport: {
    path: '/issue_reports.IssueReportsService/CreateIssueReport' as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: CreateIssueReportRequest): Buffer =>
      Buffer.from(CreateIssueReportRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): CreateIssueReportRequest => CreateIssueReportRequest.decode(value),
    responseSerialize: (value: CreateIssueReportResponse): Buffer =>
      Buffer.from(CreateIssueReportResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): CreateIssueReportResponse => CreateIssueReportResponse.decode(value),
  },
  getIssueReport: {
    path: '/issue_reports.IssueReportsService/GetIssueReport' as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: GetIssueReportRequest): Buffer =>
      Buffer.from(GetIssueReportRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetIssueReportRequest => GetIssueReportRequest.decode(value),
    responseSerialize: (value: GetIssueReportResponse): Buffer =>
      Buffer.from(GetIssueReportResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): GetIssueReportResponse => GetIssueReportResponse.decode(value),
  },
  getIssueReports: {
    path: '/issue_reports.IssueReportsService/GetIssueReports' as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: GetIssueReportsRequest): Buffer =>
      Buffer.from(GetIssueReportsRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetIssueReportsRequest => GetIssueReportsRequest.decode(value),
    responseSerialize: (value: GetIssueReportsResponse): Buffer =>
      Buffer.from(GetIssueReportsResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): GetIssueReportsResponse => GetIssueReportsResponse.decode(value),
  },
  getIssueReportsForAccount: {
    path: '/issue_reports.IssueReportsService/GetIssueReportsForAccount' as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: GetIssueReportsForAccountRequest): Buffer =>
      Buffer.from(GetIssueReportsForAccountRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetIssueReportsForAccountRequest =>
      GetIssueReportsForAccountRequest.decode(value),
    responseSerialize: (value: GetIssueReportsForAccountResponse): Buffer =>
      Buffer.from(GetIssueReportsForAccountResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): GetIssueReportsForAccountResponse =>
      GetIssueReportsForAccountResponse.decode(value),
  },
  getIssueReportsForTable: {
    path: '/issue_reports.IssueReportsService/GetIssueReportsForTable' as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: GetIssueReportsForTableRequest): Buffer =>
      Buffer.from(GetIssueReportsForTableRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetIssueReportsForTableRequest => GetIssueReportsForTableRequest.decode(value),
    responseSerialize: (value: GetIssueReportsForTableResponse): Buffer =>
      Buffer.from(GetIssueReportsForTableResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): GetIssueReportsForTableResponse =>
      GetIssueReportsForTableResponse.decode(value),
  },
  getIssueReportsForRecord: {
    path: '/issue_reports.IssueReportsService/GetIssueReportsForRecord' as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: GetIssueReportsForRecordRequest): Buffer =>
      Buffer.from(GetIssueReportsForRecordRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetIssueReportsForRecordRequest =>
      GetIssueReportsForRecordRequest.decode(value),
    responseSerialize: (value: GetIssueReportsForRecordResponse): Buffer =>
      Buffer.from(GetIssueReportsForRecordResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): GetIssueReportsForRecordResponse =>
      GetIssueReportsForRecordResponse.decode(value),
  },
  updateIssueReport: {
    path: '/issue_reports.IssueReportsService/UpdateIssueReport' as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: UpdateIssueReportRequest): Buffer =>
      Buffer.from(UpdateIssueReportRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): UpdateIssueReportRequest => UpdateIssueReportRequest.decode(value),
    responseSerialize: (value: UpdateIssueReportResponse): Buffer =>
      Buffer.from(UpdateIssueReportResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): UpdateIssueReportResponse => UpdateIssueReportResponse.decode(value),
  },
  archiveIssueReport: {
    path: '/issue_reports.IssueReportsService/ArchiveIssueReport' as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: ArchiveIssueReportRequest): Buffer =>
      Buffer.from(ArchiveIssueReportRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): ArchiveIssueReportRequest => ArchiveIssueReportRequest.decode(value),
    responseSerialize: (value: ArchiveIssueReportResponse): Buffer =>
      Buffer.from(ArchiveIssueReportResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): ArchiveIssueReportResponse => ArchiveIssueReportResponse.decode(value),
  },
} as const;

export interface IssueReportsServiceServer extends UntypedServiceImplementation {
  createIssueReport: handleUnaryCall<CreateIssueReportRequest, CreateIssueReportResponse>;
  getIssueReport: handleUnaryCall<GetIssueReportRequest, GetIssueReportResponse>;
  getIssueReports: handleUnaryCall<GetIssueReportsRequest, GetIssueReportsResponse>;
  getIssueReportsForAccount: handleUnaryCall<GetIssueReportsForAccountRequest, GetIssueReportsForAccountResponse>;
  getIssueReportsForTable: handleUnaryCall<GetIssueReportsForTableRequest, GetIssueReportsForTableResponse>;
  getIssueReportsForRecord: handleUnaryCall<GetIssueReportsForRecordRequest, GetIssueReportsForRecordResponse>;
  updateIssueReport: handleUnaryCall<UpdateIssueReportRequest, UpdateIssueReportResponse>;
  archiveIssueReport: handleUnaryCall<ArchiveIssueReportRequest, ArchiveIssueReportResponse>;
}

export interface IssueReportsServiceClient extends Client {
  createIssueReport(
    request: CreateIssueReportRequest,
    callback: (error: ServiceError | null, response: CreateIssueReportResponse) => void,
  ): ClientUnaryCall;
  createIssueReport(
    request: CreateIssueReportRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: CreateIssueReportResponse) => void,
  ): ClientUnaryCall;
  createIssueReport(
    request: CreateIssueReportRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: CreateIssueReportResponse) => void,
  ): ClientUnaryCall;
  getIssueReport(
    request: GetIssueReportRequest,
    callback: (error: ServiceError | null, response: GetIssueReportResponse) => void,
  ): ClientUnaryCall;
  getIssueReport(
    request: GetIssueReportRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GetIssueReportResponse) => void,
  ): ClientUnaryCall;
  getIssueReport(
    request: GetIssueReportRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GetIssueReportResponse) => void,
  ): ClientUnaryCall;
  getIssueReports(
    request: GetIssueReportsRequest,
    callback: (error: ServiceError | null, response: GetIssueReportsResponse) => void,
  ): ClientUnaryCall;
  getIssueReports(
    request: GetIssueReportsRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GetIssueReportsResponse) => void,
  ): ClientUnaryCall;
  getIssueReports(
    request: GetIssueReportsRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GetIssueReportsResponse) => void,
  ): ClientUnaryCall;
  getIssueReportsForAccount(
    request: GetIssueReportsForAccountRequest,
    callback: (error: ServiceError | null, response: GetIssueReportsForAccountResponse) => void,
  ): ClientUnaryCall;
  getIssueReportsForAccount(
    request: GetIssueReportsForAccountRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GetIssueReportsForAccountResponse) => void,
  ): ClientUnaryCall;
  getIssueReportsForAccount(
    request: GetIssueReportsForAccountRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GetIssueReportsForAccountResponse) => void,
  ): ClientUnaryCall;
  getIssueReportsForTable(
    request: GetIssueReportsForTableRequest,
    callback: (error: ServiceError | null, response: GetIssueReportsForTableResponse) => void,
  ): ClientUnaryCall;
  getIssueReportsForTable(
    request: GetIssueReportsForTableRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GetIssueReportsForTableResponse) => void,
  ): ClientUnaryCall;
  getIssueReportsForTable(
    request: GetIssueReportsForTableRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GetIssueReportsForTableResponse) => void,
  ): ClientUnaryCall;
  getIssueReportsForRecord(
    request: GetIssueReportsForRecordRequest,
    callback: (error: ServiceError | null, response: GetIssueReportsForRecordResponse) => void,
  ): ClientUnaryCall;
  getIssueReportsForRecord(
    request: GetIssueReportsForRecordRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GetIssueReportsForRecordResponse) => void,
  ): ClientUnaryCall;
  getIssueReportsForRecord(
    request: GetIssueReportsForRecordRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GetIssueReportsForRecordResponse) => void,
  ): ClientUnaryCall;
  updateIssueReport(
    request: UpdateIssueReportRequest,
    callback: (error: ServiceError | null, response: UpdateIssueReportResponse) => void,
  ): ClientUnaryCall;
  updateIssueReport(
    request: UpdateIssueReportRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: UpdateIssueReportResponse) => void,
  ): ClientUnaryCall;
  updateIssueReport(
    request: UpdateIssueReportRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: UpdateIssueReportResponse) => void,
  ): ClientUnaryCall;
  archiveIssueReport(
    request: ArchiveIssueReportRequest,
    callback: (error: ServiceError | null, response: ArchiveIssueReportResponse) => void,
  ): ClientUnaryCall;
  archiveIssueReport(
    request: ArchiveIssueReportRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: ArchiveIssueReportResponse) => void,
  ): ClientUnaryCall;
  archiveIssueReport(
    request: ArchiveIssueReportRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: ArchiveIssueReportResponse) => void,
  ): ClientUnaryCall;
}

export const IssueReportsServiceClient = makeGenericClientConstructor(
  IssueReportsServiceService,
  'issue_reports.IssueReportsService',
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): IssueReportsServiceClient;
  service: typeof IssueReportsServiceService;
  serviceName: string;
};
