---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dinner-done-better-service-api-deployment
  labels:
    app: dinner-done-better-backend
    app.kubernetes.io/name: dinner-done-better-backend
spec:
  selector:
    matchLabels:
      app: dinner-done-better-backend
      app.kubernetes.io/name: dinner-done-better-backend
  replicas: 1
  template:
    metadata:
      labels:
        app: dinner-done-better-backend
        app.kubernetes.io/name: dinner-done-better-backend
    spec:
      containers:
      # this is the API server container
      - name: dinner-done-better-service-api
        image: dinner-done-better-service-api
        imagePullPolicy: IfNotPresent
        env:
          - name: "CONFIGURATION_FILEPATH"
            value: "/etc/service-config.json"
        volumeMounts:
        - name: "config"
          mountPath: "/etc/service-config.json"
          subPath: "config.json"
        - name: logs
          mountPath: /var/log/dinnerdonebetter
        ports:
        - containerPort: 8000
          name: http
        resources:
          requests:
            memory: 256Mi
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: "/_meta_/live"
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: "/_meta_/ready"
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 3
      # This is the OpenTelemetry collector sidecar
      - name: opentelemetry-collector
        image: otel/opentelemetry-collector-contrib:0.115.1
        command:
          - "/otelcol-contrib"
          - "--config"
          - "/conf/config.yaml"
        ports:
          - containerPort: 4317
            name: otel1
          - containerPort: 4318
            name: otel2
        volumeMounts:
          - name: logs
            mountPath: /var/log/dinnerdonebetter
            readOnly: true
          - name: opentelemetry-config
            mountPath: /conf
      volumes:
        # this volume contains the configuration file for the API service
        - name: "config"
          configMap:
            name: "dinner-done-better-service-api-config"
        # this volume is where we write logs to in the API, and where we read logs from in the collector.
        - name: logs
          emptyDir:
            sizeLimit: 500Mi
        # this volume contains the configuration file for the OTel collector.
        - name: opentelemetry-config
          configMap:
            name: opentelemetry-collector-config
---
