---
apiVersion: v1
kind: ConfigMap
metadata:
  name: opentelemetry-collector-config
data:
  collector.yaml: |
    receivers:
      filelog:
        include: [ /var/log/dinnerdonebetter/*.log ]
        operators:
          - type: json_parser
            timestamp:
              parse_from: attributes.time
              layout: '%Y-%m-%dT%H:%M:%S.%9N%:z'
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    processors:
      batch:
    
    exporters:
      otlp:
        endpoint: http://tempo.localdev.svc.cluster.local:3100
      prometheus:
        endpoint: http://prometheus-server.localdev.svc.cluster.local:3001
        namespace: default
      otlphttp:
        endpoint: http://loki.localdev.svc.cluster.local:3100/otlp
    
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp]
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [prometheus]
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlphttp]
---