---
apiVersion: 1
prune: true
datasources:
  - id: 1
    uid: ce73zcv9vnif4e
    orgId: 1
    name: prometheus
    type: prometheus
    typeName: Prometheus
    typeLogoUrl: public/app/plugins/datasource/prometheus/img/prometheus_logo.svg
    access: proxy
    url: http://prometheus:9090
    user: ''
    database: ''
    basicAuth: false
    jsonData:
      httpMethod: POST
    readOnly: false
    editable: true

  - id: 2
    uid: ee73zh82h7bpcd
    orgId: 1
    name: jaeger
    type: jaeger
    typeName: Jaeger
    typeLogoUrl: public/app/plugins/datasource/jaeger/img/jaeger_logo.svg
    access: proxy
    url: http://jaeger:16686
    user: ''
    database: ''
    basicAuth: false
    jsonData: {}
    readOnly: false
    editable: true

  - id: 3
    uid: ee73zh82h7pbdc
    name: Loki
    type: loki
    access: proxy
    orgId: 1
    url: http://loki:3100
    basicAuth: false
    version: 1
    editable: true
