---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: dinner-done-better-cronjob-email-prober
spec:
  # schedule: "* * * * *"
  schedule: "0 4 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: email-prober
            image: dinner-done-better-cronjob-email-prober
            imagePullPolicy: IfNotPresent
            env:
              - name: "CONFIGURATION_FILEPATH"
                value: "/etc/service-config.json"
            volumeMounts:
            - name: "config"
              mountPath: "/etc/service-config.json"
              subPath: "config.json"
            - name: logs
              mountPath: /var/log/dinnerdonebetter
          restartPolicy: OnFailure
          volumes:
            - name: "config"
              configMap:
                name: "dinner-done-better-cronjob-email-prober-config"
            # this volume is where we write logs to, and where we read logs from in the collector.
            - name: logs
              emptyDir:
                sizeLimit: 500Mi
---
