SELECT
    valid_measurement_conversions.id,
    valid_measurement_units_1.id,
    valid_measurement_units_1.name,
    valid_measurement_units_1.description,
    valid_measurement_units_1.volumetric,
    valid_measurement_units_1.icon_path,
    valid_measurement_units_1.universal,
    valid_measurement_units_1.metric,
    valid_measurement_units_1.imperial,
    valid_measurement_units_1.plural_name,
    valid_measurement_units_1.created_at,
    valid_measurement_units_1.last_updated_at,
    valid_measurement_units_2.id,
    valid_measurement_units_2.name,
    valid_measurement_units_2.description,
    valid_measurement_units_2.volumetric,
    valid_measurement_units_2.icon_path,
    valid_measurement_units_2.universal,
    valid_measurement_units_2.metric,
    valid_measurement_units_2.imperial,
    valid_measurement_units_2.plural_name,
    valid_measurement_units_2.created_at,
    valid_measurement_units_2.last_updated_at,
    valid_ingredients.id,
    valid_ingredients.name,
    valid_ingredients.description,
    valid_ingredients.warning,
    valid_ingredients.contains_egg,
    valid_ingredients.contains_dairy,
    valid_ingredients.contains_peanut,
    valid_ingredients.contains_tree_nut,
    valid_ingredients.contains_soy,
    valid_ingredients.contains_wheat,
    valid_ingredients.contains_shellfish,
    valid_ingredients.contains_sesame,
    valid_ingredients.contains_fish,
    valid_ingredients.contains_gluten,
    valid_ingredients.animal_flesh,
    valid_ingredients.volumetric,
    valid_ingredients.is_liquid,
    valid_ingredients.icon_path,
    valid_ingredients.animal_derived,
    valid_ingredients.plural_name,
    valid_ingredients.restrict_to_preparations,
    valid_ingredients.minimum_ideal_storage_temperature_in_celsius,
    valid_ingredients.maximum_ideal_storage_temperature_in_celsius,
    valid_ingredients.storage_instructions,
    valid_ingredients.created_at,
    valid_ingredients.last_updated_at,
    valid_ingredients.archived_at,
    valid_measurement_conversions.modifier,
    valid_measurement_conversions.notes,
    valid_measurement_conversions.created_at,
    valid_measurement_conversions.last_updated_at,
    valid_measurement_conversions.archived_at
FROM valid_measurement_conversions
         LEFT JOIN valid_ingredients ON valid_measurement_conversions.only_for_ingredient = valid_ingredients.id
         JOIN valid_measurement_units AS valid_measurement_units_1 ON valid_measurement_conversions.to = valid_measurement_units_1.id
         JOIN valid_measurement_units AS valid_measurement_units_2 ON valid_measurement_conversions.from = valid_measurement_units_2.id
WHERE valid_measurement_conversions.id = $1
  AND valid_measurement_conversions.archived_at IS NULL
  AND valid_measurement_units_1.archived_at IS NULL
  AND valid_measurement_units_2.archived_at IS NULL
