---
on:
  pull_request:
    paths:
      - backend/**

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

name: backend build
jobs:
  backend:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Build backend
        uses: dagger/dagger-for-github@v8.4.0
        with:
          version: "0.18.19"
          verb: call
          module: ./dagger
          args: backend-build --source=.
