on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

name: backend - testing something
jobs:
  run:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      matrix:
        - things: barf
          stuff: worp
        - things: yurl
          stuff: querk
    steps:
      - name: testing things
        run: echo ${{ matrix.things }}


      - name: testing stuff
        run: echo ${{ matrix.stuff }}