on: [gollum]
#  pull_request:
#    paths:
#      - backend/deploy/environments/dev/terraform/**

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

name: backend - lint terraform
jobs:
  terraform:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.23.x' ]
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.3
          cli_config_credentials_token: ${{ secrets.TERRAFORM_CLOUD_API_TOKEN  }}

      - name: Terraform Init
        working-directory: backend/deploy/environments/dev/terraform
        id: init
        run: terraform init

      - name: copy server config file
        working-directory: backend/deploy/environments/dev
        run: |
          cp config_files/service-config.json terraform/service-config.json

      # end things have to be done for terraform to succeed

      - name: Terraform Validate
        working-directory: backend/deploy/environments/dev/terraform
        id: validate
        run: terraform validate -no-color

      - name: Check formatting
        working-directory: backend/deploy/environments/dev/terraform
        id: fmt
        run: terraform fmt -check
