---
on: 
  # gollum:
  pull_request:
    paths:
      - backend/pkg/**
      - backend/internal/**
      - backend/tests/**
      - backend/testing/**

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

name: backend - integration tests
jobs:
  run:
    timeout-minutes: 25
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: run integration tests
        uses: dagger/dagger-for-github@v8
        with:
          version: "0.18.19"
          verb: call
          module: ./dagger
          args: backend-integration-tests --source=. --docker-socket=/var/run/docker.sock
