on: [gollum]
  # pull_request:
  #   paths:
  #     - backend/pkg/**
  #     - backend/internal/**
  #     - backend/go.mod
  #     - backend/go.sum

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

name: backend - unit tests
jobs:
  run:
    timeout-minutes: 25
    strategy:
      matrix:
        go-version: [ '1.23.x' ]
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: run unit tests
        working-directory: backend
        run: make test
