on: # [gollum]
  pull_request:
    paths:
      - backend/pkg/**
      - backend/internal/**
      - backend/tests/**

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

name: backend - integration tests
jobs:
  run:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: run integration tests
        working-directory: backend
        run: make integration_tests
