---
on: [gollum]
# pull_request:
#   paths:
#     - backend/pkg/**
#     - backend/cmd/**
#     - backend/internal/**
#     - backend/tests/**
#     - backend/go.mod
#     - backend/go.sum

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

name: backend - build
jobs:
  backend:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.23.x']
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build backend
        working-directory: backend/
        run: make build
