---
on:
  pull_request:
    paths:
      - backend/**/*.go

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

name: backend lint
jobs:
  golang:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: golangci-lint
        uses: dagger/dagger-for-github@v8
        with:
          version: "0.18.19"
          verb: call
          module: ./dagger
          args: backend-lint --source=.
