---
on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

name: build
jobs:
  changes:
    permissions:
      pull-requests: read
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend_webapp: ${{ steps.filter.outputs.frontend_webapp }}
      ios: ${{ steps.filter.outputs.ios }}
    steps:
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            backend:
              - backend/**
            frontend_webapp:
              - frontend/apps/web/**
              - frontend/packages/**
              - frontend/environments/dev/webapp/**
            ios:
              - ios/**/*.swift
              - ios/**/*.xcodeproj
              - ios/**/*.xcworkspace
              - ios/Makefile

  backend:
    needs: [changes]
    if: ${{ needs.changes.outputs.backend == 'true' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.25.x']
    steps:
      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v5

      - name: Build backend
        working-directory: backend/
        run: make build

  frontend_webapp:
    needs: [changes]
    if: ${{ needs.changes.outputs.frontend_webapp == 'true' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configs:
          - node: 'lts/*'
    name: webapp on ${{ matrix.configs.node }}
    steps:
      - uses: actions/checkout@v5

      - name: Setup node
        uses: actions/setup-node@v4

      - run: npm install -g yarn

      - run: yarn install
        working-directory: frontend/

      - run: yarn run build
        env:
          NEXT_COOKIE_ENCRYPTION_KEY: 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
          NEXT_BASE64_COOKIE_ENCRYPT_IV: 'QUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUE='
        working-directory: frontend/apps/web

  ios:
    needs: [changes]
    if: ${{ needs.changes.outputs.ios == 'true' }}
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_15.4.app/Contents/Developer || sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

      - name: Show Xcode version
        run: xcodebuild -version

      - name: Build iOS app
        working-directory: ios
        env:
          DESTINATION: "platform=iOS Simulator,name=iPhone 16 Pro,OS=18.6"
        run: make build
