---
concurrency:
  group: ${{ github.ref }}

on: # [pull_request]
  push:
    branches:
      - dev

name: deploy dev
jobs:
  changes:
    permissions:
      pull-requests: read
    runs-on: ubuntu-latest
    outputs:
      infra: ${{ steps.filter.outputs.infra }}
      backend: ${{ steps.filter.outputs.backend }}
    steps:
      - name: disabled
        run: echo "disabled"

#      - name: Checkout code
#        uses: actions/checkout@v5
#
#      - uses: dorny/paths-filter@v3
#        id: filter
#        with:
#          filters: |
#            backend:
#              - backend/**
#            infra:
#              - infra/**
#
#  baseline-infra:
#    needs: [changes]
#    timeout-minutes: 90
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v5
#
#      - name: authenticate with GCP
#        uses: google-github-actions/auth@v2
#        with:
#          credentials_json: '${{ secrets.DEV_GOOGLE_CLOUD_CREDENTIALS }}'
#
#      # Setup gcloud CLI
#      - name: Set up Cloud SDK
#        uses: google-github-actions/setup-gcloud@v2
#
#      # these two steps should be commented out if the cluster hasn't been created yet
#      - name: get GKE credentials
#        uses: 'google-github-actions/get-gke-credentials@v2'
#        with:
#          cluster_name: 'dev'
#          context_name: 'dev_context'
#          location: 'us-central1'
#
#      - name: copy kubeconfig
#        working-directory: backend/deploy/environments/dev
#        run: |
#          cp ${{ env.KUBECONFIG }} terraform/terraform_kubeconfig
#
#      - name: Setup Terraform
#        uses: hashicorp/setup-terraform@v3
#        with:
#          terraform_version: 1.10.3
#          cli_config_credentials_token: ${{ secrets.TERRAFORM_CLOUD_API_TOKEN  }}
#
#      - name: Terraform Init
#        working-directory: infra/deploy/environments/dev/terraform
#        id: init
#        run: terraform init
#
#      - name: Terraform Validate
#        working-directory: infra/deploy/environments/dev/terraform
#        id: validate
#        run: terraform validate -no-color
#
#      - name: Terraform Apply
#        run: terraform apply -auto-approve
#        working-directory: infra/deploy/environments/dev/terraform
#
#      - uses: dorny/paths-filter@v3
#        id: filter
#        with:
#          filters: |
#            backend:
#              - backend/**
#
#  backend-infra:
#    needs:
#      - changes
#      - baseline-infra
#    timeout-minutes: 90
#    runs-on: ubuntu-latest
#    if: ${{ needs.changes.outputs.backend == 'true' }}
#    strategy:
#      matrix:
#        go-version: ['1.26.x']
#        container-registry: ['us-central1-docker.pkg.dev']
#    steps:
#      - name: Install Go
#        uses: actions/setup-go@v6
#        with:
#          go-version: ${{ matrix.go-version }}
#
#      - name: Checkout code
#        uses: actions/checkout@v5
#
#      - name: authenticate with GCP
#        uses: google-github-actions/auth@v2
#        with:
#          credentials_json: '${{ secrets.DEV_GOOGLE_CLOUD_CREDENTIALS }}'
#
#      # Setup gcloud CLI
#      - name: Set up Cloud SDK
#        uses: google-github-actions/setup-gcloud@v2
#
#      - name: Authorize Docker push to pkg.dev
#        run: gcloud auth configure-docker ${{ matrix.container-registry }}
#
#      - name: get GKE credentials
#        uses: 'google-github-actions/get-gke-credentials@v2'
#        with:
#          cluster_name: 'dev'
#          context_name: 'dev_context'
#          location: 'us-central1'
#
#      - name: copy kubeconfig
#        working-directory: backend/deploy/environments/dev
#        run: |
#          cp ${{ env.KUBECONFIG }} terraform/terraform_kubeconfig
#
#      - name: Setup Terraform
#        uses: hashicorp/setup-terraform@v3
#        with:
#          terraform_version: 1.10.3
#          cli_config_credentials_token: ${{ secrets.TERRAFORM_CLOUD_API_TOKEN  }}
#
#      - name: Terraform Init
#        working-directory: backend/deploy/environments/dev/terraform
#        id: init
#        run: terraform init
#
#      # validate backend workspace terraform
#
#      - name: Terraform Validate
#        working-directory: backend/deploy/environments/dev/terraform
#        id: validate
#        run: terraform validate -no-color
#
#      - name: Terraform Apply
#        run: terraform apply -auto-approve
#        working-directory: backend/deploy/environments/dev/terraform
#
#      - name: remove kubernetes config
#        working-directory: backend/deploy/environments/dev
#        run: rm -f ${{ env.KUBECONFIG }} terraform/terraform_kubeconfig
#
#  applications:
#    if: always() && !failure() && !cancelled()
#    needs:
#      - backend-infra
#      - webapp-infra
#    timeout-minutes: 90
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        go-version: ['1.26.x']
#        container-registry: ['us-central1-docker.pkg.dev']
#    steps:
#      - name: Install Go
#        uses: actions/setup-go@v6
#        with:
#          go-version: ${{ matrix.go-version }}
#
#      - name: Checkout code
#        uses: actions/checkout@v5
#
#      - name: authenticate with GCP
#        uses: google-github-actions/auth@v2
#        with:
#          credentials_json: '${{ secrets.DEV_GOOGLE_CLOUD_CREDENTIALS }}'
#
#      # Setup gcloud CLI
#      - name: Set up Cloud SDK
#        uses: google-github-actions/setup-gcloud@v2
#
#      - name: Authorize Docker push to pkg.dev
#        run: gcloud auth configure-docker ${{ matrix.container-registry }}
#
#      - name: get GKE credentials
#        uses: 'google-github-actions/get-gke-credentials@v2'
#        with:
#          cluster_name: 'dev'
#          context_name: 'dev_context'
#          location: 'us-central1'
#
#      - name: setup Skaffold
#        run: gcloud components update && gcloud components install skaffold
#
#      - name: deploy kubernetes deps
#        run: kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.16.2/cert-manager.yaml
#
#      - name: Skaffold deploy
#        run: skaffold run --filename=skaffold.yaml --build-concurrency 1 --profile dev
#
#      - name: remove kubernetes config
#        working-directory: backend/deploy/environments/dev
#        run: rm -f ${{ env.KUBECONFIG }}
