---
on: 
  # gollum:
  pull_request:
    paths:
      - backend/**/*.go
      - ios/**/*.swift

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

name: formatting
jobs:
  changes:
    permissions:
      pull-requests: read
    outputs:
      backend_golang: ${{ steps.filter.outputs.backend_golang }}
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            backend_golang:
              - backend/**/*.go
            ios_swift:
              - ios/**/*.swift

  golang:
    needs: [changes]
    if: ${{ needs.changes.outputs.backend_golang == 'true' }}
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.26.x']
    steps:
      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v6

      - name: check formatting
        working-directory: backend
        run: if [ $(gofmt -l . | grep -Ev '^vendor\/' | head -c1 | wc -c) -ne 0 ]; then exit 1; fi

  swift:
    needs: [changes]
    if: ${{ needs.changes.outputs.ios_swift == 'true' }}
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: check formatting
        working-directory: ios
        run: make format-check
