---
on:
  pull_request:
    paths:
      - frontend/deploy/environments/dev/landing/terraform/**

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

name: frontend - lint landing app terraform
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5
          cli_config_credentials_token: ${{ secrets.TERRAFORM_CLOUD_API_TOKEN  }}

      - name: Terraform Init
        working-directory: frontend/deploy/environments/dev/landing/terraform
        id: init
        run: terraform init

      - name: Terraform Format
        working-directory: frontend/deploy/environments/dev/landing/terraform
        id: fmt
        run: terraform fmt -check

      - name: Terraform Validate
        working-directory: frontend/deploy/environments/dev/landing/terraform
        id: validate
        run: terraform validate -no-color
