concurrency:
  group: ${{ github.ref }}-deploy-admin

on:
  push:
    branches:
      - dev
    paths:
      - frontend/apps/admin/**
      - frontend/packages/**

name: frontend - deploy admin app to dev
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # these are used simply to ensure consistency, there should never be more than one entry in these arrays.
        gcp-region: [ 'us-central1' ]
        gcp-project: [ 'dinner-done-better-dev' ]
        container-name: [ 'admin_app_server' ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.DEV_GOOGLE_CLOUD_CREDENTIALS }}'

      # Setup gcloud CLI
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Authorize Docker push
        run: gcloud auth configure-docker

      - name: Build Container
        working-directory: frontend/
        run: |
          docker build --tag ${{ matrix.gcp-region }}-docker.pkg.dev/${{ matrix.gcp-project }}/containers/${{ matrix.container-name }}:${{ github.sha }} --file apps/admin/Dockerfile .

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.5
          cli_config_credentials_token: ${{ secrets.TERRAFORM_CLOUD_API_TOKEN  }}

      - name: Terraform Init
        working-directory: frontend/environments/dev/admin/terraform
        id: init
        run: terraform init

      - name: Terraform Format
        working-directory: frontend/environments/dev/admin/terraform
        id: fmt
        run: terraform fmt -check

      - name: Terraform Validate
        working-directory: frontend/environments/dev/admin/terraform
        id: validate
        run: terraform validate -no-color

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: frontend/environments/dev/admin/terraform

      - name: Push Container
        working-directory: frontend/
        run: |
          docker push ${{ matrix.gcp-region }}-docker.pkg.dev/${{ matrix.gcp-project }}/containers/${{ matrix.container-name }}:${{ github.sha }}
          docker push ${{ matrix.gcp-region }}-docker.pkg.dev/${{ matrix.gcp-project }}/containers/${{ matrix.container-name }}:latest

      # if this step fails, you need to add the `Service Account User` role to the GitHub Actions IAM Principal.
      - id: deploy-admin-app-server
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: 'admin-app-server'
          project_id: '${{ matrix.gcp-project }}'
          image: '${{ matrix.gcp-region }}-docker.pkg.dev/${{ matrix.gcp-project }}/containers/${{ matrix.container-name }}'
