---
on:
  pull_request:
    paths:
      - frontend/apps/**
      - frontend/packages/**

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

name: frontend - formatting
jobs:
  formatting:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['lts/*']
    name: check
    steps:
      - uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4

      - run: npm install -g yarn

      - run: yarn install
        working-directory: frontend

      - run: yarn run format-check
        working-directory: frontend
