concurrency:
  group: ${{ github.ref }}-deploy-webapp

on: [pull_request]
#  push:
#    branches:
#      - dev
#    paths:
#      - frontend/apps/web/**
#      - frontend/packages/**

name: frontend - deploy webapp to dev
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configs:
          - gcp-region: 'us-central1'
            gcp-project: 'dinner-done-better-dev'
            container-name: 'webapp_server'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.DEV_GOOGLE_CLOUD_CREDENTIALS }}'

      # Setup gcloud CLI
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Authorize Docker push
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build Container
        working-directory: frontend
        run: |
          docker build --tag ${{ matrix.configs.gcp-region }}-docker.pkg.dev/${{ matrix.configs.gcp-project }}/containers/${{ matrix.configs.container-name }}:${{ github.sha }} --build-arg SEGMENT_API_TOKEN=${{ secrets.DEV_SEGMENT_API_TOKEN }} --file apps/web/Dockerfile .
          docker build --tag ${{ matrix.configs.gcp-region }}-docker.pkg.dev/${{ matrix.configs.gcp-project }}/containers/${{ matrix.configs.container-name }}:latest --build-arg SEGMENT_API_TOKEN=${{ secrets.DEV_SEGMENT_API_TOKEN }} --file apps/web/Dockerfile .

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.5
          cli_config_credentials_token: ${{ secrets.TERRAFORM_CLOUD_API_TOKEN  }}

      - name: Terraform Init
        working-directory: frontend/environments/dev/webapp/terraform
        id: init
        run: terraform init

      - name: Terraform Format
        working-directory: frontend/environments/dev/webapp/terraform
        id: fmt
        run: terraform fmt -check

      - name: Terraform Validate
        working-directory: frontend/environments/dev/webapp/terraform
        id: validate
        run: terraform validate -no-color

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: frontend/environments/dev/webapp/terraform

      - name: Push Container
        working-directory: frontend
        run: |
          docker push ${{ matrix.configs.gcp-region }}-docker.pkg.dev/${{ matrix.configs.gcp-project }}/containers/${{ matrix.configs.container-name }}:${{  github.sha }}
          docker push ${{ matrix.configs.gcp-region }}-docker.pkg.dev/${{ matrix.configs.gcp-project }}/containers/${{ matrix.configs.container-name }}:latest

      # if this step fails, you need to add the `Service Account User` role to the GitHub Actions IAM Principal.
      - id: deploy-webapp-server
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: 'webapp-server'
          project_id: '${{ matrix.configs.gcp-project }}'
          image: '${{ matrix.configs.gcp-region }}-docker.pkg.dev/${{ matrix.configs.gcp-project }}/containers/${{ matrix.configs.container-name }}'
