on: # [pull_request]
  pull_request:
    paths:
      - frontend/apps/**
      - frontend/packages/**
      - openapi_spec.yaml

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

name: frontend - build
jobs:
  containers:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configs:
          - app: 'admin'
          - app: 'landing'
          - app: 'web'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: ${{ matrix.configs.app }} Container
        working-directory: frontend/
        run: |
          docker build --tag ${{  github.sha }} --file apps/${{ matrix.configs.app }}/Dockerfile .

  apps:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configs:
          - node: 'lts/*'
            app: 'web'
          - node: 'lts/*'
            app: 'landing'
          - node: 'lts/*'
            app: 'admin'
    name: ${{ matrix.configs.app }} on ${{ matrix.configs.node }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4

      - run: npm install -g yarn

      - run: yarn install
        working-directory: frontend/

      - run: yarn run build
        env:
          NEXT_COOKIE_ENCRYPTION_KEY: 'ZOTGz4KEhZFSM6udeESOX5JVqhtEdHdS'
          NEXT_BASE64_COOKIE_ENCRYPT_IV: 'S2IwVXVvMW9hSEl4WjQ0ak1NYW50QndMTzJBWDJFV2o='
        working-directory: frontend/apps/${{ matrix.configs.app }}
