on:
  pull_request:
    paths:
      - frontend/apps/admin/**
      - frontend/packages/**

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

name: frontend - build admin
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['lts/*']
    name: Webapp on ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3

      - run: npm install -g yarn

      - run: yarn install
        working-directory: frontend/

      - run: yarn run build
        working-directory: frontend/apps/admin

  container:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Admin Container
        working-directory: frontend/
        run: |
          docker build --tag gcr.io/dinner-done-better-dev/admin_app_server:${{  github.sha }} --file apps/admin/Dockerfile .
