---
on:
  pull_request:
    paths:
      - frontend/package.json
      - frontend/packages/**/package.json
      - frontend/apps/**/package.json

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

name: frontend - ensure strict dependency version
jobs:
  dependency_versioning:
    runs-on: ubuntu-latest
    name: check
    steps:
      - uses: actions/checkout@v4

      # no imprecise versions
      - run: if [ $(grep `find . -name "package.json" | grep -ve "node_modules"` -e '"^' | wc -l) -ne 0 ]; then exit 1; fi

      # no latest
      - run: if [ $(grep `find . -name "package.json" | grep -ve "node_modules"` -e 'latest' | wc -l) -ne 0 ]; then exit 1; fi
