---
on:
  pull_request:
    paths:
      - ios/**/*.swift

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

name: ios formatting
jobs:
  swift:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: check formatting
        working-directory: ios
        run: make format-check
