---
on: 
  # gollum:
  pull_request:
    paths:
      - backend/**/*.go
      - ios/**/*.swift
      - ./**/*.md

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

name: lint
jobs:
  changes:
    permissions:
      pull-requests: read
    timeout-minutes: 5
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      ios: ${{ steps.filter.outputs.ios }}
      markdown: ${{ steps.filter.outputs.markdown }}
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            backend:
              - backend/**/*.go
            ios:
              - ios/**/*.swift
              - ios/.swiftlint.yml
              - ios/Makefile
            markdown:
              - ./**/*.md

  markdown:
    needs: [ changes ]
    if: ${{ needs.changes.outputs.markdown == 'true' }}
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: markdownlint
        run: make lint_markdown

  golang:
    needs: [ changes ]
    if: ${{ needs.changes.outputs.backend == 'true' }}
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.26.x']
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: '${{ matrix.go-version }}'

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.10.1
          working-directory: backend

  swift:
    needs: [ changes ]
    if: ${{ needs.changes.outputs.ios == 'true' }}
    timeout-minutes: 10
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install SwiftLint
        run: brew install swiftlint

      - name: Run SwiftLint
        working-directory: ios
        run: make lint
