---
on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

name: lint terraform
jobs:
  changes:
    permissions:
      pull-requests: read
    timeout-minutes: 5
    runs-on: ubuntu-latest
    outputs:
      infra: ${{ steps.filter.outputs.infra }}
      backend: ${{ steps.filter.outputs.backend }}
    steps:
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            infra:
              - infra/deploy/environments/prod/terraform/*.tf
            backend:
              - backend/deploy/environments/prod/terraform/*.tf

  infra:
    needs: [changes]
    if: ${{ needs.changes.outputs.infra == 'true' }}
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.26.x']
    steps:
      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.3
          cli_config_credentials_token: ${{ secrets.TERRAFORM_CLOUD_API_TOKEN }}

      - name: Terraform Init
        working-directory: infra/deploy/environments/prod/terraform
        id: init
        run: terraform init

      - name: Terraform Validate
        working-directory: infra/deploy/environments/prod/terraform
        id: validate
        run: terraform validate -no-color

  backend:
    needs: [changes]
    if: ${{ needs.changes.outputs.backend == 'true' }}
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.26.x']
    steps:
      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.3
          cli_config_credentials_token: ${{ secrets.TERRAFORM_CLOUD_API_TOKEN }}

      - name: Terraform Init
        working-directory: backend/deploy/environments/prod/terraform
        id: init
        run: terraform init

      - name: Terraform Validate
        working-directory: backend/deploy/environments/prod/terraform
        id: validate
        run: terraform validate -no-color
