---
on:
  pull_request:
    paths:
      - '**/*.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

name: markdown lint
jobs:
  markdown:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: markdownlint
        uses: dagger/dagger-for-github@v8.4.0
        with:
          version: "0.18.19"
          verb: call
          module: ./dagger
          args: markdown-lint --source=.
