on:
  pull_request:
    paths:
      - openapi_spec.yaml

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

name: openapi - lint
jobs:
  golang:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: stoplightio/spectral-action@latest
        with:
          file_glob: 'openapi_spec.yaml'
