---
on: 
  gollum:
  # pull_request:
  #   paths:
  #     - backend/scripts/**/*.sh
  #     - ios/scripts/**/*.sh

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

name: shellcheck
jobs:
  changes:
    permissions:
      pull-requests: read
    timeout-minutes: 5
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      ios: ${{ steps.filter.outputs.ios }}
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            backend:
              - backend/scripts/**/*.sh
            ios:
              - ios/scripts/**/*.sh

  backend:
    needs: [changes]
    if: ${{ needs.changes.outputs.backend == 'true' }}
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Run shellcheck
        working-directory: backend
        run: make shellcheck

  ios:
    needs: [changes]
    if: ${{ needs.changes.outputs.ios == 'true' }}
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Run shellcheck
        working-directory: ios
        run: make shellcheck

