---
on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

name: unit tests
jobs:
  changes:
    permissions:
      pull-requests: read
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
    steps:
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            backend:
              - backend/**/*.go
            ios:
              - ios/**/*.swift
              - ios/**/*.xcodeproj
              - ios/**/*.xcworkspace
              - ios/Makefile

  backend:
    needs: [changes]
    if: ${{ needs.changes.outputs.backend == 'true' }}
    timeout-minutes: 25
    strategy:
      matrix:
        go-version: ['1.25.x']
    runs-on: ubuntu-latest-8-cores
    steps:
      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v5

      - name: run unit tests
        working-directory: backend
        run: make test

  ios_unit_tests:
    needs: [changes]
    if: ${{ needs.changes.outputs.ios == 'true' }}
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_15.4.app/Contents/Developer || sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

      - name: Show Xcode version
        run: xcodebuild -version

      - name: Run unit tests
        working-directory: ios
        env:
          DESTINATION: platform=iOS Simulator,name=iPhone 16 Pro,OS=18.6
        run: make unit-test

  ios_ui_tests:
    needs: [changes]
    if: ${{ needs.changes.outputs.ios == 'true' }}
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_15.4.app/Contents/Developer || sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

      - name: Show Xcode version
        run: xcodebuild -version

      - name: Run UI tests
        working-directory: ios
        env:
          DESTINATION: platform=iOS Simulator,name=iPhone 16 Pro,OS=18.6
        run: make ui-test
