---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: dinner-done-better-job-db-cleaner
spec:
  concurrencyPolicy: Replace
  schedule: "0 0 1,8,15,22 * *" # At midnight on day-of-month 1, 8, 15, and 22.”
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: db-cleaner
              image: dinner-done-better-job-db-cleaner
              imagePullPolicy: Always
              env:
                - name: "CONFIGURATION_FILEPATH"
                  value: "/etc/service-config.json"
                - name: "DINNER_DONE_BETTER_OBSERVABILITY_METRICS_OTEL_SERVICE_NAME"
                  value: "dinner_done_better_job_db_cleaner"
                - name: "DINNER_DONE_BETTER_OBSERVABILITY_TRACING_TRACING_SERVICE_NAME"
                  value: "dinner_done_better_job_db_cleaner"
              volumeMounts:
                - name: "config"
                  mountPath: "/etc/service-config.json"
                  subPath: "config.json"
          volumes:
            - name: "config"
              configMap:
                name: "dinner-done-better-job-db-cleaner-config"
---
