---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: dinner-done-better-job-email-prober
spec:
  # schedule: "* * * * *"
  schedule: "0 4 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: email-prober
              image: dinner-done-better-job-email-prober
              imagePullPolicy: Always
              env:
                - name: "CONFIGURATION_FILEPATH"
                  value: "/etc/service-config.json"
                - name: "DINNER_DONE_BETTER_OBSERVABILITY_METRICS_OTEL_SERVICE_NAME"
                  value: "dinner_done_better_job_email_probe"
                - name: "DINNER_DONE_BETTER_OBSERVABILITY_TRACING_TRACING_SERVICE_NAME"
                  value: "dinner_done_better_job_email_probe"
              volumeMounts:
                - name: "config"
                  mountPath: "/etc/service-config.json"
                  subPath: "config.json"
          restartPolicy: OnFailure
          volumes:
            - name: "config"
              configMap:
                name: "dinner-done-better-job-email-prober-config"
---
