apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - db_cleaner_cronjob.yaml
  - email_prober_cronjob.yaml
  - meal_plan_finalizer_cronjob.yaml
  - meal_plan_grocery_list_initializer_cronjob.yaml
  - meal_plan_task_creator_cronjob.yaml
  - search_data_index_scheduler_cronjob.yaml
