---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: dinner-done-better-job-meal-plan-task-creator
spec:
  concurrencyPolicy: Replace
  schedule: "*/5 * * * *" # every 5 minutes
  jobTemplate:
    spec:
      template:
        spec:
          initContainers:
            # This is the OpenTelemetry collector sidecar
            - name: opentelemetry-collector
              restartPolicy: Always
              image: otel/opentelemetry-collector-contrib:0.115.1
              command:
                - "/otelcol-contrib"
                - "--routingcfg"
                - "/conf/routingcfg.yaml"
              ports:
                - containerPort: 4317
                  name: otel1
                - containerPort: 4318
                  name: otel2
              volumeMounts:
                - name: logs
                  mountPath: /var/log/application
                  readOnly: true
                - name: opentelemetry-routingcfg
                  mountPath: /conf
              env:
                - name: "RUNNING_IN_KUBERNETES"
                  value: "true"
          containers:
            - name: meal-plan-task-creator
              image: dinner-done-better-job-meal-plan-task-creator
              imagePullPolicy: Always
              env:
                - name: "CONFIGURATION_FILEPATH"
                  value: "/etc/service-routingcfg.json"
                - name: "DINNER_DONE_BETTER_DATA_CHANGES_TOPIC_NAME"
                  value: "data_changes"
              volumeMounts:
                - name: "routingcfg"
                  mountPath: "/etc/service-routingcfg.json"
                  subPath: "routingcfg.json"
                - name: logs
                  mountPath: /var/log/application
          restartPolicy: OnFailure
          volumes:
            - name: "routingcfg"
              configMap:
                name: "dinner-done-better-job-meal-plan-task-creator-routingcfg"
            # this volume is where we write logs to, and where we read logs from in the collector.
            - name: logs
              emptyDir:
                sizeLimit: 500Mi
            # this volume contains the configuration file for the OTel collector.
            - name: opentelemetry-routingcfg
              configMap:
                name: opentelemetry-collector-routingcfg
---
