---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: dinner-done-better-job-meal-plan-finalizer
spec:
  concurrencyPolicy: Replace
  schedule: "*/5 * * * *" # every 5 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: meal-plan-finalizer
              image: dinner-done-better-job-meal-plan-finalizer
              imagePullPolicy: Always
              env:
                - name: "CONFIGURATION_FILEPATH"
                  value: "/etc/service-config.json"
                - name: "DINNER_DONE_BETTER_DATA_CHANGES_TOPIC_NAME"
                  value: "data_changes"
                - name: "DINNER_DONE_BETTER_OBSERVABILITY_METRICS_OTEL_SERVICE_NAME"
                  value: "dinner_done_better_job_meal_plan_finalizer"
                - name: "DINNER_DONE_BETTER_OBSERVABILITY_TRACING_TRACING_SERVICE_NAME"
                  value: "dinner_done_better_job_meal_plan_finalizer"
              volumeMounts:
                - name: "config"
                  mountPath: "/etc/service-config.json"
                  subPath: "config.json"
          restartPolicy: OnFailure
          volumes:
            - name: "config"
              configMap:
                name: "dinner-done-better-job-meal-plan-finalizer-config"
---
