---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: dinner-done-better-job-search-data-index-scheduler
spec:
  concurrencyPolicy: Replace
  schedule: "*/30 * * * *" # every 30 minutes
  jobTemplate:
    spec:
      template:
        spec:
          initContainers:
            # This is the OpenTelemetry collector sidecar
            - name: opentelemetry-collector
              restartPolicy: Always
              image: otel/opentelemetry-collector-contrib:0.115.1
              command:
                - "/otelcol-contrib"
                - "--config"
                - "/conf/config.yaml"
              ports:
                - containerPort: 4317
                  name: otel1
                - containerPort: 4318
                  name: otel2
              volumeMounts:
                - name: logs
                  mountPath: /var/log/application
                  readOnly: true
                - name: opentelemetry-config
                  mountPath: /conf
              env:
                - name: "RUNNING_IN_KUBERNETES"
                  value: "true"
          containers:
            - name: search-data-index-scheduler
              image: dinner-done-better-job-search-data-index-scheduler
              imagePullPolicy: Always
              env:
                - name: "CONFIGURATION_FILEPATH"
                  value: "/etc/service-config.json"
                - name: "SEARCH_INDEXING_TOPIC_NAME"
                  value: "search_index_requests"
                - name: "DINNER_DONE_BETTER_OBSERVABILITY_METRICS_OTEL_SERVICE_NAME"
                  value: "dinner_done_better_job_search_data_index_scheduler"
                - name: "DINNER_DONE_BETTER_OBSERVABILITY_TRACING_TRACING_SERVICE_NAME"
                  value: "dinner_done_better_job_search_data_index_scheduler"
              volumeMounts:
                - name: "config"
                  mountPath: "/etc/service-config.json"
                  subPath: "config.json"
                - name: logs
                  mountPath: /var/log/application
          restartPolicy: OnFailure
          volumes:
            - name: "config"
              configMap:
                name: "dinner-done-better-job-search-data-index-scheduler-config"
            # this volume is where we write logs to, and where we read logs from in the collector.
            - name: logs
              emptyDir:
                sizeLimit: 500Mi
            # this volume contains the configuration file for the OTel collector.
            - name: opentelemetry-config
              configMap:
                name: backend-opentelemetry-collector-config
---
